### ISSUE TITLE
日期选择器的交互优化

### ISSUE THREAD

**Issue by muyiyr** [arco-design/arco-design#1001]
没有初始值的时候，hover第二个元素，叠加了选中后的样式，如图
![20220615-105237](https://user-images.githubusercontent.com/32588751/173726769-9078f6c3-5c29-45f4-b5b9-c25115a73590.gif)
期望，可以在hover的时候不叠加选中后的样式
![20220615-105310](https://user-images.githubusercontent.com/32588751/173726783-f4dd121e-4399-43e6-97b1-cc6608a7653b.gif)

**Comment by jiahao-c** [comment]
没懂耶...目前已经选择一个range后，range是浅色，再hover选的话，新range是深色，感觉符合逻辑的他。 两张动图里的样式也没看出区别....方便再更清晰的说明一下吗？

**Comment by muyiyr** [comment]
在初始选择的时候，hover应该是浅色，但是hover第二个值的时候hover会叠加选中之后的class，出现选中之后的样式

**Comment by muyiyr** [comment]
> 没懂耶...目前已经选择一个range后，range是浅色，再hover选的话，新range是深色，感觉符合逻辑的他。 两张动图里的样式也没看出区别....方便再更清晰的说明一下吗？


就是在初始选择日期选择器的时候，hover应该是浅色，但是hover第二个值的时候hover会叠加选中之后的class，出现选中之后的样式

**Comment by muyiyr** [comment]
> 没懂耶...目前已经选择一个range后，range是浅色，再hover选的话，新range是深色，感觉符合逻辑的他。 两张动图里的样式也没看出区别....方便再更清晰的说明一下吗？

这个问题我和pengjiyuan聊过了哈，他说算个小优化项....
