### ISSUE TITLE
[Tree] blockNode={true} 效果与期望不符

### ISSUE THREAD

**Issue by kkkisme** [arco-design/arco-design#1006]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.0
- **Framework version:** Vue
- **Browser:** chrome102.0.0.0
- **Reproduction Link:** https://arco.design/react/components/tree#%E8%8A%82%E7%82%B9%E5%8D%A0%E4%B8%80%E8%A1%8C

## What is expected?
和semi design 效果一致

## Steps to reproduce
SemiDesign效果：(blockNode默认为true)
https://semi.design/zh-CN/navigation/tree

AntDesign 虽然blockNode效果和arco-design 一样，但其提供了目录形式来达到预期效果
https://ant.design/components/tree-cn/#components-tree-demo-directory

![image](https://user-images.githubusercontent.com/18638401/174201087-907496ee-64be-4cbf-8f8a-dc0781fc8aa0.png)

![image](https://user-images.githubusercontent.com/18638401/174201243-fa8ad5ac-6468-4457-b99f-91b6a5784832.png)

![image](https://user-images.githubusercontent.com/18638401/174201470-c96e1a15-86c0-40bf-82f8-4bdd01cf404c.png)

**Comment by jiahao-c** [comment]
你期望的一整行，指的是这部分也要填上吗？
<img width="648" alt="Screen Shot 2022-06-18 at 9 22 26 PM" src="https://user-images.githubusercontent.com/8275280/174462080-4a00c510-d2fd-4b66-beb7-f4fd4d122a52.png">

（即semi这样，左边也填上的这种吗？）
<img width="391" alt="Screen Shot 2022-06-18 at 9 23 17 PM" src="https://user-images.githubusercontent.com/8275280/174462084-5d0a5603-2b19-4e1b-91cf-4eaa32694d95.png">

**Comment by kkkisme** [comment]
> 你期望的一整行，指的是这部分也要填上吗？ <img alt="Screen Shot 2022-06-18 at 9 22 26 PM" width="648" src="https://user-images.githubusercontent.com/8275280/174462080-4a00c510-d2fd-4b66-beb7-f4fd4d122a52.png">
> 
> （即semi这样，左边也填上的这种吗？） <img alt="Screen Shot 2022-06-18 at 9 23 17 PM" width="391" src="https://user-images.githubusercontent.com/8275280/174462084-5d0a5603-2b19-4e1b-91cf-4eaa32694d95.png">

是的

**Comment by jiahao-c** [comment]
> ![image](https://user-images.githubusercontent.com/18638401/174696994-fcfa7bd4-1102-4f85-8b25-9cc5bd5b5584.png) ![image](https://user-images.githubusercontent.com/18638401/174697124-ff8ae1a5-482c-4a53-bab0-1b5c6c4669ae.png) ![image](https://user-images.githubusercontent.com/18638401/174697235-5f8c4b84-60c3-458e-9447-3d0faafedb94.png) ![image](https://user-images.githubusercontent.com/18638401/174697327-0ea1c31f-4836-4541-b576-cbfdab16c1f4.png)
> 
> 基本上常见的树形结构的hover、select高亮都包含了缩进的部分，看起来也整齐一些

嗯嗯，我也同意，我这几天试着改一下
