### ISSUE TITLE
Typography.Paragraph 使用 ellipsis 属性中的 suffix 参数会导致高度变化的闪烁

### ISSUE THREAD

**Issue by cagen** [arco-design/arco-design#1007]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.0
- **Framework version:** 18
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/3f93jc

## What is expected?
1. 希望计算高度时无高度变化导致的闪烁

## Steps to reproduce
1. 打开官方的 DEMO：https://arco.design/react/components/typography#%E7%9C%81%E7%95%A5
2. 初次加载可能看不清楚，刷新一下 codesandbox 右侧的预览页面即可复现
3. 如果效果不明显，可以把文字再加长一些

**Comment by cagen** [comment]
@yuhan0709 
这是原来 Example 的效果
https://user-images.githubusercontent.com/5174809/174829768-f2546c23-bfba-419f-8c9b-5de97fcd38c9.mov

把文字加长之后比较容易看得出来
https://user-images.githubusercontent.com/5174809/174829970-cac400dc-b4c7-4209-8359-dc1fbe25a491.mov

**Comment by yuhan0709** [comment]
这个在上个版本重构了折叠整体逻辑，应该不会出现这个问题了，先关了哈。
