### ISSUE TITLE
面板分割组件，浏览器放大缩小的问题。

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#1016]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.1
- **Browser:** chrome102.0.0.0

### 比如面板分左右两个，最外层内容根据浏览器宽度改变：
- 简单说，就是一个div，宽度100%；
- 把这个div分割成两个，左边区域最大300px，右边为剩下的最大宽度；
- 假设浏览器目前为1280的宽度，打开这个页面没有任何问题；
- 现在把浏览器调整到1920的宽度，它会按照1280的百分比，设置到调整后的大小上，实际左侧面板宽度超过了300px；
- 然后当手动调整分割线的时候，会突然卡一下，并调整到300px；

- generated by arco-issue. DO NOT REMOVE -->

**Comment by MisterLuffy** [comment]
https://codesandbox.io/s/angry-sun-bneqnx?file=/demo.js
没有复现此情况，或者可能是已经修复了。如果仍有此问题，请重新打开此 Issue。
