### ISSUE TITLE
有没有计划，支持下无障碍？增加一些无障碍组件？

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#1017]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
就像头条，知乎那样。

## What problem does this feature solve?
支持无障碍，高龄、长辈等视力障碍人士。但是无论是咱们的头条，还是人家的知乎，貌似功能，UI设计都一个样。有点丑。如果有这个计划的话，希望在设计上下点儿功夫。

**Comment by PengJiyuan** [comment]
组件层面已经支持了很多无障碍的特性：https://github.com/arco-design/arco-design/issues/160。

**Comment by PengJiyuan** [comment]
不过感觉你说的无障碍更多的是适老设计，我感觉这个可以作为我们风格配置平台的一个主题。

**Comment by kwooshung** [comment]
> 不过感觉你说的无障碍更多的是适老设计，我感觉这个可以作为我们风格配置平台的一个主题。

不不，不是这样，是头条首页，点击左上角无障碍后，从上方弹出来的东西，那个里面的组件
