### ISSUE TITLE
全局配置Input的allowClear为true会导致InputNumber组件出现清除Icon，但是InputNumber没有allowClear属性导致这个icon去不掉

### ISSUE THREAD

**Issue by shixinxin1111** [arco-design/arco-design#1020]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.1
- **Browser:** chrome102.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/mystifying-pond-hrzn46?file=/demo.js:0-407

## What is expected?
希望全局配置Input的时候，不要影响到InputNumber的默认属性，特别是InputNumber没有的属性，如allowClear

## Steps to reproduce
鼠标移动到InputNumber上可看一个清除图标

**Comment by yinkaihui** [comment]
inputnumber是复用的 input 组件，可以暂时在 InputNumber 中的 Input 的 allowClear 属性强制为 false。 后续看下是不是可以在一些基础组件上加一个属性来控制基础组件只从 props 读属性，忽略 configProvider 中 componentConfig 配置。
