### ISSUE TITLE
线上运行如何设置动态主题

### ISSUE THREAD

**Issue by strongyc** [arco-design/arco-design#1025]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.1
- **Browser:** chrome102.0.0.0

## Extra info
如何设置动态主题

## What is expected?
如何设置动态主题

## Steps to reproduce
线上运行时如何选择颜色后，如何设置动态主题

**Comment by yinkaihui** [comment]
可以参考一下 arco pro 右上角切换主题的实现？  https://react-pro.arco.design/dashboard/workplace
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/23161413/175001870-780bde06-4ae9-4183-914a-27e115a2769d.png">
