### ISSUE TITLE
Dropdown组件的交互UI建议再细致一些，若弹出方向position默认值为向上 (top/tl/tr) 时，右侧三角箭头改为"向上∧"

### ISSUE THREAD

**Issue by awebird** [arco-design/arco-design#1035]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
可参考bootstrap的Dropdown组件的Dropup属性，历史版本有单独的Dropup组件
https://v5.bootcss.com/docs/components/dropdowns/

## What problem does this feature solve?
如果 弹出方向position默认值为向上 (top/tl/tr) 时，Dropdown其实变成了Dropup
右侧的三角箭头，是带有交互引导性的，箭头指向的方向给用户以这个方向会弹出菜单的引导暗示
PS: 如果做的更细致一些，在边缘检测自动判断弹出方向时，最好也能做到箭头方向的自动变化

**Comment by PengJiyuan** [comment]
Icon 是自己传入的，手动改一下就行。Dropdown 不仅有方向图标，是可以传入任意图标的，内部不会做处理。
