### ISSUE TITLE
希望drawer能增加失去焦点自动隐藏, 而不是点击蒙层关闭. 

### ISSUE THREAD

**Issue by OrrinHatch** [arco-design/arco-design#1037]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
未知

## What problem does this feature solve?
提高用户体验度吧,不需要用户点击右上角关闭图标来关闭

## Extra info
发生在我不使用蒙层时, 无法在用户失去drawer焦点时关闭它.我自己也封装了一个FocusManager 但却不能在drawer中使用
```import React, { useState } from 'react';

interface Props {
  children: React.ReactNode;
  onBlur: (e) => void;
  onFocus: (e) => void;
}

export function FocusManager({ children, onFocus, onBlur }: Props) {
  let _timeoutID;

  const _onFocus = (e) => {
    clearTimeout(_timeoutID);
    onFocus(e);
  };

  const _onBlur = (e) => {
    _timeoutID = setTimeout(() => {
      onBlur(e);
    }, 0);
  };

  return (
    <div onFocus={_onFocus} onBlur={_onBlur}>
      {children}
    </div>
  );
}
```

**Comment by yinkaihui** [comment]
一般是 `esc` 关闭弹出层元素？drawer 组件内部默认会锁焦点
