### ISSUE TITLE
DatePicker显示异常

### ISSUE THREAD

**Issue by LaamGinghong** [arco-design/arco-design#105]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.23.5
- **系统版本:** macOS BigSur 11.6
- **浏览器版本:** Google Chrome 95.0.4638.54
- **复现地址:** https://codesandbox.io/s/rough-dust-sjgtx?file=/index.js

## 额外补充
实际展示为 Invalid Date

## 预期结果
DatePicker正确展示日期

## 复现步骤
DatePicker 增加 showTime、format="YYYY-MM-DD HH:mm:ss"这两个props，传入的value格式为 "YYYY-MM-DD"

**Comment by PengJiyuan** [comment]
理论上传值的format应该和format一致。
这里增加一个保底逻辑吧，如果format string为invalid，去尝试使用 YY-MM-DD
