### ISSUE TITLE
Docgen Inconsistency 

### ISSUE THREAD

**Issue by jiahao-c** [arco-design/arco-design#1051]
目前 clone 后 ，`main` 分支 **不作任何修改**的情况下，直接 `yarn docgen` 也会带来很多变动。

<img width="497" alt="image" src="https://user-images.githubusercontent.com/8275280/175839022-f2180b60-0798-44b2-912d-c44bd085e0d1.png">

是不是过往有些直接在 `README` 里改了doc的情况？这样对后续的开发不友好，每次 docgen 都会多出来一些自己没动过的变更....希望有办法解决一下~

**Comment by MisterLuffy** [comment]
其实基本上都是生成的 API 顺序的改变，不过现在工具已经支持自定义排序规则了。我们可以加一下排序规则，一方面可以减少上边的问题，另一方面也可以提升 API 文档的阅读体验。
