### ISSUE TITLE
文档疑惑-dayjs不支持时区？

### ISSUE THREAD

**Issue by szmxx** [arco-design/arco-design#1053]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.36.0
- **Browser:** chrome102.0.0.0
- **Reproduction Link:** https://arco.design/react/docs/question

<img width="952" alt="image" src="https://user-images.githubusercontent.com/24505926/176086458-bd5d566b-244e-41df-ac2c-fefa2a78133c.png">

**Comment by PengJiyuan** [comment]
写这个文档的时候还是不支持的，现在 dayjs 本身是支持时区了。
但是 dayjs 本身的 utc 时间和 timezone 有一些问题，所以组件库还是自己处理了时区，见 demo
