### ISSUE TITLE
modal对话框默认遮罩层无效

### ISSUE THREAD

**Issue by wanhusheng** [arco-design/arco-design#106]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** arco-design
- **System:** win10
- **Browser:** 谷歌
- **Reproduction Link:** https://github.com/arco-design/arco-design/issues

## What is expected?
加油，帮忙改下bug

## Steps to reproduce
加油，帮忙改下bug

**Comment by kirazxyun** [comment]
@wanhusheng 你好，需要提供一下 demo 复现一下问题哦。

**Comment by wanhusheng** [comment]
![image](https://user-images.githubusercontent.com/93570335/140717139-116130aa-c939-4642-8b00-6c3432883fae.png)

**Comment by wanhusheng** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)
> 
> ## Basic Info
> * **Package Name And Version:** arco-design
> * **System:** win10
> * **Browser:** 谷歌
> * **Reproduction Link:** https://github.com/arco-design/arco-design/issues
> 
> ## What is expected?
> 加油，帮忙改下bug
> 
> ## Steps to reproduce
> 加油，帮忙改下bug



> @wanhusheng 你好，需要提供一下 demo 复现一下问题哦。

具体表现为如图所示，不知道是什么原因？
