### ISSUE TITLE
table rowData 格式未向下兼容

### ISSUE THREAD

**Issue by Webwwl** [arco-design/arco-design#1061]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.1
- **Framework version:** react: 18.0.0
- **Browser:** chrome102.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/rough-bird-q2w6kb?file=/src/App.js

## What is expected?
当 table data 是字符串数组时，render 函数的 rowData 格式向下兼容

## Steps to reproduce
@arco-design/web-react 版本在 2.35.0 升级至 2.35.1 后， 当 table data 类型是 string[]， render 函数接收的 rowData 不一致

**Comment by PengJiyuan** [comment]
这些神奇的用法都是咋发掘出来的

**Comment by PengJiyuan** [comment]
2.36.1兼容了一下

**Comment by Webwwl** [comment]
> 2.36.1兼容了一下

赞~
