### ISSUE TITLE
form setFieldsValue won't override initialValue before Form is mounted, only for empty array values

### ISSUE THREAD

**Issue by voderl** [arco-design/arco-design#1085]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.36.1
- **Framework version:** React 17.0.2
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/summer-leaf-6zjvuy?file=/demo.js

## What is expected?
setFieldsValue will override initialValue anytime

## Steps to reproduce
open the codesandbox page, the "name" is empty string, but the "select" is initialValues

**Comment by foreverzmy** [comment]
"@arco-design/web-react": "2.66.1" have this problem still.

**Comment by foreverzmy** [comment]
> "@arco-design/web-react": "2.66.1" have this problem still.

@SleepDevil
