### ISSUE TITLE
ICONXXX 希望支持 import * as 方式引入

### ISSUE THREAD

**Issue by guoenyue** [arco-design/arco-design#109]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
例如antd  可以使用以下方式遍历所有可渲染的图标
```
import * as ALLICONS from '@ant-design/icons';

const allIcons = ALLICONS as Record<string, ReactNode>;

render:

{Object.keys(ALLICONS).map((icon: string) => {
        const Icon = allIcons[icon];
        if (
          [
            'default',
            'IconProvider',
            'AntdIcon',
            'setTwoToneColor',
            'createFromIconfontCN',
            'getTwoToneColor',
          ].indexOf(icon) === -1
        ) {
          return <Icon key={icon} />;
        }
        return null;
      })}

```

## What problem does this feature solve?
有很多需要选图标的场景，当前通过import * 引入所有图标会导致loadComponent报错，只能在项目中一个个枚举所需图标然后自己组装数组，挺难用的，而且文件头上引入几十上百icon属实难看

**Comment by PengJiyuan** [comment]
好的，我们看下怎么支持

**Comment by yinkaihui** [comment]
https://codesandbox.io/s/tu-biao-yin-yong-i6rjk?file=/index.js  试了一下可以呀

是在项目中配置了对图标的按需加载么？如果配置了的话，是没有办法这么引用的

**Comment by guoenyue** [comment]
项目是基于arco-cli创建的简单模版项目 
在那个项目里直接引入确实不行，但我试了直接从 @arco-design/web-react/icon/index.es.js 这里直接引入成功了

以下是基于@arco-design/arco-cli工具创建的极简版项目中成功方式


```ts

import React, { SFC } from 'react';
import * as ICONS from '@arco-design/web-react/icon/index.es.js';

interface DIProps {
  type: string;
}

export const DynamicIcon: SFC<DIProps> = (props) => {
  const { type, ...extraProps } = props;

  const Icon = ICONS[type];
  if (!Icon) {
    return null;
  }
  return <Icon {...extraProps} />;
};


```

**Comment by PengJiyuan** [comment]
arco-cli 初始化的项目默认是开启了 icon 的按需加载了

**Comment by guoenyue** [comment]
好的，明白了，还在慢慢摸索中，组件使用体验还不错

**Comment by PengJiyuan** [comment]
> 好的，明白了，还在慢慢摸索中，组件使用体验还不错

有问题随时提issue，或者在群里提问都可以。
