### ISSUE TITLE
空白表格table的第一行没有边框

### ISSUE THREAD

**Issue by hemisu** [arco-design/arco-design#1115]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.36.1
- **Framework version:** React 17
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/aroc-empty-table-left-board-bug-c1mx44

<img width="619" alt="image" src="https://user-images.githubusercontent.com/11391390/177986220-d47288bf-000c-4561-af20-61bf1bdbe7bc.png">

## What is expected?
应该有左侧边框

## Steps to reproduce
基础用法table将datasource设为空即可复现

**Comment by chenc041** [comment]
根据你提供的 codesandbox 没有复现
![截屏2022-07-11 15 30 18](https://user-images.githubusercontent.com/16097887/178211530-b657d76e-3f8d-4969-a27c-8c0edfc203cd.png)

**Comment by hemisu** [comment]
> 根据你提供的 codesandbox 没有复现 ![截屏2022-07-11 15 30 18](https://user-images.githubusercontent.com/16097887/178211530-b657d76e-3f8d-4969-a27c-8c0edfc203cd.png)

出现在2.36.1 目前2.37了，需要修复到2.36.2

**Comment by chenc041** [comment]
> 

对于这个问题个人建议升级到 2.37
因为 2.37 修复了不少问题, 而且 aroc-design 是遵循 semr 版本升级 所以直接升级不会有什么问题

**Comment by hemisu** [comment]
> > 
> 
> 对于这个问题个人建议升级到 2.37 因为 2.37 修复了不少问题, 而且 aroc-design 是遵循 semr 版本升级 所以直接升级不会有什么问题
36->37 改了，semver规定次版本号是当你做了向下兼容的功能性新增；这个属于向下兼容的问题修正

**Comment by yuhan0709** [comment]
> 次版本号是 feature + bugfix, 小版本号是仅仅 bugfix
