### ISSUE TITLE
DatePicker 组件在 format 参数为 "YYYY-MM-DDTHH:mm:ssZ"，时间范围选择会出现异常，仅能选择小时

### ISSUE THREAD

**Issue by FeLpc** [arco-design/arco-design#1120]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.0
- **Framework version:** React
- **Browser:** chrome103.0.0.0

## Steps to reproduce
复现代码：

```
     <DatePicker
        showTime={{
          defaultValue: "04:05:06"
        }}
        format="YYYY-MM-DDTHH:mm:ssZ"
      />
```

<img width="369" alt="image" src="https://user-images.githubusercontent.com/11614970/178180772-8b6f794f-0418-4c3a-9f25-eb47bb072221.png">

**Comment by PengJiyuan** [comment]
麻烦设置一下 showTime.format = 'HH:mm:ssZ' 吧，自动截取没有支持这种格式，现在加怕有坑

**Comment by PengJiyuan** [comment]
麻烦设置一下 showTime.format = 'HH:mm:ss' 吧，现在自动识别 time format 没有支持这种格式，加上怕有坑。
