### ISSUE TITLE
modal组件与spin组件一起封装使用时 spin组件会把 loading属性的值渲染到页面上

### ISSUE THREAD

**Issue by linyongqi666** [arco-design/arco-design#1122]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.36.1
- **Framework version:** react 18 
- **Browser:** chrome102.0.0.0

## Steps to reproduce
// 组件
export default function LModal(props: Props) {
  const { loading = false, tip = '', type = '' } = props
  const onCancel = () => {
    props.onCancel && props.onCancel(type)
  }
  const onOk = () => {
    props.onOk && props.onOk(type)
  }
  return (
    <Modal
      { ...props }
      onOk={onOk}
      unmountOnExit
      onCancel={onCancel}
    >
      <Spin loading={loading} tip={tip}>
        { 
          123
          // props.children
        }
      </Spin>
    </Modal>
  )
}

// 使用
<LModal
          { ...modalObj }
          loading={ modalLoading ? 1 : 0}
          onOk={() => isShowModal(false)}
          onCancel={() => isShowModal(false)}
        >
          { renderModal() }
        </LModal>

**Comment by MisterLuffy** [comment]
看起来是你这边把 `loading` 属性直接传递给 `Modal` 的。
![image](https://user-images.githubusercontent.com/29861850/178889908-c9ec4568-5397-4f7d-a57c-d5f369778d6a.png)

**Comment by MisterLuffy** [comment]
Issue 暂时先关闭了，如果仍有问题可以重新打开。
