### ISSUE TITLE
React does not recognize the `_ignorePropsFromGlobal` prop on a DOM element.

### ISSUE THREAD

**Issue by cjzgitHub** [arco-design/arco-design#1125]
Pagination 分页组件配置了showJumper也会出现相同问题，
InputNumber 在form里使用也出现了相同的问题

请帮忙看下react17.x umi 3.5.26
![image](https://user-images.githubusercontent.com/38244432/178399784-5536d34a-7479-4e6e-b089-31745a846e6d.png)

**Comment by MisterLuffy** [comment]
https://github.com/arco-design/arco-design/pull/1070 已经在 2.36.1 修复，可以升级后再看一下。
