### ISSUE TITLE
Description对齐方式异常

### ISSUE THREAD

**Issue by shixinxin1111** [arco-design/arco-design#1127]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.0
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/dreamy-williamson-smdc0g?file=/demo.js

## What is expected?
希望可以对齐

## Steps to reproduce
可以看到 Hometown 和 Address 没有对齐

**Comment by yuhan0709** [comment]
Description 这个实现方式是靠的 table，vertical-align 值直接从 <td/> 继承而来的`middle`，你可以加一个样式 style={{verticalAlign: "top" }}。改样式默认值的话组件库升级可能会造成比较大的影响哈
