### ISSUE TITLE
Typography展开文本显示问题

### ISSUE THREAD

**Issue by shixinxin1111** [arco-design/arco-design#1143]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.0
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/sleepy-visvesvaraya-vbrzqy?file=/demo.js

## What is expected?
希望第一个展开与文本还保持在同一行，同第二个一样

## Steps to reproduce
可以看到第一个展开两个字跑到第二行了

**Comment by jiahao-c** [comment]
文字受 prop 传入的 width 限制，还在第一行的话就 width 不够用了，只能 wrap 到第二行了....

**Comment by shixinxin1111** [comment]
那应该减少一个字的显示呀，怎么能让展开跑到第二行呢？

**Comment by yuhan0709** [comment]
楼上正解
