### ISSUE TITLE
Button设置Icon后，指定Icon的font-size会导致Icon不居中

### ISSUE THREAD

**Issue by KoitoTouko** [arco-design/arco-design#1146]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.1
- **Browser:** chrome101.0.4951.67
- **Reproduction Link:** https://codesandbox.io/s/bitter-cloud-2i8pof?file=/demo.js

**Comment by PengJiyuan** [comment]
现在的居中需要用 vertical-align，我在想用 flex 布局，这样居中就比较容易了，不知道有没有什么坑

**Comment by canvascat** [comment]
`vertical-align: <length>;` 使元素的基线对齐到父元素的基线之上的给定长度。可以是负数。然而
> HTML 规范没有详细说明部分[可替换元素](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Replaced_element)的基线，如[<textarea>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/textarea) ，这意味着这些元素使用此值的表现因浏览器而异。

所以我的建议是，所有非文字的居中对齐全部采用 `flex` 🐱‍🏍

**Comment by yinkaihui** [comment]
当前版本不会进行变更，避免引起无法预知的问题。。存在大版本迭代时建议升级调整
