### ISSUE TITLE
Select 选择器支持创建的时候，快速在输入框输入会出现not data的闪动

### ISSUE THREAD

**Issue by lynn1286** [arco-design/arco-design#1156]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.1
- **Framework version:** "next": "^12.2.1-canary.2"
- **Browser:** chrome103.0.0.0

## What is expected?
不会出现闪动not data 的问题

## Steps to reproduce
allowCreate 属性设置为true ，然后快速在输入框输入值

**Comment by lynn1286** [comment]
@yinkaihui  大佬能否安排解决下这个问题

**Comment by MisterLuffy** [comment]
麻烦提供一下 CodePen 的 Demo 或者录个动图演示一下，没有成功复现这种情况。

**Comment by lynn1286** [comment]
https://codesandbox.io/s/fast-fire-tzhkvg?file=/pages/index.js

**Comment by lynn1286** [comment]
![未命名_](https://user-images.githubusercontent.com/40122311/180594795-d4bd5018-f796-4e32-add2-f38c9b2a7ebd.gif)

**Comment by lynn1286** [comment]
快速输入的情况下会出现not data 状态

**Comment by jiahao-c** [comment]
试了下，好像只有在nextjs里才能复现。。[普通的](https://codesandbox.io/s/musing-boyd-zwqbp9?file=/demo.js ) 项目里复现不了
