### ISSUE TITLE
Some components do not pass through HTML data-* attributes

### ISSUE THREAD

**Issue by 532596364** [arco-design/arco-design#1159]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.37.1
- **浏览器版本:** chrome103.0.0.0
- **复现地址:** https://codesandbox.io/s/gallant-jennings-rtilp9?file=/demo.js

## 额外补充
Have a look at the source code, fork down to try, there are about 29 of the following, may be missing。
Affix
Alert
Anchor
AutoComplete
BackTop
Breadcrumb
Cascader
ConfigProvider
DatePicker
Divder
Drawer
Dropdown
InputNumber
InputTag
List
Pagination
Popconfirm
Popover
Progress
ResizeBox
Select
Skeleton
Slider
Spin
Statistic
Steps
Table
Tooltip
Transfer

## 复现步骤
Select and Button two components respectively added a custom attribute data-xxx, click the button can see the corresponding attribute value, button can get, select can not get, you can also review the code to see element

**Comment by yinkaihui** [comment]
- [ ] Affix
- [ ] Alert
- [ ] Anchor
- [ ] AutoComplete
- [ ] BackTop
- [ ] Breadcrumb
- [ ] Cascader
- [ ] ConfigProvider
- [ ] DatePicker
- [ ] Divder
- [ ] Drawer
- [ ] Dropdown
- [ ] InputNumber
- [ ] InputTag
- [ ] List
- [ ] Pagination
- [ ] Popconfirm
- [ ] Popover
- [ ] Progress
- [ ] ResizeBox
- [ ] Select
- [ ] Skeleton
- [ ] Slider
- [ ] Spin
- [ ] Statistic
- [ ] Steps
- [ ] Table
- [ ] Tooltip
- [ ] Transfer

**Comment by p0301y** [comment]
We desperately need this capability, Is there an approximate repair time for this?
