### ISSUE TITLE
Nextjs 国际化失败 Cannot use import statement outside a module with dynamic import of Nextjs

### ISSUE THREAD

**Issue by Vita-zzzxw** [arco-design/arco-design#1163]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.1
- **Framework version:** 2.37.0
- **Browser:** chrome103.0.0.0

## What is expected?
nextjs国际化正常使用

## Steps to reproduce
nextjs  中引入import enUS from '@arco-design/web-react/es/locale/en-US';  
报错：import 'dayjs/locale/en';
^^^^^^

SyntaxError: Cannot use import statement outside a module

利用dynamic异步导入
 Cannot read property 'Typography' of null

**Comment by findridoy** [comment]
I am also facing this issue.

**Comment by yuhan0709** [comment]
Refer this issue: https://github.com/asyncapi/asyncapi-react/issues/177

**Comment by Vita-zzzxw** [comment]
import enUS from '@arco-design/web-react/es/locale/en-US'; 报错


......\node_modules\@arco-design\web-react\es\locale\zh-CN.js:1
import 'dayjs/locale/zh-cn';

**Comment by Naveenkumar-asokan** [comment]
I am also facing the same issue, when running the test cases. 
i am using jest with react testing library
