### ISSUE TITLE
formItem 的require标志 *号位置异常

### ISSUE THREAD

**Issue by forestlan** [arco-design/arco-design#1164]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.37.1
- **浏览器版本:** chrome103.0.0.0

## 预期结果
*号对齐

## 复现步骤
<FormItem label="Tag Name" field="tag_name" rules={[{ required: true, message: 'Please enter a tag name' }]}>
            <Input />
          </FormItem>
设置label及require：true时，*号无法对齐

**Comment by jin337** [comment]
我也出现了类似的问题，请问你是如何解决的？

**Comment by xuyunan** [comment]
最新版本,还有这个问题啊, "@arco-design/web-react": "^2.65.0"

**Comment by xuyunan** [comment]
好像是和tailwindcss 样式冲突了, 先这样解决了
.arco-form-item-symbol {
  display: inline-block;
}
