### ISSUE TITLE
vite构建应用打包报错

### ISSUE THREAD

**Issue by dxl519** [arco-design/arco-design#1171]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.37.1
- **框架版本:** React :18.0.0
- **浏览器版本:** chrome103.0.0.0
- **复现地址:** https://codepen.io/dxl519/pen/jOzwEoK

## 复现步骤
    import {
    DatePicker,
} from '@arco-design/web-react';

**Comment by dxl519** [comment]
这是我的vite配置

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths';
// 引入按需加载插件
import vitePluginImp from "vite-plugin-imp";
// https://vitejs.dev/config/

export default defineConfig({

  plugins: [
    react(),
    tsconfigPaths(),
    // vitePluginImp({
    //   libList: [
    //     {
    //       libName: "@arco-design/web-react",
    //       style: (name) => {
    //         return [
    //           // 加载框架的主要样式文件 index.less
    //           "@arco-design/web-react/lib/style/index.less",
    //           // 根据name值按需加载相关组件样式
    //           `@arco-design/web-react/lib/${name}/style/index.less`,
    //         ];
    //       },
    //     },
    //   ],
    // }),
  ],
  css: {
    preprocessorOptions: {
      less: {
        // 支持内联 JavaScript
        javascriptEnabled: true,
      },
    },
  },
});

**Comment by dxl519** [comment]
我的vite配置
`import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths';
// 引入按需加载插件
import vitePluginImp from "vite-plugin-imp";
// https://vitejs.dev/config/

export default defineConfig({

  plugins: [
    react(),
    tsconfigPaths(),
    // vitePluginImp({
    //   libList: [
    //     {
    //       libName: "@arco-design/web-react",
    //       style: (name) => {
    //         return [
    //           // 加载框架的主要样式文件 index.less
    //           "@arco-design/web-react/lib/style/index.less",
    //           // 根据name值按需加载相关组件样式
    //           `@arco-design/web-react/lib/${name}/style/index.less`,
    //         ];
    //       },
    //     },
    //   ],
    // }),
  ],
  // build: {
  //   rollupOptions: {
  //     external: ["@arco-design/web-react/es/date-picker", "@arco-design/web-react/lib/date-picker/style/index.less"]
  //   }
  // },
  css: {
    preprocessorOptions: {
      less: {
        // 支持内联 JavaScript
        javascriptEnabled: true,
      },
    },
  },
});


`

**Comment by dxl519** [comment]
我的vite配置
`
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths';
import vitePluginImp from "vite-plugin-imp";

export default defineConfig({

  plugins: [
    react(),
    tsconfigPaths(),
    vitePluginImp({
      libList: [
        {
          libName: "@arco-design/web-react",
          style: (name) => {
            return [
              "@arco-design/web-react/lib/style/index.less",
              `@arco-design/web-react/lib/${name}/style/index.less`,
            ];
          },
        },
      ],
    }),
  ],
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  },
});



`

**Comment by yuhan0709** [comment]
报啥错啊

**Comment by dxl519** [comment]
> * [https ://codepen.io/dxl519/pen/jOzwEoK](https://codepen.io/dxl519/pen/jOzwEoK)

 https://codepen.io/dxl519/pen/jOzwEoK

**Comment by MisterLuffy** [comment]
![image](https://user-images.githubusercontent.com/29861850/180378137-0d411621-9caa-416e-a29b-31fdba19e837.png)
似乎是路径错了，应该是 `DatePicker` 而非 `date-picker`，可以尝试修改一下插件配置。
http://unpkg.com/@arco-design/web-react@2.32.0/lib/DatePicker/style/index.less

**Comment by dxl519** [comment]
> ![图片](https://user-images.githubusercontent.com/29861850/180378137-0d411621-9caa-416e-a29b-31fdba19e837.png) http://unpkg.com/@arco-reactlib@2.32.0/web-reactlib@2.32.0/DatePicker/style/index.less `DatePicker`_ `date-picker`_ [_](http://unpkg.com/@arco-design/web-react@2.32.0/lib/DatePicker/style/index.less)

是的，因为的node_modules依赖里面的文件地址是DatePlcker ，打完包是date-picker，我想弄按需加载
