### ISSUE TITLE
在Form表单中使用Switch组件，不能正确的给Switch设置状态

### ISSUE THREAD

**Issue by zmbxy** [arco-design/arco-design#1182]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.2
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/goofy-mendeleev-vcri3s?file=/demo.js

## What is expected?
在form中给switch赋值时，能够正确显示状态

## Steps to reproduce
如demo示例中所示。在给Form设置initialValues或者通过form.setFieldValue or form.setFieldsValue时，Switch无法正确显示状态UI

## Disclaimer 

 Submitting offensive issues will result in being blocked from arco-design organization.

**Comment by jiahao-c** [comment]
重现代码里的Switch 没啥问题啊，可以开可以关，log出来的值也是正确的

**Comment by yinkaihui** [comment]
是不是没有个 FormItem 设置 `triggerPropName=checked` ?

**Comment by zmbxy** [comment]
oh，sorry, 我没注意到``triggerPropName`这个属性，有点被antd的`valuePropName`洗脑了
