### ISSUE TITLE
google自动翻译场景下，typography组件内部报错，导致组件渲染失败

### ISSUE THREAD

**Issue by Jiyp** [arco-design/arco-design#1185]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.37.2
- **浏览器版本:** chrome103.0.0.0

## 复现步骤
该问题是 react 的 bug，参考链接： https://github.com/facebook/react/issues/17256

## 声明 

 如果提交带有攻击性的 issue，提交者将会被禁止在 arco-design 组织下发言。

**Comment by yuhan0709** [comment]
这个 issue 待定，改的话要造成 dom 层级变化比较多。
