### ISSUE TITLE
vite构建react应用    DatePicker组件报错信息如下

### ISSUE THREAD

**Issue by dxl519** [arco-design/arco-design#1187]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.36.0
- **框架版本:** 18.0.0
- **浏览器版本:** chrome103.0.0.0

## 复现步骤
vite打包部署到线上，有的页面刷新会报错，报错信息如下：ypeError: rt.exports.__asign is not a function
    at ft (Combination.7a9107a3.js:1:1615)
    at Combination.7a9107a3.js:1:1756
lc @ index.1107f4f0.js:32
Uncaught TypeError: rt.exports.__assign is not a function

**Comment by dxl519** [comment]
Failed to resolve import "@arco-design/web-react/lib/date-picker/style/index.less" from "src/pages/VisitorManagement/form.tsx". Does the file exist?
11:56:27 [vite] Internal server error: Failed to resolve import "@arco-design/web-react/lib/date-picker/style/index.less" from "src/pages/VisitorManagement/form.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/duxiaolun/Desktop/code/my-react-app/src/pages/VisitorManagement/form.tsx
  1  |  import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/form/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/input/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/select/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/button/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/grid/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/date-picker/style/index.less'; ; import RefreshRuntime from "/@react-refresh";
     |

**Comment by OrrinHatch** [comment]
我用的是主题

**Comment by OrrinHatch** [comment]
`import vitePluginForArco from '@arco-plugins/vite-react';

export default defineConfig((configEnv) => {
  const isDevelopment = configEnv.mode === 'development';

  return {
    plugins: [
      splitVendorChunkPlugin(),
      vitePluginForArco({
        theme: '@arco-themes/react-arco-pro',
      }),
      svgr({
        exportAsDefault: true,
        svgrOptions: {}
      }),
      react(),
    ],`

**Comment by OrrinHatch** [comment]
```
import vitePluginForArco from '@arco-plugins/vite-react';

export default defineConfig((configEnv) => {
  const isDevelopment = configEnv.mode === 'development';

  return {
    plugins: [
      splitVendorChunkPlugin(),
      vitePluginForArco({
        theme: '@arco-themes/react-arco-pro',
      }),
      svgr({
        exportAsDefault: true,
        svgrOptions: {}
      }),
      react(),
    ],
```

**Comment by yuhan0709** [comment]
> Failed to resolve import "@arco-design/web-react/lib/date-picker/style/index.less" from "src/pages/VisitorManagement/form.tsx". Does the file exist? 11:56:27 [vite] Internal server error: Failed to resolve import "@arco-design/web-react/lib/date-picker/style/index.less" from "src/pages/VisitorManagement/form.tsx". Does the file exist? Plugin: vite:import-analysis File: /Users/duxiaolun/Desktop/code/my-react-app/src/pages/VisitorManagement/form.tsx 1 | import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/form/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/input/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/select/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/button/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/grid/style/index.less';import '@arco-design/web-react/lib/style/index.less';import '@arco-design/web-react/lib/date-picker/style/index.less'; ; import RefreshRuntime from "/@react-refresh"; |

现在解决了吗，还报错吗？

**Comment by dxl519** [comment]
>报错以后，我就直接换组件库了
