### ISSUE TITLE
Support addBefore/addAfter attribute in InputNumber/Select component

### ISSUE THREAD

**Issue by lvqq** [arco-design/arco-design#1191]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Input componet supports it already.

## What problem does this feature solve?
Common feature. In some situations, we use general design of Front/Post label and find it not supported in other components excluding Input

**Comment by MisterLuffy** [comment]
There are already two buttons around InputNumber, so it's not suitable to add this feature. Maybe you can try Input.Group like [this](https://codesandbox.io/s/blissful-hypatia-ikrws6?file=/demo.js).

**Comment by 1371164370** [comment]
> There are already two buttons around InputNumber, so it's not suitable to add this feature. Maybe you can try Input.Group like [this](https://codesandbox.io/s/blissful-hypatia-ikrws6?file=/demo.js).

按钮太多不行，这是arco的设计理念吗。从功能性来说InputNumber加上addBefore/addAfter还是会更完善的，比如对整个组件的错误状态控制更好。
