### ISSUE TITLE
基于vite运行时，a-pagination 和 a-input-number 同时使用导致a-pagination跳转框样式错乱

### ISSUE THREAD

**Issue by boomstackcn** [arco-design/arco-design#1193]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.33.1
- **Framework version:** Vue 3.2.25
- **Browser:** chrome103.0.5060.134

## Steps to reproduce
主要是 .arco-input-number{ width: 100% } 覆盖了 .arco-pagination-jumper-input{ width: 40px }

**Comment by MisterLuffy** [comment]
如果是 Vue 版本的 Issue，请至 [Arco Vue](https://github.com/arco-design/arco-design-vue) 创建。PS：最好提供一个 Demo。
