### ISSUE TITLE
When using the arco-vite template, the page is inaccessible after the SwitchOmega agent is enabled

### ISSUE THREAD

**Issue by JSMengLingqi** [arco-design/arco-design#1198]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.2
- **Browser:** chrome103.0.0.0

## What is expected?
when i use arco-vite-template, start SwitchOmega proxy can access the page normally

**Comment by MisterLuffy** [comment]
Is this a Arco-Pro issue? Plz go [Arco Pro Vue](https://github.com/arco-design/arco-design-pro-vue/issues) or [Arco Pro React](https://github.com/arco-design/arco-design-pro/issues) to raise an issue.
