### ISSUE TITLE
表格 rowClassName 添加伪类样式的情况下会导致当前行出现错位

### ISSUE THREAD

**Issue by lynn1286** [arco-design/arco-design#1208]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.37.2
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/arcobiao-ge-cuo-wei-wen-ti-lyonrj?file=/demo.tsx:1438-1450

## What is expected?
不会出现错位，或者有其他的解决方案

## Steps to reproduce
给表格添加属性 rowClassName ， 设置伪类样式，after 或 before 样式后，表格行出现错位

**Comment by lynn1286** [comment]
https://codesandbox.io/s/arcobiao-ge-cuo-wei-wen-ti-lyonrj?file=/demo.tsx:1438-1450

**Comment by lynn1286** [comment]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/40122311/181690186-f636d756-3284-4ad2-bbd3-89b674dad864.png">

**Comment by PengJiyuan** [comment]
你想组件库怎么解决呢？

**Comment by lynn1286** [comment]
请问我该如何做才能在表格当前行添加一层遮罩？例如上面示例所展示的那样

**Comment by PengJiyuan** [comment]
直接给行加不太行，会影响 table 元素。要我加的话我可能给这个 tr 下每一个单元格里的div下设置一个伪元素，想办法撑开盖满。
