### ISSUE TITLE
使用color时，会使用css变量，有没有降级处理的工具

### ISSUE THREAD

**Issue by WebGuHui** [arco-design/arco-design#1228]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.38.0
- **Browser:** chrome103.0.0.0

**Comment by yinkaihui** [comment]
可以参考这里最下方描述：https://arco.design/react/docs/theme

<img width="860" alt="image" src="https://user-images.githubusercontent.com/23161413/182991973-c1bb99f5-976b-4e24-8a8a-c9fdca72e6b0.png">
