### ISSUE TITLE
DatePicker: WeekPicker 选择周时hover值和选择面板的值不同

### ISSUE THREAD

**Issue by zhaogang6682** [arco-design/arco-design#1229]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.38.0
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/cranky-currying-o7n7qo?file=/demo.js:219-227

## What is expected?
WeekPicker hover时，输入框中的值和hover行前的周相对应
![image](https://user-images.githubusercontent.com/109260418/182090647-d8cfd099-9d2a-47b8-b8b8-0d52ab26fc4c.png)

select 选中onChange返回值和输入框中的值不同
![image](https://user-images.githubusercontent.com/109260418/182101799-ea258ed5-47b5-47cf-a9f5-dcd16439c18d.png)

## Steps to reproduce
在中文环境下，WeekPicker hover时，输入框中的值和hover行前的周不对应

**Comment by SleepDevil** [comment]
看了一下，是dayjs的问题

**Comment by PengJiyuan** [comment]
这个问题在于不同的locale的weekStart是不一样的，输入的locale是中文，weekStart是1，en-US weekStart是0。我看下怎么统一一下。
