### ISSUE TITLE
Upload 组件 accept 字段传入 "*/*" 时，无法正常上传文件

### ISSUE THREAD

**Issue by wuhao-igno** [arco-design/arco-design#1230]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.38.0
- **Browser:** chrome103.0.5060.134

## Extra info
`Upload` 组件内部会使用 `isAcceptFile` 对 `accept` 字段做检查，[isAcceptFile 中对于 MIME 类型进行判断时](https://github.com/arco-design/arco-design/blob/69b8c6d0787a3b0a99b7b4564e7ba7356c2d8e53/components/Upload/util.tsx#L24)，仅考虑了指名了一类 MIME 类型且没有指明子类的情况，并未考虑传入 `*/*` 的场景

## What is expected?
`Upload` 组件的 `accept` 字段传入 `*/*` 时，预期应该所有类型的文件都能被上传

## Steps to reproduce
`Upload` 组件的 `accept` 字段传入 `*/*` 时，上传文件后无反应

**Comment by SleepDevil** [comment]
不好意思，我之前没发现这种情况，将在下个版本修复
