### ISSUE TITLE
Popover 给其组建的时候不会触发

### ISSUE THREAD

**Issue by jollazzlw** [arco-design/arco-design#1231]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.38.0
- **Browser:** chrome103.0.0.0

我在准备给popover封装的时候遇到一个问题。

const QuestionIcon: React.FC<IProps> = ({
  iconWidth = 14,
  iconHeight = 14,
}) => {
  return (
    <svg
      ....
    </svg>
  );
};
export const IconQuestion = ({
}) => {
  if (!popoverContent) {
    return null;
  }

  return (
    // TODO 这里为什么不能直接组件调用？
    <Popover
      content="222"
      style={{
        zIndex: 999999999,
      }}
      onVisibleChange={() => {
        console.log('test___________>++++++++');
      }}>
      ` <QuestionIcon />`  { 这样不可以触发事件*/}
       `{QuestionIcon({})} `  {/*   这样可以触发事件*/}
    </Popover>
  );
};

**Comment by yinkaihui** [comment]
可以参考下这里尝试解决下？ [常见问题](https://arco.design/react/docs/question#popover-tooltip-popconfirm-trigger-%E5%9C%A8%E5%8C%85%E8%A3%B9%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%97%B6%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%BC%B9%E5%87%BA%E5%B1%82%EF%BC%9F )
