### ISSUE TITLE
firefox 浏览器，select 搜索模式，若已有值，则需点击两次输入框才能弹出下拉菜单

### ISSUE THREAD

**Issue by cao2028196** [arco-design/arco-design#1232]
![image](https://user-images.githubusercontent.com/20718563/182313731-0622a2ea-5228-4670-932d-1acbe1d3ee12.png)

**Comment by MisterLuffy** [comment]
尝试复现了一下，这似乎是一个 FireFox 的问题。在 [这个例子](https://codesandbox.io/s/elated-jackson-vqvopl?file=/demo.js) 中，如果点击右侧的灰色区域，`onClick` 回调是无法被触发的。
![image](https://user-images.githubusercontent.com/29861850/183020351-35aa01dd-6005-4134-88dd-eeaea7d49780.png)

**Comment by eijil** [comment]
input style 加 pointerEvents: 'none' 可以么

**Comment by eijil** [comment]
> 尝试复现了一下，这似乎是一个 FireFox 的问题。在 [这个例子](https://codesandbox.io/s/elated-jackson-vqvopl?file=/demo.js) 中，如果点击右侧的灰色区域，`onClick` 回调是无法被触发的。 ![image](https://user-images.githubusercontent.com/29861850/183020351-35aa01dd-6005-4134-88dd-eeaea7d49780.png)

pointerEvents:focused ?'none':'auto'  这样可以么？

**Comment by edc-hui** [comment]
我来修复此问题

**Comment by edc-hui** [comment]
@MisterLuffy 你好，请问下更新快照的命令是什么？CONTRIBUTING.zh-CN.md文档上面没有找到
