### ISSUE TITLE
需要协助. Trigger组件定位问题

### ISSUE THREAD

**Issue by OrrinHatch** [arco-design/arco-design#1234]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
类似与MUI的anchorEl 
```
<Popper id={id} open={open} anchorEl={anchorEl}>
        <Box sx={{ border: 1, p: 1, bgcolor: 'background.paper' }}>
          The content of the Popper.
        </Box>
</Popper>
```

## What problem does this feature solve?
Trigger根据子组件进行定位, 是否可以支持手动传入定位元素

## Extra info
例如 一个button组件被Trigger组件包裹了, Trigger自定义了一些菜单项, 点击某一处菜单打开另外的Trigger组件, 我希望它的定位也能根据button进行定位, 我该如何去做呢?  我尝试了Trigger组件继续嵌套Trigger,这是框架所不允许的!

**Comment by OrrinHatch** [comment]
<img width="452" alt="截屏2022-08-04 17 49 53" src="https://user-images.githubusercontent.com/99718299/182818404-e17fba74-1d4c-43ce-8859-c9e169d8353b.png">

**Comment by yinkaihui** [comment]
> 例如 一个button组件被Trigger组件包裹了, Trigger自定义了一些菜单项, 点击某一处菜单打开另外的Trigger组件, 我希望它的定位也能根据button进行定位, 我该如何去做呢? 我尝试了Trigger组件继续嵌套Trigger,这是框架所不允许的!

你好，Trigger 是可以嵌套 Trigger 的。 这里提供一个思路


```

const [popupVisible, setPopupVisible] = useState(false);
<Trigger popupVisible={popupVisible} onVisibleChange={setPopupVisible}>
  <Trigger
    popup={() => {
      return (
        <ul>
          <li onClick={() => setPopupVisible(true)}>1</li>
          <li>2</li>
          <li>3</li>
        </ul>
      );
    }}
  >
    <span>text</span>
  </Trigger>
</Trigger>;

```

**Comment by OrrinHatch** [comment]
按照以上的方式,并不能允许! 
https://codepen.io/orrinhatch/pen/NWYzRLY?editors=1111

**Comment by yinkaihui** [comment]
https://codepen.io/yinkaihui/pen/abjOEmr?editors=0010 属性名称拼错了 ，可以调整下再看看
