### ISSUE TITLE
unsupport happyLoader plugin

### ISSUE THREAD

**Issue by zhangxuyang-web** [arco-design/arco-design#124]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** "@arco-design/web-react": "^2.24.0",
- **系统版本:** mac
- **浏览器版本:** chorme
- **复现地址:** https://arco.design/issue-helper?repo=arco-design

## 预期结果
~

## 复现步骤
When use happyPack plugin, 
The following information is displayed:

arco-design/webpack-plugin]: less-loader not found! The theme and modifyVars has no effective, please check if less-loader is added.
arco-design/webpack-plugin]: babel-loader not found! Import on demand has no effective, please check if babel-loader is added.

      new HappyPack({
        id: "babel-loader",
        loaders: [
          {
            loader: "babel-loader",
            options: {
              cacheDirectory: true,
              cacheCompression: true,
              presets: [
                "@babel/preset-env",
                "@babel/preset-react",
                "@babel/preset-typescript"
              ],
              plugins: [
                [
                  "babel-plugin-import",
                  {
                    libraryName: "@arco-design/web-react",
                    libraryDirectory: "es",
                    camel2DashComponentName: false,
                    style: true // 样式按需加载
                  }
                ],
                "transform-class-properties",
                "@babel/plugin-transform-runtime",
                "babel-plugin-styled-components",
                "babel-plugin-react-scoped-css",
                isDev && "react-refresh/babel"
              ].filter(Boolean)
            }
          }
        ]
      }),

**Comment by PengJiyuan** [comment]
@kirazxyun 看下

**Comment by kirazxyun** [comment]
@zhangxuyang-web  你好，happypack 的打包机制使我们的插件处理失效了，具体解决方案还没有找到，要麻烦您稍等一周，我们研究一下如何解决这个问题～

**Comment by WooodHead** [comment]
遇到了同样的问题。

**Comment by yaogengzhu** [comment]
解决了么？

**Comment by kirazxyun** [comment]
@zhangxuyang-web 这个问题在 `@arco-plugins/webpack-react` 这个包里已经解决了，请将 `@arco-design/webpack-plugin` 替换成 `@arco-plugins/webpack-react` 使用方法是一致的，无需修改其他。
