### ISSUE TITLE
option组件，不用i18n绑定值的时候，会报错。2.29.0以下没问题

### ISSUE THREAD

**Issue by zoomc** [arco-design/arco-design#1240]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome103.0.5060.134

**Comment by MisterLuffy** [comment]
Plz reopen it after provide more information.
