### ISSUE TITLE
暗黑模式中Form组件Input选择提示内容，UI错误

### ISSUE THREAD

**Issue by fengxinhhh** [arco-design/arco-design#1242]
如图：
![image](https://user-images.githubusercontent.com/78004597/183057481-f58a2043-a0fc-4d0f-a3f2-12a46295b7d6.png)
![image](https://user-images.githubusercontent.com/78004597/183057491-9b172364-59ad-4c7b-bd35-2c794ccc2e39.png)

**Comment by yinkaihui** [comment]
chrome 下表单的自动填充效果导致的，实际业务使用时可以在`Form` 设置 `autoComplete=off`

**Comment by fengxinhhh** [comment]
发现了，确实只有chrome会这样，但我觉得文档对于用户来讲这看起来像是一个bug

**Comment by fengxinhhh** [comment]
我提个pr吧

**Comment by yinkaihui** [comment]
#1279
