### ISSUE TITLE
怎么使用配置文件？

### ISSUE THREAD

**Issue by tomguan** [arco-design/arco-design#1243]
arch-design-pro 脚手架创建的项目。有没有配置文件之类的，根据部署的环境， 选择不同的 请求host

**Comment by yuhan0709** [comment]
> arch-design-pro 脚手架创建的项目。有没有配置文件之类的，根据部署的环境， 选择不同的 请求host

1. 在执行脚本的时候加上 [webpack环境变量](https://webpack.docschina.org/guides/environment-variables/) 
2. 通过 [webpack.DefinePlugin](https://juejin.cn/post/6844903728772808717) 把变量注入到代码里
`vite` 跟 `next` 应该也有类似的方法 ，可以搜一下
