### ISSUE TITLE
table children列支持子列的排序

### ISSUE THREAD

**Issue by YPBQWE** [arco-design/arco-design#1250]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.38.1
- **框架版本:** 16.14.0
- **浏览器版本:** chrome103.0.0.0

## 预期结果
1.预期子列应该也进行排序

## 复现步骤
1. 在column中添加children子列
2. 在子列中添加sorter排序
3.点击排序无反应

**Comment by PengJiyuan** [comment]
麻烦提供一下 codesandbox 吧，我这里试了一下是可以排序的
