### ISSUE TITLE
申请 IconBox 快速上手指南

### ISSUE THREAD

**Issue by Ohcui** [arco-design/arco-design#1251]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
当前公开版本 IconBox 无快速上手指南，创建新项目时“字体前缀”和“npm 包名”无解释，用户难以创建新 IconBox 项目并应用到项目中

**Comment by n0ruSh** [comment]
可以参考下这里的文档哈 ～

![image](https://user-images.githubusercontent.com/7504237/183833272-6dc3bfd5-0ff5-46fd-acde-f7eaf98134f6.png)
