### ISSUE TITLE
使用Modal.info，提示需要支持react18

### ISSUE THREAD

**Issue by wenyanxiang0415** [arco-design/arco-design#1256]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.37.2
- **框架版本:** 18.2.0
- **浏览器版本:** chrome103.0.0.0

## 预期结果
组件支持react18

## 复现步骤
使用Modal.info弹窗提示信息，浏览器提示，react_devtools_backend.js:4026 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by yinkaihui** [comment]
#1367
