### ISSUE TITLE
Select  使用自定义 option 组件问题

### ISSUE THREAD

**Issue by huxiangtao** [arco-design/arco-design#126]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react: 2.18.0
- **系统版本:** macOS Monterey 12.0.1
- **浏览器版本:** 95.0.4638.69（正式版本） (x86_64)
- **复现地址:** https://webide.bytedance.net/s/d8cn7zrl?file=/index.js

## 额外补充
Select  使用自定义 option 组件的时候，在触发下拉框展开的时候，之前选中的 option 无法保持高亮效果

## 预期结果
选中某个选项后，再点击 select，下拉框出现后，之前选中的项会保持 hover 的样式（背景色及字体加粗）

## 复现步骤
选中某个选项后，再点击 select，下拉框出现，之前选中的 option 高亮效果无法保持

**Comment by MisterLuffy** [comment]
Same issue with #125
