### ISSUE TITLE
table 组件固定列样式混乱

### ISSUE THREAD

**Issue by dora-exku** [arco-design/arco-design#1261]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.38.1
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/bold-lake-tx8y9v

## What is expected?
修复好样式

## Steps to reproduce
见链接

**Comment by PengJiyuan** [comment]
两个问题：
1. 每个 column 都需要设置 dataIndex
2. 有一列需要不设置宽度

改完后的代码：https://codesandbox.io/s/divine-frog-vwgmsg?file=/src/App.js
