### ISSUE TITLE
Why is today's date disabled? The shortcut shownowbtn can still be used

### ISSUE THREAD

**Issue by SeanHit** [arco-design/arco-design#1265]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.35.1
- **Framework version:** 17
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/dreamy-liskov-ihyd2u?file=/demo.js

## What is expected?
The disabled date contains the current time. The current time cannot be operated

## Steps to reproduce
 <DatePicker
      style={{ width: 200 }}
      // why showNowBtn default value is true
      disabledDate={(current) => current.isBefore(dayjs())}
    />

**Comment by SeanHit** [comment]
![image](https://user-images.githubusercontent.com/51781927/184283453-8c51fcd4-e242-486a-b3b1-22ff28c84421.png)

**Comment by PengJiyuan** [comment]
disabledTime cannot prevent quick selection, you can set `showNowBtn=false` to hide button 「today」.
