### ISSUE TITLE
Select同时开启allowCreate和showSearch，远程搜索返回的数据value和输入的内容一致时，只展示手动创建的选项，无法选择传入选项

### ISSUE THREAD

**Issue by chenyikai-eason** [arco-design/arco-design#1269]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.38.1
- **Browser:** chrome104.0.0.0

## What is expected?
value相同时，应该展示传入option的选项，而不是创建的选项

## Steps to reproduce
1. 使用Select，同时开启allowCreate和showSearch
2. onSearch搜索函数中，setOptions( [{ label: 'test',  value: 'test', extra: 'abcd' }])
3. Select输入test，只展示一个选项，该选项为allowCreate创建的选项，而不是options传入的选项，无法获取传入option的extra等内容

**Comment by MisterLuffy** [comment]
试了一下在 `2.28.0` 之后的版本里这个问题已经不存在了，可以升级一下。https://codesandbox.io/s/laughing-feistel-74rpe7?file=/demo.js
