### ISSUE TITLE
官方提供多主题支持

### ISSUE THREAD

**Issue by wuchunfu** [arco-design/arco-design#1272]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
抖音创作服务平台品牌风格

## 预期解决问题
希望支持像 semi-design 提供的多主题，比如：抖音创作服务平台品牌风格、飞书Universe Design风格、剪映 - 艺术家开放平台风格、火山引擎品牌风格、一个轻量美观的桌面端设计系统、Figma theme by Semi Design 等，最希望支持的主题是 抖音创作服务平台品牌风格

**Comment by PengJiyuan** [comment]
https://arco.design/themes。风格配置平台看一下，已经 3000+ 主题了，可以看下有没有你需要的，也可以自己维护一个主题。
