### ISSUE TITLE
TimePicker.RangePicker为小时精度时，支持和DatePicker.RangePicker一样的交互模式

### ISSUE THREAD

**Issue by claneo** [arco-design/arco-design#1281]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
no

## What problem does this feature solve?
快速选择时间范围

类似下图，但是只有 0-23 小时可选

另外分钟精度说不定也可以用一样的交互，相当于把月换成小时，把日换成分钟

![image](https://user-images.githubusercontent.com/11372744/184569870-08d5573d-9a8b-4349-8b6d-cc4da6e6c7dc.png)

**Comment by PengJiyuan** [comment]
额 这个还是用物料来实现吧，不在交互设计里
