### ISSUE TITLE
select多选模式且宽度样式设置为auto时，focus时宽度会突变

### ISSUE THREAD

**Issue by legolaserea** [arco-design/arco-design#1283]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.39.0
- **框架版本:** react 16.12.0
- **浏览器版本:** chrome104.0.0.0
- **复现地址:** https://codepen.io/lenntony/pen/gOeBQpX?editors=0010

## 额外补充
目前版本表现是，focus时宽度会增加4px。

## 预期结果
1. focus时组件宽度不变化
2. 在点击删除后，组件自动缩小宽度

## 复现步骤
1. 设置select为多选模式，设置宽度style为auto，设置默认选项
2. 页面加载完成后，点击select使得处于focus状态

**Comment by MisterLuffy** [comment]
仅优化了显式指定 `showSearch = false` 的情况。因为在允许输入的情况下，聚焦之后必须保留输入框的宽度以保证光标可见，并且这种情况下输入文本也会使组件宽度改变，也算是符合预期的表现。
