### ISSUE TITLE
Select component drag bug

### ISSUE THREAD

**Issue by linzhefeng** [arco-design/arco-design#1285]
When I set dragToSort to true and update disabled value from false to true at the same time, there is a problem with the Select component
bug demo: https://codesandbox.io/s/clever-mahavira-dxvrhv?file=/demo.js
screenshot：
![image](https://user-images.githubusercontent.com/50944875/184616725-12c74620-4878-4819-8627-ad4c53b6e60e.png)

**Comment by MisterLuffy** [comment]
Hi, did you save your demo code? It seems like this now.
![image](https://user-images.githubusercontent.com/29861850/185539126-2f062c58-3e62-4c5b-a985-0f0e285d3fff.png)

**Comment by MisterLuffy** [comment]
Plz reopen it after providing a valid demo.
