### ISSUE TITLE
为啥Input正常情况下会有灰色的背景色，给人的感觉是被禁用的

### ISSUE THREAD

**Issue by moshuchao** [arco-design/arco-design#1288]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.0
- **Browser:** chrome103.0.0.0

![image](https://user-images.githubusercontent.com/27390758/184809444-cd9816fd-bdcb-4693-920f-cc3056c220d6.png)

**Comment by MisterLuffy** [comment]
你好，这是我们组件的面性设计风格。如果你觉得这种风格不适合你的使用场景，也可以尝试使用 Arco 主题商店定制样式，比如这个 [线性主题](https://arco.design/themes/design/544/setting/components/Input)。
