### ISSUE TITLE
在循环中使用popover，气泡卡片不能正常关闭

### ISSUE THREAD

**Issue by ddamowang** [arco-design/arco-design#1289]
我在table中尝试使用popover组件，并在popover中使用button，希望能够使用button关闭popover。
我为每个popover绑定不同的 :popup-visible，然后通过点击事件修改popover的展示状态，可以实现这一功能，
但如果我点击打开一个popover后不关闭，再打开其他的popover则可以打开多个卡片。
代码：
![image](https://user-images.githubusercontent.com/49475299/184843789-832812c2-6a99-4304-9b16-b468e5f9c191.png)
效果实例：
![image](https://user-images.githubusercontent.com/49475299/184844028-8f2979ed-da7c-49b3-aba7-87ff78960774.png)
请问我该如何修改，或如何关闭当前已经打开的popover？

**Comment by yinkaihui** [comment]
在打开第二个弹出层时设置上一个弹出层的 popup-visible = false ? 可能需要在业务里维护多个弹出层开发的现实状态
