### ISSUE TITLE
Tree nodes blink when expanded

### ISSUE THREAD

**Issue by youkeyao** [arco-design/arco-design#1299]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.39.0
- **框架版本:** React 18
- **浏览器版本:** chrome104.0.0.0
- **复现地址:** https://codesandbox.io/s/epic-swirles-xjevld

## 预期结果
the children of this node will blink

## 复现步骤
click on a node to expand

**Comment by yinkaihui** [comment]
fixed in #2338
