### ISSUE TITLE
官网设计资源中后台最佳实践链接失效 404

### ISSUE THREAD

**Issue by sroxck** [arco-design/arco-design#130]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** 无
- **系统版本:** macOs BigSur 11.6
- **浏览器版本:** 谷歌 95.0.4638.69（正式版本） (arm64)
- **复现地址:** https://arco.design/react/docs/start

## 预期结果
如果开放,请展示figma内容,不开放可以隐藏掉这个链接

## 复现步骤
导航栏设计中,ArcoPro 中后台最佳实践figma项目无法访问
![image](https://user-images.githubusercontent.com/51316180/141080916-2f368797-73c4-4bdf-a832-547c9bf60755.png)

**Comment by PengJiyuan** [comment]
目前 pro 正在做 V2 升级，会提高设计质量，也会增加一些经典场景页面，所以资源先下掉了。我们把链接隐藏一下吧

**Comment by sroxck** [comment]
好的👌🏻
