### ISSUE TITLE
ConfigProvider配置了prefixCls后， Table设置scroll 或者 column设置了 fixed: 'left' | 'right', 界面白屏

### ISSUE THREAD

**Issue by JhonYoung** [arco-design/arco-design#1314]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.0
- **Framework version:** react@17.0.1
- **Browser:** chrome104.0.0.0

## What is expected?
期望配置了prefixCls 可以正常使用

## Steps to reproduce
console提示
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('xxx arco-table-has-fixed-col-right') contains HTML space characters, which are not valid in tokens.

**Comment by PengJiyuan** [comment]
无法复现
