### ISSUE TITLE
table虚拟滚动和固定列样式冲突

### ISSUE THREAD

**Issue by dongzhe3917875** [arco-design/arco-design#1319]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.1
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/eager-firefly-1nkbdb?file=/demo.js

## What is expected?
1. 无论条数是多少，固定列显示和交互正常

## Steps to reproduce
1. 开启table的虚拟滚动和固定列
2. 把数据条数设置到虚拟滚动阈值以下
3. 发现固定列相关样式丢书

**Comment by PengJiyuan** [comment]
阈值是100，暂时 `virtualized={data.length > 100}` 处理吧
