### ISSUE TITLE
Message 组件支持 prefix 仅受 ConfigProvider 局部作用

### ISSUE THREAD

**Issue by Mistyyyy** [arco-design/arco-design#1340]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
not found

## What problem does this feature solve?
我的 ConfigProvider 只作用了一个小模块，改了 prefixCls， 但是只要加载了这个模块后，全局的 Message 组件的 prefixCls 都变了，Message 组件不在这个模块内

**Comment by yuhan0709** [comment]
这个需要新增 `useMessage` 方法，类似 `useModal` 然后 `Notification`  也需要支持下。
