### ISSUE TITLE
a-tree组件，某个节点，disable状态下，子节点选中，父节点无状态改变

### ISSUE THREAD

**Issue by wangziqin123** [arco-design/arco-design#1348]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.2
- **Framework version:** 2.39.3
- **Browser:** chrome104.0.0.0

## Extra info
应该是某个节点在disabled状态下，子阶段选中，disable的节点呈半选diabled状态

**Comment by MisterLuffy** [comment]
Arco Vue 版本的 Issue，请至 https://github.com/arco-design/arco-design-vue/issues。
