### ISSUE TITLE
Autocomplete can't focus when be put inside a Popconfirm of dropdown

### ISSUE THREAD

**Issue by hijiangtao** [arco-design/arco-design#1352]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.2
- **Framework version:** React 
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/autocomplete-cant-focus-when-put-inside-a-popconfirm-of-dropdown-kle0gf?file=/demo.js

## Extra info
maybe it's not a problem of autocomplete itself, I replace it with input and other component, the same error occurs.

**Comment by MisterLuffy** [comment]
需要为 `Popconfirm` 的时间阻止冒泡，为了避免 `Dropdown` 的触发节点在点击下拉菜单时失焦，点击 MenuItem 时会把焦点重新赋给 `Dropdown` 的触发节点。

https://codesandbox.io/s/autocomplete-cant-focus-when-put-inside-a-popconfirm-of-dropdown-forked-90xx28?file=/demo.js

**Comment by hijiangtao** [comment]
这层逻辑让组件库来包装是不是更合适一些？我写了一个 demo https://codesandbox.io/s/input-no-focus-problem-when-put-inside-a-popconfirm-of-dropdown-with-ant-design-wm2w9h
