### ISSUE TITLE
Drawer mask 点击事件会透传到组件外面

### ISSUE THREAD

**Issue by LaamGinghong** [arco-design/arco-design#136]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.24.0
- **系统版本:** MacOS BigSur
- **浏览器版本:** ChromeV95
- **复现地址:** https://codesandbox.io/s/cool-moon-ire4o

## 预期结果
外面的点击事件不会被触发

## 复现步骤
1. 点击打开抽屉
2. 点击mask关闭抽屉

**Comment by kirazxyun** [comment]
你好，子组件的 click 事件是会冒泡到父级的，这个现场符合预期哦

**Comment by LaamGinghong** [comment]
> 你好，子组件的 click 事件是会冒泡到父级的，这个现象符合预期哦

按照之前在oncall聊的，drawer和modal对外提供mask的点击事件用于屏蔽

**Comment by kirazxyun** [comment]
我们同学给出了很好的解决方案就是用 div 包裹 drawer 或者 modal，在 div 上阻止事件，你可以试试

**Comment by LaamGinghong** [comment]
> 我们同学给出了很好的解决方案就是用 div 包裹 drawer 或者 modal，在 div 上阻止事件，你可以试试
> 
> > > 你好，子组件的 click 事件是会冒泡到父级的，这个现象符合预期哦
> > 
> > 
> > 按照之前在oncall聊的，drawer和modal对外提供mask的点击事件用于屏蔽

有一点问题，因为我没有像给出的demo一样直接将drawer组件放到jsx里面通过visible来控制使用，我是实现了一个 useDrawer 的函数，通过API调用的方式去控制drawer的显示。
```jsx
function App() {
  const [drawer, context] = Drawer.useDrawer()

  const handleCreate = () => {
    drawer({
       title: 'title',
       children: 'content'
    })
  }

  return <>{context}</>
```

**Comment by LaamGinghong** [comment]
@kirazxyun 如果给出的方案必须通过container去阻止事件冒泡，会多一些无用的胶水代码

**Comment by kirazxyun** [comment]
> @kirazxyun 如果给出的方案必须通过container去阻止事件冒泡，会多一些无用的胶水代码

drawer 可以加事件。但是 modal 因为已经将事件解构到了内层 dom ，所以无法通过添加事件的方式来阻止事件冒泡，只能写多余的结构来达到目的了。
