### ISSUE TITLE
Table onFilter 当清空所有的过滤选项时回调不执行，且 onFilter 的value参数拿到的是单个值，而不是一个数组，在 vue 里面就是一个数组

### ISSUE THREAD

**Issue by jadestrong** [arco-design/arco-design#1372]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.3
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/reverent-dew-r6mbnw?file=/index.js:121-143

## What is expected?
预期是勾掉所有要显示的 salary 之后都不展示

## Steps to reproduce
1. 默认是勾选了所有的 filter;
2. 当将所有的 filter 都勾掉之后，数据就全部显示了

**Comment by PengJiyuan** [comment]
没看明白，勾掉所有不就是没有筛选条件了，肯定是显示所有啊

**Comment by jadestrong** [comment]
是这样，默认是想勾选所有的，这样所有都展示，用户可以勾掉它不想要的，如果都勾掉了，就显示 NO Data 了，但是现在都勾上和都不勾是一个表现，当都不勾的时候，看起来就根据没去执行过滤函数，我记得我试了 arco-design-vue 表现就是符合预期的

**Comment by jadestrong** [comment]
![image](https://user-images.githubusercontent.com/18475217/191891164-dd206828-21b8-4dfd-9406-2ead1d2c34f5.png)
我重新改了下上面的 codesandbox demo, 改了下 onFilter ，只显示 value 和勾选项相等的项，默认全选了，当我点掉所有的filter选项时，应该都不展示的，但是现在的表现就是，全选和全不选的效果是一样的，这应该是不对的吧

**Comment by PengJiyuan** [comment]
点掉所有的时候，表示没有任何筛选条件，也就是不需要筛选，显示的就是全量数据。这个逻辑一直都是这样的，未来也不会改，改了会造成更大的breakingchange。
