### ISSUE TITLE
InputNumber组件formatter后带有空格不能被删除

### ISSUE THREAD

**Issue by llabbss** [arco-design/arco-design#1374]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.27.1
- **Framework version:** react: 17.0.0
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/heuristic-fermi-02fsxm?file=/src/index.js

## What is expected?
希望formatter之后的数据可以正常删除

## Steps to reproduce
在使用formatter格式化之后，inputNumber中的value带上了空格，在删除时，如果遇上空格，删除便不会执行，在onChange函数中也不会执行；
目前我们使用keydown事件进行判断处理

**Comment by MisterLuffy** [comment]
调试了一下发现：在删除空格之后组件内部是把值调整为 `1000` 的，但由于 `formatter` 的存在，输入框的文本被重新格式化为 `1000 `，所以就选入了一个循环。

![image](https://user-images.githubusercontent.com/29861850/190582859-9232aff6-ae70-47ef-9ae7-081b0cfc7757.png)

可以通过修改你的正则为 `/(.{4}(?!$))/g` 来避免为末尾的数字添加空格，从而解决这个问题。
