### ISSUE TITLE
<Link> 会造成页面刷新

### ISSUE THREAD

**Issue by yuanzhixiang** [arco-design/arco-design#1376]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
<Link> 会造成页面刷新，有没有可以不造成页面刷新但更新页面的组件。
Acro 中有类似 react-route 的 Link 的组件么？

**Comment by wymli** [comment]
+1
