### ISSUE TITLE
增加文件夹类的icon

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design#1381]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/58337359/189490689-c00218d0-5fdf-4654-b931-3f89fcf0230d.png">

## What are the similar cases of this feature

<FolderAddOutlined /> <FolderOutlined /> <FolderOpenOutlined />

## What problem does this feature solve?
类似文件夹相关的集合操作找不到相关图标，这种应该是比较常见需求吧

**Comment by yuhan0709** [comment]
官网里有呢～ <img width="1048" alt="image" src="https://user-images.githubusercontent.com/23137528/190048243-07ee7dbb-40e8-4c74-8cee-6115e1483811.png">

**Comment by lin-mt** [comment]
没有展开文件夹的icon
________________________________
发件人: yuhan0709 ***@***.***>
发送时间: Wednesday, September 14, 2022 10:56:56 AM
收件人: arco-design/arco-design ***@***.***>
抄送: lin-mt ***@***.***>; Author ***@***.***>
主题: Re: [arco-design/arco-design] 增加文件夹类的icon (Issue #1381)


官网里有呢～ [image] <https://user-images.githubusercontent.com/23137528/190048243-07ee7dbb-40e8-4c74-8cee-6115e1483811.png>

―

**Comment by PengJiyuan** [comment]
可以去 https://arco.design/iconbox 找找看，自带的图标可能会有些场景覆盖不到
