### ISSUE TITLE
能否提供一个upload的自定义上传的onsucess等的demo

### ISSUE THREAD

**Issue by wanhusheng** [arco-design/arco-design#139]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
能否提供一个upload的自定义上传的onsucess等的demo

## What problem does this feature solve?
能否提供一个upload的自定义上传的onsucess等的demo

## Extra info
感谢

**Comment by yinkaihui** [comment]
https://arco.design/react/components/upload#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0%E5%AE%9E%E7%8E%B0
