### ISSUE TITLE
table点击操作列的编辑按钮，编辑列表某一项内容使文字过长，然而设置了tooltip和ellipsis在编辑完成后，列表数据刷新了，tooltip没有展示，刷新页面，才能显示tooltip

### ISSUE THREAD

**Issue by yimengzhiqian** [arco-design/arco-design#1409]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.0
- **Framework version:** vue table 2.36.0
- **Browser:** chrome104.0.0.0

## What is expected?
期望编辑完成，数据改变，tooltip可以展示出来

## Steps to reproduce
1、列表中每一项设定最大宽度，tooltip和ellipsis属性，点击操作列的编辑按钮，弹窗显示编辑面板
2、编辑列表中某一项内容，使内容超出设定的最大宽度，保存数据，编辑弹窗关闭
3、列表数据刷新，超出设定宽度的项显示了...但是鼠标划入，未显示tooltip全部内容
4、刷新页面，该超出设定宽度的项，可以显示tooltip内容展示全部字段（同理从有tooltip再减少字段内容，tooltip也未消失，而是需要刷新页面才能消失）

**Comment by yuhan0709** [comment]
复现的 codepen 给一下

**Comment by yuhan0709** [comment]
用了 typography 吗

**Comment by yimengzhiqian** [comment]
> 复现的 codepen 给一下

https://codesandbox.io/s/zen-leftpad-xn5n0o?file=/src/App.vue 已经在用户群说过了，你们的开发已确认是bug

**Comment by PengJiyuan** [comment]
额。。vue的去vue仓库提啊。https://github.com/arco-design/arco-design-vue
