### ISSUE TITLE
table排序无法去掉默认（不排序）的情况

### ISSUE THREAD

**Issue by yimengzhiqian** [arco-design/arco-design#1415]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.0
- **Framework version:** vue 2.40.0
- **Browser:** chrome105.0.0.0

## What is expected?
期望可以通过设置sortDirections中的值来控制是否需要默认（不排序）的情况

## Steps to reproduce
1、设置排序sortDirections=['ascend','descend'];
2、点击切换排序，一直点击降序，排序字段不是一直降序，而是升序、降序、不排序来回轮还换，想要可以自定义控制排序

**Comment by PengJiyuan** [comment]
确实是无法去掉不排序的

**Comment by PengJiyuan** [comment]
真要做可以通过受控解决吧
