### ISSUE TITLE
Cascader 取消父子关联多选的组件，从接口获取的数据放进去，里面的复选框没办法点击

### ISSUE THREAD

**Issue by start-point** [arco-design/arco-design#1423]
从接口拿数据渲染没办法点击，

如果直接定义一个 const option = [...写死数据]   这样放进去 是可以点击的

但是数据没办法写死，这个组件有缺陷 没办法用

如果不理解 我可以提供例子

**Comment by start-point** [comment]
![image](https://user-images.githubusercontent.com/83851349/192078439-76dad79a-3948-4794-a765-d7de90c76b34.png)

那个定时器 模拟接口，这样的写法 页面上显示的 Cascader 组件是没办法点击选中的 希望能解决一下

**Comment by start-point** [comment]
该问题指针对：父子解除关联的级联菜单
还有 官网的这个组件也有问题，选中了如果子级全部被选中了，就没有办法选择父级了

**Comment by start-point** [comment]
俩个问题 望解决

**Comment by curedboy** [comment]
我也发现了这个问题，当某个项的children为空数组时，就变得无法选中。这里有个示例： https://codesandbox.io/s/exciting-chandrasekhar-v1p689?file=/demo.js

**Comment by start-point** [comment]
好兄弟 根据你这个例子 我截个图，在给级联菜单 加上父子取消关联的属性的时候
![image](https://user-images.githubusercontent.com/83851349/193840759-f512eece-3745-4e90-843e-9cd05b6d1f48.png)

就如图上而言，左侧 可乐 雪碧被选择了，但是前面的饮料是无法选中的 根本就点击不了

这个也就是 我上面说的 子级被全部选中了 父级无法选择的问题
