### ISSUE TITLE
Switch 组件支持自定义开启和关闭时的 Value 

### ISSUE THREAD

**Issue by daiwawawa** [arco-design/arco-design#1432]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
-

## What problem does this feature solve?
业务中经常会有 0 代表关闭 1 代表开启的需求，通过自定义开启和关闭时的 Value 可以解决

**Comment by PengJiyuan** [comment]
```js
const newValue = value ? 1 : 0
```
是不是就行了，这个感觉没必要支持
