### ISSUE TITLE
InputTag add maxTagCount prop

### ISSUE THREAD

**Issue by zyc95** [arco-design/arco-design#1445]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What problem does this feature solve?
The maximum number of tags to be displayed, after that it will be displayed as  N

**Comment by zyc95** [comment]
Can anyone help support this feature? Need to collapse tags when there are many input tags

**Comment by MisterLuffy** [comment]
You can custom tag rendering logic via `renderTag`. View this [demo](https://arco.bytedance.net/react/en-US/components/input-tag#Render-tag).

**Comment by zyc95** [comment]
ok, I will tty it
