### ISSUE TITLE
The page shakes when you select option for the first time

### ISSUE THREAD

**Issue by Semlaw** [arco-design/arco-design#1446]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Browser:** chrome105.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/hsoor0
![2JhQJlBdiE](https://user-images.githubusercontent.com/18466228/194735035-a2de96bc-72da-4b61-886d-ee849291d68a.gif)

**Comment by yinkaihui** [comment]
试下 animation=false ?

**Comment by MisterLuffy** [comment]
This bug is fixed at `2.46.1`.
