### ISSUE TITLE
Cascader搜索场景下，目前是大小写敏感的。希望可以允许开发者指定是否大小写敏感

### ISSUE THREAD

**Issue by linapengzhe** [arco-design/arco-design#1456]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Cascader搜索场景下，目前是大小写敏感的。希望可以允许开发者指定是否大小写敏感

## What problem does this feature solve?
Cascader搜索场景下，目前是大小写敏感的。希望可以允许开发者指定是否大小写敏感

**Comment by yinkaihui** [comment]
可以通过 `filterOption` 自定义搜索规则～
