### ISSUE TITLE
**Tabs** when using card or card-gutter type, the style is wrong sometimes

### ISSUE THREAD

**Issue by Bluecracker** [arco-design/arco-design#147]
The following pics shows when the <Tabs> is **NORMAL**: there's no line under the tab which is clicked
![image](https://user-images.githubusercontent.com/78125933/141437667-e220f833-0b66-49ff-a61b-7e9ea42e0767.png)
![image](https://user-images.githubusercontent.com/78125933/141435715-ebbe19f1-9182-4310-8c08-f167cddde221.png)

However sometimes it is **ABNORMAL**: there **IS** a line under the tab and the tabs seems not align
![image](https://user-images.githubusercontent.com/78125933/141437227-c5ea8c75-65f4-4f39-b159-18bdec6fb34d.png)
![image](https://user-images.githubusercontent.com/78125933/141437083-c3c5f509-3f63-48ed-b7cb-f5ca80eca235.png)

**Comment by PengJiyuan** [comment]
Can you provide a codepen to reproduce？
