### ISSUE TITLE
Menu.Submenu 希望支持仅点击下拉箭头可展开子菜单的功能

### ISSUE THREAD

**Issue by shadowfish07** [arco-design/arco-design#1471]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
做一个支持嵌套分类栏，需要能够点到子菜单

## What problem does this feature solve?
现在设置Menu.Submenu selectable后，行为和预期还是不太一致，点击子菜单标题，虽然会有选中态，但是还会触发收缩、打开子菜单的表现，很奇怪

**Comment by MisterLuffy** [comment]
选中和展开是不冲突的两个行为，`selectable` 只是对于普通 SubMenu 增添了一个可选中的特性。

**Comment by shadowfish07** [comment]
> 选中和展开是不冲突的两个行为，`selectable` 只是对于普通 SubMenu 增添了一个可选中的特性。

嗯嗯，是的，那么问题本质应该是目前暴露的API不能支持去更加灵活地控制收缩的逻辑，如果能够提供下拉箭头的触发事件就好了

**Comment by yinkaihui** [comment]
直接定制下 `icons.horizontalArrowDown` ，自行设置个箭头图标，并添加监听事件？
