### ISSUE TITLE
Cascader【mode='multiple'】 组件中数据中children为空数组的时候，选择单项不生效  。

### ISSUE THREAD

**Issue by 15822115472** [arco-design/arco-design#1474]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.40.2
- **浏览器版本:** chrome106.0.0.0
- **复现地址:** https://codepen.io/15822115472/pen/NWMmpEP?editors=001

## 预期结果
children为[]的时候也可以正常点选

**Comment by yinkaihui** [comment]
`2.41.0-beta.0` 已修复
