### ISSUE TITLE
自定义筛选清空后 icon未清空高亮

### ISSUE THREAD

**Issue by liangjiax** [arco-design/arco-design#1476]
自定义筛选清空后 icon未清空高亮
https://codesandbox.io/s/lively-glitter-w2f71u?file=/demo.js

**Comment by luckyship** [comment]
i find the reason, i will create pr to solve it.

**Comment by luckyship** [comment]
@liangjiax your code has error
```
setFilterKeys(value ? [value] : []);
```
the `value` is array, so it don't excute `[]`, you should update code below 
```
setFilterKeys(value.length ? [value] : []);
``

**Comment by liangjiax** [comment]
> 



> @liangjiax your code has error
> 
> ```
> setFilterKeys(value ? [value] : []);
> ```
> 
> the `value` is array, so it don't excute `[]`, you should update code below
> 
> ```
> setFilterKeys(value.length ? [value] : []);
> ``
> ```

感谢感谢  我也发现是我的问题了

**Comment by cat-uncles** [comment]
我用的是Cascader放到table自定义筛选，icon没有高亮
