### ISSUE TITLE
Button支持传入 ref

### ISSUE THREAD

**Issue by 18888628835** [arco-design/arco-design#1478]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
 您好，我在使用组件时，发现 Button 组件不能传入 ref，而 Antd 的 Button 组件实际上是可以传入 ref 的。这给某些需要使用模拟点击的场景提供了便利。比如，我想要控制 Popconfirm 的 ok 按钮时，如果允许传入 ref，那我就可以手动调用它了

## What problem does this feature solve?
请问 Button 组件是否能够支持传入 ref 呢？

**Comment by MisterLuffy** [comment]
支持的，可以参考这个 [Demo](https://codesandbox.io/s/silent-glade-5q6uit?file=/demo.js)。
