### ISSUE TITLE
select组件的popup的trigger缺少一个arco-select开头的类，导致主题风格配置平台上不能给select的popup自定义css样式

### ISSUE THREAD

**Issue by watermelon0314** [arco-design/arco-design#1479]
<img width="2105" alt="image" src="https://user-images.githubusercontent.com/82018215/196869136-ba79eecc-b056-4f61-830a-aa6b0d37a7a4.png">

**Comment by MisterLuffy** [comment]
`arco-select` 的类名不是挂在这个 DOM 上的，而是触发节点上。配置平台 less 的写法直接这么写就可以了：

```
.@{select-prefix-cls} {
  &-popup {
    padding: 6px;
  }
}
```
