### ISSUE TITLE
table 开启表头分组、最右侧列固定、水平滚动时，最右侧表头单元格边框样式有问题

### ISSUE THREAD

**Issue by sufengyong** [arco-design/arco-design#1480]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.39.3
- **Browser:** chrome106.0.0.0

## What is expected?
最右侧列的表头的边框和表格内容有断裂感

## Steps to reproduce
1. 初始化一个表格，表头开启分组、最右边的列固定、开启水平滚动
2. 将水平滚动条滚到中间，观察最右边的列的边框
3. 
![image](https://user-images.githubusercontent.com/22764370/196871544-00b6b508-6ed2-4167-8749-565d15f31c41.png)

**Comment by PengJiyuan** [comment]
无法复现
