### ISSUE TITLE
Table 配置checkbox后，selectedRowKeys改变时，columns->render会触发data.length次

### ISSUE THREAD

**Issue by zhaogang6682** [arco-design/arco-design#1485]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.40.2
- **浏览器版本:** chrome106.0.0.0
- **复现地址:** https://codesandbox.io/s/affectionate-hugle-kq1b11?file=/demo.js

## 预期结果
点击复选按钮，不会触发columns下的render

## 复现步骤
点击复选按钮，会触发data.length次columns下的render，可以看console
![image](https://user-images.githubusercontent.com/109260418/197107957-1808d344-2fe1-4c53-9683-8e1a8b733eba.png)

**Comment by xavier-zy** [comment]
我也遇到了这样的问题，整个table都会重新render

**Comment by zhaogang6682** [comment]
这个问题大约那个版本可以修复啊@yinkaihui
