### ISSUE TITLE
table组件设置日期自定义筛选框时，点击清除日期，onFilter函数内的筛选条件没有被删除

### ISSUE THREAD

**Issue by zlq055** [arco-design/arco-design#1491]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Framework version:** react：16.8
- **Browser:** chrome105.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/morning-firefly-mzubcw?file=/src/index.js

**Comment by luckyship** [comment]
@zlq055  you can try this.

```
onClear={() => {
  // setFilterKeys([]);
  confirm([]);
}}
```

**Comment by zlq055** [comment]
> luckyship

这个方法可以解决。谢谢！

**Comment by zlq055** [comment]
> @zlq055 you can try this.
> 
> ```
> onClear={() => {
>   // setFilterKeys([]);
>   confirm([]);
> }}
> ```



> @zlq055 you can try this.
> 
> ```
> onClear={() => {
>   // setFilterKeys([]);
>   confirm([]);
> }}
> ```

@luckyship 解决了。谢谢啦！

**Comment by zlq055** [comment]
请问 table 组件的刷新有什么方法吗？
________________________________
发件人: Xu Chao ***@***.***>
发送时间: 2022年10月24日 11:41
收件人: arco-design/arco-design ***@***.***>
抄送: zlq ***@***.***>; Mention ***@***.***>
主题: Re: [arco-design/arco-design] table组件设置日期自定义筛选框时，点击清除日期，onFilter函数内的筛选条件没有被删除 (Issue #1491)


@zlq055<https://github.com/zlq055> you can try this.

onClear={() => {
  // setFilterKeys([]);
  confirm([]);
}}


―
