### ISSUE TITLE
Transfer的item disabled掉之后，item包括其表示可拖动的icon全部置灰，但实际item仍可拖动，icon的表现与实际不符

### ISSUE THREAD

**Issue by 1371164370** [arco-design/arco-design#1498]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Framework version:** React 17.0.2
- **Browser:** chrome106.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/gallant-mestorf-tm632b?file=/demo.js

## What is expected?
当item实际可拖动时，希望拖动icon可以亮起

**Comment by MisterLuffy** [comment]
已在 `2.41.0-beta.1` 禁止拖动 `disabled` 的条目。
