### ISSUE TITLE
Popover 的触发方式为Click时，希望增加，容器发生了滚动，也会消失的属性开关选项

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#1505]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
antd不清楚是怎样的，我这边今天打不开他们官网。

## 预期解决问题
比如某些扩展内容显示，就比如头像吧，click点开后popover显示基本信息，当页面滚动的时候，不希望它一直显示，滚动的时候也会消失。就像设置了触发方式为：hover一样，但是不希望鼠标悬停在指定元素上就显示，而是点击。我看触发器Trigger有个containerScrollToClose属性，就用这个属性刚好！

## 补充 于 2022年10月25日 17:03:14
既然popover有了，那么顺便Tooltip也加上吧，虽然我可以通过Trigger来实现，但是代码臃肿了，不入直接使用官方组件，加个属性来的爽快！

## 我还提了另外一个需求，不知是否看到了？

- [Form表单验证，设置validateTrigger=blur后，增加验证回调函数或事件](https://github.com/arco-design/arco-design/issues/1466)

**Comment by yinkaihui** [comment]
所有的弹出型组件都可以通过 triggerProps 传入 Trigger 的属性，比如 `triggerProps={{ containerScrollToClose: true }}`

**Comment by kwooshung** [comment]
> 所有的弹出型组件都可以通过 triggerProps 传入 Trigger 的属性，比如 `triggerProps={{ containerScrollToClose: true }}`
我设置了，发现效果好像并不好使，我一会儿再试试去~

**Comment by kwooshung** [comment]
> 所有的弹出型组件都可以通过 triggerProps 传入 Trigger 的属性，比如 `triggerProps={{ containerScrollToClose: true }}`
确实可以，多谢啦！
