### ISSUE TITLE
bug：在 `Dropdown` 组件中嵌套使用 `Modal` 时， `Modal` 状态会受 `Dropdown` 的行为影响

### ISSUE THREAD

**Issue by amadeus711** [arco-design/arco-design#1506]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.40.2
- **框架版本:** ^17.0.0
- **浏览器版本:** chrome106.0.0.0
- **复现地址:** https://codesandbox.io/s/elated-tdd-ynpox7?file=/demo.js

## 预期结果
给 `Dropdown` 组件添加类似  `Modal` 组件的 `getChildrenPopupContainer ` 属性（不确定这样是否能根治）

## 复现步骤
1. 打开复现地址，将鼠标 hover 到 `Dropdown` 组件上，并点击 modal1 按钮
2. 当 `Modal` 弹出后，鼠标移出当前屏幕（比如移到浏览器地址栏）
3. 此时 `Modal` 受 `Dropdown` 影响，关闭，但实际上 `Modal` 的 `visible` 并没有改变（依然为 `true`）
4. 再次将鼠标 hover 到 `Dropdown`，下拉面板出来时  `Modal` 就会出现

**Comment by yuhan0709** [comment]
加一个 `unmountOnExit={false}` 就可以了
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/23137528/198498350-3955f36f-78ec-4247-ba34-3cab2c3d788c.png">

**Comment by amadeus711** [comment]
> 加一个 `unmountOnExit={false}` 就可以了 <img alt="image" width="1085" src="https://user-images.githubusercontent.com/23137528/198498350-3955f36f-78ec-4247-ba34-3cab2c3d788c.png">

这样是治标不治本吧，根本原因不是 `Modal` 的原因，而是 `Dropdown` 对 `Modal` 的影响。

**Comment by MisterLuffy** [comment]
这个行为实际上是符合预期的，Modal 作为 `dropdownList` 的子节点时，在 `dropdownList` 被销毁时它也将被一起销毁，这是 React 的特性。
避免这个问题只需要给 Modal 换个挂载位置就行了，Dropdown 里的按钮仅进行组件状态的切换：
![image](https://user-images.githubusercontent.com/29861850/199916770-69c223c6-c3e8-4433-a0a7-a70c7f248a5b.png)
