### ISSUE TITLE
表格设置onRow点击事件会跟多选框的change 事件产生冲突

### ISSUE THREAD

**Issue by lynn1286** [arco-design/arco-design#1507]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Browser:** chrome106.0.0.0

复现代码： https://codesandbox.io/s/wizardly-bird-4ei3w7?file=/demo.js

**Comment by yuhan0709** [comment]
这就是符合预期的呀，那你的预期是什么

**Comment by PengJiyuan** [comment]
没看出来哪儿冲突了，都是正常执行的

**Comment by lynn1286** [comment]
@PengJiyuan  Checkbox 的点击事件冒泡了呀，点击Checkbox触发了 onRow -> onClick 的事件了， 我不确定这个是组件库内部处理还是外部可以控制

**Comment by PengJiyuan** [comment]
我看了下你的 demo，rowSelection 也没有 onClick 这个参数啊

**Comment by JNUfeatherwit** [comment]
我也遇到这个问题了，想阻止冒泡，但是check的click点击回调没有暴露出来，没法阻止
