### ISSUE TITLE
TimelineItem doesn't work if it's in a separate component

### ISSUE THREAD

**Issue by lvqq** [arco-design/arco-design#1509]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Browser:** chrome106.0.0.0

## What is expected?
It works fine

## Steps to reproduce
![image](https://user-images.githubusercontent.com/29809148/197931132-cf900e51-4ea3-496f-98d3-e31b2c83a0e7.png)

**Comment by yinkaihui** [comment]
Timeline.Item 必须作为 Timeline 的直接子节点

**Comment by yuhan0709** [comment]
@lvqq Indeterminate child nodes will not be rendered，Need to manually determine it's a TimelineItem
Check out the demo below https://codesandbox.io/s/quirky-sun-m3d3ol?file=/demo.js:397-443
