### ISSUE TITLE
InputNumber 使用 formatter 在结尾加字符后无法删除

### ISSUE THREAD

**Issue by chenchen112** [arco-design/arco-design#1510]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Framework version:** "16.14.0"
- **Browser:** chrome106.0.0.0
- **Reproduction Link:** https://codepen.io/chenchen112/pen/vYrYqeV?editors=0011

## What is expected?
希望可以正常删除

**Comment by luckyship** [comment]
@chenchen112 这是你代码的问题，如果你想删除`°`，formater函数会加上`°`，所以你没办法删除`°`，但是可以把光标移动到前面，删除数字是不影响的

**Comment by chenchen112** [comment]
> @chenchen112 这是你代码的问题，如果你想删除`°`，formater函数会加上`°`，所以你没办法删除`°`，但是可以把光标移动到前面，删除数字是不影响的

如果是这样，那会有更好的办法实现我想要的效果么（数字后面紧接一个字符单位）？
我会觉得这个问题的关键在于 formatter 的执行时机

**Comment by chenchen112** [comment]
在 arco 里，只要传了 formatter ，最终 input 的 value 一定是 formatter 过的：
![image](https://user-images.githubusercontent.com/58901888/198206923-d6358ef0-ec0d-442c-8203-c815db040ef9.png)

但 antd 并不会在 userInputting 的时候立即做 formatter
![image](https://user-images.githubusercontent.com/58901888/198207403-441a48ca-93b2-44c7-9dea-16e76342c435.png)

**Comment by luckyship** [comment]
@chenchen112 为啥不用前后缀的方式呢，我感觉你这种场景更适合前后缀啊
![image](https://user-images.githubusercontent.com/22162049/198209070-bb320df2-2ca1-4d6c-beec-afce2b07097b.png)

**Comment by chenchen112** [comment]
> @chenchen112 为啥不用前后缀的方式呢，我感觉你这种场景更适合前后缀啊 ![image](https://user-images.githubusercontent.com/22162049/198209070-bb320df2-2ca1-4d6c-beec-afce2b07097b.png)

如果可以的话我当然也想啦 :( ，UI设计如此 :

**Comment by chenchen112** [comment]
> > @chenchen112 为啥不用前后缀的方式呢，我感觉你这种场景更适合前后缀啊 ![image](https://user-images.githubusercontent.com/22162049/198209070-bb320df2-2ca1-4d6c-beec-afce2b07097b.png)
> 
> 如果可以的话我当然也想 :( ，UI设计如此

**Comment by liuxinqiong** [comment]
遇到同样的问题

**Comment by MisterLuffy** [comment]
> 在 arco 里，只要传了 formatter ，input 的 value 一定是 formatter 过的： ![image](https://user-images.githubusercontent.com/58901888/198206923-d6358ef0-ec0d-442c-8203-c815db040ef9.png)
> 
> 但 antd 并不会在 userInputting 的时候立即做 formatter ![image](https://user-images.githubusercontent.com/58901888/198207403-441a48ca-93b2-44c7-9dea-16e76342c435.png)

感觉你说的有道理，这种情况的确无解，在失焦后触发格式化好一些，或者暴露一个标记是否正在编辑的参数，留给用户自己选择。

**Comment by chenchen112** [comment]
yep！ 🤗🤗🤗
