### ISSUE TITLE
Upload: Cannot upload file when set accept only '.heic' files

### ISSUE THREAD

**Issue by busyxiang** [arco-design/arco-design#1511]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Framework version:** 18.0.0
- **Browser:** chrome106.0.0.0

## What is expected?
The onChange callback should fire when selecting a '.heic' file when the accept field is set to accept '.heic' files only

## Steps to reproduce
Add the Upload component and set the accept field to accept only '.heic' files, then select a '.heic' file but then onChange did not trigger

**Comment by yinkaihui** [comment]
https://codepen.io/yinkaihui/pen/bGKdRqO?editors=0010 
你好，没有办法复现，可以尝试升级下版本

**Comment by busyxiang** [comment]
谢谢回复，我的意思是就算能够选择.heic文件，但是onChange是不会触发的，连upload list也不回出现

**Comment by yinkaihui** [comment]
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/23161413/199936257-0a0300ae-25aa-4903-96f8-9715b5b3f28f.png">
无法复现，方便提供个 codepen 么

**Comment by busyxiang** [comment]
https://user-images.githubusercontent.com/19426419/200285162-c617e1bf-6550-4099-b14a-35c79abf679c.mov

**Comment by yinkaihui** [comment]
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/23161413/201275678-1a90bf11-8ec1-4076-b97a-756c9b7722b7.png">
尝试换一个浏览器试试呢？ 在提供的 demo 上依然无法复现。。。

**Comment by busyxiang** [comment]
尝试使用了Safari浏览器,还是不能。我本身使用Brave的

**Comment by yinkaihui** [comment]
应该是后缀名是大写导致的，我们修复下
