### ISSUE TITLE
Treeselect：单选模式下支持选择内容自定义渲染

### ISSUE THREAD

**Issue by q6655443322** [arco-design/arco-design#1519]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
多选模式下的renderTag

## What problem does this feature solve?
希望能够支持单选模式自定义渲染选择内容，部分需求场景需要

**Comment by yinkaihui** [comment]
https://arco.design/react/components/tree-select#%E8%AE%BE%E7%BD%AE-value-%E6%A0%BC%E5%BC%8F 可以参考这个～
