### ISSUE TITLE
使用@arco-plugins/vite-react怎么配置按需加载，文档上面不全啊

### ISSUE THREAD

**Issue by kuiGe11** [arco-design/arco-design#1522]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.0
- **Framework version:** react^17.0.2
- **Browser:** chrome106.0.0.0

**Comment by PengJiyuan** [comment]
js 的按需加载直接 tree-shaking 就行了吧
