### ISSUE TITLE
[BUG] Collapse组件不能在Next.js下工作。(Undefined is not interable)

### ISSUE THREAD

**Issue by PrinOrange** [arco-design/arco-design#1523]
**在Next.js空项目**下使用Arco Design的`Collapse`组件，依赖版本信息如下：
```
    "@arco-design/web-react": "^2.41.0",
    "next": "13.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
```
填入[官方Demo中任一`Collapse`组件的用法](https://arco.design/react/components/collapse#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95)，
组件渲染正常，但当点击`Collapse`展开折叠面板时，Next.js报错，提示
`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`
报错栈信息如下：
![image](https://user-images.githubusercontent.com/73331790/198818852-2c70909c-dfd5-4305-9d2b-71dd80c00c97.png)

**Comment by PrinOrange** [comment]
我在`Create-React-App`下也试了一次，也是同样的报错内容
![image](https://user-images.githubusercontent.com/73331790/198819248-607a7176-f5db-49c8-935f-b5f899baa59c.png)

**Comment by MisterLuffy** [comment]
我在 Arco Pro 的 CRA 项目中试了一下没有遇到上边的报错

**Comment by yuhan0709** [comment]
Related To: #1524
