### ISSUE TITLE
[BUG] : Tabs组件无法在Next.js下正常显示Active Tab

### ISSUE THREAD

**Issue by PrinOrange** [arco-design/arco-design#1524]
依赖版本如下：
```
    "@arco-design/web-react": "^2.41.0",
    "next": "13.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
```

在空项目中，使用[官方Demo](https://arco.design/react/components/tabs#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)填入任一Tabs组件的使用用例，
我的代码与官方Demo基本一致：
```javascript
import { Tabs, Typography } from '@arco-design/web-react';
const TabPane = Tabs.TabPane;
const style = {
  textAlign: 'center',
  marginTop: 20,
};

export default function Home() {
  return (
    <div>
      <Tabs defaultActiveTab="1">
        <TabPane key="1" title="Tab 1">
          <Typography.Paragraph >Content of Tab Panel 1</Typography.Paragraph>
        </TabPane>
        <TabPane key="2" title="Tab 2" disabled>
          <Typography.Paragraph >Content of Tab Panel 2</Typography.Paragraph>
        </TabPane>
        <TabPane key="3" title="Tab 3">
          <Typography.Paragraph >Content of Tab Panel 3</Typography.Paragraph>
        </TabPane>
      </Tabs>
    </div>
  );
}

```
预期结果应当如下：

![image](https://user-images.githubusercontent.com/73331790/198840524-ef8c2d76-9ba5-4f05-83cd-901bcf1658d4.png)

但是实际效果如下：

![image](https://user-images.githubusercontent.com/73331790/198840546-83d81130-e90d-4faf-8ab1-33846828d041.png)

发现`Tab1`的内容`Content of Tab Panel 1`并没有按预期结果渲染出来，而是一片空白。

所以，必须手动点击一次`Tab1`，才能正常显示里面的内容。
![image](https://user-images.githubusercontent.com/73331790/198840630-ed49f6f7-a0db-4da1-8fbf-87c381a709a9.png)

打开Devtools检查报错，发现来自React的一条警告：

![image](https://user-images.githubusercontent.com/73331790/198840659-dfde4382-d200-4d05-8055-0d7b5d92ab8a.png)

**猜测是Tabs组件使用了findDOM这个已被废弃的API，所以失效报错。**

**Comment by PrinOrange** [comment]
关闭`Strict Mode`后仍然失效报错。

**Comment by PrinOrange** [comment]
关闭React严格模式以后就没出现过这个问题，猜测是依赖了不支持的findDOMNode这个API

**Comment by yuhan0709** [comment]
> 关闭React严格模式以后就没出现过这个问题，猜测是依赖了不支持的findDOMNode这个API

目前组件库确实还有些地方用到了 findDOMNode  而且由于历史原因无法替换，替换后用户升级可能会造成样式丢失布局错误。在3.0版本我们将会全部替换哈。
