### ISSUE TITLE
Next.js 使用InputTag组件聚焦时报栈溢出

### ISSUE THREAD

**Issue by dongjycode** [arco-design/arco-design#1526]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.0
- **Framework version:** React 17.0.2
- **Browser:** chrome107.0.0.0

## What is expected?
报错原因及解决

## Steps to reproduce
1、pages/页面.tsx中引用InputTag组件
2、回到浏览器查看渲染效果，当点击InputTag组件聚焦时报
```
Unhandled Runtime Error
RangeError: Maximum call stack size exceeded
```

截图如下：
<img width="954" alt="image" src="https://user-images.githubusercontent.com/91414395/199009606-22b48ccc-caa9-4c97-af79-a4d9b49de96a.png">

**Comment by dongjycode** [comment]
经验证，修改函数名称后正常
<img width="828" alt="image" src="https://user-images.githubusercontent.com/91414395/199055646-2ddf4bbe-0b31-429a-8fa4-bae772a6dcea.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/91414395/199055514-554fab41-0884-4a20-874a-61c54f74fdd4.png">


尚不知InputTag在TypeScript和Next.js 中使用的场景下，为什么会出现函数自己调用自己的问题

**Comment by MisterLuffy** [comment]
我在 arco-pro-next 中试了一下，没有能够复现。感觉这个报错的地方很奇怪。
![image](https://user-images.githubusercontent.com/29861850/199910608-d03559fa-bcd9-49fe-b45e-2c728710655f.png)
