### ISSUE TITLE
Form.Item中嵌套，文本对齐方式和之前的版本不一致

### ISSUE THREAD

**Issue by zhaogang6682** [arco-design/arco-design#1528]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.41.0
- **浏览器版本:** chrome106.0.0.0
- **复现地址:** https://codesandbox.io/s/interesting-wildflower-8eh4wt?file=/demo.js:547-553

## 预期结果
对齐方式还是居中对齐，2.40.2之前的版本如图
![image](https://user-images.githubusercontent.com/109260418/199225977-55194654-5bf2-45ed-9f83-cbc07e00e3b6.png)

## 复现步骤
目前2.41.0版本样式如图，切换版本就可以复现
![image](https://user-images.githubusercontent.com/109260418/199225912-545b7c94-9175-4781-bb4f-da4af16ed0be.png)

**Comment by MisterLuffy** [comment]
Same with #1529
