### ISSUE TITLE
Support success status in validateLevel in FormItem rules

### ISSUE THREAD

**Issue by lvqq** [arco-design/arco-design#1530]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
As same as the status defined in validateStatus field in FormItem props

## What problem does this feature solve?
Now validateLevel field supports error and warning status, success status is needed

**Comment by yinkaihui** [comment]
可以描述下什么场景下需要用到么

**Comment by lvqq** [comment]
业务场景中的 rules 是动态生成的，需要通过 rules 中的 validateLevel 来指定校验状态，包括 success 状态，直接使用 validateStatus 不太方便
