### ISSUE TITLE
react 开关组件存在问题

### ISSUE THREAD

**Issue by liuyike98** [arco-design/arco-design#1544]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.41.1
- **框架版本:** react
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://arco.design/react/components/switch

## 预期结果
开关从左边拨到右边，会先向左抖一下再到右边，vue版无此问题！

## 复现步骤
波动开关，慢放

**Comment by liuyike98** [comment]
https://user-images.githubusercontent.com/87092276/200118054-03fc770a-6c0a-49ae-9a5a-e7ea539d773c.mp4

看慢动作，会像左弹一下再往右，很难受，vue的是正常的

**Comment by xueerli** [comment]
+1
