### ISSUE TITLE
load-more 懒加载 在二级数据被编辑后如何更新

### ISSUE THREAD

**Issue by qingtiantongxie** [arco-design/arco-design#1546]
table load-more  懒加载默认只会调用一次接口  然后数据就被缓存了  再次点击不会更新数据

我的子数据有添加和编辑功能   请问怎么在子数据被编辑后更新子数据？

**Comment by yuhan0709** [comment]
麻烦提供一个复现demo呢～ 我们这边可以根据demo看下怎么处理这个问题

**Comment by qingtiantongxie** [comment]
我之前给您的字节邮箱发了一封邮件  里面有具体的demo地址  你也可以访问这个🔗： https://stackblitz.com/edit/angular-dksirk?file=src/App.vue

**Comment by flsion** [comment]
> 我之前给您的字节邮箱发了一封邮件 里面有具体的demo地址 你也可以访问这个🔗： https://stackblitz.com/edit/angular-dksirk?file=src/App.vue

懒加载的数据目前没有方法获取到，缓存在了内部。这里考虑可以增加一个change事件的触发，将加载后的数据传出。
可以到 Vue 组件库的仓库提个 feature request https://github.com/arco-design/arco-design-vue/issues

**Comment by xzhq** [comment]
我也遇到同样问题，很尴尬，采用刷新整页，体验不好。

**Comment by tongxin2013** [comment]
插眼
