### ISSUE TITLE
InputNumber在删除后恢复光标的位置

### ISSUE THREAD

**Issue by Ldb19980415** [arco-design/arco-design#1549]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
antd的inputNumber支持比如 123，455  当光标在3的后点，点击删除后，光标保留在当前位置，而不是直接跑到末尾5的后面！

## 预期解决问题
InputNumber在删除后恢复光标的位置.(当前是点删除之后会跑到最后一位，尤其是在包含千分位逗号的情况下

**Comment by luckyship** [comment]
你可以升级最新版本，https://github.com/arco-design/arco-design/pull/1516/，现在支持在formatter中加参数判断是否是正在输入
