### ISSUE TITLE
Layout.Sider 在默认收起状态下打开会闪一下，先触发展开再收起

### ISSUE THREAD

**Issue by MegaShow** [arco-design/arco-design#1550]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.1
- **Browser:** chrome107.0.0.0

## Extra info
这个 commit 引入的问题
https://github.com/arco-design/arco-design/commit/fe7960ecee2069eedc03bf498341664a4986acb9

```typescript
useEffect(() => {
  setSiderWidth(collapsed ? collapsedWidth : propsWidth);
}, [collapsed, propsWidth, collapsedWidth]);
```

## What is expected?
默认收起状态时打开，直接是收起状态，不会先展开后收起

**Comment by chenchen112** [comment]
👍
