### ISSUE TITLE
form label 增加 tooltip 不兼容布局

### ISSUE THREAD

**Issue by pleiades-embers** [arco-design/arco-design#1554]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
     <Form.Item
        label="Field B"
        tooltip={{ title: 'Tooltip with customize icon', icon: <InfoCircleOutlined /> }}
      >

## What problem does this feature solve?
form label 后面增加一个图标  会自动换行

**Comment by yinkaihui** [comment]
方便给个 demo 么，我们 Form.Item 好像没有 tooltip 属性

**Comment by pleiades-embers** [comment]
> 方便给个 demo 么，我们 Form.Item 好像没有 tooltip 属性

demo:https://github.com/arco-design/arco-design/issues/1554#issuecomment-1311174557
arco 的label 增加 tooltip 会影响布局 希望arco增加一个类似的属性
