### ISSUE TITLE
骨架屏图片节点样式无法解析百分比

### ISSUE THREAD

**Issue by YOUAHAHAH** [arco-design/arco-design#1565]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.2
- **Framework version:** 18.2.0
- **Browser:** chrome107.0.0.0

## Steps to reproduce
 <Skeleton
        loading={loading}
        text={false}
        className={b.skeleton}
        image={{
          style: {
            **width: "70%", // 此处百分比无法被解析**
            height: 600,
            borderRadius: "10px",
          },
        }}
        animation
      >

**Comment by YOUAHAHAH** [comment]
我还想问一下，后续会将所有组件都变成函数式组件吗

**Comment by siam-ese** [comment]
You can add this to your style
```css
.my-skeleton .arco-skeleton-header {
  width: 100%;
}
```

**Comment by YOUAHAHAH** [comment]
> You can add this to your style
> 
> ```css
> .my-skeleton .arco-skeleton-header {
>   width: 100%;
> }
> ```

.skeleton {
  width: 80%;
  height: 600px;
  margin: 0 auto;
}
