### ISSUE TITLE
配合tailwindcss使用时，部分组件样式会被tailwindcss默认样式影响，例如switch组件的背景色被覆盖，form组件必选提示图标错位

### ISSUE THREAD

**Issue by PathfinderH** [arco-design/arco-design#1567]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.41.2
- **框架版本:** 18.2
- **浏览器版本:** chrome98.0.4758.139

## 预期结果
在使用tailwind时，组件样式不会被影响

**Comment by jumperchuck** [comment]
https://www.tailwindcss.cn/docs/preflight#preflight-1

**Comment by PathfinderH** [comment]
> https://www.tailwindcss.cn/docs/preflight#preflight-1

多谢

**Comment by langziyang** [comment]
能不能在使用@tailwind base;的情况下解决兼容问题呢?tailwind实在太方便了

**Comment by vimplus** [comment]
2.64.1 版本了都还没修，KPI完成了没人维护了？

**Comment by WangJM001** [comment]
借楼打个广告，有兴趣的可以看看，欢迎Star[呲牙]

🚀 MetisUI-一套企业级 React-Tailwind 组件库
是为喜欢 Ant Design 和 Tailwind CSS 的开发者量身定制的解决方案！
✅ 灵活的样式覆盖
✅ 增强的交互功能
✅ 轻量化与高可定制性
立即体验:  https://metisui.com
源码: https://github.com/metisjs/metis-ui
