### ISSUE TITLE
表单FormItem包裹一个div标签 更改的值丢失

### ISSUE THREAD

**Issue by YOUAHAHAH** [arco-design/arco-design#1574]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.2
- **Browser:** chrome107.0.0.0

 <FormItem
              field="captcha"
              rules={[{ required: true, message: "请输入验证码" }]}
            >
              {/* <div style={{ display: "flex" }}> */}
              <Input
                style={{ width: "60%", marginRight: "20px" }}
                placeholder="请输入验证码"
                prefix={<IconMessage />}
                allowClear={true}
                height="40px"
                autoComplete="off"
              />
              <Captcha ref={captchaRef} onChange={handleChange} charNum={4} />
              {/* </div> */}
            </FormItem>

[@arco-design/web-react]: changed value missed, please check whether extra elements is outta input/select controled by Form.Item

**Comment by YOUAHAHAH** [comment]
<FormItem
              field="captcha"
              rules={[{ required: true, message: "请输入验证码" }]}
            >
              <Input
                style={{ width: "55%" }}
                placeholder="请输入验证码"
                prefix={<IconMessage />}
                allowClear={true}
                height="40px"
                autoComplete="off"
              />
              <Captcha ref={captchaRef} onChange={handleChange} charNum={4} />
            </FormItem>

 onValuesChange={(v, vs) => {
              console.log(v, vs);
            }}
这里 无法获取 唯一标识 captcha 的值

**Comment by yinkaihui** [comment]
Form.Item 必须直接包裹在输入控件外层，因为Form.Item 会对子节点注入一些 props 来收集表单值。 去掉 div 的话应该是可以正常收集

**Comment by CurrentIndex** [comment]
我想封装一些代码，如下：
```ts
import { Empty, Form, FormItemProps, Message, Select, Spin } from '@arco-design/web-react';
import { useEffect, useState } from 'react';

interface AsyncDataSelectProps<T> {
    onSearch: (value: string) => Promise<T[]>;
    labelKey: keyof T;
    valueKey: keyof T;
    formItemProps: FormItemProps;
}

export function AsyncDataSelect<T>({ onSearch, labelKey, valueKey, onChange, formItemProps }: AsyncDataSelectProps<T>) {
    const [searchLoading, setSearchLoading] = useState(false);
    const [options, setOptions] = useState<{ label: string; value: string }[]>([]);
    const search = async (value) => {
        try {
            setSearchLoading(true);
            const options = await onSearch(value);
            setOptions(options.map((option) => ({ label: option[labelKey], value: option[valueKey] })));
            setSearchLoading(false);
        } catch (e) {
            Message.error(e.message);
            setSearchLoading(false);
        }
    };

    useEffect(() => {
        search('').then();
    }, []);

    const loadingContent = (
        <div className="flex items-center justify-center">
            <Spin style={{ margin: 12 }} />
        </div>
    );

    return (
        <Form.Item {...formItemProps (这里推断异常) }>
            <Select
                placeholder="请选择"
                showSearch={true}
                filterOption={false}
                options={options}
                notFoundContent={searchLoading ? loadingContent : <Empty />}
                onSearch={search}
                onChange={onChange}
            />
        </Form.Item>
    );
}
```
然后在Form的Context中调用，如下：

```ts
<Grid.Col span={24}>
    <AsyncDataSelect
        onSearch={async (value) => {
            const res = await searchExercises({ page: 0, size: 10, name: value });
            return res.data?.content;
        }}
        labelKey="name"
        valueKey="id"
        formItemProps={{
            label: '演习',
            field: 'exerciseId' as any (这里推断异常),
        }}
    />
</Grid.Col>
```
Issue的限制让我必须以令人难以接受的方式使用我的封装，我有大量的异步加载的`<Select/>` & `options -><Select/>`。有任何其他解决方案？
