### ISSUE TITLE
希望 Tree 组件的 NodeProps 增加一个 hover 属性

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design#1584]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
Yapi 的接口管理，在 hover 时才显示操作选项
<img width="343" alt="image" src="https://user-images.githubusercontent.com/58337359/202771466-c8fc9b82-1ce4-42b1-8a6a-52d581253c99.png">

## 预期解决问题
在使用 `renderExtra` 时，希望可以根据用户的 hover 情况展示 `renderExtra` 的内容

**Comment by lin-mt** [comment]
TreeSelect 也可以增加类似效果

**Comment by yinkaihui** [comment]
可以配合 renderTitle 使用～  你可以在 renderTitle 返回的节点上监听 mouseEnter 等事件，来进行额外节点的渲染
