### ISSUE TITLE
上传组件Upload在react18版本是，多选的时候，在onChange方法里面获取的files永远都是只有一个元素的数组[{xxx}]

### ISSUE THREAD

**Issue by perfectyang** [arco-design/arco-design#1587]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.3
- **Framework version:** react 18
- **Browser:** chrome107.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/dry-mountain-0oxcv9?file=/demo.js

## Extra info
回退到react17版本就没有问题

**Comment by 0ldm0s** [comment]
nextjs 13.x+ react18同样有此问题，并且form.resetFields()时，表单内容虽然已被清除，但上传组件中的内容不会被清除。

**Comment by BboyAwey** [comment]
+1 坐等修复
