### ISSUE TITLE
Pagination的pageSizeChangeResetCurrent属性在设置为false时，改变pageSize希望可以动态重新计算当前页

### ISSUE THREAD

**Issue by UrimThummim** [arco-design/arco-design#1589]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
其他组件库中分页器的使用？（待调研

## What problem does this feature solve?
场景：有100条数据，每页10条，用户当前在第5页，即查看的是所有数据中的41-50条。此时，用户将pageSize从10切换成了20

- 现状：pageSizeChangeResetCurrent为true时，当前页刷新为第1页；pageSizeChangeResetCurrent为false时，当前页仍为第5页
- 期望：当前页更新为第3页，因为第41-50条数据在pageSize变为20后会在第3页
- 解决的问题：改变pageSize时不会导致之前在浏览的数据丢失，用户需要重新寻找的情况

**Comment by luckyship** [comment]
> 期望：当前页更新为第3页，因为第41-50条数据在pageSize变为20后会在第3页

这个不太现实，你这个是从小变大，如果从大变小，比如20切成10，原来的应该展示20条数据，现在只展示10条数据，应该展示哪一页？

**Comment by UrimThummim** [comment]
可以展示前10条吧？这样至少在从小变大的情况下不会发生数据丢失；从大变小的场景下，比如用户实际想看后10条，那他也只向后翻一页就可以了 —— 可以知道自己想看的数据是在哪一个范围内

**Comment by luckyship** [comment]
这种功能可以自己封装一下，现在主流的框架页码控制(比如antd、element)，基本都是如果保持当前选中的页码，如果超过页码，显示最后一页

**Comment by yuhan0709** [comment]
这种场景组件库统一处理可能会有争议，考虑到通用场景还是建议业务方自己进行受控处理
