### ISSUE TITLE
 Progress wrong color expected

### ISSUE THREAD

**Issue by edwardsal20** [arco-design/arco-design#159]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react: 2.24.1
- **System:** mac
- **Browser:** chrome
- **Reproduction Link:** https://codesandbox.io/s/mystifying-fermi-c084v?file=/src/App.tsx

## Extra info
thank you

## What is expected?
every progress has 2 colors

## Steps to reproduce
see annotation

**Comment by NicodeSS** [comment]
It should be noted that TypeScript says “ProgressProps” has no "trailColor" property at all, it doesn't match with the description in official component API doc.
![image](https://user-images.githubusercontent.com/31835580/141935227-8f7d8764-ce85-4543-8dc9-29619b4e0ad2.png)
