### ISSUE TITLE
自定义单选框组按钮的场景下，嵌入多选框后无法触发多选框的change事件

### ISSUE THREAD

**Issue by lynn1286** [arco-design/arco-design#1596]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.41.3
- **Browser:** chrome107.0.0.0

## Extra info
demo 复现： https://codesandbox.io/s/currying-feather-k0o0uh?file=/demo.js

**Comment by MisterLuffy** [comment]
需要为 `<Checkbox />` 阻止冒泡，`<Radio />` 的子元素会被放置在 `<label />` 标签中，点击时会触发第一个表单元素。
https://codesandbox.io/s/mystifying-kirch-4wfbgn?file=/demo.js
