### ISSUE TITLE
Upload limit属性maxCount为0时还可以点击上传按钮

### ISSUE THREAD

**Issue by zhaogang6682** [arco-design/arco-design#1602]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.41.3
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://codesandbox.io/s/great-rain-peel5l?file=/demo.js

## 额外补充
调整判断方式
文件地址components\Upload\upload.tsx
const exceedLimit = limit.maxCount && limit.maxCount <= fileList.length; 改为const exceedLimit = isNumber(limit.maxCount) && limit.maxCount <= fileList.length;

## 预期结果
limit={{
            maxCount: 0,
            hideOnExceedLimit: false,
          }}，上传按钮为禁用状态,减少用户操作过程

## 复现步骤
maxCount属性为动态属性，所以可能为0需要禁用
![image](https://user-images.githubusercontent.com/109260418/203899563-14e108a5-797f-479a-83e5-b831ec077390.png)

**Comment by yinkaihui** [comment]
这个直接用 disabled 属性即可？

**Comment by zhaogang6682** [comment]
传入disable后limit属性将会失效

**Comment by yinkaihui** [comment]
试试想要禁用的时候给 maxCount 设置为 -1 ？ 这里直接调整可能对以前设置 limit={0} 时的行为产生影响
