### ISSUE TITLE
table，default-expand-all-rows无效

### ISSUE THREAD

**Issue by yuyachong** [arco-design/arco-design#1616]
版本：2.39.1

`{"code":1000,"msg":"ok","data":[{"id":5,"name":"111","parent_id":0,"path":"0,5","create_time":"2022-11-26 16:34:34","update_time":null,"delete_time":null,"children":[{"id":6,"name":"22222","parent_id":5,"path":"0,5,6","create_time":"2022-11-26 16:35:05","update_time":"2022-11-26 16:36:47","delete_time":null}]}]}`

顶级分类会出现“+”  也可以点开，   但是default-expand-all-rows不能全部展开

**Comment by yuyachong** [comment]
`<a-table ref="tableRef" :data="treeData" :stripe="true" :default-expand-all-rows="true" 
				:pagination="false" :scroll="{x: '100%', y: '100%'}">
					<template #columns>
						<a-table-column title="名称" data-index="name"></a-table-column>
						
						<a-table-column :width="260">
							<template #title>
								操作
								<a-button type="primary" @click="addCategory()" size="mini">添加顶级</a-button>
							</template>
							<template #cell="{ record }">
								<a-link :hoverable="false" @click="$jump('../list?category_id=' + record.id)">列表</a-link>
								<a-divider direction="vertical"></a-divider>
								<a-link :hoverable="false" @click="addCategory(record)">添加子类</a-link>
								<a-divider direction="vertical"></a-divider>
								<a-link :hoverable="false" @click="editCategory(record)">编辑</a-link>
								<a-divider direction="vertical"></a-divider>
								<a-link :hoverable="false" @click="delCategory(record.id)">删除</a-link>
							</template>
						</a-table-column>
					</template>
				</a-table>`

**Comment by yuyachong** [comment]
<a-table ref="tableRef" :data="treeData" :stripe="true" :default-expand-all-rows="true" 
				:pagination="false" :scroll="{x: '100%', y: '100%'}">
					<template #columns>
						<a-table-column title="名称" data-index="name"></a-table-column>
						
						<a-table-column :width="260">
							<template #title>
								<text style="margin-right: 10px;">操作</text>
								<a-button type="primary" @click="addCategory()" size="mini">添加顶级</a-button>
							</template>
							<template #cell="{ record }">
								<a-link :hoverable="false" @click="$jump('../list?category_id=' + record.id)">列表</a-link>
								<a-divider direction="vertical"></a-divider>
								<a-link :hoverable="false" @click="addCategory(record)">添加子类</a-link>
								<a-divider direction="vertical"></a-divider>
								<a-link :hoverable="false" @click="editCategory(record)">编辑</a-link>
								<a-divider direction="vertical"></a-divider>
								<a-link :hoverable="false" @click="delCategory(record.id)">删除</a-link>
							</template>
						</a-table-column>
					</template>
				</a-table>

**Comment by yuyachong** [comment]
`nextTick(() => {
					proxy.$refs['tableRef'].expandAll()
				})`

此方法有效

**Comment by PengJiyuan** [comment]
麻烦提到 vue 仓库 https://github.com/arco-design/arco-design-vue
