### ISSUE TITLE
希望 Input.Password 提供可定制 icon 的 api

### ISSUE THREAD

**Issue by chenchen112** [arco-design/arco-design#1622]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.42.0
- **Framework version:** react: "17.0.2"
- **Browser:** chrome107.0.0.0

![image](https://user-images.githubusercontent.com/58901888/204684661-ffc52d1e-93fb-41f8-8398-07072d011b70.png)

**Comment by yinkaihui** [comment]
`suffix` 属性即可定制

**Comment by chenchen112** [comment]
> `suffix` 属性即可定制

那我还需要自己监听 visibility
