### ISSUE TITLE
会提供类似@ant-design/pro-components/ProDescriptions的组件吗

### ISSUE THREAD

**Issue by GitKou** [arco-design/arco-design#1637]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
@ant-design/pro-components里的可编辑的定义列表场景非常常见，不知道arco能不能也出一个https://procomponents.ant.design/components/descriptions/#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E5%AE%9A%E4%B9%89%E5%88%97%E8%A1%A8

## What problem does this feature solve?
可以直接在Description详情页编辑字段，不用重新编写表单组件。。。

**Comment by PengJiyuan** [comment]
官方暂时没有人力，看社区有没有人有兴趣。
