### ISSUE TITLE
How to change Modal size. Its looks like have 3 type of modal size in spec document, but i not found in source code

### ISSUE THREAD

**Issue by moonrailgun** [arco-design/arco-design#1649]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 

In spec: https://arco.design/docs/spec/modal
![image](https://user-images.githubusercontent.com/6964737/207605539-88b4585a-a4fd-40e0-99f1-d88023242d9a.png)

It looks like have 3 types: small/default/large, but i not found in source code. lts looks like not compatible.

## What problem does this feature solve?
add `size` for `<Modal />` and `modal.confirm`. so every one can change modal size.

## What are the similar cases of this feature
and how to change size by alternative plan? just modify style with `style: {width: xxx, height: xxx}` is not work 

![image](https://user-images.githubusercontent.com/6964737/207604994-3222d4a1-f738-4226-8c2f-c466252f32aa.png)

because its dom will limit content and keep its always small.(although container is large)

**Comment by yinkaihui** [comment]
这个不是 Modal 组件的尺寸，是给出的三种不同的建议尺寸。我们文档后续调整下避免歧义

**Comment by moonrailgun** [comment]
@yinkaihui 感谢你的回复，所以有什么好的方式修改modal的大小么？（除了加className然后通过className改内部样式）

**Comment by yilujun100** [comment]
@moonrailgun 可以通过style属性去修改模态框的样式，比如宽度：
<Modal
  ...
  style={{ width: '720px' }}
>
</Modal>
