### ISSUE TITLE
form表单的 initialValue 对switch无效

### ISSUE THREAD

**Issue by legends-killer** [arco-design/arco-design#165]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react: 2.24.1
- **System:** macOS 12.0.1
- **Browser:** 95.0.4638.69 (Official Build) (arm64)
- **Reproduction Link:** https://codesandbox.io/s/adoring-bash-3g831?file=/src/App.tsx

## Extra info
https://github.com/ant-design/ant-design/issues/25091

## What is expected?
Form initial value should be attached to the switch component.

## Steps to reproduce
The initial value of the form is invalid for the switch component.

**Comment by yinkaihui** [comment]
在对应的 `Form.Item` 上设置 `triggerPropName` 为 `checked`
