### ISSUE TITLE
table 组件开启virtualized 后，自定义components 的body 配置失效

### ISSUE THREAD

**Issue by miroku-y** [arco-design/arco-design#1650]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.42.2
- **Framework version:** 2.42.2
- **Browser:** chrome108.0.0.0

## What is expected?
文档上只是描述开启虚拟滚动后，树形结构给关闭了，但是现在components 的配置也失效，无法完成自定义

## Steps to reproduce
1. 打开官网
2. 定位到最后一个demo 大数据
3. 在codePen 中打开，加入如下配置
 components={{
            body: {
              row: <div>123</div>,
            },
          }}

**Comment by PengJiyuan** [comment]
符合预期的，虚拟化的时候，row强制为div
