### ISSUE TITLE
Table组件，同时配置onClick与onChange，并且两个事件里面都去控制了行选中，此时点击Checkbox，会出现选中不了的情况

### ISSUE THREAD

**Issue by edc-hui** [arco-design/arco-design#1653]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.42.2
- **Framework version:** react 17.0.2
- **Browser:** chrome108.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/friendly-moon-990je1?file=/demo.js:1644-1652

## What is expected?
行选中的受控，不能因为onClick与onChange同时控制而出现异常

## Steps to reproduce
1. 直接点击Checkbox，选中不了
2. 先点击行，行被选中，此时再去点击Checkbox，取消选中不成功

**Comment by yinkaihui** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/23161413/208352445-3cf1e327-b2dd-4b5e-b6f7-a7babd86553a.png">

可以阻止下 checkbox 上 click 事件的冒泡
