### ISSUE TITLE
【React】InputTag 在作为表单控件使用时，切换到 error 态发生高度抖动

### ISSUE THREAD

**Issue by czpcalm** [arco-design/arco-design#1657]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.42.2
- **Browser:** chrome108.0.0.0
- **Reproduction Link:** https://codepen.io/czpcalm/pen/KKBKGRg?editors=0010

## Extra info
1. 在设置了placeholder之后才有这个问题。2. 如果不设置required，也不会，应该是在切换的error态的时候导致的。

## What is expected?
输入框不抖动

## Steps to reproduce
输入任意内容回车保存，然后删除，触发校验，可以看到输入框抖动。

**Comment by yinkaihui** [comment]
尝试设置 animation=false 试试？ 临时可以这样 fix 下，具体的问题需要进一步排查下
