### ISSUE TITLE
pagination.current拿不到实时值

### ISSUE THREAD

**Issue by AndrewOYLK** [arco-design/arco-design#1659]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.42.2
- **Framework version:** React ^18.2.0
- **Browser:** chrome108.0.0.0

**Comment by yuhan0709** [comment]
有复现Demo吗。
