### ISSUE TITLE
使用vite工程化的时候，引入你们的ui，报ResizeObserver loop limit exceeded的错误

### ISSUE THREAD

**Issue by panqibao** [arco-design/arco-design#1660]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.42.2
- **Browser:** chrome107.0.0.0

<img width="929" alt="image" src="https://user-images.githubusercontent.com/16532058/208791464-88123e76-917f-4382-ae68-43401ee6f298.png">

**Comment by yinkaihui** [comment]
直接引入就报错了么？ 辛苦可以给一些信息么，我们尝试复现下？

**Comment by panqibao** [comment]
对，直接引入就报错。单独引入一个组件不会，应该是整个项目引用的组件多了就报错了。
我之前是用的webpack5没有啥问题，这几天改成了vite4，结果就一直报这个错。
