### ISSUE TITLE
Descriptions 配置属性layout="inline-horizontal"和tableLayout="fixed"后展示错位，是否复合预期？

### ISSUE THREAD

**Issue by zhaogang6682** [arco-design/arco-design#1662]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.42.2
- **浏览器版本:** chrome108.0.0.0
- **复现地址:** https://codesandbox.io/s/quizzical-noyce-3th4j3?file=/demo.js

## 复现步骤
文本太长出现换行
![image](https://user-images.githubusercontent.com/109260418/209053551-c1b92086-fd04-4ff5-8320-fd0bfd7f0b54.png)

**Comment by yuhan0709** [comment]
正常的，要想不错位可以用 `horizontal` 模式，可以看下控制台 DOM 节点比较下两种模式的区别。或者你这个案例可以给最后一条最长的值设置一个宽度，我把 `Demo` 改了下可以看下

https://codesandbox.io/s/hopeful-carson-y5kse8?file=/demo.js
