### ISSUE TITLE
Select 组件，异步获取 options， showSearch 开启时点击选择框光标底部文案不是当前选中选项的 label 而是 placeholder

### ISSUE THREAD

**Issue by growuper** [arco-design/arco-design#1675]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.43.0
- **Framework version:** react
- **Browser:** chrome108.0.0.0

## What is expected?
光标底部文案是当前选中选项的 label

## Steps to reproduce
1. Select 组件、showSearch: true，异步获取 options， showSearch
2. 先选中一个值，然后点击选择框，光标底部文案不是当前选中选项的 label 而是 placeholder

**Comment by MisterLuffy** [comment]
需要为 `showSearch` 传入 `{ retainInputValue: true } `，在聚焦时保留输入框的内容。
