### ISSUE TITLE
transfer 支持左侧数据选择后出现在右侧且左侧数据不消失

### ISSUE THREAD

**Issue by yinkaihui** [arco-design/arco-design#1679]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
transfer 支持左侧数据选择后出现在右侧且左侧数据不消失

## What problem does this feature solve?
transfer 支持左侧数据选择后出现在右侧且左侧数据不消失

**Comment by MisterLuffy** [comment]
Already support in `2.21.0`.
