### ISSUE TITLE
TS如何动态引入Icon

### ISSUE THREAD

**Issue by csshidi** [arco-design/arco-design#1681]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.43.0
- **Framework version:** React 18.2.0
- **Browser:** chrome109.0.0.0

## Steps to reproduce
icon从后端返回
像这样引入
`<Icon name="dashboard" />`

**Comment by PengJiyuan** [comment]
这种属于全量引用了，不是很推荐。要是想这么搞可以自己封装一个 Icon 组件。
```js
import * as icons from '@arco-design/web-react';
```
就能通过 icons.IconXXX 去调用了。
然后你在 Icon 组件里把相关逻辑封装一下
