### ISSUE TITLE
图片组件，希望增加懒加载功能

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#1682]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.43.0
- **浏览器版本:** chrome108.0.0.0

## 预期结果
功能我想不必多说了，虽然市面上有很多懒加载组件，但是得修改，就算如此风格不统一，不够优雅。我认为再加入这么一个功能，图片组件堪称完美啦！

**Comment by yuhan0709** [comment]
详细描述下需求呢？如果是加载到适口才展示的话，那从组件层面不好把控

**Comment by kwooshung** [comment]
> 详细描述下需求呢？如果是加载到适口才展示的话，那从组件层面不好把控

确实是这样的效果。或者能不能提供相关的事件，让我们自己操作，或者提供一个单独的懒加载的组件，比如丰富下layout的功能？

**Comment by kwooshung** [comment]
> 详细描述下需求呢？如果是加载到适口才展示的话，那从组件层面不好把控

我已经详细描述了，这已经过了好久了哦，是否可以考虑加入到3.0？

**Comment by kwooshung** [comment]
好久没来，发现功能已经加入了实现了，太帅了吧！
