### ISSUE TITLE
Add ability for Arco Design Tables to be Transposed

### ISSUE THREAD

**Issue by kevinchua6** [arco-design/arco-design#1683]
- [X] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
I propose that we add the ability for tables to be transposed (ie have their data in a horizontal format). This can be added in a form of a prop like `transpose={true}`. This should be natively added as the workaround for this is quite a hassle, requiring us to manually change column names and manually transpose our data. 

I have asked in the internal oncall group about this feature, and the only workaround seems to be transposing the data manually, which was quite a bit of work for something that is fairly common.

## Extra info
I have did an MVP for this feature. Will create a PR for this if the maintainer thinks that this is worth doing.

Currently, the default vertical table looks like this: 
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/45702380/209899775-2d622179-57c4-4eb6-8e59-a5ed9322ab6f.png">

If a table would be transposed, it will look like this, with the headers at the side:
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/45702380/209899918-a2d87c3a-9119-4266-940d-67c86c431d01.png">

Let me know if this feature is worth looking at.

## What problem does this feature solve?
Currently, we can only show tables which have headers at the top. Sometimes, we might need headers at the side of the table

## What are the similar cases of this feature
When you want your data to be side scrollable instead of vertically scrollable, this function might be useful. Transposed tables are also quite common.

**Comment by kevinchua6** [comment]
Hi, sorry but can I get a response on this?

**Comment by yuhan0709** [comment]
This performance is quite different from the native `<table/>`, Maybe you need to reverse the data and columns yourself. 

Or you can see if the [Descriptions](https://arco.design/react/components/descriptions) meets the requirements.
<img width="976" alt="image" src="https://user-images.githubusercontent.com/23137528/212243452-33e95897-43b6-4db0-87ec-0f09cf27fe14.png">
