### ISSUE TITLE
树组件渲染在展开节点时会出现dom节点闪烁跳动？

### ISSUE THREAD

**Issue by huangxok** [arco-design/arco-design#1691]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.33.1
- **Framework version:** React 18.2.0
- **Browser:** chrome108.0.0.0

## Extra info
react 17.x.x版本没有此问题

## What is expected?
不应该出现闪烁跳动

**Comment by huangxok** [comment]
补充code live
https://codesandbox.io/s/cool-lumiere-qj1697?file=/demo.js

**Comment by kwooshung** [comment]
果然是“字节跳动”出品
![0D519238](https://user-images.githubusercontent.com/3413930/224516238-b4087f7c-3da0-415d-8368-5e7755c57457.png)

**Comment by kurisu994** [comment]
same

**Comment by yinkaihui** [comment]
#2338
