### ISSUE TITLE
Custom format with input enabled on date input

### ISSUE THREAD

**Issue by alkanna** [arco-design/arco-design#1693]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
None that I can think of

## What problem does this feature solve?
Right now whenever we change the `format` of a `DatePicker` input, we cannot type it manually anymore, it forces the user to use the date picker and select it by hand, which some people might find more cumbersome than just typing a date by hand.

**Comment by jiahao-c** [comment]
Hi @alkanna  I'm not able to reproduce this issue.
For example, I assigned a custom format in the following code. I can still type manually in the date picker.

https://codesandbox.io/s/quirky-brook-qs1e60?file=/demo.js


Can you please provide a codesandbox link that reproduces this problem?

**Comment by alkanna** [comment]
Hey @jiahao-c , it seems to be my bad indeed !
I was using as shown in the doc this format :
`format={(value) => `custom format: ${value.format('YYYY-MM-DD')}`}`

Your example is working perfectly on my end, sorry for the erroneous report.
