### ISSUE TITLE
input组件中使用:input-attrs="{type:'seach'}"修改input的type无效

### ISSUE THREAD

**Issue by moshang16** [arco-design/arco-design#1699]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.36.1
- **Framework version:** vue 3.2.38
- **Browser:** chrome108.0.0.0

## What is expected?
希望相关api有官方实例指引

## Steps to reproduce
<a-input :input-attrs="{type:'seach'}" v-model="form.name" placeholder="请输入档案名称">
          <template #prefix>
            <i class="ylm-iconfont ylm-icon-search" />
          </template>
        </a-input>

**Comment by yinkaihui** [comment]
通过 <Input.Search /> 使用搜索框
