### ISSUE TITLE
InputNumber boundary instability

### ISSUE THREAD

**Issue by KuaiYu95** [arco-design/arco-design#1712]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.43.2
- **Browser:** chrome108.0.0.0

## What is expected?
fix this bug

## Steps to reproduce
1. open the url (https://arco.design/react/components/input-number#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)
2. 基础用法：input 15
3. Quickly repeat switch 14 and 15 
4. It's going to turn 15 into 14 （This is a maximum problem，The minimum is the same.）

**Comment by MisterLuffy** [comment]
Can't reproduce the situation you describe. Can you provide a screen recording for this?
