### ISSUE TITLE
ModalForm 点击右上角图标无法关闭 modal

### ISSUE THREAD

**Issue by pleiades-embers** [arco-design/arco-design#1717]
version :2.43.0
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/44309088/212243488-56766345-a27d-4272-a629-d9aa1c63fb8f.png">

**Comment by yuhan0709** [comment]
给一个codepen呢

**Comment by pleiades-embers** [comment]
官网文档最新的案例就是
