### ISSUE TITLE
Menu 组件按需加载 less 报错

### ISSUE THREAD

**Issue by giflee** [arco-design/arco-design#1724]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Browser:** chrome109.0.0.0

<img width="763" alt="image" src="https://user-images.githubusercontent.com/9374871/212543167-64536e5a-0e96-42fd-a3e2-f55bc8a295f4.png">

**Comment by giflee** [comment]
babel-plugin-import  style 配置为 true 的时候，有个less变量报错了

**Comment by giflee** [comment]
目前 style 配置为 css 降级处理了

**Comment by MisterLuffy** [comment]
![image](https://user-images.githubusercontent.com/29861850/216528764-adccfafb-ce4a-4aec-b812-e78b89c7dc48.png)

第九行应该是对应这个变量，看不出来为什么会报错。
