### ISSUE TITLE
有没有觉得 Menu 作为顶部导航菜单加上图标时，图标与文字的间隔太宽？

### ISSUE THREAD

**Issue by shi-yang** [arco-design/arco-design#1726]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Framework version:** React 18
- **Browser:** chrome109.0.0.0

## Steps to reproduce

直接按照文档的教程，然后加入图标：
[https://arco.design/react/components/menu#%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA%E8%8F%9C%E5%8D%95](https://arco.design/react/components/menu#%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA%E8%8F%9C%E5%8D%95)

比如，如下代码的使用：

```
       <Menu mode='horizontal' defaultSelectedKeys={['1']}>
        <MenuItem key='1'><IconHome />Home</MenuItem>
        <MenuItem key='2'><IconFile />Solution</MenuItem>
        <MenuItem key='3'><IconCloud />Cloud Service</MenuItem>
        <MenuItem key='4'><IconUser />Cooperation</MenuItem>
      </Menu>
```

可以得到如下的效果：

<img width="596" alt="image" src="https://user-images.githubusercontent.com/5102567/212838896-408f1c19-1b66-4379-bcf6-9fdb515b503a.png">

这个宽度在垂直菜单下看着倒没觉得会有啥，可是水平菜单这么一排过来看着就好宽啊，因为这样会导致图标跟文字之间看起来像是孤立的，而不是一体的，降低用户识别菜单项的效率。

看到代码里面设置了是 `16px`，是设计就是这么设计的吗？如果设计师觉得这么设计的好，那就是我个人审美的问题了，我自己项目里优化掉；可是如果此处还有优化的空间，希望arco把这个细节优化下。

## Extra info

强迫症看到这个细节很在意，为此特地调研了下其它家：

Semi Design：8px
Ant Design: 10px
TDesign: 8px

以及正在用的 Github：
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/5102567/212850568-e4912216-7a75-4134-b39d-7d651016bb49.png">

**Comment by SkyAshuai** [comment]
已收到反馈，我们会对这里进行下优化

**Comment by yinkaihui** [comment]
@MisterLuffy  水平时 8px
