### ISSUE TITLE
数字输入框使用 formatter 后光标位置有问题

### ISSUE THREAD

**Issue by chenchen112** [arco-design/arco-design#1730]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Framework version:** React
- **Browser:** chrome108.0.0.0
- **Reproduction Link:** https://codepen.io/chenchen112/pen/KKByXyR?editors=0011

![20230119144341_rec_](https://user-images.githubusercontent.com/58901888/213374011-309a6636-e935-49c7-8e13-4457f8b888a6.gif)

## What is expected?
光标正常

## Steps to reproduce
选中数字和结尾的符号时光标没问题，但如果只选中数字部分然后开始输入，输入第一个数字后光标会移到最前面

**Comment by MisterLuffy** [comment]
尝试 [此写法](https://codepen.io/misterluffy/pen/NWBemxm?editors=0011)，在用户输入时直接返回输入框本身的文本。
