### ISSUE TITLE
只要把Menu.SubMenu包一层函数组件再使用就会丢失子项的缩进

### ISSUE THREAD

**Issue by shadowfish07** [arco-design/arco-design#1733]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Browser:** chrome109.0.0.0
- **Reproduction Link:** https://codepen.io/shadowfish07/pen/YzjedMO?editors=001

## Steps to reproduce
```
const { Menu } = window.arco;
const { IconApps, IconBug, IconBulb } = window.arcoicon;
const MenuItem = Menu.Item;
const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

const Test = () => {
  return (
    <Menu.SubMenu key="1234aa" title="123456">
      <Menu.Item key="aaa">123</Menu.Item>
    </Menu.SubMenu>
  );
};

const App = () => {
  return (
    <div className="menu-demo" style={{ height: 600 }}>
      <Menu
        style={{ width: 200, height: "100%" }}
        hasCollapseButton
        defaultOpenKeys={["0"]}
        defaultSelectedKeys={["0_1"]}
      >
        <Menu.SubMenu key="ccc" title="123456">
          <Menu.Item key="ddd">123</Menu.Item>
        </Menu.SubMenu>
        <Test />
      </Menu>
    </div>
  );
};

ReactDOM.render(<App />, CONTAINER);

```
![image](https://user-images.githubusercontent.com/38303418/214110797-d48baf72-2384-435d-9188-ceda5b20b3cc.png)

**Comment by shadowfish07** [comment]
补充：用Test() 语法出来结果是对的

**Comment by MisterLuffy** [comment]
`Menu` 需要对其子节点进行遍历来寻找其中的 `SubMenu` 和 `MenuItem`，只会对其子元素进行判断是否为 Menu 子组件，不会对用户自定义组件进行递归判断。 具体逻辑可以参考这段[代码](https://github.com/arco-design/arco-design/blob/main/components/Menu/util.ts#L94)。

另外 `<Test />` 和  `Test()` 是两个不同的用法，前者是将 `Test` 作为一个 React 组件来使用，后者只是将其当做一个返回 ReactElement 的函数。这种写法 `Menu` 所接收到的 Children 是不一样的。
