### ISSUE TITLE
弹出选择下拉框后，页面滚动时没有随着页面滚动，造成输入框和选择下拉框分离

### ISSUE THREAD

**Issue by tianmiao168** [arco-design/arco-design#1736]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.2
- **Browser:** chrome108.0.0.0

**Comment by yinkaihui** [comment]
[ 可以看下这里 👉](https://arco.design/react/docs/question#%E4%BD%BF%E7%94%A8-trigger-%E7%BB%84%E4%BB%B6%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%BC%B9%E5%87%BA-%E5%A6%82-tooltip-popover-select-%E7%AD%89%E7%BB%84%E4%BB%B6%EF%BC%8C%E5%BC%B9%E5%87%BA%E6%A1%86%E4%BD%8D%E7%BD%AE%E4%B8%8D%E5%AF%B9%EF%BC%8C%E6%88%96%E8%80%85%E5%9C%A8%E6%BB%9A%E5%8A%A8%E6%97%B6%E5%BC%B9%E5%87%BA%E6%A1%86%E6%B2%A1%E6%9C%89%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E3%80%82)
