### ISSUE TITLE
FormInstance 功能拓展

### ISSUE THREAD

**Issue by LaamGinghong** [arco-design/arco-design#174]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
无

## 预期解决问题
FormInstance 能够手动控制表单项的禁用状态

## 额外补充
https://angular.cn/api/forms/FormControl
参考 Angular 的表单实例

**Comment by yinkaihui** [comment]
这个应该不会支持，现在 `form` 的方法都是对表单值的操作，对 UI 的修改建议还是通过props设置

**Comment by LaamGinghong** [comment]
感觉目前这个 FormInstance 的能力太弱了，当初应该是照着 antd 来实现导致的
