### ISSUE TITLE
Typography cssEllipsis 若初始化未触发超出省略则始终不能触发，无法自适应

### ISSUE THREAD

**Issue by liumengyuangit** [arco-design/arco-design#1740]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Browser:** chrome109.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/angry-flower-sfi8gw

## What is expected?
初始化未触发溢出时，自适应窗口也能正常展示溢出省略号

**Comment by yuhan0709** [comment]
https://codesandbox.io/s/sharp-bose-f97ip5?file=/src/App.js

**Comment by ITrokie** [comment]
@PengJiyuan
