### ISSUE TITLE
Table中使用Typography并开启cssEllipsis单行省略失效

### ISSUE THREAD

**Issue by xueerli** [arco-design/arco-design#1742]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Browser:** chrome109.0.5414.87
- **Reproduction Link:** https://codesandbox.io/s/bold-waterfall-1fl8x7?file=/src/App.js:539-549

## Extra info
rows不为1时可以多行省略

## What is expected?
Table中可以开启cssEllipsis单行省略

**Comment by yuhan0709** [comment]
在 table 里使用 Typography 需要给 `Typography` 设置宽度才行，具体原因可以看这个 issue https://github.com/arco-design/arco-design/issues/1438

**Comment by xueerli** [comment]
> 在 table 里使用 Typography 需要给 `Typography` 设置宽度才行，具体原因可以看这个 issue #1438

如果给Typography设置宽度，就不能根据Table自适应调整省略的宽度了
