### ISSUE TITLE
Table多级表头   冻结列   多选时存在样式问题

### ISSUE THREAD

**Issue by UrimThummim** [arco-design/arco-design#1744]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.0
- **Framework version:** React 17.0.2
- **Browser:** chrome110.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/xenodochial-drake-wpmsk6?file=/demo.js

## What is expected?
期望列冻结对一级表头和二级表头均生效，但目前仅对一级表头生效

## Steps to reproduce
1. rowSelection属性的fixed子属性设置为'left'
2. 使用嵌套列的方式实现多级表头
3. 给「一级表头」和「一级表头」下的首个「二级表头」的fixed属性都设置为"left"

**Comment by lrenc** [comment]
本周将修复这个问题，在使用时需要注意（多级表头可以看作为一颗树），当有任意一个叶子节点被设置了fixed属性时，整颗树都需要设置相同的fixed属性，所有叶子节点都需要指定width属性。#1840 
```javascript
const columns = [
  {
    title: "Basic",
    fixed: "left",
    children: [
      {
        title: "Name",
        dataIndex: "name",
        fixed: "left",
        width: 200
      },
      {
        title: "Salary",
        dataIndex: "salary",
        fixed: "left",
        width: 200
      }
    ]
  },
  {
    title: "Others",
    children: [
      {
        title: "Address",
        dataIndex: "address",
        width: 200
      },
      {
        title: "Email",
        dataIndex: "email",
        width: 200
      }
    ]
  },
  {
    title: "Action",
    dataIndex: "action",
    fixed: "right",
    width: 100
  }
];
```
