### ISSUE TITLE
The amount of data is too large, the rendering of the select component is stuck.

### ISSUE THREAD

**Issue by rodger025** [arco-design/arco-design#1754]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.1
- **Browser:** chrome109.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/practical-chebyshev-2b2t9l?file=/demo.js

## What is expected?
Expect normal rendering

## Steps to reproduce
When the options is too large, the component is stuck.

**Comment by MisterLuffy** [comment]
It the mount of selected options is not too large, performance will be better. I have no idea on how to optimize it. If you have any idea, a PR is welcomed.
