### ISSUE TITLE
[Select] It is expected that select option can be selected and copied when mouse down

### ISSUE THREAD

**Issue by mintftw** [arco-design/arco-design#1755]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature

![img_v2_a536abd4-2418-4b37-91d4-d84617f6460g](https://user-images.githubusercontent.com/124557321/216905709-d5fc4235-b2f8-415a-b7e1-815fbd79a533.gif)

![img_v2_2dc46ed7-2c8f-4198-afd5-05531bf8496g](https://user-images.githubusercontent.com/124557321/216905744-d2f47d2b-4e7f-47dc-96ba-111bca8c3f69.gif)

## What problem does this feature solve?
copy select option label

**Comment by MisterLuffy** [comment]
![Kapture 2023-02-10 at 15 40 23](https://user-images.githubusercontent.com/29861850/218031580-5bc07570-84c8-47c6-9a18-5b4ed9778577.gif)

We prevent the default event behavior of `onMouseDown` on dorp-down list to prevent input element losing focus status. [code](https://github.com/arco-design/arco-design/blob/main/components/Select/select.tsx#L506)

We don't want to change this.
