### ISSUE TITLE
【React】TreeSelect单选模式下，选中某一项下拉面板收起后没有触发onVisibleChange

### ISSUE THREAD

**Issue by lijiawei0602** [arco-design/arco-design#1757]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.44.1
- **浏览器版本:** chrome109.0.0.0
- **复现地址:** https://codesandbox.io/s/jovial-tesla-yfz3pk

## 预期结果
选中下拉面板中的某一项后触发onVisibleChange的回调，参数为false

## 复现步骤
点开TreeSelect下拉面板，选中某一项，查看console控制台内容

**Comment by jiahao-c** [comment]
可能就是这么设计的😂 
选中某一项触发 `onChange`，不选的情况下直接展开收起触发 `onVisibleChange`
