### ISSUE TITLE
Next项目中通过 npm i @arco-design/web-react 安装arco，按需引入组件时出现样式错误

### ISSUE THREAD

**Issue by Liukaixin93** [arco-design/arco-design#1761]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.1
- **Framework version:** react: 18.2.0
- **Browser:** chrome108.0.0.0

**Comment by charlesOrz7** [comment]
me too!

**Comment by yinkaihui** [comment]
可以具体一些么。。

**Comment by Liukaixin93** [comment]
感谢关注，问题已解决，在根文件 _app.tsx 增加样式文件的引入







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arco-design/arco-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arco-design/arco-design] Next项目中通过 npm i @arco-design/web-react 安装arco，按需引入组件时出现样式错误 (Issue #1761)





 
可以具体一些么。。

**Comment by guangzan** [comment]
> 感谢关注，问题已解决，在根文件 _app.tsx 增加样式文件的引入
> […](#)

这样操作样式不是按需引入的
