### ISSUE TITLE
tooltip 的 content 设置为经过 Typography 包装的文字，在开启 suffix 或设置为可展开后，点击 suffix 时触发 Modal 组件显示，tooltip 不会消失

### ISSUE THREAD

**Issue by Jiyp** [arco-design/arco-design#1771]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.44.2
- **浏览器版本:** chrome109.0.0.0
- **复现地址:** https://webide.bytedance.net/s/create-react-appmoldzw4x-lksx7arn?file=/index.tsx

## 预期结果
触发 Modal 组件后，tooltip 节点隐藏

**Comment by yuhan0709** [comment]
我们的 `interface` 定义是 `string`，所以将 `suffix` 直接作为 `useEffect` 的依赖了。

在 `state` 变化重新渲染之后，传了复杂类型的 `suffix` 其实就不是同一个了， 所以用 `useMemo`包一下就好。

![P9oiP6v0o4](https://user-images.githubusercontent.com/23137528/222036659-b3c6f212-ad2a-42c8-ae92-a27966b5b4a3.jpg)
