### ISSUE TITLE
选择框，搜索结果列表，滚动到了最下方

### ISSUE THREAD

**Issue by charlesflare** [arco-design/arco-design#1773]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.44.2
- **框架版本:** React
- **浏览器版本:** chrome109.0.0.0

## 预期结果
搜索结果列表默认从前往后查看，滚动到 top 0

## 复现步骤
选择一个列表的非首项值，然后进行搜索

**Comment by MisterLuffy** [comment]
这个是因为如果 Select 有选中的选项，在打开下拉列表时会自动滚动到已选选项的位置。搜索后列表得到了更新，但列表本身的滚动条位置不会改变，所以仍然停留在列表底部。

考虑了一下在选项更新时直接将列表滚动高度置 0 很有可能造成界面抖动或者扰乱用户，所以这个情况不准备进行处理。
