### ISSUE TITLE
日历-卡片日历，demo点击今天无反馈

### ISSUE THREAD

**Issue by SkyAshuai** [arco-design/arco-design#1778]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.3
- **Browser:** chrome109.0.0.0

## What is expected?
点击今天按钮可以跳转到今天

**Comment by PengJiyuan** [comment]
建议使用 DatePicker，triggerElement={null} 就可以只用面板。
