### ISSUE TITLE
树组件 checkedStrategy 增加一个策略，使子节点不全选时，将父节点设成 checked 状态

### ISSUE THREAD

**Issue by wuhao-igno** [arco-design/arco-design#178]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
目前要实现这样的效果，需要将 `checkStrictly` 设置成 `true`，取消父子节点关联，通过自定义选中取消逻辑的方式来实现；但是这样的实现方式下，父节点无法显示为半选中状态，目前提供的 api 中似乎并不能控制某一节点的 `CheckBox` 的状态，所以期望能够将这一逻辑收到组件中处理。

## 预期解决问题
参考[官方案例](https://arco.design/react/components/tree#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F)，当取消选中 0-0-1 时，0-0 也会从 `checkedKeys` 中被移除，期望能在通过增加 `checkedStrategy` 的可选项，增加一个策略，使得 0-0 下有任一子节点被选中时，0-0 也被加入到 `checkedKeys` 中

**Comment by yinkaihui** [comment]
你在监听onCheck的时候，可以获取到当前选中节点的路径节点信息，直接放到checkedKeys里就行吧 ？

**Comment by wuhao-igno** [comment]
> 你在监听onCheck的时候，可以获取到当前选中节点的路径节点信息，直接放到checkedKeys里就行吧 ？

是可以的，我现在就是这么处理的，但是这样处理的话，当父节点有子节点未选中时，父节点的 `CheckBox` 是选中状态而不是半选中状态，而目前也没有口子能控制树中节点的 `CheckBox` 状态

**Comment by yinkaihui** [comment]
一旦取消父子节点关联，那节点就只跟自己有关系，那么就只有选中和未选中状态。。 我不太清楚你是什么场景下需要取消父子节点关联的同时去根据子节点状态更新父节点状态，感觉这个逻辑有点奇怪

**Comment by wuhao-igno** [comment]
> 一旦取消父子节点关联，那节点就只跟自己有关系，那么就只有选中和未选中状态。。 我不太清楚你是什么场景下需要取消父子节点关联的同时去根据子节点状态更新父节点状态，感觉这个逻辑有点奇怪

就是我在预期解决问题中的描述，目前当子节点中任意一项被设为取消状态时，对应的所有父节点都被设置成了取消状态，从 checkedKeys 中被移除，我目前需要的时候当子节点中任意一项被设为取消状态时，父节点仍为选中状态，只有所有子节点被取消时，父节点才被认为取消；在目前现有的 `checkedStrategy` 没有一个策略能实现这样的效果，所以需要取消父子节点关联手动实现这样的联动。

这就是我一开始说的期望能够增加 `checkedStrategy` 的可选项来实现这个关联，然后你评论了可以监听 `onCheck` 方法来做处理，我就说明了一下为什么这么处理不能满足我的需求。如果在 `checkedStrategy={false}` 的情况下监听 `onCheck` 方法，组件内部的 `checkedKeys` 联动优先级会高于外部受控的值，导致即使外部受控值和组件本身持有的状态不一致，造成实际的 `checkedKeys` 变化是不符合预期的。

其实父子节点关联本来就应该会存在两种状态吧，一种是子节点不全选认为父节点未选中，另一种是子节点全不选才认为父节点未选中。

**Comment by yinkaihui** [comment]
支持 `tree` 的 `checkbox` 接收 `checkboxProps`
