### ISSUE TITLE
能否提供配置, 剔除所有组件的 fill 样式?

### ISSUE THREAD

**Issue by vaynevayne** [arco-design/arco-design#1793]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/124666577/220045383-762c93d6-1ae2-45a8-9d09-057f0acf90ee.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/124666577/220045423-4a6e3aec-1b70-4c7b-853a-665d33659534.png">

fill 样式 懂我意思吧

**Comment by PengJiyuan** [comment]
风格配置平台去看看
