### ISSUE TITLE
【功能请求】组件 - 其他 - 水印

### ISSUE THREAD

**Issue by KS-OTO** [arco-design/arco-design#1796]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
ant设计：https://ant-design.antgroup.com/components/watermark-cn
TD设计：https://tdesign.tencent.com/vue/components/watermark

## 预期解决问题
水印，作为toB、toG行业，常用的信息防伪、版权标识手段，在特定场景（如：敏感信息展示页面、合同签约页面）都有其必要性。
望增加，以满足严肃场景下的使用需要。

期望实现有：
· 2种展示形式：文字、图片
· 2种布局：文字、图片的单行布局，以及纯文字的多行布局

**Comment by yuhan0709** [comment]
https://arco.design/material/detail?name=@arco-materials/watermark

**Comment by KS-OTO** [comment]
> https://arco.design/material/detail?name=@arco-materials/watermark

嗯嗯，看到了。但是这个他方贡献的物料是react实现，我是vue。我很认可物料库这个设计，它对生态的丰富和社区参与贡献有助益。
但，仍然建议【水印】这类“基础”组件可以得到官方支持。

**Comment by G-Akiraka** [comment]
好多物料都是 react 其实对于用vue是很不方便的，官方支持其实更好

**Comment by yinkaihui** [comment]
#2263 #1678
