### ISSUE TITLE
Select Option 无法支持“空格”字符串选项展示

### ISSUE THREAD

**Issue by gitwillsky** [arco-design/arco-design#1802]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.0
- **Browser:** chrome110.0.0.0

## What is expected?
展示四个选项

## Steps to reproduce
```ts
const { Select } = window.arco;
const Option = Select.Option;
const options = ['Beijing', 'Shanghai', 'Guangzhou', ' '];

const App = () => {
  return (
    <Select placeholder='Please select' style={{ width: 154 }}>
      {options.map(option => (
        <Option key={option}  value={option}>
          {option}
        </Option>
      ))}
    </Select>
  );
};

ReactDOM.render(<App />, CONTAINER)
```

**Comment by MisterLuffy** [comment]
https://codesandbox.io/s/holy-bird-xiecg8?file=/demo.js
由于空字符串无法使用 `line-height` 将 DOM 高度撑开，所以视觉上似乎这个选项不存在。需要将空字符串转为 `&nbsp;`，通过 `options` 传入的选项内部已经做了这样的处理，直接使用 ReactChildren 传入的选项请参考上述 Demo。

**Comment by MisterLuffy** [comment]
Filxed here https://github.com/arco-design/arco-design/pull/1807
