### ISSUE TITLE
Cascader  element li remove title attribute

### ISSUE THREAD

**Issue by xiaofengqqcom123** [arco-design/arco-design#1803]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.0
- **Browser:** chrome109.0.0.0

## Steps to reproduce
Beacuse li has title attribute, so when mouse hover, show browser title.  I don't want browser title, like this
![e7d6a743-0777-4ac0-9d9e-393d156eb1da](https://user-images.githubusercontent.com/29247931/221744646-2e6a849b-1ff3-4bbb-b510-e647879616b0.jpeg)

**Comment by yuhan0709** [comment]
@yinkaihui 看下这个

**Comment by yinkaihui** [comment]
label 传个 dom 节点就能避免这个 title 属性了，为啥非得移除？
