### ISSUE TITLE
Cascader组件在切换时 清除按钮icon丢失

### ISSUE THREAD

**Issue by ysh199882** [arco-design/arco-design#1826]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.1
- **Framework version:** React
- **Browser:** chrome110.0.0.0

## What is expected?
切换Select筛选条件，Cascader组件的清除按钮不消失

## Steps to reproduce
当Cascader组件在和Select组件联动时，我切换Select中的筛选条件，Cascader组件中的清除close-btn按钮自动消失

bug复现:
未切换前的：
<img width="430" alt="image" src="https://user-images.githubusercontent.com/76462784/223612727-90aad7fb-af87-45e6-8822-d8a1c57227d8.png">
切换后清除按钮丢失：
<img width="453" alt="image" src="https://user-images.githubusercontent.com/76462784/223612768-10591107-4c66-4cff-889d-037ad5b5f2d9.png">

**Comment by yinkaihui** [comment]
可以给个详细用法么，能有 codepen 更好了～ 我在本地没有复现
