### ISSUE TITLE
table的排序sorter目前能支持完全受控吗

### ISSUE THREAD

**Issue by zhoushan1** [arco-design/arco-design#1827]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
同上

## What problem does this feature solve?
我的需求是，不需要排序有正序，倒序，取消点三下的交互形态，只需要有正序和倒序就行，不需要取消排序，现在我看table似乎是不支持的

**Comment by PengJiyuan** [comment]
sortOrder 就是受控属性，不需要取消排序的话，可以试试自己控制 sortOrder的值

**Comment by zhoushan1** [comment]
> sortOrder 就是受控属性，不需要取消排序的话，可以试试自己控制 sortOrder的值

@PengJiyuan 我看sortOrder是string类型，这个是否能支持function类型，我的需求是期望sortOrder是动态变化的
