### ISSUE TITLE
关于vue日期选择-范围性年份选择存在bug 

### ISSUE THREAD

**Issue by cmwaiwj** [arco-design/arco-design#1828]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.1
- **Browser:** chrome111.0.0.0

## Steps to reproduce
认真测试呐，你们更新了版本，都没测试吗

**Comment by PengJiyuan** [comment]
这里是 React
