### ISSUE TITLE
[ts 定义]RangePickerProps 的onChange事件, 第二个参数应该是可选的

### ISSUE THREAD

**Issue by vaynevayne** [arco-design/arco-design#1832]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.2
- **Browser:** chrome110.0.0.0

## Steps to reproduce
当封装datePicker,我不能直接使用RangePickerProps作为ts声明,
 受控模式下,传入的value是一个日期数组, 当我内部有一个按钮,手动调用onChange去修改日期时,我应该只需要传递日期数组给onChange即可,并不需要传入第二个参数, 对吧
 但是datePicker自身触发onChange,会传入第二个参数,dateString

我表达的你能理解吗?
<img width="549" alt="image" src="https://user-images.githubusercontent.com/124666577/224299893-b76bc2c7-0ae8-4e02-af8c-9260e643c43d.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/124666577/224300008-3531c3bd-f07d-4d04-8c69-2bc2bf7cb487.png">

另外建议别跳转到你们自己都的issue模板,太麻烦了,还不能贴图,

**Comment by yinkaihui** [comment]
如果对 arco 暴露出的参数有二次封装，例如你会在自己的组件里去触发 onChange（可以理解为用户监听的是你触发的 onChange，而不是 arco 的 onChange 了），建议自行声明类型定义
