### ISSUE TITLE
vue范围选择器，年份选择存在bug，

### ISSUE THREAD

**Issue by cmwaiwj** [arco-design/arco-design#1833]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.45.2
- **框架版本:** 2.40.1
- **浏览器版本:** chrome111.0.0.0
- **复现地址:** https://arco.design/vue/component/date-picker

## 额外补充
同时，单独使用year-picker时，打包失败，提示不能引出此组件

## 预期结果
年份范围可以正常选择

## 复现步骤
1..进入日期选择器；
2.点击范围选择，年份选择
3.选择具体年份，弹框重复；

**Comment by cmwaiwj** [comment]
请重视问题

**Comment by cmwaiwj** [comment]
这个问题出现在vue版本

**Comment by luckyship** [comment]
你提错地方了把，这里是react版本的，应该去vue，https://github.com/arco-design/arco-design-vue/issues
