### ISSUE TITLE
DropDown 组件搭配 Typography 的超出换行特性页面高度被撑起

### ISSUE THREAD

**Issue by kezuncheng** [arco-design/arco-design#1834]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.2
- **Framework version:** 17.0.2
- **Browser:** chrome111.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/funny-lovelace-olz7el?file=/demo.js:414-424

## Extra info
应该是 Typography 的超出折叠属性，计算的过程中添加了额外的 dom 节点，占用了额外的高度

## What is expected?
不应该影响页面的高度，不应该出现滚动条

## Steps to reproduce
点击 click me 按钮，面板展开过程中，页面高度被撑开，右侧面板会出现滚动条

**Comment by yuhan0709** [comment]
还没定位到问题，先开启 `cssEllipsis: true` 解决下。。
