### ISSUE TITLE
表头分组border显示问题

### ISSUE THREAD

**Issue by silaLi** [arco-design/arco-design#1835]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.45.2
- **浏览器版本:** chrome111.0.0.0
- **复现地址:** https://codesandbox.io/s/elastic-wing-fwe4ik?file=/src/App.js

## 复现步骤
在Table组件中使用表头分组，表头分组的border显示不全
![image](https://user-images.githubusercontent.com/13845483/224643626-df0f26df-7f25-42c2-89dc-ddeb2702c756.png)

**Comment by lrenc** [comment]
可以单独给 header 加上 border 显示
```javascript
border={{
   headerCell: true
}}
```
