### ISSUE TITLE
table 首尾分布定义  fixed: "left",  fixed: "right"，且使用summary，开启X，Y滚动时，出现cell移位

### ISSUE THREAD

**Issue by tiehongji** [arco-design/arco-design#1836]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.2
- **Framework version:** 2.45.0
- **Browser:** chrome111.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/stupefied-artem-qnov8w?file=/demo.js
- 
![c9a8d64b-d76a-4c2c-9a01-ba21b7c440d3](https://user-images.githubusercontent.com/32897147/224681253-ca9e5df6-9043-4377-b1b1-9c6bfbf4208f.jpeg)

**Comment by lrenc** [comment]
#1840

**Comment by lrenc** [comment]
Please change the value of `colSpan` from 5 to 4.
