### ISSUE TITLE
Table固定列 开启列宽度调整 固定列调整会出现问题

### ISSUE THREAD

**Issue by pyphkx** [arco-design/arco-design#1837]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.45.2
- **框架版本:** vue
- **浏览器版本:** chrome110.0.0.0

## 复现步骤
在Table左侧几个列的固定  开启列宽度调整 对固定列的宽度进行往小调整会出现 当前的bug

**Comment by PengJiyuan** [comment]
提供个codesandbox吧
