### ISSUE TITLE
popover shuts down unexpectedly

### ISSUE THREAD

**Issue by shilongReact** [arco-design/arco-design#1839]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.0
- **Framework version:** React:16.9.0
- **Browser:** chrome110.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/optimistic-zeh-kt3y38?file=/demo.js

## What is expected?
The pop-up window opens normally when the mouse touches the disabled element below it

## Steps to reproduce
If the mouse touches the disabled element below the popup window, the hover popup expansion closes unexpectedly

**Comment by PengJiyuan** [comment]
Not because of the disabled element, you can set triggerProps={{ mouseLeaveDelay: 500 }}, increase the delay time.
