### ISSUE TITLE
Switch Component can be open/close by pressing the space bar when it has been opened 

### ISSUE THREAD

**Issue by Apple-U** [arco-design/arco-design#1844]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.45.2
- **Browser:** chrome111.0.0.0

## Steps to reproduce
https://arco.bytedance.net/react/components/switch
打开之后
再按空格 可以控制开关
不需要这个多余的功能，这个功能如何关闭呢

**Comment by PengJiyuan** [comment]
这个属于无障碍增强，焦点在switch上，就可以通过空格控制开关。无法关闭。
