### ISSUE TITLE
TS2786: 'DatePicker.RangePicker' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design#1855]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.46.0
- **Framework version:** React
- **Browser:** chrome111.0.0.0

虽然不影响项目运行，但是这个样式错误会在开发过程中带来很多不便

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/58337359/226049375-8c451988-d19c-454c-9d6f-6663671d63cf.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/58337359/226050174-71ea9a42-c146-4854-8859-78ae6d44d763.png">

**Comment by adow** [comment]
我也遇到了这个问题，请问最后是怎么解决的啊？

**Comment by adow** [comment]
我现在只能把 typescript, react-dom 这些库版本退回
<img width="453" alt="image" src="https://github.com/arco-design/arco-design/assets/504314/9514455a-0e4f-4f5c-b2d0-c95097c48e7e">

**Comment by dongwujing** [comment]
我也遇到了这个问题，请问最后是怎么解决的啊？

**Comment by samkk** [comment]
我也遇到这个问题了，请问怎么解决的
'DatePicker' cannot be used as a JSX component.
Its instance type 'Component<DatePickerProps, any, any>' is not a valid JSX element.

**Comment by HoBeedzc** [comment]
我也遇到这个问题了，请问怎么解决的
