### ISSUE TITLE
TS下，Table 组件，添加过滤 sortDirections / defaultSortOrder 时，编译器报错“类型不匹配”

### ISSUE THREAD

**Issue by XLearner** [arco-design/arco-design#1857]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.46.0
- **浏览器版本:** chrome111.0.0.0
- **复现地址:** https://codepen.io/pen?&editors=001&prefill_data_id=611e1ba4-201e-4fee-966a-7b5d95ef64ba

## 复现步骤
将代码放入 typescript 环境中

![image](https://user-images.githubusercontent.com/26158725/226321990-f3821a8e-0597-492c-a925-1dffc056c9b7.png)

**Comment by lrenc** [comment]
codepen 打开代码是空的

**Comment by PengJiyuan** [comment]
![image](https://user-images.githubusercontent.com/19399269/227442572-dccd5e4d-5c96-4cd9-8a59-2b18a7556dda.png)
