### ISSUE TITLE
 Rollup failed to resolve import "@arco-design/web-vue/es/breadcrumb/style/css.js" from "src/components/breadcrumb/index.vue".

### ISSUE THREAD

**Issue by MichealJou** [arco-design/arco-design#1870]
Rollup failed to resolve import "@arco-design/web-vue/es/breadcrumb/style/css.js" from "src/components/breadcrumb/index.vue".

**Comment by yuhan0709** [comment]
请到 https://github.com/arco-design/arco-design-vue 提 issue 哈
