### ISSUE TITLE
Input.Password 和 maxLength showWordLimit 同时使用时不显示明文按钮

### ISSUE THREAD

**Issue by Minitiai** [arco-design/arco-design#1877]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.46.1
- **Framework version:** latest
- **Browser:** chrome111.0.0.0
- **Reproduction Link:** https://codepen.io/minitiai/pen/wvEbaJz?editors=001

**Comment by yinkaihui** [comment]
`showWordLimit` 属性在设计上是不应该在 `Input.Password` 上生效的，之前没有发现这个问题，目前也不适宜直接移除，下个大版本将会调整下这里的逻辑。
