### ISSUE TITLE
官网文档权限控制页面 cpu使用异常导致页面假死

### ISSUE THREAD

**Issue by moonrailgun** [arco-design/arco-design#1879]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.46.1
- **Browser:** chrome111.0.0.0
- **Reproduction Link:** https://arco.design/docs/pro/permission

## Extra info
 ![iluX2Q.png](https://i.328888.xyz/2023/03/31/iluX2Q.png)

## Steps to reproduce
打开arco design pro 文档的权限控制页面，发现cpu占用很高 别的页面没有这个问题

**Comment by yuhan0709** [comment]
修复了哈，因为这个页面原来渲染了 2 张超大的动图

**Comment by moonrailgun** [comment]
6
