### ISSUE TITLE
Collapse in Form.List, triigered an unexpected onChange event when adding item to Form.List

### ISSUE THREAD

**Issue by cfabregas** [arco-design/arco-design#1886]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.46.2
- **Framework version:** react
- **Browser:** chrome111.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/quirky-tess-e552sx?file=/demo.js

## What is expected?
nothing happened, it works well in  2.44.3

## Steps to reproduce
click add button and see console.log

**Comment by MisterLuffy** [comment]
@yinkaihui Plz have a look
