### ISSUE TITLE
使用 umd 引入 js 的同时， css 文件也是需要手动引入的吧，文档中只标注了js 文件使用 CDN 引入

### ISSUE THREAD

**Issue by nmsn** [arco-design/arco-design#1889]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.46.2
- **浏览器版本:** chrome111.0.0.0

**Comment by MisterLuffy** [comment]
是的，JS 文件是不含样式的。从 http://unpkg.com/@arco-design/web-react@2.46.2/dist/css/arco.min.css 此路径引入 CSS。

**Comment by nmsn** [comment]
建议文档中标注下
