### ISSUE TITLE
table 是否可以增加带状态表格

### ISSUE THREAD

**Issue by G-Akiraka** [arco-design/arco-design#1904]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
[![ppqMO2j.png](https://s1.ax1x.com/2023/04/10/ppqMO2j.png)](https://imgse.com/i/ppqMO2j)
参考图片

## What problem does this feature solve?
可将表格内容 highlight 显示，方便区分「成功、信息、警告、危险」等内容。 顺便自定义颜色
特殊情况下需要对表格里面的内容进行状态标记，用来更直观的查看内容

**Comment by yuhan0709** [comment]
支持 `rowClassName` 这个 API，可以看下这个demo https://codesandbox.io/s/sad-kepler-n7qt2m?file=/demo.js

**Comment by G-Akiraka** [comment]
> 支持 `rowClassName` 这个 API，可以看下这个demo https://codesandbox.io/s/sad-kepler-n7qt2m?file=/demo.js

这个是react的 vue版本并没有这个 api
