### ISSUE TITLE
DatePicker 组件的面板icon自定义问题

### ISSUE THREAD

**Issue by lynn1286** [arco-design/arco-design#1911]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.46.3
- **Browser:** chrome112.0.0.0

## What is expected?
支持自定义icon的场景下调整icon的大小导致样式错乱，高度不应该限制死

## Steps to reproduce
https://codesandbox.io/s/angry-feistel-7m4oow?file=/demo.js:95-105

**Comment by PengJiyuan** [comment]
这个预期是只能传入 icon 的，设置成按钮，不说高度，原本的hover底色还在，怎么看都有问题。想弄成这种交互还是试试用主题商店配置吧，或则样式覆盖
