### ISSUE TITLE
功能请求 Message 组件能不能带颜色状态，这样更直观察觉错误类型

### ISSUE THREAD

**Issue by G-Akiraka** [arco-design/arco-design#1912]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.46.3
- **Browser:** chrome112.0.0.0

### 原来的消息提示
[![ppvN7dS.png](https://s1.ax1x.com/2023/04/13/ppvN7dS.png)](https://imgse.com/i/ppvN7dS)

### 增加这种效果的消息提示
* 类似这种效果，更加的直观表达错误类型目前的一闪而过很不清晰

[![ppvNt54.png](https://s1.ax1x.com/2023/04/13/ppvNt54.png)](https://imgse.com/i/ppvNt54)

**Comment by PengJiyuan** [comment]
不同设计规范下的差异吧，可以用风格配置平台达到你想要的效果。https://arco.design/themes

**Comment by G-Akiraka** [comment]
> 不同设计规范下的差异吧，可以用风格配置平台达到你想要的效果。https://arco.design/themes

风格化不太合理吧，用这个实现，个人感觉特殊场景特殊需求根据实际需求操作，我先风格化试试看
