### ISSUE TITLE
Autocomplete with API data

### ISSUE THREAD

**Issue by applibs** [arco-design/arco-design#1914]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Similar case is Autocomplete API https://mui.com/material-ui/api/autocomplete/

## What problem does this feature solve?
I am looking for solution using Autocomplete with data from API. It means when I start writing some text it will show me result from API and I will select any item from list.

**Comment by applibs** [comment]
Any example using children attribute?

**Comment by MisterLuffy** [comment]
I'm not quite sure what you're wondering about. AutoComplete can not receive `children` property, the dropdown list is completely controlled by `data`.
