### ISSUE TITLE
Dropdown 支持自定义传入 droplist 组件的问题

### ISSUE THREAD

**Issue by lynn1286** [arco-design/arco-design#1923]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.47.0
- **Browser:** chrome112.0.0.0

## What is expected?
将menu组件进行封装后，样式丢失，感觉不符合预期

## Steps to reproduce
https://codesandbox.io/s/sharp-brattain-sm3b0g?file=/demo.js:603-611

**Comment by lynn1286** [comment]
还有个问题，menuItem在遍历的场景下加 空Fragment会报key的错误问题。

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/40122311/232382637-ec609a14-51f7-480a-81c7-a185f35e42e2.png">

**Comment by MisterLuffy** [comment]
这个 Warning 是一个 React 的基础问题 https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js。

Menu.Item 需要是 Menu 的直接子元素，Menu 会编辑其直接子元素收集菜单信息。如果需要对 Menu.Item 进行封装，需要一个特殊标记表示此组件为菜单项。

```js
function MyMenuItem (props) {
  return <Menu.Item {...props} />
}

MyMenuItem.menuType = 'MenuItem';
```

一般不推荐上述的做法。对于你的场景，建议构建元素数组。

```js
const eleDropdownList = [];
droplist.forEach((item, index) => {
  if (condition) {
    eleDropdownList.push(<Divider key={`${index}_divider`} />);
  }
  eleDropdownList.push(<Menu.item key={index} />)
});
```
