### ISSUE TITLE
Table组件的【可伸缩列】demo里csb缺少依赖

### ISSUE THREAD

**Issue by mfoonirlee** [arco-design/arco-design#1926]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.47.0
- **Browser:** chrome111.0.0.0

## Steps to reproduce
在这个页面 https://arco.design/react/components/table#%E5%8F%AF%E4%BC%B8%E7%BC%A9%E5%88%97
打开codesandbox报错

**Comment by PengJiyuan** [comment]
代码在codesandbox打开的逻辑里，确实没有包含这个包，只带着一些通用的包过去了。像是resize drag 之类的包，自己手动加一下吧~
