### ISSUE TITLE
List组件 page size change 显示不出来

### ISSUE THREAD

**Issue by sujingclg** [arco-design/arco-design#1933]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.47.0
- **Browser:** chrome112.0.0.0
- **Reproduction Link:** https://codepen.io/sssjuing/pen/ExdNOzr?editors=001

**Comment by MisterLuffy** [comment]
弹出框未展示是因为 `arco-list-wrapper` 存在 `overflow: hidden` 样式，此样式是为了清除分页器 `float: right` 的浮动影响。

最佳的修改方式是为 `Pagination` 包裹一层 `div`，然后使用 `flex` 将其右对齐，但如此会改动组件 Dom 结构，所以组件内部不便修改，请自行对 `arco-list-wrapper` 进行样式覆盖，移除 `overflow: hidden` 样式。
