### ISSUE TITLE
下拉选择的选项高度可以设置

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design#194]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 

此高度可以提供属性设置，因为当 Select 的 size 选择 small 甚至 mini 的时候，选项的高度显得有点突兀
![image](https://user-images.githubusercontent.com/58337359/142651462-f0e95c16-ee19-4ae1-9cc2-77cf02e72ed0.png)

## 现有案例
无

## 预期解决问题
可以提供属性设置选项的高度，类似 Select 的 size 属性

**Comment by MisterLuffy** [comment]
感觉这样的属性有点鸡肋。通过 CSS 进行样式覆盖，或者使用 [Arco 主题商店配置主题](https://arco.design/themes?currentPage=1&pageSize=8&tag=recommend) 配置主题可以吗？

**Comment by lin-mt** [comment]
> 似 Select 的 size 属性

有的话更好，没有的话问题不大，只是选项的高度比输入框的大，在点击输入框，弹出选项的时候会有点突兀，不知道其他人会不会有这种感觉，没有计划提供的话，可以把这个 issue 关了哈
