### ISSUE TITLE
表格设置 scrollX 不超过 100% 且数据为空时，会出现不可预期横向滚动条

### ISSUE THREAD

**Issue by whyour** [arco-design/arco-design#1958]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.47.2
- **浏览器版本:** chrome113.0.0.0
- **复现地址:** https://codesandbox.io/s/new-cdn-4ypzdv?file=/demo.js

## 预期结果
无滚动条

**Comment by whyour** [comment]
.arco-table-border .arco-table-td:first-child 设置左边框时，应该加上 not(.arco-table-empty-row) 的限制，要不然左边两个边框

**Comment by Galileo01** [comment]
constant attention
