### ISSUE TITLE
描述列表 Descriptions data渲染数据问题

### ISSUE THREAD

**Issue by YOUAHAHAH** [arco-design/arco-design#1965]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.0
- **Browser:** chrome113.0.0.0

## Steps to reproduce
  useEffect(() => {
    const arr = Object.keys(item).map(k => ({ label: k, value: item[k] }));
    console.log(arr.length); // 8
    setItemData(arr.splice(0, 2));
     //  setItemData(arr);
    console.log(arr, data); 
  }, [visible]);

 <Descriptions
        colon=" :"
        layout="inline-horizontal"
        // title="User Info"
        data={itemData}
      />

 setItemData(arr.splice(0, 2)); 可以显示数据
 setItemData(arr); 不能显示数据
 setItemData(arr.slice(0, 8));  不能显示数据
 Uncaught Error: Objects are not valid as a React child (found: object with keys {packageName, file, module, style}). If you meant to render a collection of children, use an array instead.
控制台打印有八条数据

是数据过多导致Descriptions无法渲染吗还是怎么样

**Comment by MisterLuffy** [comment]
阅读代码没有发现问题所在。请提供可以复现此问题的 Demo 地址，例如 Codepen 或者 CodeSandbox。

报错的原因大概是因为 `dataItem.value` 是一个对象（应该为 `ReactNode`），类型错误。`data` 的数据类型如下：

```ts
type DataType = {
  key?: React.Key;
  label?: ReactNode;
  value?: ReactNode;
  span?: number;
}[];
```

**Comment by YOUAHAHAH** [comment]
> 阅读代码没有发现问题所在。请提供可以复现此问题的 Demo 地址，例如 Codepen 或者 CodeSandbox。
> 
> 报错的原因大概是因为 是一个对象（应该为 ），类型错误。的数据类型如下：`dataItem.value``ReactNode``data`
> 
> ```ts
> type DataType = {
>   key?: React.Key;
>   label?: ReactNode;
>   value?: ReactNode;
>   span?: number;
> }[];
> ```

是无法渲染value为对象
