### ISSUE TITLE
Collapse.Item behaves differently on build

### ISSUE THREAD

**Issue by applibs** [arco-design/arco-design#1967]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.0
- **Browser:** chrome113.0.0.0

## What is expected?
I expect expanded colapser on click event.

## Steps to reproduce
I used yarn dev and Collapse work as expected.
When I use yarn build, then Collapse not work on click. Its always collapsed.
It happen only on one component. Anothers are OK! All looks same as others.

**Comment by MisterLuffy** [comment]
Please provide a minimal repro project, such as a Git repository.
