### ISSUE TITLE
Trigger弹层在第三方包中层级设置失效

### ISSUE THREAD

**Issue by yiescc** [arco-design/arco-design#1968]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.0
- **Browser:** chrome113.0.0.0
- **Reproduction Link:** https://github.com/yiescc/turbo-demo-20230516.git

## Extra info
构建后，第三方包中的Select的弹层层级设置失效

## Steps to reproduce
1. pnpm i  --shamefully-hoist
2. npm run build

![image](https://github.com/arco-design/arco-design/assets/87901556/387b43a9-bf3f-4a24-b7e5-ebce201176c4)

**Comment by yinkaihui** [comment]
是不是因为 arco 被打包到封装的物料里了，导致在使用的时候物料里的 select 读取的 ConfigProvider context 和 Drawer 注入的不是同一个，出现了 popupZindex 失效的情况？

**Comment by yinkaihui** [comment]
我这里是表现正常的呀 ～ 
<img width="1876" alt="image" src="https://github.com/arco-design/arco-design/assets/23161413/8169c491-c941-47b9-a6ed-1ed54867fe32">

**Comment by yiescc** [comment]
dev下正常渲染，复现需要build之后
