### ISSUE TITLE
Select 多选，输入已选中选项、回车，清除的选项不对

### ISSUE THREAD

**Issue by Alfie3621** [arco-design/arco-design#1969]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.0
- **Browser:** chrome112.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/q1brdp?file=/demo.js

## Steps to reproduce
1. 输入 abc，回车
2. 输入 ab，回车
3. 输入 ab，回车，会发现第 1 步输入的 abc 被清除了

**Comment by MisterLuffy** [comment]
以上表现实际上是符合预期的。

在设置了 `allowCreate` 允许创建选项时，输入兼具了「搜索」和「创建」的功能，在第三次输入 `ab` 时，此时符合过滤条件的选项为 `['abc', 'ab']`。

Select 搜索仅对选项列表进行过滤，并不会更改其顺序，所以此时直接回车将取消选中过滤列表的第一个。
