### ISSUE TITLE
datepicker  无法输入, onBlur时, 输入的值消失了

### ISSUE THREAD

**Issue by vaynevayne** [arco-design/arco-design#1972]
https://arco.design/react/components/date-picker#%E8%8C%83%E5%9B%B4%E9%80%89%E6%8B%A9%E5%99%A8

通过input输入时间, 当onBlur以后, 值被还原了

**Comment by PengJiyuan** [comment]
输入后 enter 确认值或者手动点到下一个输入框，两个输入框都是有效值，并且enter确认，才会生效

**Comment by vaynevayne** [comment]
好的, 请问下确认按钮是后期加的吗?  我这个版本回车没用
<img width="639" alt="image" src="https://github.com/arco-design/arco-design/assets/124666577/f28afa4f-e81a-44c9-8c4e-b48c06e8641b">

**Comment by vaynevayne** [comment]
@PengJiyuan  mac上不行

**Comment by vaynevayne** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode 可能是你们使用了不推荐的keyCode 导致的，
可以参考 https://mantine.dev/hooks/use-hotkeys/ 换成key，此外也可以封装成hook
@PengJiyuan 可以重新打开issue吗，问题还在呢
