### ISSUE TITLE
windows本地启动项目没有执行组件内置css，导致整个项目样式混乱

### ISSUE THREAD

**Issue by lucky20160622** [arco-design/arco-design#1979]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.1
- **Framework version:** React 18.0
- **Browser:** chrome113.0.0.0

## Steps to reproduce
windows本地启动项目，没有执行框架内置css文件，导致icon特别大以及button按钮没有样式，input也没样式属性，只有windows本地出现了问题，线上正常显示，macos也没问题

**Comment by MisterLuffy** [comment]
请在提供更多信息和可复现仓库后重打开此 Issue。
