### ISSUE TITLE
value 不为空导致 placeholder 不显示

### ISSUE THREAD

**Issue by Minitiai** [arco-design/arco-design#1981]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.1
- **Framework version:** latest
- **Browser:** chrome113.0.0.0
- **Reproduction Link:** https://codepen.io/minitiai/pen/gOBqOEm?editors=001

## Steps to reproduce
select 组件，当传参有 value 时，参数 placeholder 不显示

**Comment by MisterLuffy** [comment]
有 `value` 的时候 `placeholder` 不展示不是正常的逻辑吗？

**Comment by MisterLuffy** [comment]
`''` 也会被认为是合法的选项值的。 [常见问题](https://arco.bytedance.net/react/docs/question#%E4%B8%BA%E4%BB%80%E4%B9%88-null-%E5%92%8C--%E5%9C%A8-select-%E7%BB%84%E4%BB%B6%E4%B8%AD%E8%A2%AB%E5%BD%93%E4%BD%9C%E6%9C%89%E5%80%BC%E8%80%8C%E4%B8%8D%E6%98%BE%E7%A4%BA-placeholder-%EF%BC%9F)
