### ISSUE TITLE
在vite中使用rollup-plugin-visualizer打包时error InputNumber DatePicker 无法解析

### ISSUE THREAD

**Issue by YOUAHAHAH** [arco-design/arco-design#1998]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.48.2
- **Framework version:** react 18.2
- **Browser:** chrome113.0.0.0
- **Reproduction Link:** https://codesandbox.io/p/github/YOUAHAHAH/react-acro-admin/main?file=/src/components/SearchBox/src/searchBox.tsx:14,3-14,14&workspaceId=0d348359-9304-4cbc-a9d4-f64ac4fb8875

## Steps to reproduce
npm run build 的时候
Rollup failed to resolve import "@arco-design/web-react/es/input-number" from "C:/Users/YOUAH/Desktop/react/Acro/react-acro-admin/src/components/SearchBox/src/searchBox.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by MisterLuffy** [comment]
上边的地址无法打开
![image](https://github.com/arco-design/arco-design/assets/29861850/248592ee-6a80-4daa-ba3e-0ab9cc7e1287)
