### ISSUE TITLE
使用rangePicker组件后，会把moment.locale() 得到的值改为中文

### ISSUE THREAD

**Issue by hehuangz** [arco-design/arco-design#200]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** 2.22.0
- **System:** mac
- **Browser:** chrome
- **Reproduction Link:** https://codesandbox.io/s/proud-star-l1nbj?file=/index.js

## What is expected?
RangePicker不修改locale

## Steps to reproduce
RangePicker修改了Moment的locale，默认为中文了

**Comment by PengJiyuan** [comment]
经沟通已解决
