### ISSUE TITLE
menu悬浮菜单

### ISSUE THREAD

**Issue by sxdooo** [arco-design/arco-design#201]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react": "^2.19.1"
- **系统版本:** mac os 11.2.3
- **浏览器版本:** chrome 95
- **复现地址:** https://arco.design/react/components/menu#%E6%82%AC%E6%B5%AE%E8%8F%9C%E5%8D%95

## 预期结果
悬浮菜单不会消失

## 复现步骤
鼠标滑到navigation2，右侧会显示悬浮菜单，此时慢些向右滑动（想要点击右边的悬浮菜单），滑动到navigation2 与 悬浮菜单之间，悬浮菜单消失了

**Comment by MisterLuffy** [comment]
修改此行为会引起较大的 DOM 结构变动，因此不便组件内部调整。

建议通过 Menu 的 `triggerProps.mouseLeaveDelay` 延长鼠标移出时弹层自动隐藏的时间，或者 `triggerProps.popupAlign` 修改弹层的偏移位置。

```
triggerProps = {
  mouseLeaveDelay: 100,
  popupAlign: {
    right: 0,
  }
};
```
