### ISSUE TITLE
Tree performance issue when expanding a node containing large amount of children nodes

### ISSUE THREAD

**Issue by gkzhb** [arco-design/arco-design#2021]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.49.0
- **框架版本:** react 17.0.2
- **浏览器版本:** Chrome/114.0.0.0
- **复现地址:** https://codesandbox.io/s/inspiring-field-244zwm?file=/src/pages/Home/index.tsx

## 预期结果
Web page will not stuck when expanding the node

## 复现步骤
https://244zwm.csb.app/
Web page stucks when expanding "xxx" node.

## 额外补充
Performance bottleneck in these functions:
1. arco-design/components/Tree/animation.tsx filtedData
2. arco-design/components/Tree/node-list.tsx calcChildrenList
3. arco-design/components/Tree/index.tsx getNodeProps

More to see in https://bytedance.feishu.cn/docx/PRQnd0MFPo7mUzxO0AycvdPcnSe

**Comment by yinkaihui** [comment]
https://github.com/arco-design/arco-design/pull/2158
