### ISSUE TITLE
Input.Password报错content_script.js:3880 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by aide-cloud** [arco-design/arco-design#2027]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.49.1
- **框架版本:** React@18
- **浏览器版本:** chrome114.0.0.0

## 补充信息

https://github.com/arco-design/arco-design/assets/52439018/305ab9c9-3730-40c8-8d56-43ffefb070df

**Comment by yinkaihui** [comment]
你好，辛苦给个复现demo吧，也可以先行排查下是不是个 form 的 password 字段设置了非字符串的值
