### ISSUE TITLE
Tabs 的 DOM element 上出现 scrollPosition属性

### ISSUE THREAD

**Issue by karl-LiChenXiang** [arco-design/arco-design#204]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react: 2.25.0
- **System:** MAC
- **Browser:** Chrome
- **Reproduction Link:** https://arco.design/react/components/tabs

## Extra info
Tabs 的 DOM element 上出现 scrollPosition属性
![image](https://user-images.githubusercontent.com/69134891/142981683-b79e97af-d957-4fcd-b9da-ac504ba87fbd.png)
![image](https://user-images.githubusercontent.com/69134891/142981702-4bf645f0-33b5-41bf-91bf-d8fff9d1789c.png)

## What is expected?
Tabs 的 DOM element 上出现 scrollPosition属性

## Steps to reproduce
Tabs组件有问题

**Comment by qianyeyixia** [comment]
我也遇到了

**Comment by yuhan0709** [comment]
非常抱歉～ 这周修复😭
