### ISSUE TITLE
Tree组件如果节点是异步的情况时expandedKeys不展开

### ISSUE THREAD

**Issue by tipsxBase** [arco-design/arco-design#2041]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.49.2
- **Framework version:** React18.2
- **Browser:** chrome113.0.0.0

![image](https://github.com/arco-design/arco-design/assets/16009561/a971776d-f9a0-4352-be4c-7eedc775f5aa)
初始渲染时，因为还没有treeNodes 所以导致这里计算的 expendedKeys 是空
当ajax请求完成时，重新拿到数据生成treeNodes时，执行 componentDidUpdate 时，因为两次的 expendedKeys 是一样的导致 state 中的 expendedKeys 没有更新，从而导致expendedKeys 不生效

![image](https://github.com/arco-design/arco-design/assets/16009561/1a204370-136f-4b21-ac8a-34cf53c2eb47)

**Comment by yinkaihui** [comment]
可以试试在 setTreeData 之后，更新下 expandedKeys
 https://codesandbox.io/s/jovial-gauss-v3prqw?file=/demo.js
