### ISSUE TITLE
resizeObserver.js:44 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeObserverComponent2 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely 

### ISSUE THREAD

**Issue by vaynevayne** [arco-design/arco-design#2043]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.49.2
- **Browser:** chrome114.0.0.0

**Comment by PengJiyuan** [comment]
https://github.com/arco-design/arco-design/issues/1447
