### ISSUE TITLE
Select 组件定制回显内容示例代码 TS 类型报错

### ISSUE THREAD

**Issue by shi-yang** [arco-design/arco-design#2045]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.49.2
- **框架版本:** "react": "^18.2.0", "typescript": "^5.1.3"
- **浏览器版本:** chrome114.0.0.0

## 报错信息

如下图：

![image](https://github.com/arco-design/arco-design/assets/5102567/fef628e3-b420-435a-b72a-ec7987f6f992)

## 预期结果
不提示错误信息

## 复现步骤
按照官方文档的源码示例，参见 **Select - 定制回显内容** 这一部分：

官方文档链接地址：
[https://arco.design/react/components/select#%E5%AE%9A%E5%88%B6%E5%9B%9E%E6%98%BE%E5%86%85%E5%AE%B9](https://arco.design/react/components/select#%E5%AE%9A%E5%88%B6%E5%9B%9E%E6%98%BE%E5%86%85%E5%AE%B9)

**Comment by MisterLuffy** [comment]
因为 Demo 的示例代码是 JS 语法，`value` 的 TS 类型除了 `string | number` 还有可能是 `{ value: string | number; label: ReactNode }` 的形式。此处可以通过 `value as string` 解决报错。
