### ISSUE TITLE
Anywhere example using arco-plugins/packages /plugin-vite-react ?

### ISSUE THREAD

**Issue by applibs** [arco-design/arco-design#2046]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.49.2
- **Browser:** chrome114.0.0.0

## What is expected?
Nowhere is example how to override: @arco-theme-tag: body; into @arco-theme-tag: .my-class; for example.
How to do it with varsInjectScope or modifyVars? And how?

**Comment by yinkaihui** [comment]
可以参考这里～ https://github.com/arco-design/arco-plugins/tree/main/packages
