### ISSUE TITLE
官网更新日志不能正常使用浏览器的搜索功能

### ISSUE THREAD

**Issue by wuhao-igno** [arco-design/arco-design#206]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** -
- **系统版本:** macOS Big Sur 11.6(20G165)
- **浏览器版本:** Chrome 版本 95.0.4638.69（正式版本） (x86_64)
- **复现地址:** https://arco.design/react/docs/changelog

## 预期结果
使用浏览器搜索功能能够正常查询更新日志中的内容。

## 复现步骤
打开文档中的更新日志页，当页面处在顶部时，使用 command f 打开浏览器搜索功能，输入任意内容进行搜索，如 "form"；点击跳转到下一个搜索结果，一般跳到两到三个结果后会返回到页面顶部。页面向下滚动一定长度后搜索则不会有这个问题。

**Comment by PengJiyuan** [comment]
见鬼
