### ISSUE TITLE
Tabs组件的onDeleteTab属性能否设计成类似Tag的onClose一样，函数签名的返回值支持Promise类型【(key: string) => Promise<any> | void】

### ISSUE THREAD

**Issue by kaerhasnoballs** [arco-design/arco-design#2073]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
<Tabs
        onDeleteTab={(key) => {
          return new Promise((resolve, reject) => {
            Modal.confirm({
              content: 'Are you sure to close this tab, you will lose your unsaved-data?',
              onOk() {
                resolve(void 0);
              },
              onCancel() {
                reject();
              },
            });
          });
        }}
      ></Tabs>

## What problem does this feature solve?
在关闭tab之前需要做一个业务上的判断提醒用户是否关闭此tab

**Comment by MisterLuffy** [comment]
`onDeleteTab` 仅表示删除按钮被点击的回调，真正的 Tabs 改变需要自行通过更新 children 实现。所以可以在 `onDeleteTab` 回调中进行异步操作，`resolve` 之后更新 Tabs 子元素。

https://codesandbox.io/s/confident-cloud-q2gs9n?file=/demo.js
