### ISSUE TITLE
页面滑动时，Select未跟随

### ISSUE THREAD

**Issue by Xwudao** [arco-design/arco-design#2074]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.50.0
- **Browser:** chrome114.0.0.0
- **Reproduction Link:** https://hunhepan.com/#/rule_list

## Steps to reproduce
展开Select，然后滑动页面，就会发现Select选项未跟随页面滑动

![image](https://github.com/arco-design/arco-design/assets/31327868/d0cdacb7-a18f-4265-adae-5e7e30784121)

**Comment by Xwudao** [comment]
> Maybe you can use getPopupContainer to select a node

Ok, thank you.

**Comment by MisterLuffy** [comment]
或者通过 `triggerProps.updateOnScroll` 来指定在滚动时更新弹出元素位置。

**Comment by Xwudao** [comment]
> `updateOnScroll`

主要是我看官网都没有问题，而我这里是全站都有问题，这是因为啥呀
