### ISSUE TITLE
arco-table能不能支持多选几行一起拖拽排序，这样更灵活？

### ISSUE THREAD

**Issue by mjkb123456** [arco-design/arco-design#2076]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
排序更灵活，操作更快捷

**Comment by PengJiyuan** [comment]
拖拽排序是自定义拓展，配合第三方库，可以尝试一下是不是能做到
