### ISSUE TITLE
Modal 开启 autoFocus 时，Select 和 Cascader 等组件如果有 renderFormat 会导致默认值展示不正常

### ISSUE THREAD

**Issue by LaamGinghong** [arco-design/arco-design#2087]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.50.1
- **框架版本:**  React
- **浏览器版本:** chrome114.0.0.0
- **复现地址:** https://codesandbox.io/s/magical-dew-4h2vds

## 预期结果
下拉框 focus，并且正确展示选中值

## 复现步骤
打开弹窗，点击下拉选项，关闭弹出，然后再重新打开弹窗

**Comment by MisterLuffy** [comment]
1. 通过比较原生的 `<select>` 行为，通过 Tabs 为其聚焦时不会展开它的选项列表，所以此处 `autoFocus` 后未展开下拉框是符合预期的，如果确实需要自动展开，可以将 Select 的 `trigger` 设置为 `focus`；
2. 由于输入框聚焦后，Select 内将把原生的 `<input>` 渲染出来用于用户输入，如果 `renderFormat` 返回的值不是简单字符串，这是确实无法显示（`<input>` 无法渲染富文本）。

综上，上述问题暂不解决。
