### ISSUE TITLE
啥时候安排支持svelte

### ISSUE THREAD

**Issue by Cyaim** [arco-design/arco-design#2102]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
-

## What problem does this feature solve?
现在用svelte的开发者与公司越来越多，啥时候可以安排支持svelte呢

**Comment by PengJiyuan** [comment]
官方团队没计划支持，社区有想贡献的非常欢迎~
