### ISSUE TITLE
Modal计划支持拖动和放大缩小吗

### ISSUE THREAD

**Issue by 52flutter** [arco-design/arco-design#211]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
如题
## What problem does this feature solve?
如题

**Comment by yinkaihui** [comment]
https://arco.design/react/components/modal#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B8%B2%E6%9F%93%E5%AF%B9%E8%AF%9D%E6%A1%86 这里有拖拽的 demo 哈，一般这种可以通过第三方的库来实现。 有兴趣的话也可以封装一个通用物料 https://arco.design/material/
