### ISSUE TITLE
月份选择器在不手动指定时区参数的情况下会受到用户本地时区干扰

### ISSUE THREAD

**Issue by Fiv5** [arco-design/arco-design#2117]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.51.0
- **浏览器版本:** chrome114.0.0.0
- **复现地址:** https://arco.bytedance.net/react/components/date-picker#%E6%9C%88%E4%BB%BD%E9%80%89%E6%8B%A9%E5%99%A8

## 预期结果
选中几月就显示几月

## 复现步骤
1. 安装 chrome 插件（https://chrome.google.com/webstore/detail/change-timezone-for-googl/cejckpjfigehbeecbbfhangbknpidcnh/related?utm_source=ext_sidebar&hl=zh-CN）；
2. 通过插件随便设置一个其他时区；
3. 打开官网时间选择器，找到月份选择器，任意选中一个月份
4. 选中完回填的月份对应不上

**Comment by PengJiyuan** [comment]
暂时不好处理，需要调整内部 panel cell 值的逻辑，可能对已有业务造成影响。先挂着。
