### ISSUE TITLE
Drawer 在鼠标点击 弹框内 内容后，esc 就没办法关闭弹

### ISSUE THREAD

**Issue by higwendolyn** [arco-design/arco-design#2121]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.0
- **Browser:** chrome115.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/old-voice-5wgqzn?file=/index.js

**Comment by ChuTingzj** [comment]
点击过后貌似焦点重新回到了`body`上

![image](https://github.com/arco-design/arco-design/assets/89344405/d342a077-f195-4350-ab00-5680db3cf7ab)

**Comment by yinkaihui** [comment]
代码需回滚，导致点击 drawer 内部文本会直接聚焦到焦点元素
