### ISSUE TITLE
table 组件设置 scroll.x=max-content 在 safari 不生效

### ISSUE THREAD

**Issue by daiwawawa** [arco-design/arco-design#2124]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.1
- **Browser:** chrome115.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/distracted-tess-g26r9k?file=/demo.js

## Steps to reproduce
safari 浏览器打开 codesandbox 

## What is expected?
预期是表格有横向滚动条，像这样：
<img width="783" alt="image" src="https://github.com/arco-design/arco-design/assets/112484939/ab070ee1-cfd0-467a-9652-3356b66df628">
但是在 safari 中是这样的：
<img width="599" alt="image" src="https://github.com/arco-design/arco-design/assets/112484939/87916c9f-c007-41ff-9ede-36144014d0eb">
之前在旧版本的 chrome 中也遇到过

## 问题原因
<img width="717" alt="image" src="https://github.com/arco-design/arco-design/assets/112484939/4c7c4b1c-b5b0-475b-b022-7ddb722c44ad">

safari 浏览器的实现可能有点问题，table-layout: fixed 跟 width: max-content 有点冲突，导致没有产生横向滚动条。

**Comment by daiwawawa** [comment]
短期修复是否可以自己把 table-layout: fixed 的样式覆盖掉？会有啥影响吗

**Comment by PengJiyuan** [comment]
> 短期修复是否可以自己把 table-layout: fixed 的样式覆盖掉？会有啥影响吗

@daiwawawa 不设置 scroll.y 就没事儿
