### ISSUE TITLE
a-link不支持vue路由吗

### ISSUE THREAD

**Issue by The-Great-Ultimate** [arco-design/arco-design#2125]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What problem does this feature solve?
<a-link href="link">Link</a-link> 不支持vue路由吗，如果用<router-link to="/">Home</router-link>没有a-link的样式，如何做

## What are the similar cases of this feature
如何让<a-link href="link">Link</a-link>支持vue路由

**Comment by PengJiyuan** [comment]
麻烦去vue仓库提
