### ISSUE TITLE
select组件在火狐浏览器下搜索模式选中选项后需要点击两次才能展开下拉框

### ISSUE THREAD

**Issue by q6655443322** [arco-design/arco-design#2127]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.1
- **Framework version:** 17
- **Browser:** firefox115.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/spring-snowflake-wzmgmn?file=/demo.js

## What is expected?
正常点击一次即可展示下拉框

## Steps to reproduce
demo中有写

**Comment by MisterLuffy** [comment]
类似此 [Issue](https://github.com/arco-design/arco-design/issues/1232)。
在 `<input />` 移除 `pointer-events: none` 样式之后，方可表现正常。
<img width="823" alt="image" src="https://github.com/arco-design/arco-design/assets/29861850/18a21da6-efb3-4e26-ae1b-5eb43d478c0d">

**Comment by q6655443322** [comment]
好的，我试试看下

**Comment by KangXinzhi** [comment]
> 类似此 [Issue](https://github.com/arco-design/arco-design/issues/1232)。 在 `<input />` 移除 `pointer-events: none` 样式之后，方可表现正常。 <img alt="image" width="823" src="https://user-images.githubusercontent.com/29861850/259918687-18a21da6-efb3-4e26-ae1b-5eb43d478c0d.png">

可以直接移除 `pointer-events: none` 么，我看到是在 [Issue1626](https://github.com/arco-design/arco-design/pull/1626)添加的 `pointer-events: none` ？

**Comment by MisterLuffy** [comment]
> > 类似此 [Issue](https://github.com/arco-design/arco-design/issues/1232)。 在 `<input />` 移除 `pointer-events: none` 样式之后，方可表现正常。 <img alt="image" width="823" src="https://user-images.githubusercontent.com/29861850/259918687-18a21da6-efb3-4e26-ae1b-5eb43d478c0d.png">
> 
> 可以直接移除 `pointer-events: none` 么，我看到是在 [Issue1626](https://github.com/arco-design/arco-design/pull/1626)添加的 `pointer-events: none` ？

是的，应该可以。可以换一个方式解决
