### ISSUE TITLE
form triggerPropName

### ISSUE THREAD

**Issue by xiaolannuoyi** [arco-design/arco-design#2131]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.1
- **Framework version:** react
- **Browser:** chrome115.0.0.0
- **Reproduction Link:** https://codepen.io/xiaolannuoyi/pen/qBQwRzZ?editors=0010

## Steps to reproduce
设置表单控件的默认值时，嵌套了其他组件时，就不好使了

**Comment by ChuTingzj** [comment]
> Form.Item will pass the onChange and value properties to its direct child nodes. Only after calling this onChange, can its own value be collected by Form.Item. [link](https://arco.design/react/en-US/components/form#Custom-Form)

> Form.Item 会给自己的直接子节点（必须是唯一子节点）传递 onChange 和 value 属性，自定义控件只有在调用这个onChange 之后，自己的值才能被 Form.Item 收集到。[链接](https://arco.design/react/components/form#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E6%8E%A7%E4%BB%B6)

This problem can be achieved by `custom components` to meet your needs.

这个问题可以通过`自定义组件`以实现你的需求。

```javascript
const { useRef, useEffect, useState } = window.React;
const { Form, Switch, Space } = window.arco;
const FormItem = Form.Item;
const CustomSwitch = (props) => {
	console.log(props)
	 const checked = props.checked || false;
	 const handleChange = (newValue) => {
    	props.onChange && props.onChange(newValue);
   };
	return (
		<Space>
				<Switch defaultChecked={checked} onChange={handleChange} />
				<span>说明文字</span>
		</Space>
		)
}
function App() {
	const formRef = useRef();

	const onValuesChange = (changeValue, values) => {
		console.log("onValuesChange: ", changeValue, values);
	};

	return (
		<div style={{ maxWidth: 650 }}>
			<Form
				ref={formRef}
				autoComplete="off"
				initialValues={{
					switch1: true,
					switch2: true
				}}
				onValuesChange={onValuesChange}
			>
				<FormItem
					label="Switch1"
					field="switch1"
					triggerPropName="checked"
					rules={[{ type: "boolean", true: true }]}
				>
					<CustomSwitch />
				</FormItem>

				<FormItem
					label="Switch2"
					field="switch2"
					triggerPropName="checked"
					rules={[{ type: "boolean", true: true }]}
				>
						<Switch />
				</FormItem>
			</Form>
		</div>
	);
}
ReactDOM.render(<App />, CONTAINER);

```
