### ISSUE TITLE
文件夹上传组件在safria的兼容性问题 在选择“上传文件夹”上传文件的时候  正常应该不能选文件，但现在能选文件

### ISSUE THREAD

**Issue by s1p21** [arco-design/arco-design#2139]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.1
- **Browser:** safari 16.4 (18615.1.26.110.1)

**Comment by yinkaihui** [comment]
safari 下确实 webkitdirectory 不生效，但是允许选择单个文件似乎不影响功能？

**Comment by s1p21** [comment]
业务需要限制只允许选择文件夹，在chrome和safari的表现形式也不一样。

**Comment by yinkaihui** [comment]
组件库本身限制浏览器的表现形式感觉不是很合适，建议可以在业务里处理，把 accept 设置为随意的一个类型，然后在beforeUpload 里处理上传文件。这里有个 demo 可以参考下 https://codesandbox.io/s/arco-react-pr-template-forked-9ss4c4?file=/src/App.js
