### ISSUE TITLE
ResizeBox.Split 支持快速收缩

### ISSUE THREAD

**Issue by 52flutter** [arco-design/arco-design#215]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
like this https://demos.telerik.com/kendo-ui/splitter/index

## What problem does this feature solve?
很实用的功能，可以点击按钮快速收缩,不用拖动

**Comment by 52flutter** [comment]
现在限制panes只能2个，支持超过任意的分割也很好

**Comment by kirazxyun** [comment]
很棒的功能，我们研究一下加一个
