### ISSUE TITLE
Switch 带上 checkedTex 和 uncheckedText，在 Form.Item 里面，点击第三次就会报错

### ISSUE THREAD

**Issue by bestyxie** [arco-design/arco-design#2153]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.2
- **Browser:** chrome115.0.0.0

## Steps to reproduce
代码：
```
import '@arco-design/web-react/dist/css/arco.css';

import { Switch, Form } from '@arco-design/web-react';

const App = () => {
  return (
    <Form>
      <Form.Item triggerPropName="checked" field="openStatus">
        <Switch checkedText='ON' uncheckedText='OFF' />
      </Form.Item>
    
    </Form>
  );
};

export default App;
```

错误信息：
```
NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by yinkaihui** [comment]
https://codesandbox.io/s/wonderful-pateu-qv6tjm?file=/demo.js 没法复现诶

**Comment by ChuTingzj** [comment]
> https://codesandbox.io/s/wonderful-pateu-qv6tjm?file=/demo.js 没法复现诶

![image](https://github.com/arco-design/arco-design/assets/89344405/55d6e34d-3e9a-4fe7-9bc8-41f89de41264)
在真实的浏览器环境能够复现

**Comment by bestyxie** [comment]
> https://codesandbox.io/s/wonderful-pateu-qv6tjm?file=/demo.js 没法复现诶

可以复现啊，你这个链接里面的代码，我点两次就报错了

**Comment by MisterLuffy** [comment]
我也无法发现，请提供录屏或可复现 Demo。
