### ISSUE TITLE
Table开启复选框，尺寸非default时，头部全选框和列的选择框不对齐

### ISSUE THREAD

**Issue by 52flutter** [arco-design/arco-design#217]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** 2.25.0
- **System:** mac
- **Browser:** chrome
- **Reproduction Link:** https://arco.design/react/components/table#%E8%A1%A8%E6%A0%BC%E5%B1%9E%E6%80%A7

## What is expected?
对齐

## Steps to reproduce
开启复选框，尺寸选mini

**Comment by 52flutter** [comment]
![image](https://user-images.githubusercontent.com/11569655/143366398-aa5c90a3-9132-4982-926e-d05989992b26.png)

**Comment by PengJiyuan** [comment]
我这里看是对齐的。。你是什么浏览器啊？

**Comment by PengJiyuan** [comment]
无法复现，暂时关闭了

**Comment by 52flutter** [comment]
官网的demo 开复选框 尺寸选mini  我的浏览器是mac的chrome

**Comment by 52flutter** [comment]
不要开虚拟滚动

**Comment by PengJiyuan** [comment]
> 官网的demo 开复选框 尺寸选mini 我的浏览器是mac的chrome

我跟你看的同一个 demo，尺寸全试了也没问题

**Comment by 52flutter** [comment]
header fixed开了 必现呀  一个样式问题。。

**Comment by PengJiyuan** [comment]
header fixed 开了可以复现了
