### ISSUE TITLE
table组件在任意列开启排序后，data中带children的项的render方法中第二个参数始终是undefined

### ISSUE THREAD

**Issue by 173392531** [arco-design/arco-design#2170]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.0
- **Browser:** chrome115.0.0.0

**Comment by Ryuurock** [comment]
可以给个最小复现demo
