### ISSUE TITLE
怎样修改arco design pro的主题

### ISSUE THREAD

**Issue by DBA-family** [arco-design/arco-design#219]
官方说明如下：
step1 移除对 Arco 组件库默认样式的引用
确定移除项目中对@arco-design/web-react 组件库样式文件的引用，例如 @arco-design/web-react/dist/css/arco.css或@arco-design/web-react/dist/index.less

但在arco design pro主题中是不是将所有的@arco-design/web-react都改为自己的主题引用？

例如：将@arco-design/web-react 改为 @arco-theme/test-1

webpack配置中引入已经配置

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const { themeColor } = require('../src/settings.json');

const ArcoDesignWebpackPlugin = require('@arco-design/webpack-plugin');

exports.site = (config, env) => {
  config.context = path.resolve(__dirname, '..');
  config.entry = path.resolve(__dirname, '../src/index');
  config.output.path = path.resolve(__dirname, '../dist');

  config.plugins[0] = new HtmlWebpackPlugin({
    template: path.resolve(__dirname, '../public/index.html'),
  });
  config.plugins.push(new ForkTsCheckerWebpackPlugin());

  config.resolve.modules = ['node_modules'];

  config.plugins.push(new ArcoDesignWebpackPlugin({
    // modifyVars: {
    //   ...(themeColor ? { 'arcoblue-6': themeColor } : {})
    // }
    theme: '@arco-themes/react-xworker-xp-ai'
  }));

};

**Comment by yinkaihui** [comment]
没太理解你的意思，但在 arco pro 生成的项目里，直接全局查找 ` @arco-design/web-react/dist/css/arco.css ` 或 `@arco-design/web-react/dist/index.less`，如果有引用就直接删除就行。 看你发的 `webpack` 配置应该是没有问题的
