### ISSUE TITLE
Upload 在选择要上传的图片的时候，通过系统功能切换后缀后选择 非accept内的文件上传时，无响应 

### ISSUE THREAD

**Issue by bestlyg** [arco-design/arco-design#2196]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.0
- **Browser:** chrome116.0.0.0

## Extra info
在选择要上传的图片的时候，通过系统功能切换后缀后选择 非accept内的文件上传时，无响应
<img width="620" alt="image" src="https://github.com/arco-design/arco-design/assets/51100990/3c89183b-538c-43c1-a9c2-38aff6b1540a">

## Steps to reproduce
<Upload
        accept=".png"
        action="/"
        listType="picture-card"
        showUploadList={false}
        beforeUpload={(file) => {
          console.log(file);
        }}
      ></Upload>

**Comment by MaplePudding** [comment]
无响应是指组件卡死吗，我这边尝试复现只是无法上传，没有error

**Comment by bestlyg** [comment]
> 

不是指组件卡死。
比如说用这串代码，打开文件选择框后，利用extraInfo里的功能切换到所有文件，此时可以选择任意文件，不受到accept的限制，当我选择了一个pdf文件的时候，是允许选择的，但是确定后整个页面不会有任何响应，因为他不是accept中的文件，被Upload中的*isAcceptFile*函数拦截掉了。
