### ISSUE TITLE
Need required attribute in select and multi select dropdowns

### ISSUE THREAD

**Issue by Naveenkumar-asokan** [arco-design/arco-design#2197]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
If the required attribute is not added then we need to write addtional funtions and ref to make the select dropdown as mandatory

## What problem does this feature solve?
We can use the default form behaviour to check the mandatory fields.

**Comment by MisterLuffy** [comment]
Select dose not supports `required` attribute and we have no plan to add it. You need to cooperate with Form to validate it or just use `onChange` to check select value.
