### ISSUE TITLE
RTL模式cascader dropdown中的图标显示异常

### ISSUE THREAD

**Issue by MaplePudding** [arco-design/arco-design#2199]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.0
- **Browser:** chrome116.0.0.0
![image](https://github.com/arco-design/arco-design/assets/45707534/3f5d5c3a-edad-4206-96e1-5663f7aa67fa)

**Comment by MisterLuffy** [comment]
确实存在问题
