### ISSUE TITLE
Upload组件自定义更新进度条无效

### ISSUE THREAD

**Issue by jiawei5807** [arco-design/arco-design#2205]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.0
- **Framework version:** React 17
- **Browser:** chrome116.0.0.0

## Steps to reproduce
customRequest={(option) => {
                    const {onProgress, onError, onSuccess, file} = option;
                    let sum = 0;
                    let flag = true;
                    const interval = setInterval(() => {
                        let percent;
                        sum  = 50000
                        if (sum > 0) {
                            percent = (sum / file.size) * 100;
                        }
                        if (percent >= 100) {
                            flag = false;
                            clearInterval(interval);
                            onSuccess();
                        }
                        onProgress(parseInt(percent, 10));
                    }, 1000);
                }}

**Comment by yinkaihui** [comment]
方便给个 demo 么
