### ISSUE TITLE
文档问题：ArcoWebpack插件，没有1.5.0版本,如何解决使用开发者模式配置的样式未生效？

### ISSUE THREAD

**Issue by fire-hydrant** [arco-design/arco-design#2206]
按照[文档](https://arco.design/docs/designlab/use-theme-package)中介绍，
<img width="780" alt="image" src="https://github.com/arco-design/arco-design/assets/24520109/454860ff-84d5-4db2-80ce-4a9eee0141a6">
查阅ArcoWebpack插件，没有1.5.0版本，[npm包](https://www.npmjs.com/package/@arco-plugins/webpack-react)和[源码地址](https://github.com/arco-design/arco-plugins/blob/main/packages/plugin-webpack-react/package.json)中，最新版均为1.4.9

**Comment by yinkaihui** [comment]
直接安装 latest 版本就行，这里文档我们更新下，开源后换了包名，版本号重新开始了
