### ISSUE TITLE
Popover 的 children 如果不是 html 原生 DOM 或者不是 Button 组件的情况下，鼠标 Hover 不会弹出浮窗

### ISSUE THREAD

**Issue by 000vincent999** [arco-design/arco-design#2207]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.2
- **Browser:** chrome116.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/popup-demo-vhk9dv?file=/demo.js

**Comment by yinkaihui** [comment]
<img width="1160" alt="image" src="https://github.com/arco-design/arco-design/assets/23161413/811912a9-078b-492c-9e31-8246e193eb46">
