### ISSUE TITLE
Form.Item 的 dependencies 不生效

### ISSUE THREAD

**Issue by bestyxie** [arco-design/arco-design#2208]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.2
- **Browser:** chrome116.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/form-dependencies-demo-8ch43t?file=/demo.js

## Steps to reproduce
当 dependencies 中填写的表单变化后，依赖它的表单没有重新渲染

**Comment by yinkaihui** [comment]
使用 `shouldUpdate` 属性～ 
<img width="794" alt="image" src="https://github.com/arco-design/arco-design/assets/23161413/e160b9a4-381d-4ef2-a08e-fac4bf6b80cc">

**Comment by bestyxie** [comment]
> 使用 `shouldUpdate` 属性～ <img alt="image" width="794" src="https://user-images.githubusercontent.com/23161413/266532713-e160b9a4-381d-4ef2-a08e-fac4bf6b80cc.png">

dependencies 不能用，你们文档应该写清楚，或者就直接干掉这个属性，
shouldUpdate 用起来没有 dependencies 好用
