### ISSUE TITLE
Descriptions的data增加hidden属性

### ISSUE THREAD

**Issue by shixinxin1111** [arco-design/arco-design#2210]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
Descriptions的data增加hidden属性，当需要根据条件隐藏一些描述项时可以设置该字段为true。

**Comment by PengJiyuan** [comment]
自己filter就行，数据源自己还是自己控制吧

**Comment by shixinxin1111** [comment]
开发中还是经常会遇到这种需求，每次都filter特别麻烦，真的不能支持一下嘛[流泪]
