### ISSUE TITLE
Image 服务端渲染显示碎裂图

### ISSUE THREAD

**Issue by Jorge-7** [arco-design/arco-design#2215]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.51.2
- **框架版本:** react 18
- **浏览器版本:** chrome116.0.0.0

## 预期结果
服务端渲染时展示loading态

**Comment by yinkaihui** [comment]
复现： https://codesandbox.io/p/sandbox/reacrt-ssr-arco-6yjrd9
