### ISSUE TITLE
模态框需要使用 useModal 时可以创建普通对话框

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design#2240]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.53.1
- **Browser:** chrome117.0.0.0

## What is expected?
Modal.useModal(); 方法可以创建普通对话框，参与与对话框参数完全一致

## Steps to reproduce
模态的hooks能否加入自定义的文本信息对话框方法，不仅仅局限于confirm、 info等，普通对话框应该也需要使用 hook 加载，比如对话框的内容是异步组件这样使用 hook 写起来就很清晰

**Comment by yinkaihui** [comment]
modal.confirm({ simple: false }) 创建的其实就是一个普通模式的对话框？例如这个： https://codepen.io/yinkaihui/pen/WNLdVVy?editors=0010

静态方法和 <Modal/> 创建出的modal 区别主要是一些参数的默认值不同
