### ISSUE TITLE
Upload组件，批量上传，无法取消多个正在上传的资源，在react18版本下有问题

### ISSUE THREAD

**Issue by perfectyang** [arco-design/arco-design#2242]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.53.1
- **Framework version:** react 18.xx
- **Browser:** chrome116.0.0.0
- **Reproduction Link:** https://codepen.io/perfectyang/pen/Bavmjgq?editors=001

## Steps to reproduce
1,批量上传资源，等开始上传时，只能取消其中一个资源，其它资源无法取消
2，目测是下面这里有问题
![image](https://github.com/arco-design/arco-design/assets/8724828/e5774301-8cfe-4ccd-b8ab-2d6639c552fa)

**Comment by n0ruSh** [comment]
在特定旧版本的 chrome 浏览器复现过。在最新版的 chrome, edge 和 safari 都不能复现。应该是某些版本的浏览器 bug。先 暂时close 了，可以试试更新下浏览器版本。如果更新到最新版本依然有问题辛苦 reopen 下 ~
