### ISSUE TITLE
Tabs add params underlineSize 

### ISSUE THREAD

**Issue by SummerisYoung** [arco-design/arco-design#2245]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Look at arco-mobile's tabs params : underlineSize & underlineThick

## What problem does this feature solve?
The developer need to customize the width or height of the tabs underline.

**Comment by yuhan0709** [comment]
For Mobile issues, please go to this url https://github.com/arco-design/arco-design-mobile/issues 😊
