### ISSUE TITLE
Image 组件支持视频（或新增一个 Video 组件）

### ISSUE THREAD

**Issue by claneo** [arco-design/arco-design#2247]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Image 组件

## What problem does this feature solve?
场景：大量图片和视频的展示，点击后查看大图/视频

## Extra info
理论上查看视频应该不太需要放大缩小功能
和 video 的 loading 和懒加载相关的属性：preload/onLoadedMetadata

**Comment by yinkaihui** [comment]
https://github.com/bytedance/xgplayer 这个更专业一些？

**Comment by claneo** [comment]
主要是想实现一个小的缩略图，点击后查看大图这种交互，而不是具体视频怎么渲染

**Comment by yinkaihui** [comment]
目前支持了通过  imageRender 属性，自行渲染 img 标签。 如果只想要交互，可以利用这个属性去自行渲染预览弹出后的内容
