### ISSUE TITLE
table 组件列可以设置min-width

### ISSUE THREAD

**Issue by xiaolannuoyi** [arco-design/arco-design#2248]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
只设置width，宽度就固定死了

## What problem does this feature solve?
对应列的最小宽度，与 width 的区别是 width 是固定的，min-width 会把剩余宽度按比例分配给设置了 min-width 的列

**Comment by PengJiyuan** [comment]
可以通过 headerCellStyle 和 bodyCellStyle 设置
