### ISSUE TITLE
表单项遍历生成, 无法获取到表单项最新值

### ISSUE THREAD

**Issue by luKorea** [arco-design/arco-design#2256]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.2
- **Browser:** chrome116.0.0.0

## What is expected?
使用 form.getFields获取到表单项修改的值

## Steps to reproduce
 const [fieldList] = useState<IFormItem[]>([
    {
      field: 'username',
      type: 'input',
      suffix: <IconUser />,
      placeholder: '请输入姓名'
    },
    {
      field: 'email',
      type: 'input',
      suffix: <IconEmail />,
      placeholder: '请输入邮箱'
    },
    {
      field: 'phone',
      type: 'input',
      suffix: <IconPhone />,
      placeholder: '请输入手机号码'
    },
    {
      field: 'birthday',
      type: 'date-picker',
      placeholder: '请选择日期'
    },
    {
      field: 'gender',
      type: 'select',
      placeholder: '请选择性别',
      suffix: <IconUserGroup />,
      selectOptions: [
        {
          label: '男',
          value: 1
        },
        {
          label: '女',
          value: 2
        }
      ]
    }
  ]) 
<Form
        className="form-wrapper"
        autoComplete="off"
        form={form}
        scrollToFirstError
        {...formItemLayout}
      >
        {fieldList.map((item) => (
          <Form.Item key={item.field} field={item.field}>
            {item.type === 'input' && <Input {...item} allowClear />}
            {item.type === 'date-picker' && (
              <DatePicker style={{ width: '100%' }} {...item} allowClear />
            )}
            {item.type === 'select' && (
              <Select
                allowClear
                placeholder={item.placeholder}
                suffixIcon={item.suffix}
                options={item.selectOptions}
              ></Select>
            )}
          </Form.Item>
        ))}
      </Form>

**Comment by MisterLuffy** [comment]
请提供一个在线的 CodePen Demo。

**Comment by luKorea** [comment]
> 请提供一个在线的 CodePen Demo。

https://codepen.io/korealu/pen/QWzxWao?editors=0010

**Comment by luKorea** [comment]
https://codepen.io/korealu/pen/QWzxWao?editors=0010  复现地址

**Comment by luKorea** [comment]
> https://codepen.io/korealu/pen/QWzxWao?editors=0010 复现地址
并且表单验证会失效

**Comment by yinkaihui** [comment]
https://codepen.io/yinkaihui/pen/JjwZjZW?editors=0010 写法稍微调整下？

**Comment by luKorea** [comment]
> https://codepen.io/yinkaihui/pen/JjwZjZW?editors=0010 写法稍微调整下？

可以,  难道是我逻辑且有问题?
