### ISSUE TITLE
[VerifyCodeInput/验证码输入框] 能否增加个验证码输入框的组件？我以前提交过，但是还是非常希望属于arco的基础组件。

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#2272]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
目前社区中没有特别中意的案例或组件，可能我没找到。

## 预期解决问题
这个是我之前提出的issue：https://github.com/arco-design/arco-design/issues/941

### 其他Issues
- https://github.com/arco-design/arco-design/issues/2271
- https://github.com/arco-design/arco-design/issues/2270
- https://github.com/arco-design/arco-design/issues/2269
- https://github.com/arco-design/arco-design/issues/2268
- https://github.com/arco-design/arco-design/issues/2267
- https://github.com/arco-design/arco-design/issues/2266
- https://github.com/arco-design/arco-design/issues/2265
- https://github.com/arco-design/arco-design/issues/2264
- https://github.com/arco-design/arco-design/issues/2263

> 其他同类产品issues
https://github.com/ant-design/ant-design/issues/45429
https://github.com/Tencent/tdesign-react/issues/2314

**Comment by PengJiyuan** [comment]
这个比较适合做成物料吧？

**Comment by kwooshung** [comment]
> 这个比较适合做成物料吧？
物料？现在的物料平台，说实话我感觉真的很鸡肋，质量参差不齐。1年前，你就是这样回复我的，到现在物料平台发展的，一言难尽。

**Comment by yinkaihui** [comment]
支持，初步设计和 Input.Password 同级，Input.VerifyCode
