### ISSUE TITLE
InputNumber

### ISSUE THREAD

**Issue by MrWangWei** [arco-design/arco-design#2279]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.53.2
- **框架版本:** React 17.0.2
- **浏览器版本:** 任意浏览器

## 复现步骤
1.InputNumber 设置最大，最小边界(max, min)，
2.修改数值为最小或者最大的边界值
3.快速交换多次点击  -操作（最后一次必须是 的操作）
出现问题：比如我最小值是0. 执行3步骤后(让值在0-1之间变化)，稍等一下，大概率会出现值从1重置为0的情况

**Comment by MisterLuffy** [comment]
请提供复现 Demo 和一段复现问题的录屏，从文字描述很难理解如何去复现。
