### ISSUE TITLE
Tooltip 在 Drawer 中使用时会被遮挡

### ISSUE THREAD

**Issue by claneo** [arco-design/arco-design#2282]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.54.0
- **浏览器版本:** chrome118.0.0.0
- **复现地址:** https://codesandbox.io/s/empty-water-pgc8hm?file=/demo.js

## 额外补充
建议方案：Trigger 检测到 popupContainer 有 overflow 样式时，将位置限制在 popupContainer 内部，或修改 position 为 bottom。类似目前已有功能：Trigger 的 autoFitPosition

## 复现步骤
在 Drawer 内部最上面渲染一个 Tooltip，Tooltip 内容会被 Drawer 标题遮挡

![image](https://github.com/arco-design/arco-design/assets/11372744/a74a0c0f-f44d-4d00-bf02-62a8909bbf9a)

**Comment by PengJiyuan** [comment]
可以设置 getPopupContainer 自定义弹出容器

**Comment by claneo** [comment]
为了懒得一个个改就需要直接修改 Modal 和 Drawer 的 getChildrenPopupContainer，然后为了兼容滚动的情况还要开启 updateOnScroll，这样滚动效果没有原生滚动看着流畅

**Comment by yinkaihui** [comment]
same #2151  ～ 这里先关啦

**Comment by claneo** [comment]
但是 boundaryDistance 还是很麻烦，依旧需要每个 Drawer 包一下 ConfigProvier，还需要监听 header 和 footer 的高度
