### ISSUE TITLE
DatePicker.RangePicker 用 tab 键切换开始日期和结束日期时，聚焦状态错误

### ISSUE THREAD

**Issue by promise96319** [arco-design/arco-design#2288]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.54.0
- **Browser:** chrome117.0.0.0

## Steps to reproduce
聚焦开始日期，然后 tab 键切换到结束日期，发现光标聚焦在结束日期，但是高亮显示在开始日期。

并且此时输入日期时，无法正常输入。

![image](https://github.com/arco-design/arco-design/assets/38751863/1ba4fcbd-b4b2-4804-8e17-3f31c3032fc0)

**Comment by PengJiyuan** [comment]
下个版本修复
