### ISSUE TITLE
Trigger 组件注册的document mousedown 事件是发生在事件冒泡阶段的，会导致点击页面其他元素（阻止冒泡的元素）时无法 触发select 下拉框的隐藏

### ISSUE THREAD

**Issue by FunctionRun** [arco-design/arco-design#2290]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.54.1
- **Browser:** chrome117.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/fancy-shadow-rqxvww?file=/index.js

## What is expected?
点击菜单1的时候，Select框可以隐藏

## Steps to reproduce
1. 打开https://codesandbox.io/s/fancy-shadow-rqxvww?file=/index.js，菜单1的父元素注册以下事件
```js
document.body.querySelector("#dom-menu").addEventListener(
  "mousedown",
  (event) => {
    event?.stopPropagation();
  },
  true
);
```
2. 点击Select 框打开下拉弹窗
3. 点击菜单1，Select的下拉不会隐藏，同理只要是组件内部使用了Trigger 做弹窗的，都不会自动隐藏

![image](https://github.com/arco-design/arco-design/assets/6956557/12910983-16a9-4a79-bf43-7401c99793f0)

**Comment by yinkaihui** [comment]
支持配置下 clickoutside 的事件触发阶段是 冒泡还是捕获
