### ISSUE TITLE
input/textarea 字数统计支持自定义计数规则

### ISSUE THREAD

**Issue by rpig** [arco-design/arco-design#2292]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
textarea字数统计支持中文2字符计算统计，不是算字符串长度，可以提供个开关或者函数开启

## What problem does this feature solve?
textarea字数统计支持中文2字符计算统计，不是算字符串长度，可以提供个开关或者函数开启

**Comment by MisterLuffy** [comment]
输入框文本长度由 <input /> 原生 `maxLength` 属性控制，更改这种行为需要覆盖 `value` 的 `String.prototype.length` 和 `String.prototype.slice`，成本较大，并且与浏览器原生标准不一致。故不在组件内部支持，如果确实有这种特殊需求，建议直接对其进行受控。
