### ISSUE TITLE
pageShowDate.locale is not a function

### ISSUE THREAD

**Issue by vaynevayne** [arco-design/arco-design#2293]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.54.1
- **Browser:** chrome118.0.0.0

**Comment by PengJiyuan** [comment]
Codesandbox 复现链接麻烦发一下

**Comment by vaynevayne** [comment]
https://github.com/arco-design/arco-design/blob/238efbc4c0078fc93436ee589161e8deba7e4fdb/components/DatePicker/panels/date/index.tsx#L104

<img width="605" alt="image" src="https://github.com/arco-design/arco-design/assets/124666577/bb506f13-b60d-4a99-bdc2-c82001c685eb">


老了, 看不懂哪里来的 props

**Comment by PengJiyuan** [comment]
都是上层传下来的，picker 或 picker-range

**Comment by vaynevayne** [comment]
我直接使用的 <DatePicker />, 我没传递这个 props

你说的上层 我理解不了你的意思

**Comment by PengJiyuan** [comment]
首先你得给复现的链接，不然这么没办法帮你看问题出在哪儿

**Comment by vaynevayne** [comment]
DatePicker 一用就报错了

**Comment by yinkaihui** [comment]
> DatePicker 一用就报错了

可以把用法发一下哈
