### ISSUE TITLE
Table scroll.x=max-content 和 scroll.y=true 会导致列宽不是自适应的宽度

### ISSUE THREAD

**Issue by brahmachen** [arco-design/arco-design#2306]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.54.2
- **Browser:** chrome118.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/fervent-dijkstra-65j9n2?file=/demo.js
<img width="666" alt="image" src="https://github.com/arco-design/arco-design/assets/12797533/b40fb4e6-36a5-4685-aa55-19ec554a7c37">

之前的 [issues](https://github.com/arco-design/arco-design/issues/2280) 已经关闭了，特此重开一个

**Comment by lrenc** [comment]
列宽根据内容自适应，你的内容是空的，如果这是实际生产环境中会出现的场景，建议给需要加宽的column指定width。

**Comment by brahmachen** [comment]
<img width="1293" alt="image" src="https://github.com/arco-design/arco-design/assets/12797533/fc47649f-7468-48da-87c5-6d5f43e6ecef">
@lrenc 但是为啥不设置 scroll.y 的时候列宽也根据title自适应呢，实际场景中确实用到了，比如一些内容很长的列在没数据的时候希望能尽量少的占用空间

**Comment by lrenc** [comment]
@brahmachen 加上scroll.y 之后，表头需要是固定的，在实现上会把表头和内容分成两个table实现，你可以点开element看一下，这和没有scroll.y 完全是两种情况。

**Comment by brahmachen** [comment]
@lrenc 确实是两个table实现的，但是既然body可以把header的宽度撑起来，为什么反过来就不行呢？现在这样在无数据的时候表头的渲染都乱了

**Comment by lrenc** [comment]
互相比较赋值对性能不是很友好，也可能会导致别的问题，暂时不考虑优化了，对于上图数据为空的情况，我们再优化一下
