### ISSUE TITLE
希望锚点组件可以支持折叠，类似飞书文档左侧目录

### ISSUE THREAD

**Issue by NieZhuZhu** [arco-design/arco-design#2307]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
类似飞书文档左侧目录场景需求

## What problem does this feature solve?
RT

**Comment by yinkaihui** [comment]
类似官网右侧的锚点目录一样，自行嵌套在可折叠的容器中即可
