### ISSUE TITLE
List 组件滚动场景偶现报错 Cannot read properties of null (reading 'scrollTop')

### ISSUE THREAD

**Issue by haiyun549** [arco-design/arco-design#2313]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.52.2
- **Framework version:** "react": "^18.2.0"
- **Browser:** chrome116.0.0.0

**Comment by yinkaihui** [comment]
https://github.com/arco-design/arco-design/blob/main/components/List/index.tsx#L149
判空 refScrollElement.current 即可
