### ISSUE TITLE
自定义表格筛选图标位置

### ISSUE THREAD

**Issue by lmyleo** [arco-design/arco-design#2314]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

目前表格的筛选图标位置在每一列的最右边，如果列宽度过长的话，筛选图标会距离列标题过远，希望可以自定义筛选图标的位置。
eg.
<img width="1648" alt="image" src="https://github.com/arco-design/arco-design/assets/56340530/3e5a8438-2a54-40e6-90b2-50d7ce315f8f">

**Comment by sHow8e** [comment]
@lmyleo 可以通过修改样式来达到你的目的。比如把icon的父级定位改为static。
