### ISSUE TITLE
锚点现在不支持不同页面之间跳转吗

### ISSUE THREAD

**Issue by HQ-YYK** [arco-design/arco-design#2329]
我再A页面设置了需要跳转的锚点，然后报错，加上了scrollContainer也还是报错
`<Anchor affix={false} lineless hash={false} scrollContainer={document.getElementById('about')}>
                    <span className='font-bold text-lg'>{item.title}</span>
                    {item.blockList.map((block, i) => (
                      <Link
                        key={i}
                        className='text-[#808080] mt-[4px] block hover:text-slate-300'
                        href={`/about#${block.id}`}
                        title={block.title}
                      ></Link>
                    ))}
                  </Anchor>`
                   
  `      blockList: [
      {
        title: '企业简介',
        id: 'about1'
      },
      {
        title: '发展历程',
        id: 'about2',
      },
      {
        title: '资质荣誉',
        id: 'about3'
      },
      {
        title: '客户伙伴',
        id: 'about4'
      },
    ]`

**Comment by PengJiyuan** [comment]
不同页面是啥意思，锚点不是在页面内的滚动吗？

**Comment by HQ-YYK** [comment]
不同组件直接跳转
