### ISSUE TITLE
【Feature】【Table】 表头的排序和筛选Icon支持禁用状态，并可以设置tooltip

### ISSUE THREAD

**Issue by kongyufei5039** [arco-design/arco-design#2339]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
其他组件库暂无调研

## What problem does this feature solve?
解决一些场景下需要对排序和筛选操作禁用

**Comment by PengJiyuan** [comment]
暂时没有支持的计划
