### ISSUE TITLE
table组件开启虚拟滚动后，横向滚动样式问题

### ISSUE THREAD

**Issue by ada271828** [arco-design/arco-design#2342]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.55.1
- **Browser:** chrome118.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/crazy-lumiere-l6xws3?file=/demo.tsx

## Steps to reproduce
表格往左滚动一段距离，第一列会有问题

**Comment by lrenc** [comment]
看了一下，已经好了
