### ISSUE TITLE
Table 特定情况下自动使用的 col key 重复

### ISSUE THREAD

**Issue by claneo** [arco-design/arco-design#2349]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.55.1
- **浏览器版本:** chrome118.0.0.0
- **复现地址:** https://codesandbox.io/s/mystifying-marco-rzq3m6?file=/demo.tsx

## 复现步骤
1. 开启 rowSelection 选择功能
1. 前两列均无 key 或 dataIndex

控制台显示有重复 key '1'

![image](https://github.com/arco-design/arco-design/assets/11372744/7fbe1bd4-f870-4adc-87f0-dc69d223d65d)

原因：

此处使用了 || 运算符，当 col.key 为 0 时，导致取到的 key 为 index 即 1，从而和后一列的 key 重复
https://github.com/arco-design/arco-design/blob/5a65e07fd5db8f5ddba152475bb7ba5d93a87081/components/Table/colgroup.tsx#L74

**Comment by lrenc** [comment]
在使用Table时，建议在columns加上dataIndex或key属性，防止可能会出现的一些问题
