### ISSUE TITLE
Cascader showSearch.renderOption 不会自动渲染 checkbox

### ISSUE THREAD

**Issue by kyon45** [arco-design/arco-design#2350]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.55.1
- **浏览器版本:** chrome118.0.0.0
- **复现地址:** https://codesandbox.io/s/relaxed-neco-vvgrmp?file=/demo.js

## 复现步骤
在输入框中输入字母 "d"，预期出现三个选项。
- 如果传入 showSearch=true，则会有默认的 checkbox 出现，点击与取消点击，checked 状态更新正常
- 如果传入自定义 showSearch.renderOption，则需要用户自行渲染 Checkbox，点击与取消点击无法同步 checked 状态
  
![img_v2_f3cfda2b-4d99-4ab0-b947-58c5c3c5771g](https://github.com/arco-design/arco-design/assets/34005194/05d82cca-ebd4-4e73-9828-976398ef2b07)

## 预期结果
传入自定义 showSearch.renderOption，能够渲染 Checkbox，点击与取消点击能够同步 checked 状态

## 额外补充
- 预期方案 1：传入自定义 showSearch.renderOption，通过传入额外的 showSearch.renderChecbox=true 属性，自动渲染 checkbox
- 预期方案 2：传入自定义 showSearch.renderOption，增加第三个参数 item，能够让用户自行渲染 Checkbox

**Comment by yinkaihui** [comment]
> 预期方案 2：传入自定义 showSearch.renderOption，增加第三个参数 item，能够让用户自行渲染 Checkbox
