### ISSUE TITLE
TreeSelect组件样式问题

### ISSUE THREAD

**Issue by qianchengjie** [arco-design/arco-design#2361]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.55.2
- **浏览器版本:** chrome119.0.0.0
- **复现地址:** https://codesandbox.io/s/fdi8gz?file=/demo.js

## 预期结果
组件高度不变，实际上会有高度跳动

## 复现步骤
多选选中后取消选中

**Comment by jiahao-c** [comment]
这个复现地址有问题喔 @qianchengjie

**Comment by qianchengjie** [comment]
@jiahao-c 修改了

**Comment by jiahao-c** [comment]
@qianchengjie 试了下，没发现高度跳动哇...能录个GIF或者视频吗

**Comment by qianchengjie** [comment]
奇怪，之前试了下例子是不行的，现在codesandbox的例子没问题，但是官网的demo有这个问题
https://github.com/arco-design/arco-design/assets/27612520/269ef417-3f9c-43f5-996f-db95c306b6e9

**Comment by qianchengjie** [comment]
@jiahao-c 我清了下浏览器缓存，没问题了，这个issue先关了
