### ISSUE TITLE
Steps组件设置为vertical时，自定义icon会出现偏移

### ISSUE THREAD

**Issue by Rangocold** [arco-design/arco-design#2367]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.55.2
- **框架版本:** 17.0.2
- **浏览器版本:** chrome119.0.0.0
- **复现地址:** https://codesandbox.io/s/misty-mountain-s3gzzr?file=/demo.js:1638-1648steps

## 预期结果
icon正确展示在step旁边

## 复现步骤
打开demo就可以看到，自定义icon的位置错误

**Comment by MisterLuffy** [comment]
https://codesandbox.io/s/magical-wave-nd435s?file=/demo.js

`customDot` 的作用主要是为节点添加父容器（例如 Tooltip），如果完全自定义此节点会因为类名确实而导致样式丢失。可以参考上述 Demo 为自定义的节点添加 `arco-steps-item-icon` 的类名，并且覆盖部分样式。
