### ISSUE TITLE
Modal弹窗拖出窗外问题

### ISSUE THREAD

**Issue by zhixiaotong** [arco-design/arco-design#2371]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.56.0
- **Browser:** chrome119.0.0.0
- **Reproduction Link:** https://arco.design/react/components/modal#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B8%B2%E6%9F%93%E5%AF%B9%E8%AF%9D%E6%A1%86

## Extra info
未统一，建议拖出窗外可作为配置项。两边应该保持一致

## What is expected?
统一拖动逻辑

## Steps to reproduce
react和vue版本的弹窗拖动逻辑不同，前者可拖出窗外，后者不行。同一个官方维护的产品，为什么没有统一规范呢？

**Comment by yinkaihui** [comment]
react 的 demo 可以看下详细代码，是借助的第三方拖拽库 + modal 的 modalRender API 实现的，不是组件本身的能力。

**Comment by zhixiaotong** [comment]
> react 的 demo 可以看下详细代码，是借助的第三方拖拽库 + modal 的 modalRender API 实现的，不是组件本身的能力。

这是实现的问题嘛，我的意思是，在产品的前提上，两个框架的UI展现应该一致会好点，对用户来说，使用是一样的，这是我的想法哈。
