### ISSUE TITLE
Descriptions 组件某一列内容过长时，不能完整显示，直接截断了。

### ISSUE THREAD

**Issue by korgong** [arco-design/arco-design#2372]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.54.2
- **Browser:** 119.0.6045.159
- **Reproduction Link:** https://codepen.io/HappyDays/pen/NWoyYpj?editors=001

## What is expected?
1 屏幕尺寸小的时候也能正常显示，对比了antd，他们目前的兼容是更好的。
2 如果实在过小，一行显示3列可以变为2列，只要正常显示就能接受。
3 如果需要设置最小兼容宽度，也能接受。
4 能滚动显示内容也能接受，不能直接截断了。

## Steps to reproduce
1 这一列（Residence）的内容特别长。
2 把屏幕缩小到620px宽，会发现这一列的文字不能换行截断了。
3如果把屏幕宽度缩小到520px，这一列的标题也会看不到
4 不能通过滚动显示，直接截断了。

**Comment by lrenc** [comment]
<Descriptions border data={data} style={{ width: 'fit-content' }} />
指定一下宽度试试

**Comment by lrenc** [comment]
@korgong 你先覆盖一下，这块不能保证其他场景下这么写会不会有问题，arco这边暂时还不能直接修改。
