### ISSUE TITLE
Upload 组件，可以增加一个 `beforeLoad` 事件？ 支持修改 file url

### ISSUE THREAD

**Issue by chenzn1** [arco-design/arco-design#2382]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
proxy file url

## What problem does this feature solve?
因为有些文件不能直接访问，要代理才可以

**Comment by n0ruSh** [comment]
建议通过代理工具 (e.g. charles) 处理
