### ISSUE TITLE
建议select 组件在多选模式下添加全选功能

### ISSUE THREAD

**Issue by Bmongo** [arco-design/arco-design#2386]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
当筛选后的数据量多项时，需要手动点击若干选项，建议新增全选功能，以及筛选后全选

## What problem does this feature solve?
当筛选后的数据量多项时，需要手动点击若干选项，建议新增全选功能，以及筛选后全选

**Comment by MisterLuffy** [comment]
此功能较为鸡肋，并且自行开发难度不大，请自行拓展 Select 实现，可参考 [此物料](https://arco.design/material/detail?name=@arco-materials/select-with-check-all/SelectWithCheckAll)。
