### ISSUE TITLE
Cascader组件单选的时候placeholder显示异常

### ISSUE THREAD

**Issue by zhongchunfengyyds** [arco-design/arco-design#2389]
<img width="1883" alt="image" src="https://github.com/arco-design/arco-design/assets/49225795/c86dac9d-6662-4663-b6bb-ef92740b347f">
<img width="1089" alt="image" src="https://github.com/arco-design/arco-design/assets/49225795/9ff3c896-e2ee-4b7b-8557-1209b3cebd8d">

**Comment by yinkaihui** [comment]
单选时设置value 为 undefined 表示没有值，会显示 placeholder
