### ISSUE TITLE
Typography.Text配置ellipsis失效

### ISSUE THREAD

**Issue by KoitoTouko** [arco-design/arco-design#2390]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.56.1
- **Browser:** chrome119.0.0.0

**Comment by flsion** [comment]
@KoitoTouko 麻烦提供一下具体的复现codesandbox~
