### ISSUE TITLE
Select 多选模式，Deselect 最后一个元素会有很明显的抖动

### ISSUE THREAD

**Issue by UGAROY** [arco-design/arco-design#2395]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.56.1
- **Browser:** chrome119.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/c022pt?file=/demo.js

## What is expected?
页面保持位置，不会有大抖动

## Steps to reproduce
1. 选择一个元素
2. 移除元素

https://github.com/arco-design/arco-design/assets/475069/f978dae6-e30f-409b-b482-fe93b06a7e8a

**Comment by MisterLuffy** [comment]
主要是由 Tag 消失时的动画引起的抖动，没有太好的解决办法，可以通过 `animation: false` 关闭动画来避免多选抖动。
