### ISSUE TITLE
Typography.Text的copyable能否关闭hover效果

### ISSUE THREAD

**Issue by xxqyw** [arco-design/arco-design#2402]
开启copyable后，hover复制icon会有tooltip，能否开放控制是否展示这个tooltip

**Comment by xxqyw** [comment]
开启copyable后，hover复制icon会有tooltip，能否开放控制是否展示这个tooltip

**Comment by yinkaihui** [comment]
copyable={{tooltips: []}} 试试？

**Comment by xxqyw** [comment]
> copyable={{tooltips: []}} 试试？

@yinkaihui 之前有试过，但是tooltips的类型是[ReactNode, ReactNode]，传空数组的话能运行且没有hover，但是类型会报错，并且担心后续会不会不允许这样使用

**Comment by yinkaihui** [comment]
是不是可以新增个 tooltipProps?: [TooltipProps, TooltipProps] ?
