### ISSUE TITLE
能否修改tooltip的z-index

### ISSUE THREAD

**Issue by xxqyw** [arco-design/arco-design#2403]
目前message的z-index是1003，tooltip的是1000，那么如果message中的元素有tooltip的话那么tooltip会被message遮挡

**Comment by flsion** [comment]
@xxqyw z-index 是内容控制的，会根据出现的先后顺序递增，可以提供一下具体问题的复现 codesandbox 吗？

**Comment by xxqyw** [comment]
> @xxqyw z-index 是内部控制的，会根据出现的先后顺序递增，可以提供一下具体问题的复现 codesandbox 吗？

@flsion https://codesandbox.io/p/sandbox/stoic-snyder-lndz8s?file=%2Fdemo.js%3A10%2C21

**Comment by flsion** [comment]
@xxqyw 这个是 meesage 组件脱离原本 React Context 所导致的问题，新版本增加了 Tooltip 的配置项，可以自定义下 style 来处理这个问题
