### ISSUE TITLE
DatePicker position的ts定义只有6个方向，希望支持所有12个方向

### ISSUE THREAD

**Issue by zheng-fan** [arco-design/arco-design#2415]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
无

## 预期解决问题
当前ts定义的方向只有'top' | 'tl' | 'tr' | 'bottom' | 'bl' | 'br'，但实际把12个方向传进去也是符合预期的，只是ts会报错，希望可以支持所有12个方向

**Comment by PengJiyuan** [comment]
设计上是只支持 6 个方向的，什么场景需要左边或者右边显示啊。实在想定制就用 triggerProps 吧
