### ISSUE TITLE
form.clearFields和form.setFieldValue方法都不能清空表单中的checkbox的选中状态

### ISSUE THREAD

**Issue by Freewayy** [arco-design/arco-design#2434]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.57.0
- **Framework version:** https://unpkg.com/react@16.x/umd/react.development.js
- **Browser:** Microsoft Edge 120.0.2210.61 (正式版本) (arm64)
- **Reproduction Link:** https://codepen.io/freewayy/pen/ExrzJBq#

## What is expected?
用上述api能将表单中选中状态的checkbox取消掉

## Steps to reproduce
1. form中的formItem已经设置了field属性的checkbox组件被选中
2. 使用form.clearFields和form.setFieldValue等方式都不能将checbox组件的选中状态取消

**Comment by nativejie** [comment]
`<FormItem triggerPropName="checked" wrapperCol={{ offset: 5 }} field='checkbox'>`增加`triggerPropName="checked"`属性试试

**Comment by Freewayy** [comment]
> `<FormItem triggerPropName="checked" wrapperCol={{ offset: 5 }} field='checkbox'>`增加`triggerPropName="checked"`属性试试

可以了，非常感谢
