### ISSUE TITLE
Typography组件的ellipsis在Grid布局下会失效

### ISSUE THREAD

**Issue by nativejie** [arco-design/arco-design#2443]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.57.1
- **框架版本:** React 17
- **浏览器版本:** chrome120.0.0.0
- **复现地址:** https://codesandbox.io/p/sandbox/cocky-meadow-3d3nxt?file=%2Fpackage.json%3A3%2C15-3%2C17

## 额外补充
可能得原因：
使用`Grid`布局短时间内多次触发`resize`事件，在`Typography`的`base.tsx`里的`140`行中 `diffTime`没有满足 `> 100`，我在源代码中调试的时候看到在`Grid`布局的情况下`diffTime`的间隔都是小于`100`的。
```javascript
if (resizeStatus.includes(measureStatus) && diffTime > 100) {
        resizeTime.current = currentTime;
        setWidth(currentWidth);
}
```

## 预期结果
应该省略至2行并且有展开按钮

## 复现步骤
打开`codesanbox`链接可以看到，我设置了`ellipsis={{ rows: 2, expandable: true }}`但并未省略，但如果在`Grid`前面在加一个其他的元素包裹的`Typography`，例如`div`包裹的`Typography`后面的`Grid`包裹的元素就会正常展示，在`codesandbox`里我有注明。

**Comment by flsion** [comment]
@nativejie 组合使用情况下建议使用 cssEllipsis: true，默认方式兼容性存在问题

**Comment by nativejie** [comment]
> 我在提供的`codesanbox`里加上了`cssEllipsis`属性，还是没有折叠
![image](https://github.com/arco-design/arco-design/assets/31497228/10499938-b6fb-4d23-a861-d64dfb8bca19)

**Comment by yinkaihui** [comment]
建议使用 Typography.Ellipsis 组件替代
