### ISSUE TITLE
validateMessages都支持那些模板变量，如何使用Form.Item的label占位?

### ISSUE THREAD

**Issue by howiekang** [arco-design/arco-design#2450]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
如题

## What problem does this feature solve?
如题

**Comment by nowui** [comment]
好像有validateMessages这个参数重写，
我也想问有没有简单的配置

**Comment by yinkaihui** [comment]
想要全局配置的话，在 configProvider 上直接通过 componentConfig 配置 Form 的 validateMessages 即可。
想要使用 label 占位的话，参考这样的写法就行：
<img width="521" alt="image" src="https://github.com/arco-design/arco-design/assets/23161413/511b7883-517f-4724-ab81-62044ad7a51f">

**Comment by howiekang** [comment]
好的，谢谢你。文档可以更新一下，validateMessages的参数一长串不太清晰。还有个事是要跟你说一下。
下个大版本中RulesProps的validator能不能加个参数，把当前表单域全部字段值都带上？这样应该会更灵活。
@yinkaihui

**Comment by nowui** [comment]
![image](https://github.com/arco-design/arco-design/assets/3635163/d232b6a8-e9b7-4233-9427-17d88f188269)
我想问一下：默认情况下显示label不是会更好么？“name 是必填项”变成“用户名是必填项”
这样国际化支持也比较好

**Comment by yinkaihui** [comment]
> ![image](https://private-user-images.githubusercontent.com/3635163/292845786-d232b6a8-e9b7-4233-9427-17d88f188269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTAwNTEsIm5iZiI6MTcwMzc0OTc1MSwicGF0aCI6Ii8zNjM1MTYzLzI5Mjg0NTc4Ni1kMjMyYjZhOC1lOWI3LTQyMzMtOTQyNy0xN2Q4OGYxODgyNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDc0OTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZjNjdiOWI5MmEzMWU0NzNlNWUwNTY3N2YyYzcwNTAxNzgwNDAxZDA0YmE4OWE3NTg5MzA1NmU4NzNkZDZjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wbvholOBZFSsF84lft30ofoOGzHxPtvTZNYbOjEu6xc) 我想问一下：默认情况下显示label不是会更好么？“name 是必填项”变成“用户名是必填项” 这样国际化支持也比较好 其实最终用户不需要知道field名称的

1. label 可能是比较复杂的 reactnode， 默认回显在校验信息中可能并不合适。
2. validateMessages 是后续新增的功能，不默认显示 label 也是为了和之前版本的行为保持基本一致，不对以前的用法产生影响
