### ISSUE TITLE
Select 组件开启  mode="multiple"，当选中后，取消所有选中时，输入框高度会跳变

### ISSUE THREAD

**Issue by foreverzmy** [arco-design/arco-design#2451]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.57.2
- **Browser:** chrome120.0.0.0
- **Reproduction Link:** https://arco.design/react/components/select

## Steps to reproduce
1. 打开官网 Select 组件 https://arco.design/react/components/select
2. 下滑到`多选模式`
3. 将第一个 Select 的多选的tag全部取消选择
4. 输入框的高度会跳变

![ttt](https://github.com/arco-design/arco-design/assets/11779129/a0eec020-f66d-47ef-a649-ad2cf1b236df)

**Comment by jiahao-c** [comment]
研究了下，问题应该是出在 `input-element.tsx` 里面。

确认步骤：
首先我发现， 2.53.2（以及之前）版本没有这个问题，而2.54.0（以及之后）版本存在这个问题。

- 复现链接(2.54.0): https://codesandbox.io/p/sandbox/eloquent-orla-kqgc7g
- “不复现”链接(2.53.2):  https://codesandbox.io/p/sandbox/black-microservice-j3tfqg

然后经过尝试，用 [2.53.2 版本的 input-element.tsx](https://github.com/arco-design/arco-design/blob/2.53.2/components/Input/input-element.tsx) 替换最新的 main 里面的 `input-element.tsx`，就不存在这个问题。

不过我没搞出来具体咋样能修好 😢  
蹲个PR，学习学习 🙏

**Comment by FEliuyg** [comment]
真正产生这个bug的原因是 [这段代码](https://github.com/arco-design/arco-design/blob/main/components/InputTag/input-tag.tsx#L352C20-L352C20)

```tsx
   minWidth: value.length ? undefined : '100%',
```
前提是开启了标签变化的动画，这个值默认为 `true` 的，如果你不需要标签变化的动画的话，那么你把 `animation` 设置为 `false`，就不会可以避免这个bug存在了。

这个问题产生的根本原因是标签变化有动画(animation，默认值为true)，标签消失动画的过程中，标签还占位，但是如果值为空的话，`minWidth` 设置为 `100%` 是没有动画过程的，会在下个渲染中立即生效，也就是说，刚清除最后一个的时候，是标签在消失的过程中 + 隐藏光标的 minWidth 为 100%，所以出现了两行的高度。直到标签消失的动画结束后，高度才恢复为正常一行的高度。

修复这个bug，要么不设置为 '100%'(不知道设置100%的目的是为了啥，感觉没什么用），要么就延时设置minWidth为100%

**Comment by jiahao-c** [comment]
@FEliuyg 谢谢，学习了

**Comment by jiahao-c** [comment]
@FEliuyg 谢谢解答！我在PR里留评论啦～
