### ISSUE TITLE
在Table中使用Typography.Text 中的 ellipsis ，报错：ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by Euphoria9702** [arco-design/arco-design#2452]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.2
- **Framework version:** React
- **Browser:** chrome120.0.6099.130

## Steps to reproduce
table组件columns中的代码 ：
```
 {
      dataIndex: 'pack_url',
      title: '下载链接',
      width: 260,
      render: (pack_url) =>
        pack_url ? (
          <Typography.Text
            copyable
            ellipsis={{ rows: 2, showTooltip: true }}
            style={{ marginBottom: 0 }}
          >
            {pack_url}
          </Typography.Text>
        ) : (
          '-'
        ),
    },
```

**Comment by jiahao-c** [comment]
hmm 楼上没提供复现地址，我贴一个：https://codesandbox.io/p/sandbox/headless-dream-5l94wy

<img width="573" alt="image" src="https://github.com/arco-design/arco-design/assets/8275280/5f75ab17-6576-461b-9363-4df1b980c8b1">

**Comment by flsion** [comment]
@Euphoria9702 Typography 组件不适合放在 Table 中使用，针对这种场景，我们在讨论下处理方法~

**Comment by yinkaihui** [comment]
建议使用 `Typography.Ellipsis` 组件（version 2.60.0）替代原本的 `ellipsis` 属性。
