### ISSUE TITLE
Select组件单选在选中后会触发onSearch

### ISSUE THREAD

**Issue by hahaturbo** [arco-design/arco-design#246]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** The latest
- **System:** Mac
- **Browser:** Chrome
- **Reproduction Link:** https://codesandbox.io/embed/thirsty-thunder-6hves?fontsize=14&hidenavigation=1&theme=dark

## What is expected?
单选的选项在选中之后应该不会重新触发onSearch，逻辑应该和多选保持一致。

## Steps to reproduce
正常输入搜索，查看console的输出，切换Select组件的mode，对比多选和单选的结果

**Comment by MisterLuffy** [comment]
你好。

此处的 `onSearch` 是由下拉列表隐藏时文本内容自动清空引起的，多选如果在存在输入内容时隐藏下拉列表同样会有 `onSearch` 触发。由于存在自动清空搜索文本的情况，所以 `onSearch` 的第二个回调参数提供了触发此回调的具体原因，包括 `'manual' | 'optionChecked'  | 'optionListHide'  | 'tokenSeparator'`。

[相关逻辑](https://github.com/arco-design/arco-design/blob/main/components/Select/select.tsx#L265)

**Comment by hahaturbo** [comment]
> 你好。
> 
> 此处的 是由下拉列表隐藏时文本内容自动清空引起的，多选如果在存在输入内容时隐藏下拉列表同样会有 触发。由于存在自动清空搜索文本的情况，所以 的第二个回调参数提供了触发此回调的具体原因，包括 。`onSearch``onSearch``onSearch``'manual' | 'optionChecked' | 'optionListHide' | 'tokenSeparator'`
> 
> [相关逻辑](https://github.com/arco-design/arco-design/blob/main/components/Select/select.tsx#L265)

好的，如果可以的话，希望能在文档中添加对第二个参数InputValueChangeReason的简短说明，可能会减少一些疑惑，未来不打算支持，可以关闭这个issues了，感谢！

**Comment by MisterLuffy** [comment]
> > 你好。
> > 此处的 是由下拉列表隐藏时文本内容自动清空引起的，多选如果在存在输入内容时隐藏下拉列表同样会有 触发。由于存在自动清空搜索文本的情况，所以 的第二个回调参数提供了触发此回调的具体原因，包括 。`` onSearch``onSearch``onSearch``'manual' | 'optionChecked' | 'optionListHide' | 'tokenSeparator' ``
> > [相关逻辑](https://github.com/arco-design/arco-design/blob/main/components/Select/select.tsx#L265)
> 
> 好的，如果可以的话，希望能在文档中添加对第二个参数InputValueChangeReason的简短说明，可能会减少一些疑惑，未来不打算支持，可以关闭这个issues了，感谢！

好的，我们补充一下文档。这个函数的触发时机暂时就不改了。
