### ISSUE TITLE
DatePicker.QuarterPicker 受控模式值不更新

### ISSUE THREAD

**Issue by charlzyx** [arco-design/arco-design#2466]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.58.0
- **Browser:** chrome121.0.0.0
- **Reproduction Link:** https://codesandbox.io/p/sandbox/arco-space-fragment-forked-z636vn

## Extra info
似乎是dayjs的问题 https://github.com/iamkun/dayjs/issues/2477

## Steps to reproduce
非受控模式下正常选择季度值, 受控模式下值不更新

https://github.com/arco-design/arco-design/assets/18055018/71af2eb5-bc0d-4b54-8903-fa7c94b8d0dc

**Comment by PengJiyuan** [comment]
受控的时候改一下写法
```
onChange={(v, dv) => {
   setValue(dv);
}}
```
