### ISSUE TITLE
【Typography】cssEllipsis=true, showTooltip invalid

### ISSUE THREAD

**Issue by lqxu** [arco-design/arco-design#248]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react: 2.25.1
- **System:** Mac
- **Browser:** Chrome
- **Reproduction Link:** https://codesandbox.io/s/fervent-herschel-p19u0?file=/index.js

## What is expected?
showTooltip API  is not depend on "cssEllipsis=false"

## Steps to reproduce
1. use @arco-design/web-react: 2.25.1
2. use Typography.Text
            <Typography.Text
              style={{ width: 100 }}
              ellipsis={{
                showTooltip: true,
              }}
            >
              some text, some text, some text
            </Typography.Text>
3. tooltip can't display, when i hover it

**Comment by yuhan0709** [comment]
暂时复现不出来，我想想办法🤔️

**Comment by yuhan0709** [comment]
![fb57d220-e717-4df2-a912-13698e02f9bg](https://user-images.githubusercontent.com/23137528/144416504-5d023e7a-8d52-4999-bfbb-335e9a8e7515.png)

**Comment by lqxu** [comment]
> 暂时复现不出来，我想想办法🤔️

我提供的链接里，可以直接复现的。sandbox 的链接，看第一个使用方式。

**Comment by yuhan0709** [comment]
在我和我小伙伴的电脑上真的复现不出来 麻烦提供下浏览器版本、系统版本

**Comment by lqxu** [comment]
> 在我和我小伙伴的电脑上真的复现不出来 麻烦提供下浏览器版本、系统版本

难道和浏览器版本有关？我用的是 chrome 96.0.4664.55，刚试了下 safari 也不可以。我附个截图说明
![demo](https://user-images.githubusercontent.com/26473841/144541912-d1e8b768-6691-442f-83f3-eb8ccccddc74.gif)

**Comment by yuhan0709** [comment]
https://codesandbox.io/s/winter-cherry-lbiyc?file=/index.js  你看看第三行你能打开 tooltip 吗。这个我们电脑上确实复现不了等我先定位下问题

**Comment by yuhan0709** [comment]
情况了解了 但我这里还是复现不出来，同学先用 `cssEllipsis=false` backup一下，我再定位下问题 尽早修复 笔芯～
