### ISSUE TITLE
命名空间大小写问题

### ISSUE THREAD

**Issue by hoosin** [arco-design/arco-design#249]
version: 2.6.0
ci 构建的时候会出现类似  Module not found: Can't resolve '@arco-design/web-react/lib/input'

![image](https://user-images.githubusercontent.com/3365399/144414085-42cf445b-9d60-4cb0-a0bd-473409482b6d.png)

看了一下源码组件命名空间全部是首字母大写，设计的时候没有考虑 Linux fs 对大小写敏感吗？

再看看 ant-design  https://github.com/ant-design/ant-design/tree/master/components

**Comment by PengJiyuan** [comment]
为什么这里会被编译成小写呢？大小写应该不是问题，只要保持一致就行了吧。material 也用的是驼峰命名文件夹

**Comment by hoosin** [comment]
@PengJiyuan 只是给你们一个建议

**Comment by PengJiyuan** [comment]
@hoosin OK，现在改动也会引发巨大的 breaking change
