### ISSUE TITLE
横向导航栏切换的时候 tooltip 字体颜色改变了

### ISSUE THREAD

**Issue by HQ-YYK** [arco-design/arco-design#2491]
![微信截图_20240111172208](https://github.com/arco-design/arco-design/assets/54365306/1c20e789-f3de-49da-bd65-457e45f44b27)
**切换导航栏**
![微信截图_20240111172241](https://github.com/arco-design/arco-design/assets/54365306/8313d21f-f44d-4b39-b93d-f798eebd7d16)

# 发现问题的地方
![微信截图_20240111172412](https://github.com/arco-design/arco-design/assets/54365306/801a4b43-e996-4bdb-9185-083d3e33cd54)

# 解决问题
:global(.arco-tooltip-content) {
  color: #fff !important;
}

**Comment by yinkaihui** [comment]
组件库里好像没有发现这个写法

**Comment by HQ-YYK** [comment]
我是外部进行更改的
