### ISSUE TITLE
icon 组件按类型引入

### ISSUE THREAD

**Issue by xiaobai-abc** [arco-design/arco-design#2497]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
目前只能 引入对应的icon name  然后使用组件 

## 预期解决问题
可否添加一个 统一组件 通过传入 type之类的字段 自动生成对应 icon 组件

**Comment by yinkaihui** [comment]
这个在项目里简单封装就行吧 。。 在组件库里新增会导致dist产物包含全量 icon 。。
