### ISSUE TITLE
水印组件在某些浏览器显示异常

### ISSUE THREAD

**Issue by gogoLJY** [arco-design/arco-design#2499]
# 基本信息
- 依赖包名 及 版本: @arco-design/web-react@2.57.0
- 框架版本: React
- 浏览器版本: chrome120.0.0.0
- 复现地址: https://arco.design/react/components/watermark
# 表现
![20240119-111528](https://github.com/arco-design/arco-design/assets/28554718/c486dd04-5f10-4017-815f-c90fa1482dd4)
![20240119-111600](https://github.com/arco-design/arco-design/assets/28554718/3c61bc49-1630-433d-9847-7ae3a7247537)
# 复现步骤
- 在某些版本浏览器打开 Arco 官网水印组件

**Comment by gogoLJY** [comment]
本地修复
- 添加 background-position：0 0；

**Comment by PengJiyuan** [comment]
什么浏览器？

**Comment by gogoLJY** [comment]
chrome 和 firefox，都有复现，在运营侧浏览器打开
