### ISSUE TITLE
数据展示的树 Tree 一键全部展开或者折叠

### ISSUE THREAD

**Issue by Kennnnnnji** [arco-design/arco-design#251]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
Vue

## What are the similar cases of this feature
nil

## What problem does this feature solve?
层级太多时要点很多下

**Comment by yinkaihui** [comment]
vue 的issue 在这里提 https://github.com/arco-design/arco-design-vue

**Comment by Kennnnnnji** [comment]
> vue 的issue 在这里提 https://github.com/arco-design/arco-design-vue

新feature是两边都加？还是分开的？
