### ISSUE TITLE
Inquiry Regarding English Version Support for Figma Design

### ISSUE THREAD

**Issue by Kimi-Gao** [arco-design/arco-design#2515]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
No

## What problem does this feature solve?
This UI library looks fantastic, and we would like to promote it on our company's U.S. site. However, we noticed that the current Figma design is only available in Chinese: https://www.figma.com/community/file/1053233047330321743.

Do you have any plans to provide support for an English version? Thank you.

**Comment by yinkaihui** [comment]
目前应该尽可能都用英文了。。属性可能中文比较多，后续会把属性切换到英文 ❤️
