### ISSUE TITLE
`disabledAlpha` not working in  `ColorPicker`

### ISSUE THREAD

**Issue by lightersss** [arco-design/arco-design#2528]
## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.59.1
- **Browser:** chrome120.0.0.0
- **Reproduction Link:** https://codesandbox.io/p/sandbox/stupefied-tdd-rgdmtc?file=%2Fdemo.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls4ja80f00073b6hijohbayz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls4ja80e00033b6hk02kjcew%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls4ja80f00043b6hcw88pt92%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls4ja80f00063b6hoes3e2b0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls4ja80e00033b6hk02kjcew%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls4ja80e00023b6hbvo59hey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls4ja80e00033b6hk02kjcew%2522%252C%2522activeTabId%2522%253A%2522cls4ja80e00023b6hbvo59hey%2522%257D%252C%2522cls4ja80f00063b6hoes3e2b0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls4ja80f00053b6ho052yj4o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls4ja80f00063b6hoes3e2b0%2522%252C%2522activeTabId%2522%253A%2522cls4ja80f00053b6ho052yj4o%2522%257D%252C%2522cls4ja80f00043b6hcw88pt92%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls4ja80f00043b6hcw88pt92%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

## What is expected?
AlphaInput component is disabled.

**Comment by jiahao-c** [comment]
看了下目前 disabledAlpha 只在文档里有，代码里这个功能完全没写。我有兴趣解决此 ticket，如果方便的话请 assign 给我。
我打算把将功能实现为以下这样，就是不显示滑条，但仍显示 100% 这个数值，这样用户在知道 Alpha 不能调整的同时，还知道当前数字是多少。这样可以吗？
![image](https://github.com/arco-design/arco-design/assets/8275280/48add5e5-c63c-4d67-b4e1-026e55f122aa)

**Comment by jiahao-c** [comment]
这个可以close了，我没权限close，需要 @yinkaihui  操作一下噢
