### ISSUE TITLE
Image 组件支持 onError 回调

### ISSUE THREAD

**Issue by linzhipeng98** [arco-design/arco-design#2530]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
https://ant.design/components/image-cn

## What problem does this feature solve?
有图片列表需要渲染，需要 error 状态

**Comment by linzhipeng98** [comment]
@flsion cc

**Comment by flsion** [comment]
这个事件已经支持，文档上遗漏了，我补充下
