### ISSUE TITLE
[颜色选择器/ColorPicker] 希望支持自定义触发器

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#2536]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
就像 https://ant.design/components/color-picker-cn 中的自定义触发器。

## What problem does this feature solve?
比如，我想自定义一个按钮或什么元素，我不想用默认的方式显示。

**Comment by miss85246** [comment]
复议！个人觉得这个功能也会很有用。目前只能通过 <div> 包裹 < ColorPicker /> 和想要展示的元素， 并把 ColorPicker 通过 style 设置宽高为0，才能在不影响UI的情况下直接展示，虽然能用，但总是觉得不爽。要是能改一下就好了。

另外，我还有一个其他问题，就是颜色选择器只能在`颜色发生改变`的时候或者 `下拉框收起展开时` 才能触发事件，但是有些时候业务需要共用这一个颜色选择器，不同的内容选择颜色，如果多个内容选择的都是同一个颜色，并不会触发颜色选择事件，所以希望能够在点击预设颜色或者选择历史颜色后，新增一个额外的触发事件，方便得知选择了颜色。😌
