### ISSUE TITLE
menu的选中后的左侧图标不能自定义

### ISSUE THREAD

**Issue by teashirtt** [arco-design/arco-design#2546]
## What problem does this feature solve?
图标是固定的会导致应用场景受限，MenuItemGroupProps应该提供一个插槽属性

**Comment by MisterLuffy** [comment]
React 还是 Vue 呢。Menu 选中状态只有颜色的区别，不牵扯到图标呀。

**Comment by teashirtt** [comment]
react
场景是使用 dropdown 是传入 menu 组件，在选择 menu item 后我希望可以通过图标标明现在的选择项是哪个

**Comment by teashirtt** [comment]
> React 还是 Vue 呢。Menu 选中状态只有颜色的区别，不牵扯到图标呀。

react
场景是使用 dropdown 是传入 menu 组件，在选择 menu item 后我希望可以通过图标标明现在的选择项是哪个

**Comment by MisterLuffy** [comment]
这里需要通过 Menu 的 `onClickMenuItem` 来取得点选的菜单项目，然后自行为它添加图标。因为 MenuItem 的 children 完全是自定义的，组件内部并不会自动为它添加选中图标。
