### ISSUE TITLE
arco table 默认配置， 当在非第一页操作，导致data变更，pagination 问题

### ISSUE THREAD

**Issue by huqiang-nj** [arco-design/arco-design#255]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.25.1
- **System:** mac
- **Browser:** chrome
- **Reproduction Link:** https://codesandbox.io/s/busy-zeh-6z3n8?file=/index.js

## Extra info
https://codesandbox.io/s/ji-ben-yong-fa-antd-4-17-2-forked-gn18x?file=/index.js:1274-1325

## What is expected?
默认配置，当在非第一页更新data的时候，pagination保持当前状态

## Steps to reproduce
默认配置
<Table columns={columns} dataSource={data} />
![image](https://user-images.githubusercontent.com/62658875/144566024-1727ca9f-59e5-4565-8bab-2d1a2036203a.png)
点击第2页，操作表格导致data更新，如操作input导致data的某个字段值变更。
现象：table刷新，重新回到了第一页
![image](https://user-images.githubusercontent.com/62658875/144565530-0558a4bf-f0ef-4f6d-8c4c-027b85de517a.png)

**Comment by yuhan0709** [comment]
Table 组件 `data` 变化，重置到第一页这个是符合预期的，你这种不想让他变只能自己把 `pagination` 受控一下
