### ISSUE TITLE
Message Component: 设置全局最大Message数量，比如1个

### ISSUE THREAD

**Issue by guiyumin** [arco-design/arco-design#2557]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
none

## What problem does this feature solve?
有时候页面上会由于点击多次，出现多个同样的Message，如果能设置message同时最多只有1个，保证全局只有最多一个，就很完美了

我以前用过一个js库，就是专门搞popup的，可以设置为最多同时出现1个popup，但记不起来名字了

**Comment by yinkaihui** [comment]
Message 有个 maxCount 配置，可以看下

**Comment by danaoairuike** [comment]
> Message 有个 maxCount 配置，可以看下

看到了，谢谢
