### ISSUE TITLE
为颜色选择器 ColorPicker 添加 onChooseComplete 方法

### ISSUE THREAD

**Issue by miss85246** [arco-design/arco-design#2561]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
暂无案例，但是可以参考 antd 中 ColorPicker 的 onChangeComplete 方法，有些类似。

## 预期解决问题
在一些场景下，整个页面有多个需要进行颜色选择的元素，但是这些元素共用同一个颜色选择器。当组件选择的颜色与上一次选择的颜色一致的时候，是无法触发 onChange 方法，这个时候必须要依赖 state 进行额外的设置才能完成该功能。建议添加 onChooseComplete，当关闭颜色选择框时，即便颜色并未发生变化，也返回当前选中的颜色。

**Comment by flsion** [comment]
@miss85246 ColorPicker 组件提供了 onVisibleChange 事件，可以在隐藏时获取下颜色值
