### ISSUE TITLE
Table组件会提示：Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by nowui** [arco-design/arco-design#2579]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.60.3
- **Framework version:** React 18.2.0
- **Browser:** chrome122.0.0.0
- **Reproduction Link:** https://codesandbox.io/p/devbox/6ycsz9?embed=1&file=%2Fsrc%2FApp.jsx%3A3%2C48&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltjk9sus00063b6j3n8ufzb3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltjk9sus00023b6jelcl0zu1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltjk9sus00043b6jy2hlz1zn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltjk9sus00053b6jt6d5w4s3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltjk9sus00023b6jelcl0zu1%2522%253A%257B%2522id%2522%253A%2522cltjk9sus00023b6jelcl0zu1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltjl8chl00023b6j03qrejkj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A48%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A48%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltjl8chl00023b6j03qrejkj%2522%257D%252C%2522cltjk9sus00053b6jt6d5w4s3%2522%253A%257B%2522id%2522%253A%2522cltjk9sus00053b6jt6d5w4s3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A8080%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cltjkbi9500ji3b6j8nq5ndyx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltjkbi9500ji3b6j8nq5ndyx%2522%257D%252C%2522cltjk9sus00043b6jy2hlz1zn%2522%253A%257B%2522id%2522%253A%2522cltjk9sus00043b6jy2hlz1zn%2522%252C%2522activeTabId%2522%253A%2522cltjk9sus00033b6j9pwphpwn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltjk9sus00033b6j9pwphpwn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltjkz6xl000ddlgy3areedb2%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cltjkaeug00993b6jh58u5cy9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

参考的是官方table基础用法
[](https://arco.design/react/components/table#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)
![image](https://github.com/arco-design/arco-design/assets/3635163/5cda2188-1f18-44c0-879c-85ec535534ff)

**Comment by caiguanhao** [comment]
一样的问题，临时改用 2.60.1 版本解决

**Comment by cat-uncles** [comment]
我换版本都不行的
