### ISSUE TITLE
官方水印组件在某些浏览器大屏显示异常，小屏正常

### ISSUE THREAD

**Issue by TianylCandy** [arco-design/arco-design#2585]
![image](https://github.com/arco-design/arco-design/assets/26967166/5f7e596f-9581-456d-b128-d0563fb41e52)
依赖包名 及 版本: @arco-design/web-react@2.56.0 及以上
框架版本: React
浏览器版本: chrome  122.0.6261.129 (arm64)
                    safari版本15.6.1 (17613.3.9.1.16)
显示器：23英寸（1920*1080）
复现地址: https://arco.design/react/components/watermark

**Comment by JNUfeatherwit** [comment]
在windows的chrome上显示异常

**Comment by thankwsx** [comment]
devicepixelratio是1？
