### ISSUE TITLE
select rendertag 删除tag时出现闪动

### ISSUE THREAD

**Issue by liumengyuangit** [arco-design/arco-design#2588]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.60.3
- **Browser:** chrome122.0.0.0

## What is expected?
不闪动，不出现重复渲染

## Steps to reproduce
可见arco官网 - Select - 多选模式第二/第三个案例。renderTag 只有 index = 1时渲染，删除第一个，则会出现渲染闪动
![20240314111723_rec_](https://github.com/arco-design/arco-design/assets/36722801/3d5142e1-dd52-4f2b-a36a-a29b3ceecb9f)
![20240314111822_rec_](https://github.com/arco-design/arco-design/assets/36722801/10267a27-b53e-40c0-972e-2ab6b46eb830)

**Comment by MisterLuffy** [comment]
由于 DOM 消失的时候存在动画，所以这个问题修改的成本比较大，如果对动画没有特别重的要求的话，可以设置 `animation = false` 来避免这个问题。
