### ISSUE TITLE
Input组件在自动宽度下，超出宽度的内容会被省略，但依然能横向滚动，滚动时内容依旧处于省略状态，导致滚动后展示不正确。Input 配置autoWidth和allowClear之后，配置的最小宽度失效，clear的icon位置出错。

### ISSUE THREAD

**Issue by johnwojtek** [arco-design/arco-design#2598]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.61.0
- **Browser:** chrome122.0.0.0

## What is expected?
鼠标悬浮时，内容不再进行省略。

**Comment by johnwojtek** [comment]
![Uploading 飞书20240319-170645.gif…]()

**Comment by jiahao-c** [comment]
@johnwojtek 图片挂了
