### ISSUE TITLE
tree组件受控全部展开和全部收起时，多条数据情况下展开受起展示不正确，并且会让最外层的父节点无法点击展开icon

### ISSUE THREAD

**Issue by liusexin** [arco-design/arco-design#2617]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.61.2
- **框架版本:** ^18.0.0
- **浏览器版本:** chrome123.0.0.0
- **复现地址:** https://codesandbox.io/p/sandbox/tree-demo-v9y5hl?file=%2Fsrc%2Fmock.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cludfpuic00063b6hk11u43rp%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cludfpuib00023b6hm52w4rat%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cludfpuib00033b6hoovsb0fc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cludfpuib00053b6hr4wk5dzy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cludfpuib00023b6hm52w4rat%2522%253A%257B%2522id%2522%253A%2522cludfpuib00023b6hm52w4rat%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cludftiv300023b6hxd4uyrb3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmock.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cludftiv300023b6hxd4uyrb3%2522%257D%252C%2522cludfpuib00053b6hr4wk5dzy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cludfpuib00043b6htvqs27ik%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cludfpuib00053b6hr4wk5dzy%2522%252C%2522activeTabId%2522%253A%2522cludfpuib00043b6htvqs27ik%2522%257D%252C%2522cludfpuib00033b6hoovsb0fc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cludfpuib00033b6hoovsb0fc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A13.819444444444443%257D

## 额外补充
当我折叠所有/展开所有时会将除最后一个之外的其他节点的子节点全部放在arco-tree-node-list tree-slide-expand-enter-done这个新的div下。而重新出发展开/关闭icon这些子节点又变回和父节点同级。

## 预期结果
可以正常展示，可以正常点击收起折叠icon

## 复现步骤
多条符合tree组件的数据，含有孙子节点，受控展开收起时，全部展开和全部收起展示不正确，而且只有最后一项的祖节点可以点击icon，其他祖节点不能点。

**Comment by Dachong233** [comment]
+1，我也碰到了这个问题

**Comment by ssoda01** [comment]
因为用了严格模式。

严格模式下，触发ResizeObserverComponent里的findDOMNode，导致的报错。

```
  <StrictMode>
    <App />
  </StrictMode>
```

其实这个sandbox里打开控制台已经可以看到报错了。
<img width="375" alt="image" src="https://github.com/arco-design/arco-design/assets/96223880/b30ec393-bc34-454e-9b53-0c68b6cd2009">


找了一下，发现其实Tree组件本身修过这个findDOMNode，但是触发Observer之后还是不可避免地有findDOMNode的问题。
<img width="554" alt="image" src="https://github.com/arco-design/arco-design/assets/96223880/57e4b41b-6cba-471a-b6a6-b801dd467f99">

抱歉我水平有限也无法实际解决问题，就只能说下初步发现这样
