### ISSUE TITLE
字体会放置到body上面，影响到我的项目

### ISSUE THREAD

**Issue by qiaogaolong** [arco-design/arco-design#2669]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.62.0
- **Browser:** chrome124.0.0.0

**Comment by yinkaihui** [comment]
可以用插件移除下字体 https://github.com/arco-design/arco-plugins
