### ISSUE TITLE
Upload 组件通过 customRequest 自定义 onError 后，error icon 被 hover 时渲染出错

### ISSUE THREAD

**Issue by fazdzz** [arco-design/arco-design#2681]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.62.0
- **Framework version:** React@17
- **Browser:** chrome124.0.0.0
- **Reproduction Link:** https://codesandbox.io/p/sandbox/vibrant-bardeen-35q2hy?file=%2Fdemo.js%3A5%2C20

## Extra info
Upload 源码中会将 UploadItem 的 reponse 传递给 Tooltip 的 content
- https://github.com/arco-design/arco-design/blob/main/components/Upload/list/textItem.tsx#L111

UploadItem 中 response 的类型定义是 object
- https://github.com/arco-design/arco-design/blob/main/components/Upload/list/textItem.tsx#L111

Tooltip 若 content 不是函数，会直接将 content 作为 child 渲染
- https://github.com/arco-design/arco-design/blob/main/components/Tooltip/index.tsx#L94
- https://github.com/arco-design/arco-design/blob/main/components/Tooltip/index.tsx#L131

## What is expected?
对 hover 之后的弹窗没有需求，只希望不要报错

## Steps to reproduce
1. 上传任意文件
2. 鼠标 hover 到红色的 error icon 上
3. 渲染报错 `Objects are not valid as a React child (found: object with keys {error}). If you meant to render a collection of children, use an array instead.`

**Comment by yinkaihui** [comment]
已兼容修复 `2.63.2`
