### ISSUE TITLE
[bug] Typography 组件在开启 `showTooltip : true` 时，添加了 span 导致 css 省略失效

### ISSUE THREAD

**Issue by zaiMoe** [arco-design/arco-design#2682]
这里会什么要添加 span 呢？ 
https://github.com/arco-design/arco-design/blob/5e771d6a98e588f12186ca839e9115e8e3097331/components/Typography/base.tsx#L253

**Comment by yinkaihui** [comment]
用 `Typography.Ellipsis` 替换原本的 ellipsis 属性吧
