### ISSUE TITLE
Element does not define the `getRootDOMNode` method causing a call to React.findDOMNode. but findDOMNode is deprecated in StrictMode. Please check the code logic

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#2713]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.63.0
- **框架版本:** React 18.3.1
- **浏览器版本:** Chrome 125.0.0.0 / Edge 125.0.2535.92

## 复现步骤
Next.js中，直接使用Tooltip，就会报错。

![image](https://github.com/arco-design/arco-design/assets/3413930/6088a111-485d-41d3-9b9f-001292d49b9f)

**Comment by yinkaihui** [comment]
这个报错对功能无影响，是组件内部定义抛出的错误提醒，用途是告知：findDOMNode 已废弃，避免使用。 这里的提醒逻辑不严谨，周五小版本会优化下，只在 react18  下提醒且优化下提醒内容。
