### ISSUE TITLE
Select 组件数据加载后，没有显示 value 对应的 label

### ISSUE THREAD

**Issue by linzhipeng98** [arco-design/arco-design#2728]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.0
- **Browser:** chrome126.0.0.0

## Steps to reproduce
https://codesandbox.io/p/sandbox/misty-rgb-5ly8vr?file=%2Fdemo.js%3A32%2C1

**Comment by linzhipeng98** [comment]
![screenshot-20240628-122715](https://github.com/arco-design/arco-design/assets/95921223/654164bf-812b-467f-b418-d31d012f07ee)
场景就是解析 url 上的参数，页面初始化的时候回填到表单里

**Comment by phk422** [comment]
#2732
