### ISSUE TITLE
nextjs 项目可以使用 arco-design 组件吗，为什么报错 Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by heiemooa** [arco-design/arco-design#2749]
1、创建项目 npx create-next-app@latest
2、项目中安装 yarn add @arco-design/web-react
3、page.tsx 
```
import { Button } from "@arco-design/web-react";
import Image from "next/image";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Button>按钮</Button>
    </main>
  );
}

```

4、启动 yarn dev 报错
```
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
eval
node_modules/@arco-design/web-react/icon/react-icon/context.js (3:39)
(rsc)/./node_modules/@arco-design/web-react/icon/react-icon/context.js
file:///Users/huangfushan/hfs/test/my-app/.next/server/vendor-chunks/@arco-design.js (150:1)
Next.js
eval
/./node_modules/@arco-design/web-react/icon/react-icon/IconLoading/index.js
(rsc)/./node_modules/@arco-design/web-react/icon/react-icon/IconLoading/index.js
file:///Users/huangfushan/hfs/test/my-app/.next/server/vendor-chunks/@arco-design.js (140:1)
Next.js
eval
/./node_modules/@arco-design/web-react/es/Button/index.js
(rsc)/./node_modules/@arco-design/web-react/es/Button/index.js
file:///Users/huangfushan/hfs/test/my-app/.next/server/vendor-chunks/@arco-design.js (30:1)

```

**Comment by ZLY201** [comment]
Try add `import React from 'react'` to the top of the page.

**Comment by chenguzhen87** [comment]
同问吗？

**Comment by 50431040** [comment]
最上面加上："use client"

**Comment by milobluebell** [comment]
> 最上面加上："use client"

那还哪门子支持SSR？ 😂

> https://arco.design/react/en-US/docs/question

**Comment by milobluebell** [comment]
> Try add `import React from 'react'` to the top of the js file.

Doesn't work.. T.T

**Comment by 50431040** [comment]
> > 最上面加上："use client"
> 
> 那还哪门子支持SSR？ 😂
> 
> > https://arco.design/react/en-US/docs/question

你验证下就知道是不是SSR了

**Comment by milobluebell** [comment]
> > > 最上面加上："use client"
> > 
> > 
> > 那还哪门子支持SSR？ 😂
> > > https://arco.design/react/en-US/docs/question
> 
> 你验证下就知道是不是SSR了

老兄，你都`use client`那还能叫 支持SSR 吗？ 客户端渲染是CSR。 目前看就是arco-design对ssr支持有问题导致的这个问题

**Comment by milobluebell** [comment]
Seeming like `Icon` doesn't support SSR correctly.

@MisterLuffy Please pay attentions here, ty very much!

**Comment by 50431040** [comment]
> > > > 最上面加上："use client"
> > > 
> > > 
> > > 那还哪门子支持SSR？ 😂
> > > > https://arco.design/react/en-US/docs/question
> > 
> > 
> > 你验证下就知道是不是SSR了
> 
> 老兄，你都`use client`那还能叫 支持SSR 吗？ 客户端渲染是CSR。 目前看就是arco-design对ssr支持有问题导致的这个问题

F12看下源代码，并非完全的客户端渲染
