### ISSUE TITLE
table 添加虚拟滚动后，快速滚动过程中页面会显示空白背景，会给人产生卡顿的错觉

### ISSUE THREAD

**Issue by yyyyffqqqq** [arco-design/arco-design#2761]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.1
- **Browser:** chrome126.0.0.0

## What is expected?
table 添加虚拟滚动后，快速滚动过程中页面还能看到表格行

**Comment by yyyyffqqqq** [comment]
列数增加，渲染性能也会受影响。特别是有自定义的使用render自定义cell的时候（render的渲染处理逻辑也并不复杂）

**Comment by PengJiyuan** [comment]
出现空白这个应该是虚拟滚动的通病吧，渲染逻辑就是不可见的行用空白代替，快速滚动的时候，性能受限时会出现空白。这个问题已知，后续看看怎么优化吧
