### ISSUE TITLE
怎么动态设置主题色？

### ISSUE THREAD

**Issue by qianggewudi6666** [arco-design/arco-design#2769]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.56.0
- **框架版本:** vue3

## 额外补充
动态设置了@arcoblue-6样式但按钮hover还是原来颜色怎么解决？

**Comment by yinkaihui** [comment]
参考这个吧 ：https://arco.design/react/docs/question#%E5%85%B6%E4%BB%96%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
<img width="661" alt="image" src="https://github.com/user-attachments/assets/48456042-ca62-438d-909e-9549dcfb8624">

**Comment by lynn1286** [comment]
> 参考这个吧 ：https://arco.design/react/docs/question#%E5%85%B6%E4%BB%96%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 <img alt="image" width="661" src="https://private-user-images.githubusercontent.com/23161413/355723927-48456042-ca62-438d-909e-9549dcfb8624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTAwMzAsIm5iZiI6MTczMTM4OTczMCwicGF0aCI6Ii8yMzE2MTQxMy8zNTU3MjM5MjctNDg0NTYwNDItY2E2Mi00MzhkLTkwOWUtOTU0OWRjZmI4NjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMDg3ODYyZjg4NmJhYTFhM2E4ZmIzNGEwYmU2NWM2ZmJmYzZlYjQ0YzlkMzQ5OWU0Mzg3Mzg0OGZiNmUxMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qwnuUjAt_KmB15d6uKgz34U1oR3oaFmDp0n6zorPC4k">

在 Nextjs 中如果需要根据请求获取主题色，会出现颜色闪动的问题，请问有什么解决办法吗？
