### ISSUE TITLE
popover/popconfirm包含button的disabled为true时long属性不生效

### ISSUE THREAD

**Issue by JeffreyZhang96** [arco-design/arco-design#278]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react：2.26.0
- **系统版本:** macOS Monterey 12.0.1
- **浏览器版本:** 96.0.4664.55
- **复现地址:** https://codesandbox.io/s/youthful-golick-xjnok?file=/index.js

## 预期结果
long属性应该生效

## 复现步骤
popover/popconfirm包含button的disabled为true时long属性不生效

**Comment by PengJiyuan** [comment]
disabled 的 Button 按钮需要加上 `style={{ display: 'block' }}`，因为 disabled 的按钮会做一个特殊处理，为了防止 disabled 时无法触发事件，会把 button 标签包裹了一个 span 标签。
