### ISSUE TITLE
Tabs组件js报错 Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by cfabregas** [arco-design/arco-design#2780]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)
来自slardar监控报警
![img_v3_02do_0c30874d-6fc2-4fe8-be31-6e892902ec5g](https://github.com/user-attachments/assets/6c01ecb4-1ae5-4eaf-8e5e-05a311c7e9b3)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.1
- **Browser:** chrome126.0.0.0

**Comment by PengJiyuan** [comment]
已发版
