### ISSUE TITLE
使用了Menu组件的自动省略，浏览器视窗缩小，某临界点，会不停自动计算，导致浏览器不停闪烁

### ISSUE THREAD

**Issue by skyweaver213** [arco-design/arco-design#2785]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.3
- **Framework version:** latest
- **Browser:** chrome127.0.6533.100
- **Reproduction Link:** https://codesandbox.io/p/sandbox/dreamy-platform-z8ht5c?file=%2Fdemo.js%3A14%2C6

## What is expected?
期望触发省略时候，浏览器不闪烁

## Steps to reproduce
1. 访问打开 https://codesandbox.io/p/sandbox/dreamy-platform-z8ht5c?file=%2Fdemo.js%3A14%2C6
2. 逐点，来回缓慢 不断缩小浏览器，到一定省略号临界值，浏览器会不停闪烁（推测死循环计算）
![11111](https://github.com/user-attachments/assets/2b3dc4fa-9a41-4e53-88fd-45ed3a161d42)

**Comment by ftao123** [comment]
demo里面css样式提供一下，你的demo里面提供错了

**Comment by skyweaver213** [comment]
> 1. https://codesandbox.io/p/sandbox/dreamy-platform-z8ht5c?file=%2Fdemo.js%3A14%2C6

不好意思，刚更新了，再访问一下页面

**Comment by skyweaver213** [comment]
> demo里面css样式提供一下，你的demo里面提供错了，我怀疑是你外层样式造成这个问题

https://codesandbox.io/p/sandbox/dreamy-platform-z8ht5c?file=%2Fdemo.js%3A14%2C6
不好意思，刚更新了，再访问一下页面 @ftao123

**Comment by PengJiyuan** [comment]
确实复现了， @yinkaihui 之前是不是有碰到过这个问题？

**Comment by ftao123** [comment]
已经修复提交了PR
