### ISSUE TITLE
form表单项目如果设置了rules={[{ required: false }]}也会导致出现.arco-form-item-status-warning（黄底）样式

### ISSUE THREAD

**Issue by DuLinRain** [arco-design/arco-design#279]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react: 2.26.0
- **System:** MAC
- **Browser:** CHROME
- **Reproduction Link:** https://codesandbox.io/s/interesting-snowflake-4hfi2?file=/index.js:2803-2832

## What is expected?
灰底

## Steps to reproduce
1. form表单项目设置field和rules={[{ required: false }]}
2. form.submit

**Comment by nanxiaobei** [comment]
刚升级，就发现了这个很明显的 bug ...
