### ISSUE TITLE
NextJS 中使用 Trigger 组件弹出 Input 框无法输入

### ISSUE THREAD

**Issue by codingschoolkid** [arco-design/arco-design#2791]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.3
- **Framework version:** React ^18  NextJS 14.2.6
- **Browser:** 版本 127.0.6533.122（正式版本） （64 位）

## What is expected?
Input框正常输入

## Steps to reproduce
1. 使用 nextjs 创建一个新项目
2. 修改 page.tsx 为以下代码

```
"use client";
import { Input, Trigger } from "@arco-design/web-react";
import "@arco-design/web-react/dist/css/arco.css";

export default function Home() {
  return (
    <Trigger popup={() => <Input value="xixihaha" />} position="bl">
      <h1>Hello world</h1>
    </Trigger>
  );
}
```

3. 启动
弹出的 Input 框中无法输入

![20240825-212838](https://github.com/user-attachments/assets/e35db752-4204-4487-ba50-b88d37ebba6b)

**Comment by PengJiyuan** [comment]
Input 组件设置 value 是受控模式，可以了解下受控和非受控的区别。
