### ISSUE TITLE
添加setupProxy.js后,页面打不开了

### ISSUE THREAD

**Issue by ljxpython** [arco-design/arco-design#2793]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.63.3
- **Browser:** chrome127.0.0.0

## Steps to reproduce
我照着https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually官方文档配置代理,添加了一个src/setupProxy.js,只要添加了这个文件,页面就打不开了,这个很奇怪

**Comment by youzi-2333** [comment]
不要下载这个文件！这是一个计算机病毒

Don't download this! This is a computer virus.

**Comment by PengJiyuan** [comment]
看着应该去给 cra 提issue
