### ISSUE TITLE
请问mobile版本有吗？大概什么时候开源？

### ISSUE THREAD

**Issue by ColinChen2** [arco-design/arco-design#28]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
ant-design-mobile

## 预期解决问题
Mobile版本也是你们团队维护吗？

**Comment by DreamPWJ** [comment]
移动版支持Taro小程序码？@PengJiyuan

**Comment by PengJiyuan** [comment]
> 移动版支持Taro小程序码？@PengJiyuan

暂时没有计划支持哈

**Comment by taosiqi** [comment]
顶，react就ant-design-mobile能拿出手 ，希望丰富下生态 （T￢T)/

**Comment by Tenodec** [comment]
@PengJiyuan 讲道理，抓紧时间啊哈哈哈，腾讯的TdesignBug太多了，如果可以发展支持小程序版本就更好了，就算只支持字节小程序，网友也好复刻，社区就来了。

**Comment by ronghang** [comment]
> 预计明年年初开源

目前移动端开源了吗？

**Comment by PengJiyuan** [comment]
> > 预计明年年初开源
> 
> 目前移动端开源了吗？

真的马上就要开源了，现在有些内部流程在走

**Comment by baiachen** [comment]
是安排明天开源吗

**Comment by Tenodec** [comment]
> 是安排明天开源吗



> > > 预计明年年初开源
> > 
> > 
> > 目前移动端开源了吗？
> 
> 真的马上就要开源了，现在有些内部流程在走

啥时候可以开，哈哈哈哈

**Comment by codytan** [comment]
内部流程走完了么
