### ISSUE TITLE
ColorPicker，在弹出画板上按下鼠标选择颜色，鼠标移出画板时，会出发外层DOM的选择。原生input和antd的ColorPicker则不会

### ISSUE THREAD

**Issue by dinfer** [arco-design/arco-design#2817]
查看了相关文档，没有找到如何控制鼠标按下且移动出ColorPicker弹出层导致外层DOM元素被选择的方式。

- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.64.0
- **Browser:** chrome128.0.0.0

**Comment by dinfer** [comment]
官网上的组件即可复现

arco 的现象

https://github.com/user-attachments/assets/57dcdf22-6166-4b3d-8c7a-b1d521cba58f

antd 的现象

https://github.com/user-attachments/assets/4192f7b1-2327-46c0-a614-66ca85cca869

**Comment by ftao123** [comment]
onMouseDown事件中没有阻止浏览器默认行为
