### ISSUE TITLE
验证码输入框 代码示例问题

### ISSUE THREAD

**Issue by ohaiya** [arco-design/arco-design#2843]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.64.0
- **浏览器版本:** chrome129.0.0.0
- **复现地址:** https://arco.design/react/components/verification-code#%E9%85%8D%E5%90%88%E8%A1%A8%E5%8D%95%E4%BD%BF%E7%94%A8

## 复现步骤
示例代码中：

<VerificationCode size='large' validate={({inputValue}) => **/d/.test(inputValue)}** />

应为：

<VerificationCode size='large' validate={({inputValue}) => **/\d/.test(inputValue)}** />

**Comment by yinkaihui** [comment]
md loader 对文档转义有问题，后续有时间看下怎么调整下， 源文档写的是 ` /\d/.test(inputValue)}`  https://github.com/arco-design/arco-design/blob/main/components/VerificationCode/__demo__/validate.md?plain=1#L30
