### ISSUE TITLE
upload 组件 customRequest 传一个 async function 导致 abort 不生效

### ISSUE THREAD

**Issue by fengChongxiu** [arco-design/arco-design#286]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** 2.26.0
- **System:** mac
- **Browser:** chrome
- **Reproduction Link:** https://arco.design/react/components/upload

## What is expected?
能正常 abort

## Steps to reproduce
customRequest 传 async function 即可复现
![image](https://user-images.githubusercontent.com/17736007/145018704-a7efb404-0a46-48cd-a05c-8f65c2a0d186.png)
这里的 request 在 customRequest 为 async function 时是一个 promise，直接像下面那样消费是有问题的

![image](https://user-images.githubusercontent.com/17736007/145018636-3c721d76-bcee-4aa5-9669-215f390de944.png)

**Comment by Bohan-J** [comment]
+1，目前要实现abort就要把customRequest中的异步逻辑都写成promise...then的形式，不太优雅
