### ISSUE TITLE
Typography 组件开启 ellipsis 后在 Description 中样式变更

### ISSUE THREAD

**Issue by Fiv5** [arco-design/arco-design#289]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react: 2.25.0
- **系统版本:** Mac
- **浏览器版本:** Chrome latest
- **复现地址:** https://webide.bytedance.net/s/arco-typography-bug-6myde12h

## 预期结果
样式对齐

## 复现步骤
在 2.25.0 版本，可以看到开启了 ellipsis 的 Typography 在 Description 中没有对齐，而在之前的版本中是对齐的。

相关 MR：https://github.com/arco-design/arco-design/pull/191

**Comment by yuhan0709** [comment]
同学 Typography 默认是直接通过css进行省略的哈，在 `overflow：hidden` 和` display: inline-block`  一起使用的情况下会造成 `baseline` 移动，所以高度确实有点问题。 具体解决方案可以看一下这个 https://segmentfault.com/a/1190000040403898

**Comment by yuhan0709** [comment]
这种特殊场景的样式问题 组件库这边不好把控，所以需要用户手动加一下样式～ 笔芯
