### ISSUE TITLE
能否公开一下生成主题工具中【根据当前基色生成一套色阶】的算法？

### ISSUE THREAD

**Issue by 826327700** [arco-design/arco-design#2892]
![image](https://github.com/user-attachments/assets/e4f5144c-71a6-4df7-b8fd-49fcb2ec3870)

测试了一下 生成的色阶都挺搭配基色的。
有这功能 我就可以在运行时无限自定义主题了，万分感谢！

**Comment by roojay520** [comment]
@826327700  https://www.npmjs.com/package/@arco-design/color
