### ISSUE TITLE
Vue Web怎么一直加载打不开？？？

### ISSUE THREAD

**Issue by l527911714** [arco-design/arco-design#2893]

**Comment by LoYoi-i** [comment]
貌似挂了

**Comment by yinkaihui** [comment]
https://arco-design-vue.netlify.app/ 可以先看这个，官网我们尽快修复

**Comment by A2Data** [comment]
{"errorCode":"404ID","errorMessage":"Not found, please make sure your service has been deployed and your invoke endpoint/domain is correct"}
这么大的公司 咋还会有这个问题呢，还没好呢。

**Comment by ZeroYuJie** [comment]
现在还是404，不应该呀

**Comment by newstart0514** [comment]
生态产品好像也挂了
