### ISSUE TITLE
Form.Item shouldUpdate 这个 props 不支持指定某个控件值变化时重新渲染

### ISSUE THREAD

**Issue by daiwa233** [arco-design/arco-design#297]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** latest
- **System:** mac
- **Browser:** chrome
- **Reproduction Link:** https://codesandbox.io/s/objective-maxwell-lggx6?file=/index.js:1484-1517

## What is expected?
console 中不会打印 values

## Steps to reproduce
选择颜色 ：C

**Comment by yinkaihui** [comment]
因为你 `shouldUpdate` 判断的时候用的 `type` 字段，改成 `prev.color !== next.color`  试试 ？

**Comment by daiwa233** [comment]
> 因为你 `shouldUpdate` 判断的时候用的 `type` 字段，改成 `prev.color !== next.color` 试试 ？

我的期望是仅当 type 这个 field 变化时才重新渲染，所以设置 shouldUpdate 等于 () => prev.type !== next.type 

然后发现当 shouldUpdate 是 falsy 时，form 中的任一项 改变时，formItem 的 children 依然会被调用欸，这个符合预期嘛
```jsx
        <Form.Item noStyle>
          {(values) => {
            console.log(values);
            return values.type ? (
              <Form.Item field="remark" label="Remark">
                <Input.TextArea placeholder={values.type + " remark"} />
              </Form.Item>
            ) : null;
          }}
        </Form.Item>
```

**Comment by yinkaihui** [comment]
啊 ，刚开始理解错了。 不过我刚刚试了下 ，选颜色的时候并没有触发 `console.log(values, '__________')` 呀 

https://codesandbox.io/s/nifty-sutherland-7fnzs

**Comment by daiwa233** [comment]
> 啊 ，刚开始理解错了。 不过我刚刚试了下 ，选颜色的时候并没有触发 `console.log(values, '__________')` 呀
> 
> https://codesandbox.io/s/nifty-sutherland-7fnzs

sorry，搞错了，之前没看到其他地还有 console。没问题 了
