### ISSUE TITLE
table 的 rowSelection.onChange 无法区分取消全选与切换分页两种情况

### ISSUE THREAD

**Issue by Youjingyu** [arco-design/arco-design#320]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** latest
- **System:** all
- **Browser:** all
- **Reproduction Link:** https://codesandbox.io/s/recursing-chaum-ywd20?file=/index.js

## What is expected?
rowSelection.onChange 能够区分取消全选与切换分页两种情况

## Steps to reproduce
需求：table 切换到第二页后，回到第一页，应该保留用户的行选中状态。arco 貌似没有这个功能，现在想到的做法是，我们自己保存被选择行的 rowKey
但在 table 有选择的行情况下，rowSelection.onChange 在取消全选与切换分页时都会触发，onChange 回调中的 selectedRowKeys  都是空数组，无法区分区分这两种场景，从而我们无法确定是否要清空保存的 rowKey

**Comment by Youjingyu** [comment]
经过验证后，在配置了 pagination.onChange 时，在切换分页时，就不会触发 rowSelection.onChange  了。感觉这个行为不太合理

**Comment by yuhan0709** [comment]
hello～ table切换到第二页然后回到第一页保留选中状态。

这个可以设置 `checkCrossPage: true` 和 `preserveSelectedRowKeys: true` 就可以啦

具体解释可以看官网文档哈 https://arco.design/react/components/table#api
