### ISSUE TITLE
Cannot open theme in design lab, 500 Internal Server Error

### ISSUE THREAD

**Issue by Kimi-Gao** [arco-design/arco-design#322]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** -
- **System:** -
- **Browser:** -
- **Reproduction Link:** https://arco.design/themes/design/544

## What is expected?
-

## Steps to reproduce
open the link

## Extra info
https://arco.design/themes/api/common/getAllConfig 500 Internal Server Error
{"message":"Cannot read property 'type' of undefined","requestId":"2021121602290001025101102116B11CEB"}
<img width="1169" src="https://user-images.githubusercontent.com/12554487/146297024-bed7956e-4a5f-451d-ad23-c0306b47b819.png">

**Comment by yinkaihui** [comment]
服务已恢复，造成不便非常抱歉
