### ISSUE TITLE
carousel 中如何关闭 loop 效果？

### ISSUE THREAD

**Issue by nervouself** [arco-design/arco-design#333]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react: 2.26.1
- **System:** mac 12.0.1
- **Browser:** chrome
- **Reproduction Link:** https://arco.design/react/components/carousel

## What is expected?
希望 loop 效果可以关掉，到最左（最右）停住不能再滚动

## Steps to reproduce
just click

**Comment by MisterLuffy** [comment]
你好，需要增加新特性支持，请留意下个中版本。

**Comment by MisterLuffy** [comment]
思考了一下组件本身不太适合添加这个特性，因为它不是一个常用的属性。建议通过 `carousel` 属性获得组件引用，自行实现箭头翻页的逻辑。
