### ISSUE TITLE
官网示例中，表格大数量量展示，显示上有点没有对齐

### ISSUE THREAD

**Issue by zmbxy95** [arco-design/arco-design#34]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info
- **依赖包名 及 版本:** @arco-design/web-react:2.23.4
- **系统版本:** windows 11
- **浏览器版本:** chrome93
- **复现地址:** https://codesandbox.io/s/etb7p?file=/index.js

## 预期结果
表格列表头与内容能对其

## 复现步骤
如图所示：
![image](https://user-images.githubusercontent.com/50108232/138997166-75532cbb-c58d-431b-a298-8761a2f236c8.png)

**Comment by LanJamRom** [comment]
这个问题比较致命，列多就完全对不齐了，什么时候能修复一下

**Comment by PengJiyuan** [comment]
@LanJamRom 这周修一下
