### ISSUE TITLE
`arco-theme-tag` does not support multiple selectors

### ISSUE THREAD

**Issue by imhele** [arco-design/arco-design#349]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Detail
- **Package Name And Version:** @arco-design/web-react: 2.27.0
- ** System:** macOS 12
- ** Browser:** Chrome 96
- **Reproduction Link:** -

## What is expected?
CSS vars & dark theme should take effect under both elements `#app_a` and `#app_b` at the same time.

## Steps to reproduce
Set `'arco-theme-tag'` to `'#app_a, #app_b'` in `lessOptions.modifyVars`.

**Comment by imhele** [comment]
This should fix it:
![image](https://user-images.githubusercontent.com/32428655/147210462-43f9cfe8-ebd9-47da-93f8-f6f1d52dd043.png)

**Comment by yinkaihui** [comment]
2.27.1 支持
