### ISSUE TITLE
Support size & prefix prop in Autocomplete component

### ISSUE THREAD

**Issue by lvqq** [arco-design/arco-design#351]
- [x]  I'm sure this does not appear in the issue list of the repository

## What problem does this feature solve?
Support size & prefix prop in AutoComplete component, as like Select.

**Comment by lvqq** [comment]
- [x]  I'm sure this does not appear in the issue list of the repository

## Basic Info

## What are the similar cases of this feature

## What problem does this feature solve?
Support size & prefix prop in AutoComplete component, as like Select.

**Comment by MisterLuffy** [comment]
You can pass in all properties of Input via `inputProps`, like `inputProps: { size: 'mini', prefix: '$' }`.
