### ISSUE TITLE
Modal cannot be focus when using ConfigProvider

### ISSUE THREAD

**Issue by ChrisShen93** [arco-design/arco-design#352]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.27.0
- **System:** macos
- **Browser:** chrome Version 96.0.4664.110
- **Reproduction Link:** https://codesandbox.io/s/pensive-tess-0y33o?file=/index.js

## What is expected?
Input.Textarea can be focused

## Steps to reproduce
hover the button, then click the menu. The Input.Textarea cannot be focused in Modal.

**Comment by yuhan0709** [comment]
@ChrisShen93 

Hello~ 这个问题本质原因是因为冒泡。因为 `React` 默认行为会将事件冒泡到 `Parent Nodes` 上 。 所以在 `Modal` 内的点击时间其实会冒泡到 `DropDown` 下面的 `Menu.Item`。而 `DropDown` 内部一些逻辑也用到了 `focus`。所以会出现抢焦点的问题。

问题定位到了，我们团队内部讨论了很久，`React` 默认行为也是一直向上冒泡，从组件库这边真的很难把控，跟 `Modal` 类似的弹出组件的各种事件都要阻止冒泡 。

遇到这种场景需要用户手动用 `div` 包一层组织冒泡。 笔芯～
https://codesandbox.io/s/eloquent-cdn-soqf6?file=/modal-test.js
