### ISSUE TITLE
When select.option's content  is too long，tooltip component displays the position offset in select component

### ISSUE THREAD

**Issue by someoneInGit** [arco-design/arco-design#354]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react 2.24.0
- **系统版本:** macOS Big Sur 11.6
- **浏览器版本:** chrome 96.0.4664.110
- **复现地址:** https://codesandbox.io/s/jovial-tamas-c6yfy?file=/index.js:897-898

## 预期结果
No offset

## 复现步骤
Mouse over select.option and watch  the location of the tooltip

**Comment by yinkaihui** [comment]
![Uploading image.png…]()

**Comment by yinkaihui** [comment]
span 标签的内容实际上很长，所有tooltip看起来显示不正确

**Comment by yinkaihui** [comment]
![image](https://user-images.githubusercontent.com/23161413/147324723-abf09938-3850-44d7-9adc-70d60f4fcd57.png)
