### ISSUE TITLE
Input支持自动去除前后空格

### ISSUE THREAD

**Issue by yewenjunfighting** [arco-design/arco-design#356]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
用户在Input输入的时候，有时候会无意识的在前后输入一些空格，这可能会在数据处理的时候出现一些问题，当然前端可以处理，但如果Input组件可以支持会方便很多

**Comment by yewenjunfighting** [comment]
最好在用户输入的时候，不要去除空格，返回值的时候，再把空格去掉

**Comment by MisterLuffy** [comment]
个人感觉比较鸡肋，与在 `onChange` 回调中对值进行 `trim()` 相比没有明显的效率提升。

**Comment by rccoder** [comment]
+1，我也一直期望有这个功能

举个常用的例子，一个大表格里，很多 Input，一般都要 trim，如果组件不支持的话，我可能要一个个的去 trim 之类的，或者包装出个 Custom Input
