### ISSUE TITLE
穿梭框可以做到左边列表，右边表格么

### ISSUE THREAD

**Issue by xiesr** [arco-design/arco-design#364]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
穿梭框可以做到左边列表，右边表格

**Comment by MisterLuffy** [comment]
可参考此 [Demo](https://codesandbox.io/s/cool-voice-donc6?file=/index.js)
