### ISSUE TITLE
Dropdown width submenu, appear with no animation

### ISSUE THREAD

**Issue by PengJiyuan** [arco-design/arco-design#366]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** 2.27.1
- **System:** Mac
- **Browser:** Chrome
- **Reproduction Link:** https://arco.design/react/components/dropdown#%E5%A4%9A%E7%BA%A7%E8%8F%9C%E5%8D%95

## What is expected?
Appear with animation

## Steps to reproduce
Just click the button

**Comment by MisterLuffy** [comment]
@yinkaihui Have a look of this demo. If there is a popup in popup-content, animation will not work. https://codesandbox.io/s/hungry-grothendieck-lozzv?file=/index.js
