### ISSUE TITLE
DatePicker 组件在选择时间时是否可以优化一下交互？

### ISSUE THREAD

**Issue by luxiaodou** [arco-design/arco-design#371]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
希望实现的效果可以参考 Chrome 自带的 <input type="datetime-local">
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
以及 antd 的 DatePicker 
https://ant.design/components/date-picker-cn/#header

## What problem does this feature solve?
现在的 DatePicker 组件在使用 showTime 字段开启时间选择后，需要手动点击下方的「选择时间」/ 「选择日期」按钮来进行 TimePicker 和 DatePicker 的切换。但这个切换步骤实际是没有意义的，因为我启用 showTime 十有八九是需要选择时间的。
能否将这个切换省去，这两个选择器同时放在弹窗里？
![1cyMZJ0BTG](https://user-images.githubusercontent.com/12815138/147638985-9f10a978-affa-411a-8c0c-e21315a2ccae.png)

**Comment by fafadesigner2** [comment]
hi~ 感谢这位同学反馈，Date Picker 的组件我们在range picker 交互改版的时候，重点考虑了两种场景和路径，1）先选日期范围，再选具体时间点。2）先选择起始时间点，再选择结束时间点。最后调研了用户习惯，在范围选择器的场景里是场景1 更常见，所以改成了再次点击 “选择时间” 的交互。在单点时间选择的面板当中，我们可以改成双面板的设计 ~

**Comment by fafadesigner2** [comment]
您好,你的邮件已收到.我会尽快回复您的!

**Comment by FAKER-A** [comment]
> hi~ 感谢这位同学反馈，Date Picker 的组件我们在range picker 交互改版的时候，重点考虑了两种场景和路径，1）先选日期范围，再选具体时间点。2）先选择起始时间点，再选择结束时间点。最后调研了用户习惯，在范围选择器的场景里是场景1 更常见，所以改成了再次点击 “选择时间” 的交互。在单点时间选择的面板当中，我们可以改成双面板的设计 ~
==================================================================
你好，我有点疑问，在现有的设计下，会不会就舍弃掉了更加精细话的disabled功能？
例子：
      需求：用户可选最大时间范围为12个小时，存在开始和结束时间跨天的情况
      用户的开始时间点如果选择的是 12 点之前，那么结束时间就要禁用到当天，如果用户选择12点之后，那么结束时间就要禁用到第二天。
当前的这种设计无法先确定开始/结束的时间点，好像就无法做类似存在夸天禁用的需求诶，不知道我分析的是不是存在遗漏的点 @fafadesigner2

**Comment by fafadesigner2** [comment]
您好,你的邮件已收到.我会尽快回复您的!
