### ISSUE TITLE
日期hover事件 控制日期样式

### ISSUE THREAD

**Issue by accforgit** [arco-design/arco-design#372]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
1. 当鼠标悬浮到任意日期时，对外发出 hover 事件，参数为这个日期的信息
2. 允许外部精确控制每个日期的样式

上述二者结合，可以实现的效果为：实现动态预设范围。例如，我想动态选择所需日期最近三天的日期范围，鼠标移动端到12.01这个日期，可以控制让12.01  12.02 1203 这三天的日期变为蓝色选择态

**Comment by PengJiyuan** [comment]
可以用定制单元格实现： https://codesandbox.io/s/suspicious-jepsen-s7h6m
