### ISSUE TITLE
[DesignLab] Can't reset/revert style changes on Shadow

### ISSUE THREAD

**Issue by Kimi-Gao** [arco-design/arco-design#386]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** 2.27.2
- **System:** -
- **Browser:** -
- **Reproduction Link:** https://arco.design/themes

## What is expected?

All changes on `Shadow` should be resettable, and now I can't release theme package because I don't know what's changed on `Shadow`.

## Steps to reproduce

![Xnip2022-01-04_16-05-44](https://user-images.githubusercontent.com/12554487/148028611-9682a542-cf58-4084-a431-0f7e7dab3f54.jpg)
![image](https://user-images.githubusercontent.com/12554487/148030191-0ad6b120-fd62-47d8-aba5-d8f71951294f.png)

![Xnip2022-01-04_16-05-59](https://user-images.githubusercontent.com/12554487/148028635-df04a4c9-9432-4724-ae70-bacdc3d79468.jpg)
![Xnip2022-01-04_16-06-11](https://user-images.githubusercontent.com/12554487/148028646-8f6437b2-af92-43d4-b223-6d2ace08df4f.jpg)

**Comment by PengJiyuan** [comment]
已支持批量撤销
