### ISSUE TITLE
RangePicker 没有选择完成以后的回调 ，onChange 会触发2次

### ISSUE THREAD

**Issue by busyzz-1994** [arco-design/arco-design#391]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Antd 的 RangePicker  的 onChange 事件会在 ''开始'' 和 ''结束'' 时间 选择完成以后执行该回调，而当前的 onChange 事件在选择开始和结束时候都会执行一次，一共执行了2次，不是很合理，希望修改或者再添加一个类似的事件回调

## What problem does this feature solve?
Antd 的 RangePicker  的 onChange 事件会在 ''开始'' 和 ''结束'' 时间 选择完成以后执行该回调，而当前的 onChange 事件在选择开始和结束时候都会执行一次，一共执行了2次，不是很合理，希望修改或者再添加一个类似的事件回调

**Comment by gansong99** [comment]
解决了吗？怎么解决的
