### ISSUE TITLE
link 包在 Menu 组件下导致显示错误

### ISSUE THREAD

**Issue by fengChongxiu** [arco-design/arco-design#405]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** 2.26.0
- **系统版本:** mac
- **浏览器版本:** chrome
- **复现地址:** https://codesandbox.io/s/quizzical-frost-4i4rv?file=/index.js:763-1000

## 预期结果
高亮 item 和路径匹配

## 复现步骤
来回点击 home 和 about会导致下面这种样子
![image](https://user-images.githubusercontent.com/17736007/148371195-44b05c1b-1508-42e0-8774-eb520bd0196c.png)

**Comment by MisterLuffy** [comment]
MenuItem 的高亮状态内部是点击即切换的，可以考虑使用受控在路由变化之后再切换菜单状态。

**Comment by fengChongxiu** [comment]
> MenuItem 的高亮状态内部是点击即切换的，可以考虑使用受控在路由变化之后再切换菜单状态。

路由切换不是点击即切换的嘛，感觉应该也是个同步操作呀
