### ISSUE TITLE
size设置无效

### ISSUE THREAD

**Issue by lyndonliu89757** [arco-design/arco-design#420]
1、全局配置ConfigProvider 修改Table、Pagination的size属性无效；
2、Tabs rounded类型 size设置成mini无效。

**Comment by yinkaihui** [comment]
1. rounded 类型的tabs组件不支持size属性
2. 全局size在有些size属性比较特殊的组件确实不生效，可以通过componentConfig针对组件设置下默认属性，也会在全局所有这个组件生效
