### ISSUE TITLE
带有时间选择的 RangePicker 组件存在 bug 

### ISSUE THREAD

**Issue by busyzz-1994** [arco-design/arco-design#424]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react : 2.27.2
- **System:** macOS
- **Browser:** chrome
- **Reproduction Link:** https://codesandbox.io/s/agitated-dijkstra-7drpw?file=/src/App.js

## What is expected?
期望：不管是先选结束时间还是后选结束时间，defaultValue 的顺序保持不变

## Steps to reproduce
先选结束时间再选开始时间，点击确认以后，showTime={{ defaultValue: ["00:00", "04:05"], format: "HH:mm" }} 中的 defaultValue 顺序发生了改变

**Comment by busyzz-1994** [comment]
先点结束时间，再选择开始时间 变成了 YYYY-MM-DD 04:05 - YYYY-MM-DD 00:00  , 比如 你先选择 1月15号 再选择1月1号，变成了 2022-01-01 04:05 - 2022-01-15 00:00 , 期望的是  2022-01-01 00:00 - 2022-01-15 04:05

**Comment by busyzz-1994** [comment]
@PengJiyuan

**Comment by jiahao-c** [comment]
@busyzz-1994  根据你提供的codesandbox链接，先选择结束再选择开始，没有重现这个bug。

<img width="595" alt="image" src="https://user-images.githubusercontent.com/8275280/155045060-f8f035e2-33bb-4a5a-8c0e-9d613cfbe9d9.png">

**Comment by PengJiyuan** [comment]
> 先点结束时间，再选择开始时间 变成了 YYYY-MM-DD 04:05 - YYYY-MM-DD 00:00 , 比如 你先选择 1月15号 再选择1月1号，变成了 2022-01-01 04:05 - 2022-01-15 00:00 , 期望的是 2022-01-01 00:00 - 2022-01-15 04:05

感觉你说的应该 sort 排序之后的行为，这个是符合预期的
