### ISSUE TITLE
Anchor scroll-into-view not works with scrollContainer

### ISSUE THREAD

**Issue by MisterLuffy** [arco-design/arco-design#429]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.28.0
- **复现地址:** https://www.npmjs.com/package/compute-scroll-into-view

## 复现步骤
View the usage of compute-scroll-into-view, actions is an Array, should use actions.forEach() to justify elements scrollLeft/Top.

**Comment by MisterLuffy** [comment]
![image](https://user-images.githubusercontent.com/29861850/148923756-a08436ed-ac36-40fe-b437-4420c264cdf0.png)

**Comment by yuhan0709** [comment]
@MisterLuffy 哥哥自己修一下嘛～
