### ISSUE TITLE
Popconfirm 与 table 、tag 结合使用 ，位置不对

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design#436]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.28.0
- **Browser:** chrome97.0.4692.71
- **Reproduction Link:** https://codesandbox.io/s/crazy-visvesvaraya-mfspq?file=/index.js

## What is expected?
点击 delete ，气泡对话框位置在 delete 按钮位置

**Comment by chenc041** [comment]
你那个写法貌似不对,  因为 ```Tag``` 加了 ```closable```的话 点击之后 就直接把 ```Tag``` 标签隐藏了, 所以 ```Popcomfirm``` 就获取不到正确的位置信息了
建议改成这样
```ts
render: (col, record, index) => (
      <Popconfirm
        title="Are you sure you want to delete?"
        onOk={() => {}}
        onCancel={() => {}}
      >
        <Button>
          <span style={{ color: "#FF7D00", fontWeight: 600 }}>$</span>
          {record.salary} delete
        </Button>
      </Popconfirm>
    )
```

**Comment by lin-mt** [comment]
> ```ts
> {record.salary}
> ```

antd 是可以的哦～

**Comment by lin-mt** [comment]
> 你那个写法貌似不对, 因为 `Tag` 加了 `closable`的话 点击之后 就直接把 `Tag` 标签隐藏了, 所以 `Popcomfirm` 就获取不到正确的位置信息了 建议改成这样
> 
> ```ts
> render: (col, record, index) => (
>       <Popconfirm
>         title="Are you sure you want to delete?"
>         onOk={() => {}}
>         onCancel={() => {}}
>       >
>         <Button>
>           <span style={{ color: "#FF7D00", fontWeight: 600 }}>$</span>
>           {record.salary} delete
>         </Button>
>       </Popconfirm>
>     )
> ```

antd 是可以的哦

**Comment by chenc041** [comment]
> > 你那个写法貌似不对, 因为 `Tag` 加了 `closable`的话 点击之后 就直接把 `Tag` 标签隐藏了, 所以 `Popcomfirm` 就获取不到正确的位置信息了 建议改成这样
> > ```ts
> > render: (col, record, index) => (
> >       <Popconfirm
> >         title="Are you sure you want to delete?"
> >         onOk={() => {}}
> >         onCancel={() => {}}
> >       >
> >         <Button>
> >           <span style={{ color: "#FF7D00", fontWeight: 600 }}>$</span>
> >           {record.salary} delete
> >         </Button>
> >       </Popconfirm>
> >     )
> > ```
> 
> antd 是可以的哦

我来试试

**Comment by chenc041** [comment]
> > 你那个写法貌似不对, 因为 `Tag` 加了 `closable`的话 点击之后 就直接把 `Tag` 标签隐藏了, 所以 `Popcomfirm` 就获取不到正确的位置信息了 建议改成这样
> > ```ts
> > render: (col, record, index) => (
> >       <Popconfirm
> >         title="Are you sure you want to delete?"
> >         onOk={() => {}}
> >         onCancel={() => {}}
> >       >
> >         <Button>
> >           <span style={{ color: "#FF7D00", fontWeight: 600 }}>$</span>
> >           {record.salary} delete
> >         </Button>
> >       </Popconfirm>
> >     )
> > ```
> 
> antd 是可以的哦

我提了个 pr 来解决的这个问题, 等 他们 review 下看看吧 😁
