### ISSUE TITLE
Badge color属性只作用于dot模式的徽标，status默认作用于dot模式

### ISSUE THREAD

**Issue by xzdry** [arco-design/arco-design#452]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
使用badge组件二次封装的时候，如果传了color就默认变成dot形式的徽标会让color这个属性很有迷惑性。我认为这个属性应该同样可以作用于数字形式的badge，比如推特的数字徽标就是蓝色的      
       
同样的，status也是，设置后自动变为dot模式，之后无法通过清空status值得方式动态变回数字模式，只能delete status这个属性，这点在文档里也没有相应的说明      

个人感觉可以加一个判断，让status只在`dot=true`的时候生效来明确这一行为

## 预期解决问题
color属性可以作用于数字模式的徽标
明确status的行为

**Comment by PengJiyuan** [comment]
建议通过 style 自定义样式实现，否则改动会造成 breaking change
