### ISSUE TITLE
Table组件展开行问题

### ISSUE THREAD

**Issue by lvyou-ly** [arco-design/arco-design#453]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
https://radar2.fedev.bytedance.net/radar/session-tools?activeKey=searchBehavior&appName=news_article%2Cnews_article_lite&orderType=2&requestTime=2021-12-12%2C2022-01-10&searchQuery=%E5%AD%97%E8%8A%82%E8%B7%B3%E5%8A%A8

## 预期解决问题
1.提高展开行展开的响应速度，目前为3s
2.展开行时，之前展开过的行不希望重新触发展开

**Comment by PengJiyuan** [comment]
@lvyou-ly 链接没有权限，能详细描述一下问题吗
