### ISSUE TITLE
时间选择组件

### ISSUE THREAD

**Issue by ckmilse** [arco-design/arco-design#454]
初始值是23:59:59时，需要滚动下拉才能看到其他值

**Comment by ckmilse** [comment]
![Uploading 飞书20220117-111712.png…]()

**Comment by ckmilse** [comment]
![飞书20220117-111712](https://user-images.githubusercontent.com/10125008/149768564-142e8ac8-20c8-44a8-b679-c851357bae19.png)

**Comment by PengJiyuan** [comment]
选中的值会置顶的，符合预期
