### ISSUE TITLE
step的disabled没有禁用样式

### ISSUE THREAD

**Issue by yumenglixu** [arco-design/arco-design#461]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
分步的时候，禁用态样式看不出来区别
![tf4YLOOIyi](https://user-images.githubusercontent.com/8264828/149722338-fb00e609-0f67-47e8-b18d-4e526ca198e5.png)

**Comment by PengJiyuan** [comment]
你好，设计上没有禁用样式。
