### ISSUE TITLE
Upload picture-card 组件的 tip 会影响组件宽度，设计如此吗？

### ISSUE THREAD

**Issue by ExcitedSpider** [arco-design/arco-design#492]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.28.2
- **Browser:** chrome97.0.4692.71
- **Reproduction Link:** https://codepen.io/excitedqe/pen/dyZbWZK?editors=001

![image](https://user-images.githubusercontent.com/35751871/150772513-4bcdfc8f-d1c5-4aeb-b937-d645e1bb46bd.png)

## What is expected?
我感觉交互上来说卡片宽度不应该被影响，并且 tip 应该一直在左侧

**Comment by yinkaihui** [comment]
你好，没有预期到 tip 在 picture-card 下生效的场景，这个地方我们优化调整下
