### ISSUE TITLE
用fontSize属性修改图标大小，然后用Space组件进行分隔，设置align="center"，垂直居中，发现图标有一点往上偏移

### ISSUE THREAD

**Issue by shixinxin1111** [arco-design/arco-design#495]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.28.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://codepen.io/shixinxin1111/pen/PoJreEx?editors=0010

## Extra info
用fontSize属性修改图标大小，然后用Space组件进行分隔，设置align="center"，垂直居中，发现图标有一点往上偏移，前面那个是用原生的flex布局写的，没有偏移，这是什么原因？

## What is expected?
希望可以垂直居中

## Steps to reproduce
用fontSize属性修改图标大小，然后用Space组件进行分隔，设置align="center"，垂直居中，发现图标有一点往上偏移，前面那个是用原生的flex布局写的，没有偏移，这是什么原因？

**Comment by ai977313677** [comment]
看上去像是垂直对齐的问题，可以试试图表的 `style={{ verticalAlign: 'midlle' }}` 这样

**Comment by PengJiyuan** [comment]
这个其实是 arco-space-item 这一个div中，icon没有垂直居中。给这个类加一下 `display: flex; align-items: center`。
