### ISSUE TITLE
[Image.Preview] "1:1" button doesn't work correctly

### ISSUE THREAD

**Issue by webzhao** [arco-design/arco-design#499]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.28.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://codepen.io/webzhao/pen/wvPBEEr

## What is expected?
Image should be displayed as its original size 658×2047

## Steps to reproduce
1. Open the Reproduction link
2. Click "1:1" button

**Comment by yuhan0709** [comment]
This is expected, the image size will be limited by the container size
