### ISSUE TITLE
Popover在特定组件时无法显示

### ISSUE THREAD

**Issue by imjonat** [arco-design/arco-design#506]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.28.2
- **系统版本:** Mac12.0
- **浏览器版本:** chrome97.0.4692.99
- **复现地址:** https://codesandbox.io/s/eager-noyce-sq24n?file=/index.js

## 预期结果
左侧组件理应可以展示popover

## 复现步骤
可见左边popover无法展示popover内容，右侧可以

**Comment by yinkaihui** [comment]
![image](https://user-images.githubusercontent.com/23161413/152737249-1d116267-9298-4c2c-8b32-0b3848432470.png)

你好自定义组件需要接收 Popover 注入的props，类组件也同样～

**Comment by imjonat** [comment]
> ![image](https://user-images.githubusercontent.com/23161413/152737249-1d116267-9298-4c2c-8b32-0b3848432470.png)
> 
> 你好自定义组件需要接收 Popover 注入的props，类组件也同样～

非常感谢同事的解答~同时希望可以在官网有注明~
