### ISSUE TITLE
文档文案错误

### ISSUE THREAD

**Issue by Tyresee** [arco-design/arco-design#508]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.28.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://github.com/arco-design/arco-design/blob/845dee21a0f9effd44edb3485d92ee7680fa21f2/site/docs_spec/philosophy.zh-CN.md

## What is expected?
“包容开放的体系才能浪漫的解决问题。” 中的第二个“的”应该改成“地”

**Comment by yinkaihui** [comment]
欢迎提 PR 呀
