### ISSUE TITLE
Tooltip 的 delay 属性在受控模式下不生效

### ISSUE THREAD

**Issue by elaine1234** [arco-design/arco-design#510]
React 版本的 Arco， Tooltip 的 delay 属性( mouseEnterDelay & mouseLeaveDelay ) 在受控模式下不生效
详情可见以下 demo👇🏻
 https://codepen.io/elaine1100/pen/jOaVoYE?editors=001

希望在受控模式下 delay 仍然生效

**Comment by chenc041** [comment]
`Tooltip` 是不支持 `mouseEnterDelay` 和 `mouseLeaveDelay` 这两个属性的
所以不管是不是受控,  `delay` 都不会生效
`mouseEnterDelay` 和 `mouseLeaveDelay` 这两个属性只在 `Trigger` 上可用

**Comment by yinkaihui** [comment]
可以通过 `triggerProps={{mouseEnterDelay: xx}}` 传入

**Comment by chenc041** [comment]
> 可以通过 `triggerProps={{mouseEnterDelay: xx}}` 传入

为啥不设计成作为在 `Tooltip` 的 props, 而是提供了这种直接覆盖底层组件属性的方式?
感觉很奇怪啊 😂

**Comment by PengJiyuan** [comment]
> > 可以通过 `triggerProps={{mouseEnterDelay: xx}}` 传入
> 
> 为啥不设计成作为在 `Tooltip` 的 props, 而是提供了这种直接覆盖底层组件属性的方式? 感觉很奇怪啊 😂

主要为了增强对底层弹出逻辑的控制，所有Trigger参数都可定制
