### ISSUE TITLE
Select maxTagCount 响应式 超出自动省略

### ISSUE THREAD

**Issue by lastSeries** [arco-design/arco-design#536]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
https://codesandbox.io/s/46ijh

## What problem does this feature solve?
多选下通过响应式布局让选项自动收缩

**Comment by MisterLuffy** [comment]
我们不准备在组件内部支持此特性，建议通过对 Select 进行二次封装以实现此功能。
