### ISSUE TITLE
Tab里面使用Table的分页器sizeChange，可能会存在隐藏的问题

### ISSUE THREAD

**Issue by ai977313677** [arco-design/arco-design#537]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.28.1
- **Browser:** chrome98.0.4758.80
- **Reproduction Link:** https://codesandbox.io/s/serverless-smoke-bm7bm?file=/index.js

## What is expected?
展示选框弹出选项内容

## Steps to reproduce
在Tab下的table中仅一条数据（多条也行，但需要保证高度）时，点击分页器的更改页大小的选框，弹出的内容会被遮住。

**Comment by ai977313677** [comment]
提供的codesandbox示例中，点击选择框，可以发现没有看到弹出选项。

但实际已经弹出来了，只不过因为超出了TabPane容器的高度，所以被遮住了。可以通过检查元素看到对应的弹出层。

**Comment by PengJiyuan** [comment]
可以把弹出框的容器设置成别的，这里 TabPanel 的 overflow: hidden 会遮挡
