### ISSUE TITLE
[feature request] InputNumber 组件支持 autoComplete 属性

### ISSUE THREAD

**Issue by xxleyi** [arco-design/arco-design#543]
目前业务中 QA 提出 InputNumber 组件下，浏览器的自动补全干扰正常使用，希望能够禁用。

但是 Arco  InputNumber 不支持 autoComplete 属性，同时 Input 组件已经做了支持，所以希望 InputNumber 组件也能支持一下。

**Comment by ai977313677** [comment]
感觉这个可以用Input实现InputNumber的功能

**Comment by MisterLuffy** [comment]
可以尝试直接使用 `AutoComplete` 组件？数字输入框的自动补全感觉很奇怪。

**Comment by xxleyi** [comment]
> 可以尝试直接使用 `AutoComplete` 组件？数字输入框的自动补全感觉很奇怪。

因为 InputNumber 内部还是原生 input，浏览器会会尝试添加自动补全。正是因为数字输入场景的自动补全很奇怪，所以 QA 提了 bug。所以希望 Arco 支持 InputNumber 接受 autoComplete 属性，业务上就可以传 off 来关闭它。

**Comment by yinkaihui** [comment]
你好，在 `2.27.0` 里 `InputNumber` 应该已经支持了接收 `Input` 全部的属性
<img width="829" alt="image" src="https://user-images.githubusercontent.com/23161413/155454754-14084bdb-d3e9-4493-ae66-67f5163d7a24.png">

**Comment by xxleyi** [comment]
@yinkaihui thanks!
