### ISSUE TITLE
Form.Item + DatePicker.WeekPicker 无法设置值

### ISSUE THREAD

**Issue by a8655099449** [arco-design/arco-design#553]
描述：
在formItem里面，DatePicker.WeekPicker无法设置值
```js
import { DatePicker, Form } from "@arco-design/web-react";
import React from "react";

export default function DatePickerWeek() {
  return (
    <Form>
      <Form.Item label="选择周" required field={`aaa`}>
        <DatePicker.WeekPicker />
      </Form.Item>
    </Form>
  );
}
```
`  "@arco-design/web-react": "^2.28.2",`

**Comment by a8655099449** [comment]
![动画2](https://user-images.githubusercontent.com/58685483/154886835-cd09e05d-6c68-4bc7-9626-73c0e6f1f200.gif)

问题如图所示

**Comment by yinkaihui** [comment]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/23161413/155471580-5e3f934d-c8ae-4b79-84a7-2ee66b8eceaa.png">
试一下这样呢

**Comment by quanru** [comment]
这个还没有解决吗？
