### ISSUE TITLE
Form中的TreeSelect设置labelInValue属性为true，自定义treeNode的title为ReactNode类型时报错

### ISSUE THREAD

**Issue by Amy-zsy** [arco-design/arco-design#558]
![image](https://user-images.githubusercontent.com/33154660/154661001-9280b095-e077-441a-aa5a-b5c6e7a22744.png)
<img width="897" alt="Screen Shot 2022-02-18 at 18 02 49" src="https://user-images.githubusercontent.com/33154660/154661085-4e6666f3-b527-4a5b-a086-ef05308efa37.png">

**Comment by yuhan0709** [comment]
复现地址在这里～ `iterativelyGetKeys` 那个函数 `obj` 判断要过滤一下是 `ReactNode` 的情况。https://codepen.io/yuhan0709/pen/abVqNQY?editors=0010

**Comment by jiahao-c** [comment]
> 复现地址在这里～ `iterativelyGetKeys` 那个函数 `obj` 判断要过滤一下是 `ReactNode` 的情况。https://codepen.io/yuhan0709/pen/abVqNQY?editors=0010

@yuhan0709 试着用了下复现地址，没看到console报 `maximum call stack size exceeded` 这个错呀？我试着点击了每个选项，也没有出现这个问题，都正常log出来了：
<img width="814" alt="image" src="https://user-images.githubusercontent.com/8275280/156870196-bc6dc8bf-0d7f-4e5f-a3a2-a9a3270d0252.png">

请问是我复现方式不对吗？
