### ISSUE TITLE
全屏状态下，Dropdown 下拉菜单不可见～

### ISSUE THREAD

**Issue by yaogengzhu** [arco-design/arco-design#559]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.27.0
- **System:** mac
- **Browser:** chrome98.0.4758.80
- **Reproduction Link:** [s.yaogeng.top](https://s.yaogeng.top/)

## What is expected?
全屏状态，下拉菜单可见

## Steps to reproduce

非全屏状态---

<img width="216" alt="image" src="https://user-images.githubusercontent.com/42566669/154686963-32190ca1-a63f-4e20-a1bc-0bc31d5aeb4a.png">

全屏状态

<img width="231" alt="image" src="https://user-images.githubusercontent.com/42566669/154687186-0aa3ad43-3669-4be6-9c61-3a4d84bfb7bf.png">

**Comment by chenc041** [comment]
最好可以提供一个最小可复现的仓库, 包含代码的那种

**Comment by yaogengzhu** [comment]
> 最好可以提供一个最小可复现的仓库, 包含代码的那种

可以提供代码！演示全屏不了。https://codesandbox.io/s/boring-meadow-hfp66p?file=/src/App.js

**Comment by chenc041** [comment]
> https://codesandbox.io/s/boring-meadow-hfp66p?file=/src/App.js

改成 ` const [, { toggleFullscreen }] = useFullscreen(() => document.documentElement);` 就可以了
但是为什么在 root 会导致 dropdown menu 没有弹出, 这个我也不是很清楚 😂

**Comment by chenc041** [comment]
> > 最好可以提供一个最小可复现的仓库, 包含代码的那种
> 
> 可以提供代码！演示全屏不了。https://codesandbox.io/s/boring-meadow-hfp66p?file=/src/App.js

个人觉得除非是 video 这样的元素, 否则都应该放在根元素也就是 [documentElement](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/documentElement) 上
