### ISSUE TITLE
Support press enter to confirm

### ISSUE THREAD

**Issue by CherishIt** [arco-design/arco-design#56]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
Enter to confirm is normal behaviour

## 预期解决问题
Add the ability to confirm or submit a Modal using keyboard.

Proposed methods：
1. focus on ok button by default
or
2. add a boolean prop "enterToConfirm" as "escToExit" is already implemented

**Comment by PengJiyuan** [comment]
Thanks for your suggestion, currently the button doesn't have a focus style, so that the current focus button cannot be seen when the tab is switched. We will add the focus style of the button later, and then focus on the confirm button by default.

**Comment by PengJiyuan** [comment]
Add button focus style
