### ISSUE TITLE
使用babel-plugin-import 自动导入的style后， 无法使用modifyVars 定制主题

### ISSUE THREAD

**Issue by Pmj136** [arco-design/arco-design#573]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
babel-plugin-import

## What problem does this feature solve?
1、经过我的分析，css.js 导入的是 ./index.css ，也就是编译好的less，因此无法改变主题。
如果要使modifyVars定义主题生效，需要导入index.less，less才可以，不能使用编译好的css
2、解决方案：因此我自定义一个路径 style:name=> `@arco-design/web-react/es/${ name }/style/index.less`，但是还需要在main.tsx： import '@arco-design/web-react/es/style/index.css' 在能使用完整的样式
3、这样一来，就感觉多了一些步骤，所以希望官方将css.js中的样式改为index.less，不知道有什么问题

**Comment by yinkaihui** [comment]
和 `css.js` 同级有个 `index.js`，这个是引入的 less 文件。
