### ISSUE TITLE
Modal中的popup会限制在弹窗窗口范围内，很丑

### ISSUE THREAD

**Issue by claneo** [arco-design/arco-design#578]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.29.1
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://codesandbox.io/s/quirky-joana-f3eimk?file=/index.js

## Extra info

Modal 内默认设置的 getPopupContainer 是 content，导致 popup 会被局限在这个范围内

![image](https://user-images.githubusercontent.com/11372744/155445687-700143a9-fdf8-4189-8ad7-837e27a26fa9.png)

https://github.com/arco-design/arco-design/blob/3282079ee297ae8f0f0f7d5b6cc79d0f6429246b/components/Modal/modal.tsx#L235-L249

如果换成外层的 modal-wrapper，效果会好很多

![image](https://user-images.githubusercontent.com/11372744/155445830-34771866-ac8d-4172-a5da-7b7e828dda02.png)

## What is expected?
popup可以操出弹窗的范围

**Comment by claneo** [comment]
还有 Drawer

**Comment by chenc041** [comment]
`Tooltip` 和 `Drawer` 都是支持自定义挂载点的, 可以看下 `getPopupContainer` 这个属性
比如你这个就可以改成这样
```ts
function Demo() {
  const ref = useRef(null);
  return (
    <div>
      <Modal
        visible={true}
        autoFocus={false}
        focusLock={false}
        ref={ref}
        style={{ width: 200 }}
        // getChildrenPopupContainer={() => document.querySelector(".arco-modal-wrapper")}
      >
        <Tooltip
          popupVisible
          content={
            <span style={{ whiteSpace: "normal" }}>
              long long long long long long long long long long long long long
              long long long long long long long long long long long long long
              long
            </span>
          }
          getPopupContainer={() => ref.current}
        >
          <span>Hover me</span>
        </Tooltip>
      </Modal>

      <Tooltip content="long long long long long long long long long long long long long long long long long long long long long long long long long long long">
        <span>Hover me</span>
      </Tooltip>
    </div>
  );
}
```

![截屏2022-02-24 上午10 39 39](https://user-images.githubusercontent.com/16097887/155447091-8afba906-bfd5-4c63-95c6-935cdbc65a73.png)

**Comment by claneo** [comment]
嗯，我上面第二个截图就是加了 getChildrenPopupContainer，我意思是能不能改下默认的行为，要不然改每个地方的代码太累了

如果之前的行为没什么特殊考虑的话

**Comment by chenc041** [comment]
我觉得可以考虑下 
等内部沟通下 这个问题哈 😁

**Comment by yinkaihui** [comment]
> 嗯，我上面第二个截图就是加了 getChildrenPopupContainer，我意思是能不能改下默认的行为，要不然改每个地方的代码太累了
> 
> 如果之前的行为没什么特殊考虑的话

看下 `ConfigProvider` 组件的[ `componentConfig` 属性](https://arco.bytedance.net/react/components/config-provider#%E7%BB%84%E4%BB%B6%E9%85%8D%E7%BD%AE)，可以全局配置所有组件的默认属性

**Comment by chenc041** [comment]
应该这么改一下 就不需要每个地方改了
https://codepen.io/chenc041/pen/KKyBJNR?editors=0010

**Comment by claneo** [comment]
> 默认行为是不好改了, 需要考虑向下兼容的问题 然后全局配置这么改一下就不需要每个地方再改了, https://codepen.io/chenc041/pen/KKyBJNR?editors=0010

嗯，思路了解了。这里其实需要更复杂一点，从当前节点向上寻找到最近的 .arco-modal-wrapper，否则没法处理多个 Modal 的情况

**Comment by chenc041** [comment]
> > 默认行为是不好改了, 需要考虑向下兼容的问题 然后全局配置这么改一下就不需要每个地方再改了, https://codepen.io/chenc041/pen/KKyBJNR?editors=0010
> 
> 嗯，思路了解了。这里其实需要更复杂一点，从当前节点向上寻找到最近的 .arco-modal-wrapper，否则没法处理多个 Modal 的情况

多个modal 的情况我有个思路是把modal 的 body 动态替换就好了
比如这样
```ts
import "@arco-design/web-react/dist/css/arco.css";
import { Modal } from "@arco-design/web-react";

const App = () => {

  const renderModalBody = (type: string) => {
    switch (type) {
      case 'name':
        return <div>2323</div>
      case  'age':
        return  <div>age</div>
      default:
        return null;
    }
  }

  return (
    <>
      <Modal>
        {renderModalBody('name')}
      </Modal>
    </>
  );
};

export default App

```

**Comment by claneo** [comment]
> 

然后 getChildrenPopupContainer 去找这个 renderModalBody？那 popup 又被限制在 Modal 内容里了。。。

**Comment by chenc041** [comment]
> > 
> 
> 然后 getChildrenPopupContainer 去找这个 renderModalBody？那 popup 又被限制在 Modal 内容里了。。。

你先全区配置好
再用下边的方法 在当前不就是不会存在多个 modal 的情况了...
那自然 也就不用处理 你说的  `从当前节点向上寻找到最近的 .arco-modal-wrapper` 的问题了呀

**Comment by chenc041** [comment]
> > > 
> > 
> > 
> > 然后 getChildrenPopupContainer 去找这个 renderModalBody？那 popup 又被限制在 Modal 内容里了。。。
> 
> 你先全局配置好 再用下边的方法 在当前不就是不会存在多个 modal 的情况了... 那自然 也就不用处理 你说的 `从当前节点向上寻找到最近的 .arco-modal-wrapper` 的问题了呀

**Comment by claneo** [comment]
但是多个 Modal 的情况确实需要存在的，否则只是简单替换内容的话，里面组件的状态都丢了

**Comment by chenc041** [comment]
> 但是多个 Modal 的情况确实需要存在的，否则只是简单替换内容的话，里面组件的状态都丢了

modal 状态丢失不是应该的吗?
就拿编辑来说 每次打开弹窗 不都应该是重置状态吗?
你说的保留状态 是啥场景啊?

**Comment by claneo** [comment]
比如 A Modal 正在编辑表单，然后里面有个操作需要弹出 B Modal，里面可能是个确认操作，可能是更进一步的编辑操作。这时候 A Modal 的内容就消失了

**Comment by chenc041** [comment]
> 比如 A Modal 正在编辑表单，然后里面有个操作需要弹出 B Modal，里面可能是个确认操作，可能是更进一步的编辑操作。这时候 A Modal 的内容就消失了

是这么个情况
实在不行 把 modal 再包一层, 然后在使用的时候传个新的 className 进去

**Comment by chenc041** [comment]
没啥新问题 issue 关掉了哈 
有新问题 再沟通
