### ISSUE TITLE
Drawer auto focus on button it's unexception

### ISSUE THREAD

**Issue by makmav** [arco-design/arco-design#580]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.29.1
- **System:** macOS
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://codesandbox.io/s/loving-leavitt-toijg1?file=/index.js

## What is expected?
click open drawer 
show top content

## Steps to reproduce
1. click open drawer
2. the scroll auto scroll to the button posotion

**Comment by PengJiyuan** [comment]
`autoFocus` 设置为 `false`，全局设置可以通过 ConfigProvider 组件。
