### ISSUE TITLE
输入滑动条tips覆盖标题栏问题

### ISSUE THREAD

**Issue by yehuo** [arco-design/arco-design#582]
## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.29.1
- **System:** Ubuntu
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://arco.design/react/components/slider#%E6%8E%A7%E5%88%B6%20tooltip%20%E7%9A%84%E5%B1%95%E7%A4%BA

## What is expected?
滑动输入条被拉到标题栏上方后，tooltip默认应当被隐藏

## Steps to reproduce
向上拉动页面时候，tooltip会覆盖到标题栏上方，而此时滑动条已经不可拉动

**Comment by yuhan0709** [comment]
Hello 这个是符合预期的，因为tooltip的打开关闭时有一个动画的，会持续一小段时间。

**Comment by Siton2100** [comment]
> Hello 这个是符合预期的，因为tooltip的打开关闭时有一个动画的，会持续一小段时间然后完全关闭

Thanks

**Comment by yehuo** [comment]
Thanks for reply.
