### ISSUE TITLE
Input.Password 组件无法通过 ConfigProvider 配置全局默认属性

### ISSUE THREAD

**Issue by xxleyi** [arco-design/arco-design#583]
而且 Input 组件配置的全局属性还会作用到 Input.Password 上

**Comment by PengJiyuan** [comment]
> 而且 Input 组件配置的全局属性还会作用到 Input.Password 上

因为Input.Password 底层用的就是 Input，所以Input的全局属性会生效。

**Comment by xxleyi** [comment]
> > 而且 Input 组件配置的全局属性还会作用到 Input.Password 上
> 
> 因为Input.Password 底层用的就是 Input，所以Input的全局属性会生效。

这样子啊，业务中希望给 password 传 autocomplete=new-password 的 默认值，那看来只能自己去覆盖了
