### ISSUE TITLE
【Feature】Select 支持分组全选功能 for `Select.OptGroup`

### ISSUE THREAD

**Issue by fz6m** [arco-design/arco-design#585]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
特别是在 分组很多 选项很多 的场景，可以很好的处理一组一组数据

## What problem does this feature solve?
目前只支持单项的多选勾选，期望分组后，也可以一次性选择一个组，这样会非常方便

**Comment by MisterLuffy** [comment]
建议通过受控模式来扩展此功能，我已经提供了一个带有全选功能的[ Select 物料](https://arco.design/material/detail?name=@arco-materials/select-with-check-all)，具体实现可参考[源码](https://github.com/MisterLuffy/arco-select-plus/blob/main/packages/select-with-check-all/src/index.tsx)。

**Comment by fz6m** [comment]
> Select 物料

谢谢，你写的真好 🥰 。
