### ISSUE TITLE
form中的type是number的校验，带空格的值也可以通过校验，form内是input，不是inpuitnumber

### ISSUE THREAD

**Issue by rfangjiayou** [arco-design/arco-design#601]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.29.2
- **Browser:** chrome96.0.4664.110
- **Reproduction Link:** https://codepen.io/pen?&editors=001

## What is expected?
带空格的值不能通过校验

**Comment by chenc041** [comment]
https://codepen.io/pen?&editors=001 这个链接里内容挂了 重新补一个吧
