### ISSUE TITLE
rounded tabs 不同尺寸没有区别

### ISSUE THREAD

**Issue by MiloWang2048** [arco-design/arco-design#603]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.29.2
- **系统版本:** macOS
- **浏览器版本:** chrome97.0.4692.99
- **复现地址:** https://arco.bytedance.net/react/components/tabs

## 预期结果
跟其他一样，有大小区分

## 复现步骤
在「不同尺寸」面板下，type选择rounded，四种尺寸没有区别

**Comment by MiloWang2048** [comment]
设计问题不算问题？
text和rounded都没有区分大小

**Comment by yinkaihui** [comment]
抱歉，这个设计资源里后续补充了 rounded 类型区分尺寸，组件库之后会支持下。 文本类型的 tabs 只有文字和背景色， 应该不需要区分尺寸 ？

**Comment by MiloWang2048** [comment]
文字尺寸也算尺寸的一部分吧？还是希望尽可能考虑周全，或者在文档里标注一下
