### ISSUE TITLE
modal里的单选按钮偏移

### ISSUE THREAD

**Issue by q774221810** [arco-design/arco-design#620]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.30.0
- **Browser:** chrome98.0.4758.109
- **Reproduction Link:** https://codesandbox.io/s/purple-waterfall-p4n9j4?file=/index.js

## What is expected?
不要偏移

**Comment by q774221810** [comment]
![image](https://user-images.githubusercontent.com/66249292/157160295-8a7f7b95-3f26-42a5-a695-25da80695369.png)

**Comment by yuhan0709** [comment]
不好意思我这里没有复现诶
<img width="575" alt="image" src="https://user-images.githubusercontent.com/23137528/157577650-067e9d0a-a4c0-4267-8e40-fde0f72177d7.png">
