### ISSUE TITLE
The animation attribute of select is true, but there is no animation effect when adding tag

### ISSUE THREAD

**Issue by DAHUIAAAAA** [arco-design/arco-design#622]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.30.0
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://arco.design/react/components/select

## What is expected?
Repair animation. If you can, can you provide an interface that can customize animation?

**Comment by MisterLuffy** [comment]
Version `2.27.0` caused this bug.
