### ISSUE TITLE
表格分组表头支持fixed

### ISSUE THREAD

**Issue by liunana1230** [arco-design/arco-design#636]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
表头分组后不能固定列

**Comment by PengJiyuan** [comment]
应该是可以的吧，前提是固定的列是rowSpan撑满的。你可以提供一个codesandbox看看
