### ISSUE TITLE
Table组件在filterDropdown使用DatePicker无法筛选

### ISSUE THREAD

**Issue by Qinruiy** [arco-design/arco-design#639]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.30.1
- **System:** MacOSX
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://codesandbox.io/s/festive-dust-0v7nfk?file=/src/App.tsx

## What is expected?
DatePicker能筛选日期

## Steps to reproduce
点击日期筛选
选择日期

**Comment by PengJiyuan** [comment]
![image](https://user-images.githubusercontent.com/19399269/158508276-a9cc5ed9-583c-4261-98a7-fb68408649d1.png)

confirm 可以接收参数，立即触发筛选
