### ISSUE TITLE
All `triggerElement` should expose current option

### ISSUE THREAD

**Issue by lianghx-319** [arco-design/arco-design#641]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Just DX improvement, because sometimes we don't need controlled input, but we need to custom triggerElement!

## What problem does this feature solve?
Nowadays if want to custom `triggerElement` for `Select` component, the only way to get current option is storing the current option in state, so props `triggerElement` in all `Select` likes components, should expose current option, then we can access current option like `(option) => <TriggerElement.option={options} />`

**Comment by lianghx-319** [comment]
In this case, this is no way to display current option

```ts
import { Select } from '@arco-design/web-react';
import { SelectorTrigger } from './SelectorTrigger';

export const TimeGranularitySelector = () => {
  return <Select {...{ triggerElement: <SelectorTrigger value={???}></SelectorTrigger> }} />;
};
```

I think is should provide another way to define `triggerElement` like this

```ts
import { Select } from '@arco-design/web-react';
import { SelectorTrigger } from './SelectorTrigger';

export const TimeGranularitySelector = () => {
  return <Select {...{ triggerElement: (currentOption) => <SelectorTrigger value={option.label}></SelectorTrigger> }} />;
};
```

**Comment by ExcitedSpider** [comment]
Same for me. It really need a render-prop pattern api.

**Comment by MisterLuffy** [comment]
`triggerElement` appears in AutoComplete/Select/TreeSelect/DatePicker. Check them all.
