### ISSUE TITLE
是否可以实现可编辑的表格

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design#642]
arco-design的技术选型，设计风格都极大的满足了我的使用需求。
但是在学习它的过程中遇到了些难题，请问表格组件有数据可编辑功能么，我觉得这是挺常用的需求的，但不知道为什么各个UI框架都没有类似的封装。

**Comment by hehehai** [comment]
可以自己实现下，官网案例

https://arco.design/react/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E5%8D%95%E5%85%83%E6%A0%BC

**Comment by hehehai** [comment]
@yymjku18 你好，可以自己实现下，官网案例

https://arco.design/react/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E5%8D%95%E5%85%83%E6%A0%BC

**Comment by yymjku18** [comment]
> 
非常感谢，确实很好的实现了我的需求，可是我用的是VUE的话该怎么办呢。VUE那边给的案例都还比较少

**Comment by yymjku18** [comment]
@hehehai 非常感谢，确实很好的实现了我的需求，可是我用的是VUE的话该怎么办呢。VUE那边给的案例都还比较少

**Comment by PengJiyuan** [comment]
> > 
> 
> 非常感谢，确实很好的实现了我的需求，可是我用的是VUE的话该怎么办呢。VUE那边给的案例都还比较少

@yymjku18 可以去 [vue 仓库](https://github.com/arco-design/arco-design-vue) 提 issue 哈～
