### ISSUE TITLE
Table组件开启虚拟滚动时，能支持固定列

### ISSUE THREAD

**Issue by Jiyp** [arco-design/arco-design#644]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
当前开启虚拟滚动时，不支持固定列

## 预期解决问题
Table组件开启虚拟滚动时，能支持固定列

**Comment by zyw-981204** [comment]
预计会在啥时候发官方版

**Comment by PengJiyuan** [comment]
这个本周聊了一下，进入日程了，预计下个 `2.33.0`
