### ISSUE TITLE
Form 设置初始值的问题

### ISSUE THREAD

**Issue by Tenodec** [arco-design/arco-design#645]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.29.1
- **浏览器版本:** chrome99.0.4844.51
- **复现地址:** https://codesandbox.io/s/late-tree-g3zfhz?file=/src/App.tsx

## 预期结果
赋值成功

**Comment by chenc041** [comment]
改成这样, 亲测有效
```ts
<Button
    onClick={() => {
      form.setFieldsValue({ group: [2] });
    }}
  >
    button
</Button>
```
或者
```ts
<Button
    onClick={() => {
      form.setFieldsValue({ group: ['two'] });
    }}
  >
    button
</Button>
```
