### ISSUE TITLE
对 trigger/tooltip/popover 增加一个 API：当检测到页面滚动的时候，关闭 popup

### ISSUE THREAD

**Issue by dongskyler** [arco-design/arco-design#652]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
N/A

## What problem does this feature solve?
- 当 tooltip/popover 在表单 cell 内（默认 getPopupContainer={() => document.body}），表单内横向滚动的时候，tooltip/popover 不随着横向滚动而滚动。

- 如果设置 getPopupContainer={(triggerNode) => triggerNode.parentNode} 的话，tooltip/popover 会随着表单横向滚动。但是，表单第一行触发的 popover 会被 overflow: hidden 截断。

- 所以，可能的最简单的方案是：当监听到滚动的时候，隐藏 trigger/tooltip/popover 的 popup。

- 因此建议：对 trigger/tooltip/popover 增加一个 API（boolean）：当检测到页面滚动的时候，关闭 popup。

**Comment by yinkaihui** [comment]
之后会支持监听滚动元素更新弹出层位置，让弹出层跟随滚动
