### ISSUE TITLE
disabled button 作为子元素时，Trigger 无法透传 className 到真正的元素上

### ISSUE THREAD

**Issue by logcas** [arco-design/arco-design#659]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.30.2
- **Browser:** chrome90.0.4430.93
- **Reproduction Link:** https://codesandbox.io/s/sharp-darwin-91rdk1?file=/src/App.tsx

## What is expected?
Then className passed appears in `<button disabled />`, not in `<span />`.

## Steps to reproduce
1. Wrap a Disabled Button with Trigger or Tooltip
2. Pass a classname to Button
3. The classname appears in `<span />`, not in `<button disabled />`

**Comment by logcas** [comment]
是有意为之？那怎么把类名传到对应的位置呢

**Comment by PengJiyuan** [comment]
> 是有意为之？那怎么把类名传到对应的位置呢

有意为之，为了解决禁用的表单元素无法符合预期的处理click hover 等事件。className传到外层span，可以这样写样式吧。
```css
.x .arco-button,
.x {
  width: 100%;
}
```
