### ISSUE TITLE
InputNumber 的 formatter 和 parser不生效

### ISSUE THREAD

**Issue by gezichenshan** [arco-design/arco-design#661]
version: "@arco-design/web-react": "^2.30.1"

看官网示例是生效的, 自己用不生效.

**Comment by chenc041** [comment]
给个复现的 codesandbox 地址吧

**Comment by gezichenshan** [comment]
@chenc041 https://codesandbox.io/s/small-breeze-oji34n?file=/src/App.js
谢谢!

**Comment by chenc041** [comment]
> @chenc041 https://codesandbox.io/s/small-breeze-oji34n?file=/src/App.js 谢谢!

你这是个空的哎
把你本地不起做用的代码放上去?

**Comment by gezichenshan** [comment]
@chenc041 再试试,我现在把codesandbox的默认的代码删了.

**Comment by chenc041** [comment]
> 

你正则写错了 
换成这个试试
```ts
formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
```

**Comment by gezichenshan** [comment]
@chenc041 现在对了! cool!
正则拿来主义抄的官网的! 可能也需要改一下!

**Comment by chenc041** [comment]
> @chenc041 现在对了! cool! 正则拿来主义抄的官网的! 可能也需要改一下!

我这就是官网的....

**Comment by gezichenshan** [comment]
@chenc041 我看到的是 `formatter={(value) => `${value}`.replace(/B(?=(d{3})+(?!d))/g, ',')}`

**Comment by gezichenshan** [comment]
@chenc041 我看到的是 `formatter={(value) => `${value}`.replace(/B(?=(d{3})+(?!d))/g, ',')}`

**Comment by chenc041** [comment]
> @chenc041 我看到的是 `formatter={(value) => `${value}`.replace(/B(?=(d{3})+(?!d))/g, ',')}`

不好意思 还真是
官网是有问题, 但源码里边是好的
我来看看咋回事哈
