### ISSUE TITLE
缺少图片拖拽排序功能

### ISSUE THREAD

**Issue by frontendhz** [arco-design/arco-design#664]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
比如上传一系列图片后可以通过拖拽的方式调整图片的顺序；

## What problem does this feature solve?
图片拖拽排序

**Comment by yinkaihui** [comment]
你好，上传列表的每一项都是可以自自定义的，可以使用第三方的拖拽来实现拖拽排序。
