### ISSUE TITLE
"dev:site": "arco-scripts dev:site --port 9000" 无法完成调试编译

### ISSUE THREAD

**Issue by hqz1989** [arco-design/arco-design#669]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.30.2
- **System:** Windows 10
- **Browser:** chrome86.0.4240.198
- **Reproduction Link:** https://codesandbox.io

## Extra info
yarn run v1.22.17
$ arco-scripts dev:site --port 9000
[arco-scripts]: [                    ] 0% (0.0 seconds)i ｢wds｣: Project is running at http://127.0.0.1:9000/ 
i ｢wds｣: webpack output is served from undefined                                                                                          
i ｢wds｣: Content not from webpack is served from M:\arco-design\node_modules\@arco-design\arco-scripts\lib\config\webpack\dist 
i ｢wds｣: 404s will fallback to /index.html                                                                                                
 [arco-scripts]  Starting server on http://127.0.0.1:9000 
[arco-scripts]: [=====               ] 25% (0.7 seconds)i ｢wdm｣: wait until bundle finished: / 
[arco-scripts]: [===========         ] 54% (5.4 seconds)TypeError: Cannot read properties of undefined (reading 'lang')                    
    at getMetaFromMd (M:\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\getMeta.js:94:66)                  
    at M:\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\getMeta.js:114:20                                 
    at Array.map (<anonymous>)                                                                                                             
    at default_1 (M:\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\getMeta.js:111:28)                     
    at compileDemo (M:\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\compiler\demo.js:116:44)             
    at Object.loaderForArcoComponentDoc (M:\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\index.js:43:34) 
    at Object.default_1 (M:\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\index.js:184:37)                
    at LOADER_EXECUTION (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:119:14)                                  
    at runSyncOrAsync (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:120:4)                                     
    at iterateNormalLoaders (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
出现大量上面信息；

还有下面错误信息：
ERROR in ./node_modules/@arco-materials/site-footer/es/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules\@arco-materials\site-footer\es'

ERROR in ./node_modules/@arco-materials/site-navbar/es/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules\@arco-materials\site-navbar\es'

ERROR in ./src/index-en.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/en-US' in 'M:\arco-design\site\src'

ERROR in ./src/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/zh-CN' in 'M:\arco-design\site\src'
i ｢wdm｣: Failed to compile.

## What is expected?
无

**Comment by MisterLuffy** [comment]
手头没有 windows 的开发环境，看起来像是 Webpack 解析依赖失败了，可以尝试更改一下 [Webpack 配置](https://github.com/arco-design/arco-design/blob/main/.config/webpack.config.js#L79)。如果发现原因需要修改的话，欢迎提 PR。

**Comment by hqz1989** [comment]
恩，我也判断是Webpack配置在Windows 10上的问题。我用linux做对比排下错，试试～

**Comment by hqz1989** [comment]
@MisterLuffy 
yarn run v1.22.17
$ arco-scripts dev:site --port 9000
[arco-scripts]: [ ] 0% (0.0 seconds)i ｢wds｣: Project is running at http://127.0.0.1:9000/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from M:\arco-design\node_modules@arco-design\arco-scripts\lib\config\webpack\dist
i ｢wds｣: 404s will fallback to /index.html
[arco-scripts] Starting server on http://127.0.0.1:9000/
[arco-scripts]: [===== ] 25% (0.7 seconds)i ｢wdm｣: wait until bundle finished: /
[arco-scripts]: [=========== ] 54% (5.4 seconds)TypeError: Cannot read properties of undefined (reading 'lang')
at getMetaFromMd (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:94:66)
at M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:114:20
at Array.map ()
at default_1 (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:111:28)
at compileDemo (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\compiler\demo.js:116:44)
at Object.loaderForArcoComponentDoc (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\index.js:43:34)
at Object.default_1 (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\index.js:184:37)
at LOADER_EXECUTION (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
at runSyncOrAsync (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
at iterateNormalLoaders (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
出现大量上面信息；

这部分错误是因为Windows平台换行符是"\r\n"；
arco-markdown-loader模块无法正确正则匹配出应有的内容所造成的。
回头向[arco-cli](https://github.com/arco-design/arco-cli)库的arco-markdown-loader模块提交PR。
要等还有一Bug解决的。

**Comment by hqz1989** [comment]
还有下面错误信息：
ERROR in ./node_modules/@arco-materials/site-footer/es/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules@arco-materials\site-footer\es'

ERROR in ./node_modules/@arco-materials/site-navbar/es/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules@arco-materials\site-navbar\es'

ERROR in ./src/index-en.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/en-US' in 'M:\arco-design\site\src'

ERROR in ./src/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/zh-CN' in 'M:\arco-design\site\src'
i ｢wdm｣: Failed to compile.

在Windows和linux平台都会出现，也跟[arco-cli](https://github.com/arco-design/arco-cli)库的arco-markdown-loader模块有关。
loaderForArcoComponentDoc函数构建的内容有问题～

**Comment by hqz1989** [comment]
@MisterLuffy 

还有下面错误信息：
ERROR in ./node_modules/@arco-materials/site-footer/es/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules@arco-materials\site-footer\es'

ERROR in ./node_modules/@arco-materials/site-navbar/es/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules@arco-materials\site-navbar\es'

ERROR in ./src/index-en.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/en-US' in 'M:\arco-design\site\src'

ERROR in ./src/index.js
Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/zh-CN' in 'M:\arco-design\site\src'
i ｢wdm｣: Failed to compile.

这里的问题是 ：

> "dev": "arco-scripts dev:component" 未能完成编译，所需组件都未能生成所造成的。
> 
> 运行 "dev": "arco-scripts dev:component" 会出现：
> Failure during tsc invocation: Spawn: got event "err"！
> 
> 是 arco-script 依赖的 node-typescript-compiler 库中 compile.js 使用到 spawn 是：
> 
> const { spawn } = require('child_process')
> 
> 这在 Windows 平台有问题

解决方法：

> 将其更换为跨平台模块，如：
> 
> const { spawn } = require('cross-spawn')
> 


备注：

> 解决方式详解：https://zzz.buzz/zh/2017/02/11/node-js-cross-platform-spawn/
> 
> 关于 node-typescript-compiler 问题，详尽内容，查看 https://github.com/Offirmo/offirmo-monorepo/issues/5
>

**Comment by hqz1989** [comment]
> @MisterLuffy yarn run v1.22.17 $ arco-scripts dev:site --port 9000 [arco-scripts]: [ ] 0% (0.0 seconds)i ｢wds｣: Project is running at http://127.0.0.1:9000/ i ｢wds｣: webpack output is served from undefined i ｢wds｣: Content not from webpack is served from M:\arco-design\node_modules@arco-design\arco-scripts\lib\config\webpack\dist i ｢wds｣: 404s will fallback to /index.html [arco-scripts] Starting server on http://127.0.0.1:9000/ [arco-scripts]: [===== ] 25% (0.7 seconds)i ｢wdm｣: wait until bundle finished: / [arco-scripts]: [=========== ] 54% (5.4 seconds)TypeError: Cannot read properties of undefined (reading 'lang') at getMetaFromMd (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:94:66) at M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:114:20 at Array.map () at default_1 (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:111:28) at compileDemo (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\compiler\demo.js:116:44) at Object.loaderForArcoComponentDoc (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\index.js:43:34) at Object.default_1 (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\index.js:184:37) at LOADER_EXECUTION (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:119:14) at runSyncOrAsync (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:120:4) at iterateNormalLoaders (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:232:2) 出现大量上面信息；
> 
> 这部分错误是因为Windows平台换行符是"\r\n"； arco-markdown-loader模块无法正确正则匹配出应有的内容所造成的。 回头向[arco-cli](https://github.com/arco-design/arco-cli)库的arco-markdown-loader模块提交PR。 要等还有一Bug解决的。

也可以在 git 进行设置，检出时保留 ‘\n’ 换行，并在WebStorm IDE 进行设置，保持换行符为 '\n'，方法如下：

> 默认的换行符在各操作系统下是不一致的，Windows 是 CRLF（’\r\n’），Mac、Linux是 LF（’\n’）。
> 
> 在一些项目中，会严格限制换行符，比如在项目根目录下 .editorconfig 中设置 end_of_line = lf，当你在 Mac 下开发之后，在 Windows 上 clone 代码时， git 会自动将换行变更为系统默认的换行（’\r\n’），而且还是项目级别的。
> 
> 原因
> git 会依据平台自动变更文件换行符，这是项目级别的。
> 
> 解决办法
> 配置 git
> # windows 下是 autocrlf
> 
> #提交时转换为LF，检出时转换为CRLF
> git config --global core.autocrlf true
> 
> #提交时转换为LF，检出时不转换
> git config --global core.autocrlf input
> 
> # 推荐，项目中指定了换行，则在任何平台都只用一种换行 \n
> #提交检出均不转换
> git config --global core.autocrlf false
> 
> SafeCRLF
> 
> #推荐，拒绝提交包含混合换行符的文件
> git config --global core.safecrlf true
> 
> #允许提交包含混合换行符的文件
> git config --global core.safecrlf false
> 
> #提交包含混合换行符的文件时给出警告
> git config --global core.safecrlf warn
> 
> # IDE 设置换行
> Webstorm 中，File -> Settings -> Editor -> Code Style -> Line separator -> Unix and macOS
>

**Comment by PengJiyuan** [comment]
@hqz1989 如果可以的话辛苦提下PR吧，感谢🙏

**Comment by MisterLuffy** [comment]
> 还有下面错误信息： ERROR in ./node_modules/@arco-materials/site-footer/es/index.js Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules@arco-materials\site-footer\es'
> 
> ERROR in ./node_modules/@arco-materials/site-navbar/es/index.js Module not found: Error: Can't resolve '@arco-design/web-react/es/_util/resizeObserver' in 'M:\arco-design\site\node_modules@arco-materials\site-navbar\es'
> 
> ERROR in ./src/index-en.js Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/en-US' in 'M:\arco-design\site\src'
> 
> ERROR in ./src/index.js Module not found: Error: Can't resolve '@arco-design/web-react/es/locale/zh-CN' in 'M:\arco-design\site\src' i ｢wdm｣: Failed to compile.
> 
> 这里的问题是 ：
> 
> > "dev": "arco-scripts dev:component" 未能完成编译，所需组件都未能生成所造成的。
> > 运行 "dev": "arco-scripts dev:component" 会出现：
> > Failure during tsc invocation: Spawn: got event "err"！
> > 是 arco-script 依赖的 node-typescript-compiler 库中 compile.js 使用到 spawn 是：
> > const { spawn } = require('child_process')
> > 这在 Windows 平台有问题

这个问题我已经给 node-typescript-compiler 提了对应的 [PR](https://github.com/Offirmo/offirmo-monorepo/pull/10)，需要等作者更新依赖。同时 arco-cli 也对所有使用到 child_process.spawn 的地方进行了[审查](https://github.com/arco-design/arco-cli/commit/839ecb1fcfc1f6459be215c66b4e296af0ad9269)，处理了这种情况。
