### ISSUE TITLE
官网Table大数据demo 列错位

### ISSUE THREAD

**Issue by 52flutter** [arco-design/arco-design#695]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.0
- **System:** macOS
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://arco.design/react/components/table#%E5%A4%A7%E6%95%B0%E6%8D%AE

## What is expected?
直接看官网Demo

![image](https://user-images.githubusercontent.com/11569655/160271417-46b84e19-6a65-4a94-bdd5-ce6c0b655849.png)

**Comment by PengJiyuan** [comment]
抱歉，马上修复

**Comment by PengJiyuan** [comment]
Release version 2.31.1
