### ISSUE TITLE
Drawer里面select自动focus

### ISSUE THREAD

**Issue by silentport** [arco-design/arco-design#697]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.0
- **Browser:** chrome90.0.4430.93
- **Reproduction Link:** https://codepen.io/silentport/pen/MWrmpRw

## What is expected?
Drawer里面select不要自动focus，在用户选择时才focus

**Comment by PengJiyuan** [comment]
`autoFocus` 设置为 `false`，如果不行直接 `focusLock` 设置为 `false`。

**Comment by silentport** [comment]
> `autoFocus` 设置为 `false`，如果不行直接 `focusLock` 设置为 `false`。

可以了，感谢
