### ISSUE TITLE
ForwardRefCascaderType类型没导出导致业务ts报错

### ISSUE THREAD

**Issue by silentport** [arco-design/arco-design#705]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
no

## What problem does this feature solve?
解决这个问题： 导出的变量“xxx”具有或正在使用外部模块“"/Users/bytedance/byted/storage-components/node_modules/@arco-design/web-react/es/Cascader/cascader"”中的名称“ForwardRefCascaderType”，但不能为其命名

**Comment by silentport** [comment]
TimePicker似乎也是

**Comment by PengJiyuan** [comment]
尝试升级 ts 版本试试
