### ISSUE TITLE
Timepicker 即使输入正确也不会触发onSelect

### ISSUE THREAD

**Issue by liuyangjike** [arco-design/arco-design#706]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.1
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://codepen.io/pen?editors=0010

## What is expected?
触发onSelect,

**Comment by PengJiyuan** [comment]
onSelect 只在选择的时候触发，点击选择。

**Comment by liuyangjike** [comment]
@刘扬 如果值是符合规则的，如 01:01:01，是会触发 select 事件的，输入过程没有

**Comment by liuyangjike** [comment]
@PengJiyuan

**Comment by PengJiyuan** [comment]
> @刘扬 如果值是符合规则的，如 01:01:01，是会触发 select 事件的，输入过程没有 这个群里维护者说的

好
