### ISSUE TITLE
怎么配置全局字体大小及一些组件默认padding等如input组件？

### ISSUE THREAD

**Issue by pollux2021** [arco-design/arco-design#708]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
怎么配置全局字体大小及一些组件默认padding等如input组件？

**Comment by chenc041** [comment]
参考下 design lab, 应该可以实现你的需求
https://arco.design/themes/home

**Comment by pollux2021** [comment]
@chenc041 感激

**Comment by chenc041** [comment]
> @chenc041 感激

不客气
