### ISSUE TITLE
表格设置scrollX，并且没有数据时表头可以滚动

### ISSUE THREAD

**Issue by liunana1230** [arco-design/arco-design#710]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
无数据时看到所有的表头

**Comment by PengJiyuan** [comment]
scrollX 设置的就是表格宽度，跟有没有数据无关。如果希望没有数据时表头都在，那就无数据时把 scrollX 去掉
