### ISSUE TITLE
官方案例装不成功

### ISSUE THREAD

**Issue by a15218378694** [arco-design/arco-design#731]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.2
- **System:** win10
- **Browser:** chrome100.0.4896.75
- **Reproduction Link:** https://arco.design/vue/docs/pro/start

## Extra info
        ___                    ____            _
       /   |  ______________  / __ \___  _____(_)___ _____
      / /| | / ___/ ___/ __ \/ / / / _ \/ ___/ / __ `/ __ \
     / ___ |/ /  / /__/ /_/ / /_/ /  __(__  ) / /_/ / / / /
    /_/  |_/_/   \___/\____/_____/\___/____/_/\__, /_/ /_/
                                             /____/

                                                v1.25.0

Error: unable to verify the first certificate

## What is expected?
不会报错

## Steps to reproduce
arco init hello-arco-pro报错

**Comment by MisterLuffy** [comment]
请提供一下报错的截图，以方便定位问题。这个报错似乎是 SSL 安全证书认证失败导致的[问题](https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate)，但网站的安全证书从浏览器看是有效的：
![image](https://user-images.githubusercontent.com/29861850/161890861-4a583422-a83b-4dc4-9e73-42e00b55c83c.png)
因为我本地无法复现，如果方便的话，可以尝试克隆 [arco-cli 代码](https://github.com/arco-design/arco-cli/blob/main/packages/arco-cli/src/env.ts#L27) 本地调试一下。

**Comment by MisterLuffy** [comment]
这个 issue 先关闭了，如果有后续发现可继续打开它。

**Comment by bojue** [comment]
<img width="725" alt="截屏2023-01-17 下午6 15 10" src="https://user-images.githubusercontent.com/14350577/212871616-f52c463a-ac68-49d0-a160-5dee0bf34459.png">


@MisterLuffy "请提交你的 Git 修改后继续操作” 

遇到一个报错，我本地git配置一直在用，查了一下资料类似的情况：https://blog.csdn.net/tacity/article/details/127390772

**Comment by sofun520** [comment]
安装出现错误：

![Image](https://github.com/user-attachments/assets/d0219209-cb63-4c2b-a438-a6fa78bbf6e7)
