### ISSUE TITLE
table 点击某一行 有一个row-class-name的函数可以修改点击行的样式

### ISSUE THREAD

**Issue by xindiyang** [arco-design/arco-design#733]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
naiveUI 的table的row-class-name类似

## What problem does this feature solve?
行点击是，可以区分出点击的哪一行

**Comment by PengJiyuan** [comment]
目前支持 `rowClassName` 看是不是你需要的。
