### ISSUE TITLE
Modal 关闭 focusLock 时能够开启 autoFocus

### ISSUE THREAD

**Issue by claneo** [arco-design/arco-design#738]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
-

## What problem does this feature solve?
focusLock会导致 monaco editor 弹出右键菜单后瞬间消失，所以需要关掉，但是这时候 autoFocus 不起作用了
期望能实现首次弹出 Modal 时自动聚焦第一个元素，但之后不会强制锁定

**Comment by PengJiyuan** [comment]
现在 autoFocus 是靠 react-focus-lock 做的，如果禁用掉手动给第一个元素设置 autoFocus 试试

**Comment by claneo** [comment]
我这不是懒嘛

**Comment by claneo** [comment]
@PengJiyuan 话说这个 issue 模板生成的标题是不是该在前面加个 [feature request]

**Comment by PengJiyuan** [comment]
> @PengJiyuan 话说这个 issue 模板生成的标题是不是该在前面加个 [feature request]

现在我们会手动打上label的
