### ISSUE TITLE
Form组件赋值Switch该如何赋值？

### ISSUE THREAD

**Issue by lhz960904** [arco-design/arco-design#739]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.0
- **System:** Mac
- **Browser:** chrome100.0.4896.60
- **Reproduction Link:** https://codesandbox.io/embed/elated-pare-iiwjj3?fontsize=14&hidenavigation=1&theme=dark

## What is expected?
期待可以设置Switch为checked状态

**Comment by chenc041** [comment]
看下这个 
```tsx
<FormItem
      label='Switch'
      field='switch'
      triggerPropName='checked'
      rules={[
        {
          type: 'boolean',
          true: true,
          message: 'must be true',
        },
      ]}
    >
      <Switch />
</FormItem>
```
https://arco.design/react/components/form#%E5%8F%97%E6%8E%A7%E8%A1%A8%E5%8D%95

**Comment by chenc041** [comment]
https://codesandbox.io/s/autumn-pond-7bnmdr?file=/index.js

**Comment by PengJiyuan** [comment]
如上，需要设置 `triggerPropName`
