### ISSUE TITLE
checkedStrategy='parent'   value 值同时设置，有 bug

### ISSUE THREAD

**Issue by fantian007** [arco-design/arco-design#744]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.2
- **Browser:** chrome100.0.4896.75
- **Reproduction Link:** https://arco.design/react/components/cascader#%E6%94%AF%E6%8C%81%E5%A4%9A%E9%80%89

## What is expected?
checkedStrategy='parent'   value 值同时设置，选择项点击没有效果

**Comment by yinkaihui** [comment]
你好，这个没有理解，可以给个复现demo么

**Comment by fantian007** [comment]
> 你好，这个没有理解，可以给个复现demo么

可以看这个 demo:   https://codepen.io/fantian007/pen/bGaKZmr?editors=0010

就是给 Cascader 添加了 value 之后，选不中任何选项了，value 值也不生效

**Comment by yinkaihui** [comment]
写法问题，最简单的可以试试把 value 渲染成 DOM 节点看下
<img width="526" alt="image" src="https://user-images.githubusercontent.com/23161413/163528763-7492a549-0fc1-4c8b-9deb-698acc9eed24.png">

**Comment by honghaibin** [comment]
我也遇到这个问题了，请问解决了吗 @fantian007

**Comment by honghaibin** [comment]
> 



> 我也遇到这个问题了，请问解决了吗 @fantian007

Fixed this in version 2.35.0
