### ISSUE TITLE
table border 第一列合并单元格，第二列边框样式问题

### ISSUE THREAD

**Issue by xinyin1010** [arco-design/arco-design#747]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.2
- **Browser:** chrome100.0.4896.75
- **Reproduction Link:** https://codepen.io/xinyin92/pen/jOYKoLP?editors=0010

## What is expected?
第二列td不要出现左边框

**Comment by PengJiyuan** [comment]
这个不好处理，整个 border 的情况比较复杂。。。
