### ISSUE TITLE
RangePicker and SortableList component Issue

### ISSUE THREAD

**Issue by xuli-cooly** [arco-design/arco-design#754]
issue环境：最新版本的esbuild（0.14.36）
![image](https://user-images.githubusercontent.com/60103681/162919018-5ee3258f-4692-4efc-9920-50b1162ad726.png)

**Comment by PengJiyuan** [comment]
是用了 React18吗

**Comment by xuli-cooly** [comment]
> 问题环境：最新版本的esbuild（0.14.36） ![图片](https://user-images.githubusercontent.com/60103681/162919018-5ee3258f-4692-4efc-9920-50b1162ad726.png)
