### ISSUE TITLE
使用谷歌浏览器自带翻译功能将网页翻译成英文时，【Select】组件在【搜索】场景下，选中选项组件崩溃

### ISSUE THREAD

**Issue by zhuwenqi001** [arco-design/arco-design#759]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.3
- **Browser:** chrome100.0.4896.75
- **Reproduction Link:** https://arco.bytedance.net/react/components/select
![屏幕录制2022-04-14 上午11 26 06_](https://user-images.githubusercontent.com/25142129/163308712-970a6f1b-531e-4df5-9a56-789102694b75.gif)

## What is expected?
页面正常展示

## Steps to reproduce
1. 右键翻译成【英语】
2. 下拉框组件搜索信息
3. 选中其中一项后页面崩溃

**Comment by MisterLuffy** [comment]
这个问题是 Google Translate 改变了 Dom 节点导致 React 对节点的引用失效导致的，具体可以参考这个[回答](https://github.com/facebook/react/issues/11538#issuecomment-390386520)。所以我们对这个情况无能为力，也不会对它做专门的优化。
