### ISSUE TITLE
DatePicker   dayStartOfWeek  可以不要默认为 0 吗

### ISSUE THREAD

**Issue by fantian007** [arco-design/arco-design#779]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.0
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://codesandbox.io/s/floral-voice-0pyywp?file=/src/App.js

## What is expected?
 arco 中默认为 0，可以默认取 dayjs 中对应语言 （例如：zh-cn) 的默认 dayStartOfWeek 值吗？

## Steps to reproduce

           * 第一次选本周，起始日期为 04-11
           * 第二次选本周，起始日期为 04-10
           *
           * 排查结果为 dayStartOfWeek 属性覆盖了 dayjs 自身的 dayStartOfWeek

**Comment by yinkaihui** [comment]
在 `ConfigProvider` 组件里有个 `componentConfig` 配置项，可以用它来设置所有的 `DatePicker` 组件的默认属性值

**Comment by fantian007** [comment]
> 在 `ConfigProvider` 组件里有个 `componentConfig` 配置项，可以用它来设置所有的 `DatePicker` 组件的默认属性值

最后是用的这个方法，但是排查的时候废了老大劲。就是提个建议，能不能不要默认为0

**Comment by yinkaihui** [comment]
好的，我们看下
