### ISSUE TITLE
“DatePicker.RangePicker”不能用作 JSX 组件。   其实例类型 "Component<RangePickerProps, any, any>" 不是有效的 JSX 元素。

### ISSUE THREAD

**Issue by luyuanky** [arco-design/arco-design#781]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.32.0
- **浏览器版本:** chrome100.0.4896.75
- **复现地址:** 构建错误，无法提供复现链接

## 预期结果
不报错

## 复现步骤
使用arco-design pro 创建项目
无任何代码修改，正常启动
示例代码 <DatePicker.RangePicker /> 出现ts报错

![image](https://user-images.githubusercontent.com/38411718/163774322-51bc3e07-68e9-4617-bc96-46b56970252d.png)

**Comment by PengJiyuan** [comment]
react 是什么版本

**Comment by luyuanky** [comment]
> 反应是什么版本

v16.9.0

**Comment by simsir-lin** [comment]
我也遇到这种情况，请问解决了吗？

**Comment by jiahao-c** [comment]
@luyuanky  @simsir-lin  方便提供下生成出来的完整项目代码吗？可以上传到一个github repo里，然后贴个链接~

**Comment by hzgotb** [comment]
> @luyuanky @simsir-lin 方便提供下生成出来的完整项目代码吗？可以上传到一个github repo里，然后贴个链接~

react的类型错误。https://github.com/facebook/react/issues/24304#issue-1196695161

**Comment by yuhan0709** [comment]
可以自查一下是不是有多版本的@types/react
https://github.com/react-navigation/react-navigation/issues/10507#issuecomment-1097594510

**Comment by luyuanky** [comment]
> 可以自查一下是不是继承的@types/react [react-navigation/react-navigation#10507（评论）](https://github.com/react-navigation/react-navigation/issues/10507#issuecomment-1097594510)

果然是这个问题 发现内部依赖有多个@types/react的版本 
![image](https://user-images.githubusercontent.com/38411718/176110729-b1adc973-9aee-4c48-9370-383d5b4d0ef5.png)

**Comment by hesetiema** [comment]
临时的办法：`const RangePicker = DatePicker.RangePicker as any;`

**Comment by yinkaihui** [comment]
> 可以自查一下是不是有多版本的@types/react [react-navigation/react-navigation#10507 (comment)](https://github.com/react-navigation/react-navigation/issues/10507#issuecomment-1097594510)

一般是这个原因导致的，可参考解决方案
