### ISSUE TITLE
table组件内rowSelection配置了selectedRowKeys之后点击多选框没有反应

### ISSUE THREAD

**Issue by lcllhh** [arco-design/arco-design#793]
<a-table :data="tableData" style="margin: 10px 0" :pagination="false" :row-selection="rowSelection"
              row-key="id" @selection-change="tableSelect1">

const rowSelection = {
  type: 'checkbox',
  showCheckedAll: true,
  selectedRowKeys: tableCheckKeysAll.value,
};

**Comment by chenc041** [comment]
你这是 vue的吧?
麻烦去 vue 那边提哈

**Comment by baboony** [comment]
听我的  我刚写到这边，解决了这个问题。 :row-selection="rowSelection" rowSelection

**Comment by lcllhh** [comment]
> 听我的 我刚写到这边，解决了这个问题。 :row-selection="rowSelection" 在文档中并没有使用ref()包裹这段代码
> 
> rowSelection设置应该使用ref()包裹者 参考我的代码： const rowSelection = ref({ type: 'checkbox', showCheckedAll: true, defaultSelectedRowKeys: [] });

我加上了ref并没有用，只要在rowSelection里配置了selectedRowKeys这个选项，点击多选框就不会有反应
