### ISSUE TITLE
开发环境无法跨域

### ISSUE THREAD

**Issue by yangpeng1994** [arco-design/arco-design#805]
`vite.config.dev.ts` 文件设置如下：
` export default mergeConfig(
 {
    mode: 'development',
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:8080',
          changeOrigin: true,
          rewrite: path => path.replace(/^\/api/, '')
        },
      },
    },
`
yarn dev后 : 
浏览器Edge还是提示 `Access to XMLHttpRequest at 'http://localhost:8080/api/user/info' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

请问怎么解决

**Comment by sHow8e** [comment]
@yangpeng1994 你可以尝试把拦截器(/api/interceptor.ts)的baseUrl部分注释掉。同时对应的mock接口要关闭。

**Comment by yangpeng1994** [comment]
> @yangpeng1994 你可以尝试把拦截器(/api/interceptor.ts)的baseUrl部分注释掉。同时对应的mock接口要关闭。
感谢你的回答，我知道原因了，是因为这个文件指定的地址优于配置文件，已经注释掉了，正常了
arco-design-pro-vite/.env.development

**Comment by yangpeng1994** [comment]
>
