### ISSUE TITLE
Table pagination not properly rendered during data loading

### ISSUE THREAD

**Issue by WesleyWu** [arco-design/arco-design#806]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.1
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** http://react-pro.arco.design/list/search-table

## What is expected?
数据加载过程中，分页总数、页数应当保持为之前最后一次加载完成的状态

## Steps to reproduce
1、初始进来后点第2页
2、内容体裁选“横版短视频”，点查询
3、筛选后表格加载后，总数为45条，共6页
4、再点第1页，在加载过程中，分页总数闪现为总数100条，共10页
表格加载完毕后，恢复正常。

**Comment by yuhan0709** [comment]
这个是pro的逻辑问题，pro的下个版本会修复哈～
