### ISSUE TITLE
table配置showHeader={false}时, 如果 tbody 发生 resize(eg. 出现纵向滚动条)执行 setScrollBarStyle 会导致 typeError

### ISSUE THREAD

**Issue by hbli1** [arco-design/arco-design#807]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.1
- **System:** windows
- **Browser:** chrome100
- **Reproduction Link:** https://codesandbox.io/embed/shy-dawn-9x9cg0?fontsize=14&hidenavigation=1&theme=dark

## What is expected?
不出现 typeError

## Steps to reproduce
出现纵向滚动条触发 onResize 即可, 需要 windows 系统 mac 未发现问题

**Comment by hbli1** [comment]
`Cannot read properties of null (reading 'style')`

```
            if (scrollBarWidth) {
                scrollbarChanged.current = true;
                wrapper.style.overflowY = 'scroll';
                if (refTableFoot.current) {
                    refTableFoot.current.style.overflowY = 'scroll';
                }
            }
```

**Comment by PengJiyuan** [comment]
这个问题复现不出来，难道是 windows 下 parentNode 会有问题吗？
我这边直接加个判断吧。wrapper?.style.overflowY = 'scroll';

**Comment by PengJiyuan** [comment]
mac 也能复现，只要把滚动条设置为始终显示就行。
