### ISSUE TITLE
menu组件 收缩在展开后 抽屉自动关闭了

### ISSUE THREAD

**Issue by leftScience** [arco-design/arco-design#814]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.1
- **System:** mac
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://arco.design/react/components/menu

## What is expected?
别说什么了selectedKeys 受控模式，我又没刷新页面 ，我觉得默认应该保存这个抽屉打开关闭的状态 

## Steps to reproduce
打开官网menu组件-随便一个都这样

**Comment by MisterLuffy** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)
> 
> ## Basic Info
> * **Package Name And Version:** @arco-design/web-react@2.32.1
> * **System:** mac
> * **Browser:** chrome98.0.4758.102
> * **Reproduction Link:** https://arco.design/react/components/menu
> 
> ## What is expected?
> 别说什么了selectedKeys 受控模式，我又没刷新页面 ，我觉得默认应该保存这个抽屉打开关闭的状态
> 
> ## Steps to reproduce
> 打开官网menu组件-随便一个都这样

你好，我们会修复这个问题。但是似乎没有人回复过你什么 "selectedKeys 受控模式" 吧

**Comment by leftScience** [comment]
只是预判了一下你们的回答，因为我看到你们的arco design pro 管理系统里面是使用selectedKeys模式去实现上述功能的。
