### ISSUE TITLE
期望Cascader组件可以自己传入搜索值

### ISSUE THREAD

**Issue by gitducheng** [arco-design/arco-design#815]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
当Cascader组件以自定义DOM触发时（比如一个“ ”按钮），showSearch属性就失效，这时像使用搜索功能，可以自己定义dropdownRender属性（下拉面板）。但是无法再使用filterOption进行筛选。

**Comment by gitducheng** [comment]
![飞书20220426-193614](https://user-images.githubusercontent.com/20925731/165293257-f74694c2-c9ca-4085-bf08-3745d938ab58.jpg)
![飞书20220426-193622](https://user-images.githubusercontent.com/20925731/165293335-6bdd9e17-2a5c-4ea9-ba2d-93a867cf1cc7.jpg)
上面是一个使用场景示例。

**Comment by fakership** [comment]
@fakership I will resolve it

**Comment by fakership** [comment]
https://github.com/arco-design/arco-design/pull/835
