### ISSUE TITLE
为什么InputNumber组件的自定义类加到div上不加到Input上

### ISSUE THREAD

**Issue by zhuxiangming666** [arco-design/arco-design#840]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.2
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://codesandbox.io/s/5o5bks?file=/index.js

## What is expected?
InputNumber的className 提供的class 加到input上可以改变input上的样式

**Comment by chenc041** [comment]
因为 InputNumber 这个组件内部还有元素,  比如格式化 切换mode 等
如果需要改变 input 的样式 可以考虑下风格配置平台, 功能还是很强大的
https://arco.design/themes?currentPage=1&onlyPublished=false&pageSize=9&sortBy=starCount&tag=all
