### ISSUE TITLE
@arco-design/arco-site-navbar 问下，这个包是还没有开源嘛，再仓库里面没找到源码

### ISSUE THREAD

**Issue by zuoqi705** [arco-design/arco-design#85]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** - 
- **系统版本:** - 
- **浏览器版本:** - 
- **复现地址:** - 

## 预期结果
- 

## 复现步骤
 -

**Comment by yuhan0709** [comment]
哈喽，那个属于内部物料哈，暂时没有计划开源。

**Comment by zuoqi705** [comment]
got it

**Comment by unbyte** [comment]
给文档站的 search panel 相关的 keydown 事件都 `preventDefault` 一下吧，每次 ctrl k 都会唤醒浏览器的地址栏，esc 也要连按两下才能关掉

**Comment by PengJiyuan** [comment]
@unbyte 好的收到

**Comment by naruto9120** [comment]
Any ETA to make this navbar package as open-source?
