### ISSUE TITLE
Menu组件defaultOpenKeys设置了但对应的子菜单没有展开

### ISSUE THREAD

**Issue by XLearner** [arco-design/arco-design#851]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.27.0
- **Browser:** chrome101.0.4951.41

## What is expected?
指定key的submenu展开

![image](https://user-images.githubusercontent.com/26158725/168063786-4b47cd2e-ff65-462d-a4fc-2e0c59622f4b.png)
![image](https://user-images.githubusercontent.com/26158725/168063894-c85dc82f-8441-425b-9e7e-ce8038b70f32.png)
![image](https://user-images.githubusercontent.com/26158725/168063964-780cbdb9-81be-43e6-9a09-e42ff6a5a267.png)

**Comment by MisterLuffy** [comment]
这个 [Demo](https://arco.design/react/components/menu#%E7%BC%A9%E8%B5%B7%E5%86%85%E5%B5%8C%E8%8F%9C%E5%8D%95) 是带有 `defaultOpenKeys` 的用法，请提供可以复现你遇到问题的 CodePen。

**Comment by XLearner** [comment]
您好，你发送的信息我已成功接收，我会尽快回复您。Lambert Yim

**Comment by XLearner** [comment]
https://codepen.io/Lambert_/pen/abqmPMz?editors=0010

**Comment by XLearner** [comment]
> 这个 [Demo](https://arco.design/react/components/menu#%E7%BC%A9%E8%B5%B7%E5%86%85%E5%B5%8C%E8%8F%9C%E5%8D%95) 是带有 `defaultOpenKeys` 的用法，请提供可以复现你遇到问题的 CodePen。

在上面贴的 codepen 中的示例，配置了 defaultOpenKeys但没有默认展开是这里我提的问题，然后我有尝试将 Menu 标签也放在 renderMenuList 中，这样的话 配置的 defaultOpenKeys 能够默认展开，但是 defaultSelectedKeys 又不生效了

**Comment by MisterLuffy** [comment]
抱歉回复得比较晚。`defaultProps` 是在组件首次渲染时才有效的，所以在组件挂载时需要保证数据源是就绪的，可以采用这种写法 https://codesandbox.io/s/inspiring-black-effdry?file=/index.js。
Menu 会在 SubMenu 发生变化时从 `openKeys` 中过滤掉无用的 SubMenuKey，https://github.com/arco-design/arco-design/blob/main/components/Menu/index.tsx#L116，也就导致了初始化时传入的无效 openKey 被直接过滤掉了。

**Comment by 50431040** [comment]
> 抱歉回复得比较晚。`defaultProps` 是在组件首次渲染时才有效的，所以在组件挂载时需要保证数据源是就绪的，可以采用这种写法 [https://codesandbox.io/s/inspiring-black-effdry?file=/index.js。](https://codesandbox.io/s/inspiring-black-effdry?file=/index.js%E3%80%82) Menu 会在 SubMenu 发生变化时从 `openKeys` 中过滤掉无用的 SubMenuKey，https://github.com/arco-design/arco-design/blob/main/components/Menu/index.tsx#L116 ，也就导致了初始化时传入的无效 openKey 被直接过滤掉了。

demo地址访问不了呢

**Comment by LiYanyan-a** [comment]
请问是哪种写法，链接[https://codesandbox.io/s/inspiring-black-effdry?file=/index.js](https://codesandbox.io/s/inspiring-black-effdry?file=/index.js%E3%80%82)访问不了了
