### ISSUE TITLE
table的合并表头，fix下样式异常

### ISSUE THREAD

**Issue by xu-yongliang** [arco-design/arco-design#863]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.2
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://codesandbox.io/s/hungry-rgb-f8ww21?file=/index.js

## What is expected?
正常fixed

## Steps to reproduce
左右滚动就可以复现

**Comment by PengJiyuan** [comment]
表头组合的场景下，固定列暂时只支持满格的单元格。
