### ISSUE TITLE
For Cascader, clear search input on option select

### ISSUE THREAD

**Issue by limyifan1** [arco-design/arco-design#873]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
The Select component already has this feature. 

## What problem does this feature solve?
Currently when searching in Cascader in multi mode, the typed search value remains in the input box after selecting a value from the dropdown box. Hence, when the user wishes to search for another value, the user has to delete the search values first before searching for a new value. 

This is not convenient for the user and is also not consistent with the Select component's user interaction which has this feature.

**Comment by yinkaihui** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/23161413/169446441-9b5d3ecc-489d-44c6-8569-7d97acc1936c.png">

可以通过这个属性指定下
