### ISSUE TITLE
在严格StrictMode模式下报错

### ISSUE THREAD

**Issue by panqibao** [arco-design/arco-design#875]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.33.0
- **Browser:** chrome101.0.4951.41

## Extra info
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

## What is expected?
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

## Steps to reproduce
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by PengJiyuan** [comment]
你好，目前没有很好的办法，官方提供的 ref 无法覆盖类组件的情况。我们会继续跟进这个问题。

**Comment by PengJiyuan** [comment]
Duplicate: https://github.com/arco-design/arco-design/issues/875

**Comment by vaynevayne** [comment]
覆盖不到类组件, 意思就是类组件下仍然有提示, 但hooks下没有提示 
这很好啊, 不太理解为什么会成为一个理由呢
