### ISSUE TITLE
Layout.Sider 在resize之后collapse行为失效

### ISSUE THREAD

**Issue by MeaKaka** [arco-design/arco-design#882]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.33.0
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://codepen.io/h-x-h/pen/abqWwPp?editors=0010

## Steps to reproduce
1. 拖动可伸缩侧边栏
2. 点击折叠按钮
3. 仅按钮折叠，但是侧边栏为折叠

**Comment by yuhan0709** [comment]
看了下这个要加resizebox的onMoving参数才能完全修复～
