### ISSUE TITLE
upload 定制能力增强

### ISSUE THREAD

**Issue by yinkaihui** [arco-design/arco-design#884]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
upload 定制能力增强

## What problem does this feature solve?
1. 拓展 progress 节点定制
2. 照片墙图片定制

**Comment by danaoairuike** [comment]
恕我直言，这个PR: https://github.com/arco-design/arco-design/pull/925
对limit的改动，是一个bad design

limit: number 这很符合直觉，但现在允许传一个object，这api设计的实在是让人摸不着头脑

**limit和hideOnExceedLimit这俩互不干扰，或者说基本上毫无关联**，完全可以把hideOnExceedLimit直接设置为Upload的props，而不必隐藏在limit里面，我花了半小时debug，看源码才发现limit竟然可以给object，一点都不符合直觉

这个api设计是非常糟糕的
