### ISSUE TITLE
弹出层算法有缺陷，导致弹出提示框、提示信息等内容时触发滚动条，引起画面抖动！

### ISSUE THREAD

**Issue by windf17** [arco-design/arco-design#893]
在屏幕边缘的元素触发弹出层(如Popconfirm、Tooltip组件)时，该弹出层出现前没有滚动条，出现时会触发滚动条，弹出层消失后滚动条也消失，导致页面产生抖动，很不舒服，影响美感。
请调整算法，确保弹出层的出现不改变滚动条的状态：
1. 弹出层出现前***没滚动条***的，弹出层出现及消失均***不产生滚动条***；
2. 弹出层出现前***有滚动条***的，弹出层出现及消失均***不消除滚动条***。

**Comment by PengJiyuan** [comment]
我看了下发现滚动条计算的逻辑已经是支持了。。在使用的时候出现滚动一般是你页面的宽度没有限制到body里，比如你 navbar 或者其他东西用的 fixed 定位
