### ISSUE TITLE
Demos that depend on external packages need to be updated

### ISSUE THREAD

**Issue by yuhan0709** [arco-design/arco-design#898]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.33.1
- **浏览器版本:** chrome101.0.4951.64

## demo 依赖外部包
- [x] `react-sticky`
- [x] `react-sortable-hoc`
- [x] `react-resizable`
- [ ] `react-easy-crop`
- [ ] `react-dnd`

**Comment by yuhan0709** [comment]
Table #920

**Comment by PengJiyuan** [comment]
Duplicate: https://github.com/arco-design/arco-design/issues/47
