### ISSUE TITLE
Timeline 时间轴 Bug， label 标签不显示

### ISSUE THREAD

**Issue by ITSweets** [arco-design/arco-design#902]
请查看官网的 https://arco.design/react/components/timeline#%E7%BA%B5%E5%90%91%E6%97%B6%E9%97%B4%E8%BD%B4

将属性 mode="alternate" 设置后，位于左侧的 item 的 label 标签不显示【是位置不对】。上卖弄的链接是官网的例子，有 Bug。

请尽快修复

**Comment by eijil** [comment]
看起来是 labelPosition='relative' 的样式就是这样的 设置same就展示了

**Comment by ITSweets** [comment]
不不不，这样不合理。不管如何排版应该有的内容就应该在所有的模式下都存在啊。还是希望官方尽快修复一下。
