### ISSUE TITLE
Typography: Bold modifier not working

### ISSUE THREAD

**Issue by busyxiang** [arco-design/arco-design#904]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.33.1
- **Framework version:** React 18
- **Browser:** chrome101.0.4951.64
- **Reproduction Link:** https://codesandbox.io/s/distracted-shamir-4n268f?file=/src/App.js:205-215

## What is expected?
The text is bold when added bold modifier

## Steps to reproduce
1. Import the Typography component
2. Use any of the Typography components
3. Add bold modifier

**Comment by yuhan0709** [comment]
无法复现，是符合预期的
