### ISSUE TITLE
希望增加一个百度广告和google广告的组件

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#906]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
还是那句话，Antd 没有，我们有，就是优势！

## What problem does this feature solve?
方便前端开发调用，加速开发进度！

**Comment by PengJiyuan** [comment]
组件库不会添加，欢迎使用物料平台 https://arco.design/material
