### ISSUE TITLE
希望增加一个颜色选择器

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#907]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
Element UI 都有，他们的 antd 居然不去实现一个。
可以借鉴 https://uiwjs.github.io/react-color/ 的方式，组件分的比较细，各种组合很方便，之前我用这个组合了一个antd的，总感觉不统一。

## What problem does this feature solve?
这个问题，我曾经在Antd中提过[https://github.com/ant-design/ant-design/issues/35315](https://github.com/ant-design/ant-design/issues/35315)，他们没有此开发计划，虽然有React Color，但是输入框啊什么的，不统一。
可以在输入框中使用，就像日期时间选择器一样。

**Comment by yoyo837** [comment]
antd@5.5.0 已经有啦！https://github.com/ant-design/ant-design/pull/41990
