### ISSUE TITLE
希望增加一个主色调切换功能

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#909]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
就像antd可以动态修改primary-color，其他的其他色彩自动计算。

## What problem does this feature solve?
我们虽然有亮色暗色切换功能，能不能也动态切换主色调？https://ant-design.antgroup.com/components/config-provider-cn/#components-config-provider-demo-theme

**Comment by xiaoyierle** [comment]
+1 插个眼

**Comment by PengJiyuan** [comment]
https://github.com/arco-design/arco-design/issues/1792
