### ISSUE TITLE
希望增加一个升级浏览器的提示组件？

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#911]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
这个没考虑过，我想你们肯定有办法。

## What problem does this feature solve?
我知道这个很矛盾，浏览器不支持，怎么做组件？我想应该总有办法解决的，虽然有一些特殊HTML标签搞定，但是我觉得有了它，这个组件库会更好，不然也不会有人说，你们又写了一个Ant Design

**Comment by PengJiyuan** [comment]
组件库不会添加，欢迎使用物料平台 https://arco.design/material
