### ISSUE TITLE
Table can't scroll in Drawer 

### ISSUE THREAD

**Issue by xiaofengqqcom123** [arco-design/arco-design#93]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** 2.23.5
- **System:** mac
- **Browser:** Google
- **Reproduction Link:** https://codesandbox.io/embed/musing-estrela-gv0ce?fontsize=14&hidenavigation=1&theme=dark

## What is expected?
Table can scroll 

## Steps to reproduce
Table can't scroll in Drawer

**Comment by PengJiyuan** [comment]
You should specify `scroll.x` like `scroll={{ x: 1200 }}`
