### ISSUE TITLE
嗯，的确增加了阿拉伯语，是不是应该网页的书写方向能够设定？

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#940]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
参考：https://ant-design.antgroup.com/components/config-provider-cn/#components-config-provider-demo-direction 中的那样。

## What problem does this feature solve?
因为阿拉伯语还可以从右往左的。那么一些组件的方向可能还得有特殊的设置。

**Comment by PengJiyuan** [comment]
是的，RTL 有计划支持，我们近期做下方案调研

**Comment by PengJiyuan** [comment]
Duplicate: https://github.com/arco-design/arco-design/issues/963

**Comment by kwooshung** [comment]
> Duplicate: #963

别人和我重复，按道理来讲不应该关闭我的，把他的关闭才对。
