### ISSUE TITLE
能否增加个验证码输入框的组件？就像“飞书”登录中的那样？（API都写好了，22个，供官方参考）

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#941]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
就像“飞书”网页版登录，输入手机号后，下一步就是“填写验证码”。

## What problem does this feature solve?
验证码输入，美观，风格统一，这个功能我查了，在物料中没有的。

### 就算有或今后有：
- 估计也很难能和arco-design完美融合，风格统一
- 第三方可能会存在性能问题
- 可能无法和arco-design中的api高度相似，降低学习成本
- 无法和Form表单一起使用
- 功能不够强大
- 第三方可能无法做到及时的维护和更新

![image](https://user-images.githubusercontent.com/3413930/170844682-24e9d1e8-de0a-41e7-8684-a2c2c4719eb9.png)

## 希望的API
|参数名|描述|类型|默认值|
|---|---|---|---|
|count/length|输入框数量|`number`|`6`|
|group|多少个输入框为一组，<=1，表示没有分组|`number`|`3`|
|seg|分隔符，当group有效，才起作用，表示分组之间的间隔|`'ReactNode' \| 'string'`|`-（中横线）`|
|modify|内容格式是否可修改<br/><br/>意思是说，比如：当你输入到第4个（共6个）输入框，鼠标点击前面的输入框（<br/>&nbsp;&nbsp;&nbsp;&nbsp;也可以通过`箭头左右`控制光标在输入框中来回切换；<br/>&nbsp;&nbsp;&nbsp;&nbsp;`鼠标滚轮`也可以控制光标；<br/>&nbsp;&nbsp;&nbsp;&nbsp;控制方式也可提炼出一个api，<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;是否可以鼠标滚轮控制等<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鼠标滚轮是否是反向操作，比如前滚往后，后滚往前 切换<br/>）可以直接进修改此值；<br/><br/>如果为false，则就像“飞书”似的，直接聚焦应当输入内容的输入框。|`boolean`|`-`|
|size|输入框的尺寸|`'mini' \| 'small' \| 'default' \| 'large'`|`default`|
|disabled|是否禁用|`boolean`|`-`|
|readOnly|是否只读|`boolean`|`-`|
|placeholder|提示文字|`string`|`-`|
|error|是否是错误状态|`boolean`|`-`|
|uppercase|强制输入内容大写|`boolean`|`true`|
|addBefore|输入框前添加元素|`ReactNode`|`-`|
|addAfter|输入框后添加元素|`ReactNode`|`-`|
|prefix|添加前缀文字或者图标|`ReactNode`|`-`|
|suffix|添加后缀文字或者图标|`ReactNode`|`-`|
|allowClear|允许一键清空所有输入框|`boolean`|`-`|
|onChange|输入时的回调|`(value: string, e) => void`|`-`|
|onClear|点击清除按钮的回调|`() => void`|`-`|
|style|节点样式|`CSSProperties`|`-`|
|className|节点类名|`string \| string[]`|`-`|
|format|内容格式，全数字、字母、任意字符、正则表达式|`'number'\|'letter'\|'all'\|'Regex'`|'all'|
|value|值|与format一致|`-`|
|direction|方向，default表示跟ConfigProvider中的配置走（目前ConfigProvider还没有direction的API，希望能够加入：[在这里已经提到](https://github.com/arco-design/arco-design/issues/940)）|`'ltr'\|'rtl'\|'default'`|`default`|

## 同时还希望支持和form表单一起使用
- 内容验证之类的，就像input似的

**Comment by PengJiyuan** [comment]
组件库不会添加，欢迎使用物料平台 https://arco.design/material

**Comment by yuhan0709** [comment]
https://arco.design/material/detail?name=arco-verify-code  最近抽时间浅写了个物料
