### ISSUE TITLE
Why there still has Chinese i18n strings in bundle assets when use enUS in ConfigProvider

### ISSUE THREAD

**Issue by Xwudao** [arco-design/arco-design#948]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome101.0.4951.64

## Extra info

![Snipaste_2022-06-01_16-54-50](https://user-images.githubusercontent.com/31327868/171366804-b91ed2a6-1930-4cfa-a442-a082f66f2ea0.png)

```
import enUS from '@arco-design/web-react/es/locale/en-US';

 <ConfigProvider locale={enUS}>

</ConfigProvider>

```

**Comment by jiahao-c** [comment]
Hi, could you please provide a minimal reproducible code sample? (either as a github repo or codesandbox link)

**Comment by PengJiyuan** [comment]
Because Chinese is the default language, in locale/default.ts, it will be bundled into the component library by default.
For now, you can use https://github.com/arco-design/arco-plugins/tree/main/packages/plugin-webpack-react to change default language, `options.defaultLanguage`.

**Comment by Xwudao** [comment]
> Because Chinese is the default language, in locale/default.ts, it will be bundled into the component library by default. For now, you can use https://github.com/arco-design/arco-plugins/tree/main/packages/plugin-webpack-react to change default language, `options.defaultLanguage`.

Is there a solution in vite.js?

**Comment by Xwudao** [comment]
> Because Chinese is the default language, in locale/default.ts, it will be bundled into the component library by default. For now, you can use https://github.com/arco-design/arco-plugins/tree/main/packages/plugin-webpack-react to change default language, `options.defaultLanguage`.

update:

Thanks,
I refer to the webpack plugin and write a vite plugin.
