### ISSUE TITLE
主题“浅色”，菜单“深色”，divider分割线，还是白色的，非常显眼，不太好看！

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#956]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Framework version:** React 18
- **Browser:** chrome100.0.4896.88

## Steps to reproduce
弄个菜单，调成深色主题，菜单加入分割线，就能看到效果。

我的建议是，主题是白色，菜单是暗色的情况下，菜单中所使用的颜色变量，应该是暗色的，否则很多变量用不了了

**Comment by MisterLuffy** [comment]
你好，由于颜色变量是挂载在 `body` 节点上的，所以实现不了这样的需求，只能自行进行样式调整。

**Comment by MisterLuffy** [comment]
也可以参考 [局部暗色模式](https://arco.design/docs/designlab/partial-dark) 仅在 Menu 中使用暗色模式。
