### ISSUE TITLE
在 Next.js 中，SSR渲染时，Menu组件的 key，服务器端和客户端不一致

### ISSUE THREAD

**Issue by kwooshung** [arco-design/arco-design#958]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome102.0.5005.63

## Steps to reproduce
- 下载最新的next.js
- 安装 Arco Design
- 随便一个Menu组件文档中的代码
- 在控制台将会看到，下图所示内容

![image](https://user-images.githubusercontent.com/3413930/172029340-8175a9c9-585a-4ec9-aaa9-4569cae43b6a.png)

**Comment by MisterLuffy** [comment]
https://github.com/ariakit/ariakit/issues/844#issuecomment-997346656
https://github.com/reactwg/react-18/discussions/111
目前似乎除了 React 18 的 useId，没有可行的解决方案。

**Comment by kwooshung** [comment]
> 把生成 id 的逻辑放到第一次 render 的时候怎么样？ 服务端渲染和客户端渲染都会走这个逻辑

这个不清楚，因为直接引用的组件，是组件内部的问题，不好改，而且牵扯后期升级的问题。所以还得你们官方想想办法。

**Comment by PrinOrange** [comment]
这里我也遇到了同样的问题。对于Next.js和Remix等服务端渲染都会同样报错。
而且有这么一种规律：首次渲染时不会报错，然后再刷新重新加载页面后，aria-controls后面的id会一直递增并报错。

**Comment by PrinOrange** [comment]
> 这里我也遇到了同样的问题。对于Next.js和Remix等服务端渲染都会同样报错。 而且有这么一种规律：首次渲染时不会报错，然后再刷新重新加载页面后，aria-controls后面的id会一直递增并报错。

在Next.js中，属性不匹配会引发致命性报错：`Hydration failed because the initial UI does not match what was rendered on the server.`，成为潜在隐患。
