### ISSUE TITLE
Dropdown Menu Component must be without React.StrictMode?

### ISSUE THREAD

**Issue by Xwudao** [arco-design/arco-design#960]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome102.0.5005.63

## Extra info

If within React.StrictMode, there is an error:

![image](https://user-images.githubusercontent.com/31327868/172105105-bb03651e-a016-4efa-a554-c420ecd75df6.png)

And , can't trigger the droplist

**Comment by Xwudao** [comment]
React Version is 18

**Comment by yinkaihui** [comment]
> And , can't trigger the droplist

在 2.38.0  修复
