### ISSUE TITLE
textArea输入框有bug在设定了Max length之后输入中午再失去焦点会让英文输入导致超出Max length

### ISSUE THREAD

**Issue by xclw-hub** [arco-design/arco-design#964]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome102.0.0.0

**Comment by jiahao-c** [comment]
是不是开启了这个？
```javascript
{errorOnly: true}
```

最好提供一下可复现的代码哈
