### ISSUE TITLE
The required property of Form.Item cannot be captured by form.validate to errors

### ISSUE THREAD

**Issue by ericlee33** [arco-design/arco-design#965]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome102.0.5005.61

**Comment by ericlee33** [comment]
The expectation can be like the rule attribute, which can be captured in the errors parameter of the callback function of form.validate

**Comment by yinkaihui** [comment]
你好 可以提交一个示例 demo 吗？

**Comment by ericlee33** [comment]
https://codesandbox.io/s/wonderful-voice-w0n9dm?file=/index.js
如图，没有填写必填项，但 validate 回调中 errors 为 null

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/50297178/172842162-7429b0f0-7569-46ed-8600-ed0d2a9c6877.png">

**Comment by yinkaihui** [comment]
试下把 `required` 改为 `rules=[{ required: true }]`

**Comment by ericlee33** [comment]
> 可以试下把 `required` 改为 `rules=[{ required: true }]`

这个试过是可以的，不过 required 的这种 case 我们有考虑兼容一下吗 @yinkaihui
