### ISSUE TITLE
请问表格如何使用render，有例子吗？

### ISSUE THREAD

**Issue by 1752146907** [arco-design/arco-design#966]
![image](https://user-images.githubusercontent.com/25144704/172747205-024478f3-7ac9-4edd-aaec-bd0a16993fc0.png)
如上图

**Comment by PengJiyuan** [comment]
文档上有 API 介绍。

**Comment by 1752146907** [comment]
> 文档就是API介绍。

上面写了不正确，或者您贴个例子
