### ISSUE TITLE
RangePicker in Form.Item cannot select correct value

### ISSUE THREAD

**Issue by lyanmm** [arco-design/arco-design#968]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Framework version:** React 18.1.0
- **Browser:** chrome102.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/vitejs-vite-sanv14?file=src%2FApp.tsx

## Extra info
1.RangePicker mode date/month/year are ok
2.the Reproduction Link exmple cannot show picker panel, but in local ide work well, so just show code

## What is expected?
select correct value

## Steps to reproduce
1.use DatePicker.RangePicker wrapper in Form.Item
2.set mode 'week' or 'quarter'
3.select

**Comment by PengJiyuan** [comment]
https://codesandbox.io/s/jovial-visvesvaraya-595s4x?file=/index.js, maybe it's a bug of stackblitz.
