### ISSUE TITLE
Carousel组件，自定义子组件在mac pro上切换时，会出现闪动

### ISSUE THREAD

**Issue by dachaiyuan** [arco-design/arco-design#97]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react 2.21.1
- **System:** macOS10.15.7
- **Browser:** Chrome
- **Reproduction Link:** https://webide.bytedance.net/s/create-react-app1kwimj30-5rlayoxp?file=/index.js:1530-1540

## What is expected?
期望不要闪动

## Steps to reproduce
切换时

**Comment by MisterLuffy** [comment]
排查发现是 Carousel 子节点在类名变化时，切换 `visibility: visible/hidden` 的间隙导致的闪动。
可以暂时通过给子元素增加背景色来解决（遮挡不可见的底层元素）。
如有更好的内部兼容办法，欢迎提 PR。
