### ISSUE TITLE
Modal的hook形式调用设置simple=false不生效

### ISSUE THREAD

**Issue by jetzhliu** [arco-design/arco-design#974]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Browser:** chrome102.0.5005.63

**Comment by jetzhliu** [comment]
https://github.com/arco-design/arco-design/blob/main/components/Modal/useModal/hookModal.tsx#L52

这个地方强制设置了simple为true，导致即使传入simple参数也不能覆盖。但按照文档，这个应该是可以改才合适的。并且全局方法调用的形式也支持修改simple。
```js
  return (
    <Modal {...config} simple visible={visible} onOk={onOk} onCancel={onCancel} unmountOnExit>
      {config.content}
    </Modal>
  );
```

**Comment by fakership** [comment]
I will resolve this problem later.
