### ISSUE TITLE
tooltip在Windows系统下弹出时箭头会抖动

### ISSUE THREAD

**Issue by cfabregas** [arco-design/arco-design#976]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.34.0
- **Framework version:** react
- **Browser:** chrome102.0.5005.61

**Comment by jiahao-c** [comment]
啥浏览器啊？我拿Win10+Edge试了下，没复现

**Comment by yinkaihui** [comment]
这个应该是以前的动画效果导致的，换了动画效果应该没有这个问题了 ～
