### ISSUE TITLE
RangePicker in Form.Item cannot select correct value #968

### ISSUE THREAD

**Issue by lyanmm** [arco-design/arco-design#987]
https://codesandbox.io/s/jovial-visvesvaraya-595s4x?file=/index.js, maybe it's a bug of stackblitz.

_Originally posted by @PengJiyuan in https://github.com/arco-design/arco-design/issues/968#issuecomment-1152170725_

if set field prop in Form.Item, it cannot work well

please check newest link: https://codesandbox.io/s/nameless-flower-79mkm4?file=/index.js

**Comment by lyanmm** [comment]
if set field prop in Form.Item, it cannot work well

**Comment by PengJiyuan** [comment]
https://codesandbox.io/s/cranky-poitras-mvpkl1

Use `getValueFromEvent`.

**Comment by lyanmm** [comment]
> https://codesandbox.io/s/cranky-poitras-mvpkl1
> 
> Use `getValueFromEvent`.

please check https://github.com/arco-design/arco-design-vue/pull/1112 is the same problem that i have sent
