### ISSUE TITLE
控制 TreeSelect 中，树状数据的 icon 显示 / 隐藏

### ISSUE THREAD

**Issue by FinE54** [arco-design/arco-design#997]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 现有案例
一组 treeData 里，包含了 icon 字段值，并不需要显示这个 icon（目前没有发现相关控制显示的方式）

## 预期解决问题
在 TreeSelect 里增加控制 tree-node-icon 显示的 prop。

## 额外补充
当前操作是通过 display: none 关掉显示，或者是处理 treeData，去除掉 icon 的显示。

**Comment by yinkaihui** [comment]
不传 `icon` 属性就行了吧.. 这个本身就是传了就显示的～

**Comment by FinE54** [comment]
> 不传 `icon` 属性就行了吧.. 这个本身就是传了就显示的～

数组是后端传过来带了 icon 的，现在就是，需要手动在接口上去掉 icon 值，或者是在页面上另外再写一个 useMemo 去处理一下。感觉不太好，最好还是带个 prop 去开启和关闭显示。🤣

**Comment by yinkaihui** [comment]
通过 CSS 设置 display: none 即可？
