### ISSUE TITLE
Table 的树状表格，会给源数据的 children 加上 parent 的值

### ISSUE THREAD

**Issue by FinE54** [arco-design/arco-design#999]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.35.0
- **浏览器版本:** chrome102.0.0.0
- **复现地址:** https://codesandbox.io/s/romantic-thunder-25mpo2

## 预期结果
它不应该对原始对象进行修改的。

## 复现步骤
不需要步骤复现，只要把 data 传递给 table，如果是树形数据，自动会给 children 加上 parent。

**Comment by PengJiyuan** [comment]
已经提 PR 了 https://github.com/arco-design/arco-design/pull/990
